platform/commonUI/browse/src/creation/CreateWizard.js
platform/containment/bundle.json
platform/containment/src/CompositionModelPolicy.js
platform/containment/test/CompositionModelPolicySpec.js
platform/containment/test/CompositionMutabilityPolicySpec.js
platform/containment/test/suite.json
platform/core/src/capabilities/MutationCapability.js
platform/forms/res/templates/controls/datetime.html
platform/forms/src/controllers/DateTimeController.js
platform/forms/test/controllers/DateTimeControllerSpec.js

* Add a composition policy which requires destinations to actually have a composition 
property in their model.
* In the context of clocks/timers, this prevents being able to create a Timer in a Timer.
* Allow date-time controller to be optional (previously, its internal use of `ng-required` meant 
that it was treated as required whenever it appeared in a form)
* Specifically, treat individual fields as required only if (a) input it partially complete or 
(b) the control has been explicitly marked as required.
* Change explicit-setting-of-timestamp during mutation to allow this timestamp to be explicitly 
undefined
* Previously, would default to current timestamp if the argument was non-numeric; 
instead, check number of arguments and simply accept whatever was passed …

[Platform] Tweak misc. items to support clocks/timers

---

bundles.json
example/worker/README.md
example/worker/bundle.json
example/worker/src/FibonacciIndicator.js
example/worker/src/FibonacciWorker.js
platform/commonUI/general/res/css/theme-espresso.css
platform/commonUI/general/res/sass/helpers/_bubbles.scss
platform/commonUI/inspect/bundle.json
platform/commonUI/inspect/res/info-bubble.html
platform/commonUI/inspect/src/InfoConstants.js
platform/execution/README.md
platform/execution/bundle.json
platform/execution/src/WorkerService.js
platform/execution/test/WorkerServiceSpec.js
platform/execution/test/suite.json

For #12, add a `workerService` which runs registered web workers on a background thread. Supports execution of work (such as handling WebSocket messages) on background threads to avoid halting the UI when heavy processing (or, in the case of WebSockets, a heavy message load) is required. 
* Add the aforementioned worker service. Recognizes registered `workers` by symbolic names and instantiates them as [`Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker) objects.
* Add an example of using these workers. This example calculates Fibonacci number inefficiently on a background thread, and displays the values in the status indicator as they become available.
Command …

[Execution] Add worker service

---

platform/commonUI/browse/bundle.json
platform/commonUI/browse/res/templates/browse-object.html
platform/commonUI/browse/src/BrowseController.js
platform/commonUI/browse/src/BrowseObjectController.js
platform/commonUI/browse/test/BrowseControllerSpec.js
platform/commonUI/browse/test/BrowseObjectControllerSpec.js
platform/commonUI/browse/test/suite.json
platform/commonUI/general/src/controllers/ViewSwitcherController.js

Use and populate URL for domain objects. Specifically:
* In Browse mode, follow the path of IDs to determine initial navigation state.
* Also use "view" query string parameter to select the current view
* Update both of the above to reflect changes during use
5. Project-specific information isolated to appropriate branches? Y

[Addressability] Use/populate URL

---

platform/core/bundle.json
platform/core/src/services/Throttle.js
platform/core/test/services/ThrottleSpec.js
platform/core/test/suite.json
platform/features/plot/bundle.json
platform/features/plot/src/PlotController.js
platform/features/plot/src/modes/PlotOverlayMode.js
platform/features/plot/src/modes/PlotStackMode.js
platform/features/plot/test/PlotControllerSpec.js
platform/telemetry/src/TelemetryQueue.js

Improve performance during plotting. Specifically:
* Refactor the telemetry queue (used as an alternative to a table for subscribers who wish to receive telemetry updates for every datum that arrives) to improve insertion performance characteristics.
* Throttle updates to plot axis labels. These potentially change every time new data comes in, but in cases where data is arriving faster than it can be displayed, these only need to be recalculated at display time.
* Add `throttle` as a utility service to support the above.
Partially addresses WTD-1202; specifically, addresses the largest performance issues identified during profiling of plot updates. WTD-1218 has been filed as a followup to address the more general problem of how an overloaded client presents itself (e.g. by freezing.)
1. …

[Plot] Improve plotting performance

---

platform/commonUI/general/res/css/theme-espresso.css
platform/commonUI/general/res/sass/helpers/_bubbles.scss
platform/commonUI/inspect/bundle.json
platform/commonUI/inspect/res/info-bubble.html
platform/commonUI/inspect/src/InfoConstants.js

#14 
Added CSS class "bubble-container" to BUBBLE_TEMPLATE;
bubble-container utilizes CSS "pointer-events: none";
Changed INFO_HOVER_DELAY constant from 500ms to 2000ms;
See comments for author checklist.

[Frontend] Fix to prevent infobubbles from preventing clicks

---

app.js

Reload the bundle file from disk when requested, re-applying any
includes or excludes that were specified on the command line.
Allows a developer to make changes to bundles.json without having to
restart the server for them to take effect.

[Development] Reload bundle file with each request

---

platform/commonUI/edit/res/templates/edit-object.html
platform/commonUI/general/bundle.json
platform/commonUI/general/res/templates/containers/accordion.html

Changed the attribute of 'title' on mct-container to 'label'. This made the tooltips over the Library and Element panes in Edit mode disappear. #46.
5. Project-specific information isolated to appropriate branches? Y

[Edit] No more useless tooltips

---

.gitignore
Procfile
build-docs.sh
bundles.json
circle.yml
example/localstorage/bundle.json
example/localstorage/src/LocalStoragePersistenceProvider.js
jsdoc.json
karma.conf.js
package.json
platform/core/src/objects/DomainObject.js
platform/framework/src/resolve/BundleResolver.js
test-main.js

Adds continuous integration provided by CircleCI.  On a successful test run, JSDoc is executed and docs are published to http://nasa.github.io/openmctweb/.  A demo version of the app is also deployed to https://openmctweb-demo.herokuapp.com/.
Also adds a npm package file which serves as a task runner.
`npm install` will install all node dependencies.
`npm start` will start a local development server.
`npm test` will run all tests.
`npm run-script jshint` will run jshint (different than jslint) against all files.
`npm run-script jsdoc` will generate JSDoc for project.
Also adds a basic LocalStoragePersistenceProvider so that demo data is persisted.
Currently, the documentation exported by JSDoc is of little value, I will open a follow-up task for reformatting code so that JSDoc works …

Continuous deployment

---

platform/commonUI/browse/res/templates/create/create-menu.html

Move the ng-click directive to the li element to match the element that receives hover styles.
Fixes nasa/openmctweb#60.
Expect to pass code review? Y
Project-specific information isolated to appropriate branches? Y

[Template] Move ng-click to parent node

---

platform/representation/src/actions/ContextMenuAction.js
platform/representation/test/actions/ContextMenuActionSpec.js

* Listen for clicks and dismiss the menu when it is clicked
* Turn `off` the correct listener on the body once the menu is dismissed
* Misc. whitespace
Verified that this has desired behavior in Chrome (menu goes away when anything in it is clicked, and the action still happens; and menu goes away when clicking outside of it) for both right-click-launched menus and title-arrow-launched menus
Expect to pass code review? Y
Project-specific information isolated to appropriate branches? Y

[Menus] Dismiss menus when clicked

---

platform/commonUI/general/res/css/theme-espresso.css
platform/commonUI/general/res/sass/lists/_tabular.scss

https://github.jpl.nasa.gov/MissionControl/vista/issues/48
Simplified styles to indicate sort by asc and desc in table th elements;
(cherry picked from commit 15a2416)
Assumes that we'll add ng-click to all relevant **th** elements of the table. Add the following to the class attribute of the **th** of any table that's sortable:
- Add "sort asc" or "sort desc" (depending on sort direction) when that column is controlling the sort order.
- Add "sortable" to the **th** of any column that's clickable to control sort order. This displays the pointer cursor when the user hovers over the **th**. Don't add this to …

[Frontend] Better sorting indicators added to styles

---

platform/commonUI/general/res/css/theme-espresso.css
platform/commonUI/general/res/sass/helpers/_bubbles.scss

#75
CSS modified to utilize word-break property;

Review and integrate fix for hover bubble problem #75

---

bundles.json
example/identity/bundle.json
example/identity/src/ExampleIdentityService.js
platform/commonUI/browse/bundle.json
platform/commonUI/browse/src/creation/CreateWizard.js
platform/commonUI/browse/src/creation/CreationService.js
platform/commonUI/browse/test/creation/CreateWizardSpec.js
platform/commonUI/browse/test/creation/CreationServiceSpec.js
platform/core/src/capabilities/MetadataCapability.js
platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js
platform/entanglement/bundle.json
platform/entanglement/src/services/LocatingCreationDecorator.js
platform/entanglement/test/services/LocatingCreationDecoratorSpec.js
platform/entanglement/test/suite.json
platform/identity/bundle.json
platform/identity/src/IdentityAggregator.js
platform/identity/src/IdentityCreationDecorator.js
platform/identity/src/IdentityIndicator.js
platform/identity/src/IdentityProvider.js
platform/identity/test/IdentityAggregatorSpec.js
platform/identity/test/IdentityCreationDecoratorSpec.js
platform/identity/test/IdentityIndicatorSpec.js
platform/identity/test/IdentityProviderSpec.js
platform/identity/test/suite.json

Addresses #92; specifically:
* Add bundle `platform/identity` which provides:
* Interface definition for the `identityService`
* Default aggregation strategy ("take the first one")
* Fallback provider ("unknown user")
* Example implementation of an identity service which prompts the user with a dialog
* Decorate the creation service from `platform/identity` to attach the creator within the model
* Convert `creationService` to a composite service to facilitate the above
* Move addition of `location` property to a decorator in `platform/entanglement` for parity
* Add Creator as a property of all domain object types, to show in info bubble
* Corollary to this, filter out properties which don't have associated controls when preparing a Create dialog.
* Add an indicator which shows the …

[Identity] Add identity service

---

pom.xml

Added tomcat7-maven-plugin config to deploy the WAR to an embedded Tomat 7 container:
```shell
$ mvn tomcat7:run-war
```
This can streamline deplyment untill you start using Gulp or Grunt to serve the app one day ;)

[Build] Start the WAR in an embedded Tomcat Servlet Container

---

platform/identity/src/IdentityProvider.js
platform/identity/test/IdentityProviderSpec.js

Provide an undefined identity by default, instead of
an Unknown User. This suppresses display of identity-related
features (such as the identity indicator) while still
providing a default implementation of the identityService
for platform components to utilize. nasa/openmctweb#99

[Identity] Provide an undefined identity

---

platform/core/src/capabilities/MetadataCapability.js
platform/core/test/capabilities/MetadataCapabilitySpec.js

Don't show domain object id in info bubble; this is not
useful information to non-developers. (For developers,
this information can be retrieved from the URL by
navigating to a domain object.) WTD-1252

[Info Bubble] Remove ID

---

platform/commonUI/general/bundle.json
platform/commonUI/general/src/directives/MCTSplitPane.js
platform/commonUI/general/src/directives/MCTSplitter.js

Poll to position splitter in an `mct-split-pane`; avoids #53 
2. Unit tests included and/or updated with changes? No, see WTD-1400

[Common UI] Poll to position splitter

---

platform/core/bundle.json
platform/core/src/capabilities/CompositionCapability.js
platform/core/src/capabilities/ContextCapability.js
platform/core/src/services/Contextualize.js
platform/core/test/capabilities/CompositionCapabilitySpec.js
platform/core/test/services/ContextualizeSpec.js
platform/core/test/suite.json
platform/entanglement/bundle.json
platform/entanglement/src/services/LocatingObjectDecorator.js
platform/entanglement/test/services/LocatingObjectDecoratorSpec.js
platform/entanglement/test/suite.json

When objects have a defined `location`, use this to construct a default `context` (which may be overridden by the `composition` capability later - or it may not.)
* Separate out contextualization of domain objects from the `composition` capability into a separate verb-like service `contextualize`
* Attempting to leverage `composition` for this task directly from the `objectService` decorator in the next bullet would result in O(n^2) behavior at best (where n is tree depth), since `composition` also _uses_ the `objectService`
* Add an `objectService` decorator to the `platform/entanglement` bundle that places loaded objects in the context of their `location` (using `contextualize` from above)
2. Unit tests included and/or updated …

[Location] Add contexts to domain objects by location

---

platform/core/bundle.json
platform/features/layout/bundle.json

open #124
Removed "Default view" and "Display title by default" from
Panel configs;

Review and integrate open124

---

platform/forms/res/templates/controls/select.html

Use ng-show instead of ng-if to suppress the
'Select One' option after user has chosen something
in a select box; the latter appears to be incompatible
with Angular 1.4.x. nasa/openmctweb#113

[Forms] Fix select control

---

platform/commonUI/general/src/directives/MCTResize.js
platform/commonUI/general/test/directives/MCTResizeSpec.js

Reduce number of digest cycles triggered by mct-resize;
only trigger a new digest cycle when size actually
changes. #19.
1. Changes address original issue? Y 
5. Project-specific information isolated to appropriate branches? Y

[Common UI] Reduce digest count

---

platform/commonUI/browse/src/creation/CreationService.js
platform/commonUI/browse/test/creation/CreationServiceSpec.js
platform/commonUI/edit/src/actions/LinkAction.js
platform/commonUI/edit/src/actions/PropertiesDialog.js
platform/commonUI/edit/test/actions/LinkActionSpec.js
platform/commonUI/edit/test/actions/PropertiesDialogSpec.js
platform/core/bundle.json
platform/core/src/capabilities/CompositionCapability.js
platform/core/src/models/PersistedModelProvider.js
platform/core/test/capabilities/CompositionCapabilitySpec.js
platform/core/test/models/PersistedModelProviderSpec.js
platform/entanglement/src/actions/AbstractComposeAction.js
platform/entanglement/src/services/CopyService.js
platform/entanglement/src/services/LinkService.js
platform/entanglement/src/services/MoveService.js
platform/entanglement/test/services/CopyServiceSpec.js
platform/entanglement/test/services/LinkServiceSpec.js
platform/entanglement/test/services/MoveServiceSpec.js

Handle adding new objects to the composition of other objects as part of the `composition` capability, instead of modifying the `composition` property directly in the model. nasa/openmctweb#97 
1.   Changes address original issue? Y
2.   Unit tests included and/or updated with changes? Y
3.   Command line build passes? Y
4.   Expect to pass code review? Y

[Composition] Consolidate composition changes

---

platform/commonUI/browse/bundle.json
platform/commonUI/browse/src/creation/CreationService.js
platform/commonUI/browse/test/creation/CreationServiceSpec.js

Include a persisted timestamp when an object is first
created. nasa/openmctweb#139

[Persistence] Include timestamp on creation

---

CONTRIBUTING.md

Loosen commit message standards, to minimize clutter in GitHub
issues. nasa/openmctweb#145.

[Process] Loosen commit message standards

---

platform/core/bundle.json
platform/core/src/models/PersistedModelProvider.js
platform/core/test/models/PersistedModelProviderSpec.js

...to any domain object models loaded from persistence
which do not have one. The presence of this timestamp
is necessary for the persistence capability to determine
whether an object should be created or updated when a
request to persist is made. nasa/openmctweb#139.

[Persistence] Add persisted timestamp

---

example/profiling/bundle.json
example/profiling/src/DigestIndicator.js
platform/core/src/capabilities/MutationCapability.js
platform/core/src/services/Throttle.js
platform/core/test/services/ThrottleSpec.js
platform/search/bundle.json
platform/search/src/services/GenericSearchProvider.js
platform/search/test/services/GenericSearchProviderSpec.js

Addresses #141.
* Broadcast mutations on one global topic to avoid the need to attach mutation listeners per-object; this allows components which are interested in observing all mutations (such as GenericSearch) to maintain a single listener, instead of one per object, reducing memory usage.
* Cherry-pick a fix to `throttle` from #104 to resolve a race condition there.
* Change approach to indexing in GenericSearch to (a) avoid the use of capabilities, and (b) spread out requests for objects over time. In both cases, the intent is to reduce the CPU utilization and/or time spent associated with initial indexing. More detail is in comments on #141
* Add an indicator to `example/profiling` to report number of digest cycles per second, to aid in diagnosing performance …

[Search] Improve generic search performance

---

platform/commonUI/general/res/sass/_mixins.scss
platform/commonUI/general/res/sass/helpers/_wait-spinner.scss
platform/commonUI/general/res/sass/search/_search.scss
platform/commonUI/general/res/sass/tree/_tree.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/espresso/res/sass/_constants.scss
platform/commonUI/themes/snow/res/css/theme-snow.css
platform/commonUI/themes/snow/res/sass/_constants.scss

open #190
CSS for revised .loading class;
Commented out/removed old .loading styles;
Theme constants for loading colors added  to theme files;
See notes in #190 for usage.

Review and integrate open190: new .loading CSS class

---

platform/persistence/elastic/bundle.json
platform/persistence/elastic/src/ElasticSearchProvider.js
platform/persistence/elastic/test/ElasticSearchProviderSpec.js
platform/search/bundle.json
platform/search/res/templates/search.html
platform/search/src/controllers/SearchController.js
platform/search/src/services/GenericSearchProvider.js
platform/search/src/services/GenericSearchWorker.js
platform/search/src/services/SearchAggregator.js
platform/search/test/controllers/SearchControllerSpec.js
platform/search/test/services/GenericSearchProviderSpec.js
platform/search/test/services/GenericSearchWorkerSpec.js
platform/search/test/services/SearchAggregatorSpec.js

This branch overhauls the search providers and search services to use prototypical style and improves performance of the GenericSearchProvider and the SearchController.
The biggest performance improvement I can explain is that it is very expensive to load items from the object service vs the model service.  Reducing the number of objects that get instantiated has been beneficial.  This pull request also discovered some performance issues in the VISTA taxonomy providers, and resolving those has directly improved performance of the GenericSearchProvider.
This also resolves some bugs with the search controller that were causing multiple requests to get sent to the search service when only one should have been sent; that has been prevented inside of the search controller.
If future …

Search performance

---

platform/search/src/services/GenericSearchProvider.js
platform/search/test/services/GenericSearchProviderSpec.js

Update field name in GenericSearchProvider to reflect changes
from nasa/openmctweb#193. Avoids exceptions on mutation.
Additionally, add test case exercising relevant code and verifying
that reindexing is scheduled upon mutation as expected.

[Search] Update field name

---

platform/commonUI/general/res/templates/controls/time-controller.html
platform/commonUI/general/src/controllers/TimeRangeController.js
platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js

Allow dates to be entered as text in the start/end bounds of the time controller.
* Replace text spans with input fields in template.
* Move clickable region which exposes the date picker, such that it does _not_ get fired by clicking the input field
* Update model as text changes in response to user input
* Misc. reordering/refactoring of operations to ensure that changes to user input do not get overwritten while the user is typing

[Time Controller] Allow text entry of dates

---

platform/entanglement/bundle.json
platform/entanglement/src/actions/GoToOriginalAction.js
platform/entanglement/src/capabilities/LocationCapability.js
platform/entanglement/test/actions/GoToOriginalActionSpec.js
platform/entanglement/test/capabilities/LocationCapabilitySpec.js
platform/entanglement/test/suite.json

Adds a "Go To Original" action which navigates to an original instance of an object; see #147 
* Add a `getOriginal` method to `LocationCapability` which loads the original instance of an object.
* This implementation relies upon `objectService` to return correctly-located originals; this is assured by `LocatingObjectDecorator` in the same bundle.
* To avoid circular dependencies, a reference to `objectService` is obtained via the `$injector` instead of through normal means.
* Add a "Go To Original" action which performs a `navigate` action upon the original object instance.
* [Removed wrapper around `LocationCapability` constructor](https://github.com/nasa/openmctweb/pull/175/files#diff-2b5d6c42d31f28106f181af11fa6ad74L81); this is no longer necessary after b1654f70 …

[Entanglement] Add "Go To Original" action

---

docs/gendocs.js
package.json

Add table of contents to generated documents, without
modifying document sources; nasa/openmctweb#189.
* Add table of contents using [markdown-toc](https://github.com/jonschlinkert/markdown-toc)
* Normalize whitespace

[Documentation] Add table of contents

---

platform/commonUI/browse/bundle.json
platform/commonUI/browse/src/creation/CreationService.js
test-main.js

Specify path for uuid, making it available for any code that would require it,
without that code needing to know the path to it.
Fixes https://github.com/nasa/openmctweb/issues/211.
Assigning to @VWoeltjen for review and integrate.
2. Unit tests included and/or updated with changes? No, configuration only change

[RequireJS] Specify path for uuid

---

platform/features/plot/src/elements/PlotUpdater.js
platform/features/plot/test/elements/PlotUpdaterSpec.js

Ignore empty lines (plot lines with no data) when determining
domain extrema; avoids failure to draw multiple plot lines in
a telemetry panel, nasa/openmctweb#150.

[Plot] Ignore empty lines

---

example/generator/src/SinewaveLimitCapability.js
platform/commonUI/general/res/sass/_constants.scss
platform/commonUI/general/res/sass/_limits.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

Based on jpl github pull https://github.jpl.nasa.gov/MissionControl/vista/pull/116.
Changes the way limit CSS classes are applied: now uses 2 classes instead of one: Apply "s-limit-red" or "s-limit-yellow" to a tr element, or directly to any block element. When applied to a tr, the whole row will be colored, and a glyph icon will be added to the first cell of the row. For upper and lower limits, apply "s-limit-upr" and "s-limit-lwr" as a separate class.
Still to-do: make any mods needed in warp in order to apply classes properly.

Review and integrate open-vista54a into master

---

platform/commonUI/browse/res/templates/browse.html
platform/search/bundle.json
platform/search/res/templates/search.html

Declare Search UI components as templates instead of
representations so that they are not removed from the
DOM when no domain object is supplied. Fixes
nasa/openmctweb#234

[Search] Declare UI components as templates

---

platform/representation/src/MCTRepresentation.js
platform/representation/src/TemplateLinker.js
platform/representation/test/TemplateLinkerSpec.js

Addresses #227 (and decreases severity of #229)
* Create new child scopes in `templateLinker` whenever a call is made to change a template.
* This includes calls that have the same `templateUrl`, to handle cases such as switching from one plot to another plot.
* Tweak ordering such that scope is destroyed as soon as a call to change templates is made. This avoids cases where an existing scope (e.g. in nested `mct-representation`s) gets updated to reflect new content, only to be replaced and recreated when its parent representation gets recreated.
* Change compilation process for loaded templates to more closely resemble the way `ng-include` does it. HTML is inserted into the relevant containing element _before_ compilation; as a consequence, loaded styles are applied …

[Representation] Avoid scope reuse

---

platform/commonUI/mobile/src/MCTDevice.js
platform/commonUI/mobile/test/MCTDeviceSpec.js

When including/excluding a DOM element via mct-device,
use replaceWith() instead of parent().append() to preserve
original ordering of DOM elements from template.
nasa/openmctweb#213.

[Mobile] Don't move DOM nodes

---

docs/src/guide/index.md
platform/commonUI/general/bundle.json
platform/commonUI/general/src/StyleSheetLoader.js
platform/commonUI/general/test/StyleSheetLoaderSpec.js
platform/commonUI/themes/espresso/bundle.json
platform/commonUI/themes/snow/bundle.json

Addresses #241, which in turn supports #208 (inclusion of CSS styles for timelines, a subset of which needs to be theme-specific)
* Add a `THEME` constant to globally declare the current theme
* Allow `stylesheets` to optionally specify a `theme` property; if specified, stylesheets are only included when they match the configured theme.
* Update documentation
Note that the espresso and snow themes are still kept in separate bundles (each of which defines a different `THEME` constant which other bundles can key off of) such that switching themes may still be performed by switching bundles, to minimize impact of changes for other deployments (no configuration changes for other deployments should be needed)
2. Unit tests included …

[Themes] Include/exclude stylesheets by theme

---

platform/features/layout/src/LayoutController.js
platform/features/layout/test/LayoutControllerSpec.js

Addresses nasa/openmctweb#271, ensuring frames in a layout
are not too tiny to use, even if the grid size is small.

[Layout] Enforce minimum size on drop

---

platform/core/bundle.json
platform/core/src/services/Topic.js
platform/core/test/services/TopicSpec.js

In `topic`, when a listener throws an error, catch it and log the message.
Addresses #231. Previously, such an error would be uncaught, and topic would not notify any remaining listeners. This could result in objects [failing to persist](https://github.com/nasa/openmctweb/pull/207#issuecomment-151219179) correctly after mutation.

[Core] Catch errors from listeners in topic

---

platform/commonUI/general/res/templates/controls/datetime-field.html
platform/commonUI/general/src/controllers/DateTimeFieldController.js
platform/commonUI/general/src/directives/MCTPopup.js
platform/commonUI/general/test/controllers/DateTimeFieldControllerSpec.js

Addresses #297, wherein a flag which toggles visibility of the date-time picker gets lost in a child scope. Moving flag into a nested object resolves the issue.
Also includes a workaround for #298 which should be removed when that issue is properly resolved

[Time Conductor] Fix date picker toggles

---

platform/core/bundle.json
platform/core/src/actions/ActionProvider.js
platform/core/test/actions/ActionProviderSpec.js
platform/entanglement/src/actions/AbstractComposeAction.js
platform/entanglement/src/actions/CopyAction.js
platform/entanglement/src/actions/LinkAction.js
platform/entanglement/src/actions/MoveAction.js
platform/entanglement/test/actions/AbstractComposeActionSpec.js

Addresses nasa/openmctweb#120, wherein an exception hit while instantiating Move/Copy/Link actions causes context menu options to fail to display.
Addressing this at two levels:
* At the ActionProvider level, catch errors thrown when actions are instantiated, such that one failed instantiation will not cause the whole `getActions()` to fail (isolate errors)
* At the level of individual move/copy/link actions, add an `appliesTo` check such that the dependency on the `context` capability which causes the error is made explicit.
* Also while in there, make these proper subclasses of AbstractComposeAction 

[Actions] Avoid suppression of context menus

---

platform/core/src/types/TypeImpl.js
platform/core/test/types/TypeImplSpec.js

[bug] TypeImpl.getInitialmodel should always return a fresh (ie. cloned) model.

---

bundles.json
docs/src/guide/index.md
platform/status/README.md
platform/status/bundle.json
platform/status/src/StatusCapability.js
platform/status/src/StatusConstants.js
platform/status/src/StatusRepresenter.js
platform/status/src/StatusService.js
platform/status/test/StatusCapabilitySpec.js
platform/status/test/StatusRepresenterSpec.js
platform/status/test/StatusServiceSpec.js
platform/status/test/suite.json

Add status tracking for domain objects, and decoration of
representations with status-related classes. Supports WTD-1575
by allowing pending state of taxonomy to be handled by
status tracking and custom CSS, instead of by overriding platform
templates.
Opening for early review; still need:

[Status] Add status tracking

---

platform/commonUI/general/res/sass/forms/_selects.scss
platform/commonUI/general/res/sass/plots/_plots-main.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css
platform/features/plot/res/templates/plot.html

#251
Fixed markup and CSS to remove erroneously
applied "select" class;
Modified .select to not use overflow: hidden;
Better positioning for *-options elements;
- Command line build passes? Sure

Review and integrate open251

---

circle.yml
platform/commonUI/general/res/sass/mobile/_constants.scss
platform/commonUI/general/res/sass/mobile/_mixins.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

#169
**IMPORTANT: This should be tested on real mobile devices prior to integration!** 
open169 brings significant simplification of media query device detection to focus on width only. Tablet max-width and desktop min-widths were also modified to create gapless ranges. CSS media queries now appear to function as expected - which was not previously the case, hence #169. 
Note that in mobile emulation mode in Chrome, if the device screen width emulation setting is expanded beyond 1280 px, the UI will NOT display properly: this is due to the media query believing that we are no longer in a mobile device but are instead in desktop-mode, but mct-device says otherwise, as it's reporting what the emulator is telling it. This should not be a problem in real devices, until someone comes out with …

Review and integrate open169

---

platform/commonUI/general/res/sass/user-environ/_layout.scss
platform/commonUI/general/res/sass/user-environ/_tool-bar.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

Fixes CSS overflow problem that was hiding toolbar dropdown menus.
open #199
open #283
Tweaks to .tool-bar layout to handle very narrow widths.

Review and integrate open283

---

platform/representation/src/MCTRepresentation.js
platform/representation/test/MCTRepresentationSpec.js

Addresses #302 by differentiating between two linked instances of the same domain object from `mct-representation` when determining if a watch-invoked `refresh` can be ignored. (Previously, refresh _was_ ignored in this case, allowing for incorrect contextual behavior when this occurred.)

[Representation] Check full path when comparing domain objects

---

example/profiling/src/DigestIndicator.js
platform/commonUI/general/src/directives/MCTSplitPane.js
platform/commonUI/general/test/directives/MCTSplitPaneSpec.js
platform/commonUI/general/test/suite.json
platform/features/plot/src/MCTChart.js
platform/features/plot/test/MCTChartSpec.js
platform/persistence/elastic/src/ElasticIndicator.js
platform/persistence/elastic/test/ElasticIndicatorSpec.js

This updates usages of $interval to set `invokeApply` to `false` when desired, to reduce number of digests that get triggered. Addresses #369 
This is most significant in MCTSplitPane; without this change, there are 140 digests/sec while idle. With this change, that number drops below 10 (accounted for by indicators etc which do refresh once per second.)
* Updated digest indicator (from example/profiling) to give more current results
* Fixed usage of $interval in MCTSplitPane
* Added spec for MCTSplitPane in order to verify usage of $interval
* Spec remains mostly empty for now; WTD-1400 exists to backfill these
* Use `invokeApply=false` from `mct-chart` to reduce watch counts associated with plotting
* Fixed usage of $interval for the ElasticSearch indicator
* This …

[Performance] Fix usages of $interval

---

platform/commonUI/browse/bundle.json
platform/commonUI/browse/src/creation/CreateActionProvider.js
platform/commonUI/browse/src/creation/CreationPolicy.js
platform/commonUI/browse/test/creation/CreateActionProviderSpec.js
platform/commonUI/browse/test/creation/CreationPolicySpec.js
platform/commonUI/browse/test/suite.json
platform/entanglement/bundle.json
platform/entanglement/src/services/CopyService.js
platform/entanglement/src/services/CopyTask.js
platform/entanglement/test/services/CopyServiceSpec.js

* Created a new creation policy category and instance that returns true if tested object hasFeature('creation')`
* Modified the `CopyService` to use the persistence space of the copy target, not the object being copied
* Modified the CreateActionProvider to use new CreationPolicy
* Modified the `CopyService` to use the CreationPolicy to check whether a new object or a link should be created for the type of the object being copied.
* Added tests for CreationPolicy
* Added a new test case to test that duplication of non-createable types creates links (addresses https://github.com/nasa/openmctweb/issues/338#issuecomment-159353004 )
* Some minor refactoring of CopyService and CopyTask. Would suggest that use of instantiationCapability actually allows for more fundamental …

#338 [Copy] Copying an object with telemetry from the data dictionary results in a number of unknown objects in copied tree

---

platform/commonUI/edit/src/capabilities/EditablePersistenceCapability.js
platform/commonUI/edit/src/objects/EditableDomainObjectCache.js
platform/commonUI/edit/test/capabilities/EditablePersistenceCapabilitySpec.js

Addresses immediate cause of #305 (returning correct type from the edit-mode-wrapped persistence capability.)
Note that a [benign warning](https://github.com/nasa/openmctweb/issues/305#issuecomment-161146898). Plan to address this in the context of #368 

[Edit] Return a promise from editable persistence capability

---

platform/core/bundle.json
platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js
platform/entanglement/src/policies/CrossSpacePolicy.js
platform/entanglement/test/policies/CrossSpacePolicySpec.js

As per https://github.com/nasa/openmctweb/issues/58#issuecomment-161200080 I've pushed the notification version of it for now. Discussion needed on whether we should go with this temporary solution, or instead a blocking dialog with temporary disablement or complete removal of PersistenceFailureHandler.

[Persistence] Errors in persistence (after creating/modifying objects) should be visible to user #58

---

docs/src/guide/index.md
platform/commonUI/general/res/templates/controls/datetime-field.html
platform/commonUI/general/res/templates/controls/time-controller.html
platform/commonUI/general/src/controllers/DateTimeFieldController.js
platform/commonUI/general/src/controllers/TimeRangeController.js
platform/commonUI/general/test/controllers/DateTimeFieldControllerSpec.js
platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js
platform/forms/src/MCTControl.js

Addresses #259 and incorporates feedback from #324 by:
* Wrapping both datetime fields in the time conductor with a `form`, such that they behave like a form
* Updating outer bounds of the range selector only on form submission
* Add a hidden `submit` button such that hitting enter in a text field will trigger form submission
* Allow form submission to be triggered from the fields directly
* Trigger form submission from a datetime field when
* The text input blurs
* A choice is made from the date-time picker
Opening early for feedback (esp. from @larkin). In particular, I'm not entirely happy with the way a `submit` function gets passed into the datetime field, and am open to alternatives. Considered  `$emit`ting an event, but don't think the way such events get propagated is appropriate …

[Time Conductor] Don't update model while typing (v2)

---

platform/commonUI/general/res/sass/mobile/_constants.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

open #169 
Per comments in #358, adjusted desktop breakpoint to 1025. We still need to have a better overall strategy for determining mobile context, but this should help prevent breakage in the short-term on small desktop screens.

Review and integrate open169b

---

platform/commonUI/edit/res/templates/elements.html
platform/commonUI/general/res/sass/tree/_tree.scss
platform/commonUI/general/res/sass/user-environ/_layout.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

open #199
open #278
Changed CSS to use s-status-editing instead of .active
class;
Refined style defs to explicitly target tree and
search-results children in order to avoid items in
Inspector Elements pool from being designated as
being edited;
Removed {{searchText}} div from input-filter;

Review and integrate open199e

---

platform/features/layout/src/LayoutController.js
platform/features/layout/test/LayoutControllerSpec.js

When handling a drop into the layout, store the panel's
new position to the LayoutController's internal table of
raw positions (in addition to writing it to the configuration.)
Avoids https://github.com/nasa/openmctweb/issues/384

[Layout] Update raw positions on drop

---

docs/src/index.md

* Add spaces to 'Open MCT Web' for consistency
* Use term 'platform' instead of 'framework' for consistency
with the developer guide
* Avoid the term 'capabilities' (could be ambiguous in the context
of other documentation)
* Use canonical casing for JSDoc and JavaScript
* Simplify phrasing of first sentence
* Change casing of 'Developer Guide' for consistency with
other bullets
From review of https://github.com/nasa/openmctweb/pull/412

[Documentation] Tweak spelling / phrasing

---

platform/commonUI/general/res/sass/user-environ/_layout.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css

#426
Adds CSS to turn off pointer-events for the splitter, treeview and inspect elements when they are in a collapsed state;
- Unit tests included and/or updated with changes? N/A (no code changed)

Review and integrate open426

---

platform/entanglement/src/services/CopyTask.js
platform/entanglement/test/services/CopyTaskSpec.js

[Duplicate] Avoid error when rewriting IDs in single-element arrays

---

platform/commonUI/mobile/bundle.json
platform/commonUI/mobile/src/AgentService.js
platform/commonUI/mobile/src/DeviceClassifier.js
platform/commonUI/mobile/src/DeviceMatchers.js
platform/commonUI/mobile/src/MCTDevice.js
platform/commonUI/mobile/test/AgentServiceSpec.js
platform/commonUI/mobile/test/DeviceClassifierSpec.js
platform/commonUI/mobile/test/DeviceMatchersSpec.js
platform/commonUI/mobile/test/suite.json

Add a subset of the following CSS classes to body on application startup:
* `mobile`: Phones or tablets.
* `phone`: Phones specifically.
* `tablet`: Tablets specifically.
* `desktop`: Non-mobile devices.
* `portrait`: Devices in a portrait-style orientation.
* `landscape`: Devices in a landscape-style orientation.
* `touch`: Device supports touch events.
Class names are intentionally aligned with detectors supported by the `mct-device` directive.
Requested by @charlesh88 in the context of #169

[Mobile] Add classes for device characteristics to body

---

platform/commonUI/edit/res/templates/elements.html
platform/commonUI/general/res/sass/_icons.scss
platform/commonUI/general/res/sass/_inspector.scss
platform/commonUI/general/res/sass/_main.scss
platform/commonUI/general/res/sass/_mixins.scss
platform/commonUI/general/res/sass/_object-label.scss
platform/commonUI/general/res/sass/helpers/_wait-spinner.scss
platform/commonUI/general/res/sass/mobile/_constants.scss
platform/commonUI/general/res/sass/mobile/_tree.scss
platform/commonUI/general/res/sass/mobile/search/_search.scss
platform/commonUI/general/res/sass/search/_search.scss
platform/commonUI/general/res/sass/tree/_tree.scss
platform/commonUI/general/res/templates/label.html
platform/commonUI/general/res/templates/object-inspector.html
platform/commonUI/general/res/templates/tree-node.html
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css
platform/search/res/templates/search-item.html
platform/search/res/templates/search.html

#431 
**Pending status**: Adds solid `s-status-pending` support for object labels anywhere they are used, in tree, search results, Inspector location objects, edit mode's "Elements" pool. Add `s-status-pending` to the label's `mct-representation` class attribute.
**Markup mods**: As part of making pending status implementation a clean one, the label template, and tree items, were converted to use flex-box layout. Markup and styles have been extensively unit tested in the browser's mobile emulation mode.
**Changes to mobile navigation in the tree**: As part of the markup mods previously noted, markup in tree-node.html was greatly simplified. Multiple elements using `mct-device` have been eliminated. Mobile navigation is now more consistent with the desktop: tapping a tree item navigates, …

Review and integrate open431

---

platform/commonUI/general/res/sass/controls/_messages.scss
platform/commonUI/general/res/templates/indicator.html
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css
platform/features/clock/src/indicators/ClockIndicator.js

Provides modified behavior and abilities for status bar indicator items:
* For #336, added a 1.5 second delay before an expanded status indicator collapses.
* For #304, added a class string to the getGlyphClass function in ClockIndicator.js and added related CSS classes to allow the clock indicator to float right, be expanded by default and not collapse, and appear without its icon.
- Unit tests included and/or updated with changes? N/A (no code changed)

Review and integrate open336

---

docs/src/tutorials/index.md

From #433
Fixed an error in the markdown that caused text to render incorrectly in the bar graph tutorial.

[Documentation] Code example in bar graph tutorial incorporates text from the following paragraph

---

docs/src/design/index.md
docs/src/design/planning/APIRefactor.md
docs/src/design/proposals/APIRedesign.md
docs/src/design/proposals/APIRedesign_PeteRichards.md
docs/src/design/proposals/ImperativePlugins.md
docs/src/design/proposals/Roles.md

Creating a pull request to allow comments in-line.

[API] API Redesign Goals and Proposals

---

platform/commonUI/general/bundle.json
platform/commonUI/general/src/filters/ReverseFilter.js
platform/commonUI/general/test/filters/ReverseFilterSpec.js
platform/commonUI/general/test/suite.json
platform/features/plot/res/templates/plot.html
platform/features/plot/src/elements/PlotTickGenerator.js
platform/framework/src/register/CustomRegistrars.js

Moves reversal of tick labels (#477) out of plot controller code, to isolate plot changes to CSS/templates. Incidentally addresses #171.
@charlesh88, note that this is to branch open337. Do you see any issues with handling these changes in this fashion?

[Plot] Use filters to reverse tick labels

---

platform/commonUI/general/res/templates/controls/datetime-field.html
platform/commonUI/general/res/templates/controls/time-controller.html
platform/commonUI/general/src/controllers/DateTimeFieldController.js
platform/commonUI/general/src/controllers/TimeRangeController.js
platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js

Addresses #325, updating validation approach in cases where user-entered start time exceeds user-entered end time.
* Display start/end violations as validity violations (with `error` class)
* Utilize `validate` function passed into date-time fields as part of their form structure (consistent with other `mct-control`s)
* Pass in such `validate` functions from the time range control
* Don't "fix" start/end violations when user tabs/submits; instead, simply don't update the outer bounds until form input is valid
* Reduce minimum outer bounds span to 1 second

[Time Conductor] Update validation logic

---

platform/commonUI/browse/bundle.js
platform/commonUI/browse/src/creation/LocatorController.js
platform/commonUI/browse/test/creation/LocatorControllerSpec.js

* Fetch default root (the ROOT object) if no context is available from the provided object. Allows user in the worst case complete control over location to persist new object. The changes in #500 that make Locator optional will prevent the default context from adversely affecting the case of activities added to timelines.
* New test for default context

[Create] #491 Apply default context root in Locator when none available from object

---

platform/commonUI/browse/bundle.js
platform/commonUI/browse/src/creation/AddAction.js
platform/commonUI/browse/src/creation/AddActionProvider.js
platform/commonUI/browse/src/creation/CreateWizard.js
platform/commonUI/browse/test/creation/AddActionProviderSpec.js
platform/commonUI/browse/test/creation/CreateWizardSpec.js
platform/commonUI/edit/src/actions/SaveAction.js
platform/commonUI/edit/src/capabilities/EditableInstantiationCapability.js
platform/commonUI/edit/src/capabilities/EditableLookupCapability.js
platform/commonUI/edit/src/capabilities/EditorCapability.js
platform/commonUI/edit/src/objects/EditableDomainObject.js
platform/commonUI/edit/test/capabilities/EditableLookupCapabilitySpec.js
platform/features/timeline/src/controllers/swimlane/TimelineProxy.js
platform/features/timeline/test/controllers/swimlane/TimelineProxySpec.js

Addresses #480 and enables adding of activities to timelines in edit mode. 
1. Added a new AddAction and test specs for adding sub objects to an edited object.
2. Resolved a [problem](https://github.com/nasa/openmctweb/issues/305#issuecomment-163792108) identified in EditableDomainObject that meant DomainObject functions were not being wrapped by EditableDomainObject
3. Added new `EditableInstantiationCapability` so that objects created via the Instantiation capability of an EditableDomainObject are themselves EditableDomainObjects without needing explicit wrapping.
4. Moved some wizard-specific code shared between AddAction and SaveAction out of SaveAction and into the CreateWizard itself.
5. Modified CreateWizard to make locator optional. Locator is no longer visible …

[New Edit Mode] Adding sub objects to Timelines

---

platform/commonUI/edit/src/capabilities/EditorCapability.js
platform/commonUI/edit/src/objects/EditableDomainObjectCache.js

Addresses #660 
Problem manifested with sub-object editing in timelines as an unload warning on cancel followed by unexpected behavior. This was due to the fact that in current NEM the cancel action clears the dirty cache, however previously it was only removing the currently editing object from the cache. This caused problems in timelines which support a degree of sub-object editing, resulting in potentially multiple dirty objects in the cache. 
This modification allows clearing of the entire dirty cache in one go.
This problem does not manifest in #627 due to changes that support slightly more elegant handling of navigation change events. Clearing of the dirty cache was introduced in NEM, but subsequent refactoring should remove the need for it. …

[Edit Mode] Added ability to clear all dirty cache

---

platform/commonUI/general/res/sass/_object-label.scss
platform/commonUI/general/res/sass/tree/_tree.scss
platform/commonUI/themes/espresso/res/css/theme-espresso.css
platform/commonUI/themes/snow/res/css/theme-snow.css
platform/features/timeline/res/css/timeline.css
platform/features/timeline/res/sass/_timelines.scss
platform/features/timeline/res/templates/tabular-swimlane-cols-tree.html

Note: I based this branch off of master, but you may want to integrate it into open659 first.
open #659
[Frontend] Fixed CSS issue with Timeline label elements
CSS for .rep-object-label modified; Added CSS class
to tabular-swimlane-cols-tree.html markup;
Also cleaned up .s-status-pending styles for related
label elements;
Note that functional issues still remain (as discussed) including:
* Dragging duplicating Timeline objects, 
* Dragging the outermost parent container locking up the browser in a loop
* Drag being enabled when not in Edit mode

Review and integrate open659a into open659

---

platform/containment/src/ComposeActionPolicy.js
platform/features/timeline/src/directives/MCTSwimlaneDrop.js
platform/features/timeline/test/directives/MCTSwimlaneDropSpec.js

Addresses https://github.com/nasa/openmctweb/issues/659#issuecomment-182659801
* Added a check to the ComposeActionPolicy to prevent composition of an object with itself. Suggest that in future this could be added as a separate composition policy, but might require some refactoring of Composition policies to pass in object instances rather than types, or alternatively a new policy type that accepts object instances.
* Prevented propagation of drop event from timeline up to `DropGesture`. Suggest refactor of TimelineSwimlaneDropHandler to use DropGesture + actions instead of a dedicated drop handler

[New Edit Mode] #659 Fix to timelines

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/actions/SaveAction.js
platform/entanglement/src/services/CopyService.js
platform/entanglement/src/services/CopyTask.js
platform/entanglement/test/services/CopyServiceSpec.js
platform/entanglement/test/services/CopyTaskSpec.js

Utilize `copyService` during Save As; this allows the destination's persistence space to be used for newly-persisted objects.
Addresses #656, wherein an attempt to persist to a non-writable space results in persistence failure. (Also addresses a subtle corollary bug where objects are persisted to the _wrong_ persistence space; see [discussion](https://github.com/nasa/openmctweb/issues/656#issuecomment-182533470).)
Also removed some unused (or non-needed) dependencies and unused functions, partially addressing #630. (It was easier to follow the code for debugging purposes this way.) This is out of scope for the original issue, and I'd be happy to roll these back based on review.
Opening PR now for early review. Still to-do:

[Create] Utilize copyService during Save As

---

example/imagery/bundle.js

This is to address #703 where errors are shown in scrolling lists for imagery data.
2. Unit tests included and/or updated with changes? __N/A__

[Examples] #703 Changed imagery telemetry metadata to use 'utc' format

---

example/notifications/res/dialog-launch.html
example/notifications/res/notification-launch.html
platform/commonUI/general/res/sass/controls/_messages.scss
platform/commonUI/general/res/templates/bottombar.html
platform/commonUI/general/res/templates/indicator.html
platform/commonUI/notification/res/notification-indicator.html

#442
Removed white space from markup; Moved getGlyphClass up to status-block-holder element out of status-block; CSS mods to selectors and style defs in _messages.scss;

[Frontend] Markup, CSS changes

---

platform/commonUI/browse/res/templates/browse-object.html
platform/commonUI/edit/src/representers/EditRepresenter.js
platform/commonUI/edit/test/representers/EditRepresenterSpec.js

* Added flag "isEditable" to edit representer. This is used for conditional inclusion of markup in browse-object.html
* Added temporary conditional markup block to browse-object.html to include or not include toolbar depending on edit state. This will no longer be necessary when the changes for #627 are merged.
2. Unit tests included and/or updated with changes? N/A * 

[Timelines] #677 Applied fix to prevent editing of timelines in browse

---

circle.yml
example/export/ExportTelemetryAsCSVAction.js
karma.conf.js
package.json

This wasn't directly inspired by an issue; I noticed that circleci wasn't running JSHint so it wouldn't catch style errors.  Added JSHint to the circle configuration and fixed some style issues that would result in a broken build.
Also added a junit test reporter which allows circleci to gather profiling information about our tests and improves the reporting capabilities of circleci.
1. Changes address original issue? N*
2. Unit tests included and/or updated with changes? N
* Did not have an original issue.

[Build] run JSHint on circleci, generate test reports

---

platform/commonUI/dialog/res/templates/overlay-message-list.html
platform/commonUI/general/src/controllers/BannerController.js
platform/commonUI/notification/bundle.js
platform/commonUI/notification/src/NotificationIndicatorController.js
platform/commonUI/notification/src/NotificationService.js
platform/commonUI/notification/test/NotificationServiceSpec.js
platform/core/src/capabilities/PersistenceCapability.js

Addresses #499
* Added a new 'dismissable' attribute to notification
* All notifications now dismissable by default
* Notifications with dismassable !== false will have a dismiss action added to them automatically.
* Added new dismiss listener so that functions calling notifications can take some action if the notification is dismissed.

[Notifications] #499 All notifications now dismissable by default.

---

karma.conf.js

Addresses #672 
Keeping it simple: Enforce 80% global coverage consistent with existing [test standards](https://github.com/nasa/openmctweb/blob/dd0f9ab74e1c9ba39136bc8c17805a866c2bcbe1/CONTRIBUTING.md#test-standards).
@larkin / @akhenry - this is also an opportunity to discuss coverage requirements, if there's any interest in adjusting these. (For my part, I don't think coverage is a hugely useful metric; I do like enforcing some standard as a barrier against under-testing, and to encourage qualities associated with testability, but beyond that the value is not clear to me.)
2. Unit tests included and/or updated with changes? N/A (build-only change)

[Build] Enforce code coverage threshold

---

platform/search/src/services/GenericSearchProvider.js
platform/search/test/services/GenericSearchProviderSpec.js

Pass model directly when indexing is triggered via object mutation,
to avoid issuing an extra, unnecessary request to the server.
Additionally supports indexing of objects which have been created
but not yet persisted.
Addresses #377.

[Search] Index directly on mutation

---

gulpfile.js
platform/commonUI/browse/res/templates/browse/object-properties.html
platform/commonUI/edit/res/templates/elements.html
platform/commonUI/general/res/sass/_inspector.scss
platform/commonUI/general/res/sass/forms/_elems.scss
platform/commonUI/general/res/sass/overlay/_overlay.scss
platform/commonUI/general/res/templates/object-inspector.html
platform/features/plot/res/templates/plot-options-browse.html
platform/features/plot/src/PlotOptionsForm.js
platform/features/table/res/templates/table-options-edit.html
platform/forms/res/templates/form.html

@akhenry Relates to #729, #707 and #498. Needed by work done in open707 by Andrew. Can be integrated directly into master prior to merge into open707 if desired with no adverse effects.
Subtle but significant mods via markup and CSS changes to elements related to configuration options for plot and table object types, and holder elements in the Inspector.

Review and integrate open729

---

LICENSES.md
bower.json
main.js
platform/commonUI/general/bundle.js
platform/commonUI/general/res/templates/subtree.html
platform/commonUI/general/res/templates/tree/node.html
platform/commonUI/general/res/templates/tree/toggle.html
platform/commonUI/general/res/templates/tree/tree-label.html
platform/commonUI/general/res/templates/tree/wait-node.html
platform/commonUI/general/src/directives/MCTTree.js
platform/commonUI/general/src/ui/ToggleView.js
platform/commonUI/general/src/ui/TreeLabelView.js
platform/commonUI/general/src/ui/TreeNodeView.js
platform/commonUI/general/src/ui/TreeView.js
platform/commonUI/general/test/directives/MCTTreeSpec.js
platform/commonUI/general/test/ui/TreeViewSpec.js
test-main.js

...instead, use Zepto to handle DOM manipulations more directly in response to user actions and mutation events. Goal is to reduce the watch count associated with the tree, #732 and #315. Also serves as informative prototyping for interfaces for non-Angular UI components, #463.
Still needed for parity/completion:

[Tree] Rewrite tree without Angular

---

platform/features/table/src/controllers/RTTelemetryTableController.js
platform/features/table/test/controllers/RTTelemetryTableControllerSpec.js

Fixed a bug that caused an error to occur when new row added to realtime table. The issue was caused by the fact that a digest does not occur in between setting the `rows` element on $scope, and when the directive is informed (via $broadcast) that a new row is available. Only occurred on tables composed of multiple telemetry objects.

[Tables] #742 Fixed digest-related bug in RTTelemetryController

---

platform/commonUI/general/src/ui/TreeNodeView.js
platform/commonUI/general/test/ui/TreeViewSpec.js

Addresses #753 (newly-created objects may not have context, causing errors when these are encountered by TreeNodeView)
1. Changes address original issue? Y &ast;
&ast; Partially; other cases described in that issue are addressed in #756

[Tree] Don't assume context capability is present

---

platform/commonUI/general/res/sass/_global.scss
platform/commonUI/general/res/sass/startup-base.scss
platform/features/timeline/res/sass/_activities.scss
platform/features/timeline/res/sass/_timeline-thematic.scss
platform/features/timeline/res/sass/_timelines.scss

Implements fixes for #748, #750 and #755.
* CSS fixed so that plot-resource icon doesn't display cursor: pointer in the header
* For #750, set l-header to use user-select: none
* Fixed timeline tabular labels to remove doubled hover effects, and to only display hover effects when in edit mode
* For #755, changed s-timeline-gantt.mid to use cursor: move instead of ew-resize. Need to verify on Linux.
* Fixed scrollbar flicker observed with #748 

Review and integrate 755

---

platform/features/table/src/controllers/MCTTableController.js
platform/features/table/src/controllers/RTTelemetryTableController.js
platform/features/table/test/controllers/MCTTableControllerSpec.js
platform/features/table/test/controllers/RTTelemetryTableControllerSpec.js

Should have named this milestone Boeing - #757, #747, #727, #707
* Added a fixed row limit of 100000 (for now).
* Added a new 'remove:row' event that the MctTable directive responds to, removing the row at the provided index.
* Fixed a bug in insertion whereby numerical values were being compared as text rather than numbers
Have not implemented UI to set row limit for now. Should discuss implementation. Assuming a field in the inspector with the other table options, but currently that implies that it's only available in edit mode. Could add it as a separate browse element in the inspector. My feeling is that it should be a select box with sensible defaults, rather than a text field.
3. Command line …

[Tables] #757 Added max row limit to streaming tables

---

platform/commonUI/general/src/ui/TreeView.js
platform/commonUI/general/test/ui/TreeViewSpec.js

...by removing the incorrect expectation that a domain object
(and not just its model) will be passed in when mutation occurs.
Addresses #745.

[Tree] Refresh properly on mutation

---

package.json

Specify requirejs minor version of 2.1, as 2.2 is not compatible with karma-requirejs.
Fixes build problems that appeared after latest requirejs version bump.
1. Changes address original issue? Y (issue is described in this PR)
2. Unit tests included and/or updated with changes? N (config only change)

[Package] Specify require minor version

---

platform/features/timeline/src/controllers/swimlane/TimelineSwimlaneDecorator.js
platform/features/timeline/test/controllers/swimlane/TimelineSwimlaneDecoratorSpec.js

Addressees #715. See [comment](https://github.com/nasa/openmct/issues/715#issuecomment-199553274) on that ticket for explanation of root cause.
* Added an additional check to prevent mutation of model with unchanged value, which was in turn causing all swim-lanes in timeline to be refreshed.
* Updated tests
1. Changes address original issue?
2. Unit tests included and/or updated with changes?
3. Command line build passes?
4. Changes have been smoke-tested?

[Timelines] #715 Added a check to prevent mutation when modes are unchanged

---

platform/features/plot/src/elements/PlotTelemetryFormatter.js
platform/features/plot/test/elements/PlotTelemetryFormatterSpec.js
platform/telemetry/src/TelemetryFormatter.js
platform/telemetry/test/TelemetryFormatterSpec.js

Addresses #778 
* In TelemetryFormatter, don't apply `toFixed` - this truncates useful information in most views
* In PlotTelemetryFormatter, do apply `toFixed` - in plots, it is impractical to read Y axis labels without rounding in this manner

[Data Formats] Format numeric values with full precision

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/policies/EditableLinkPolicy.js
platform/commonUI/edit/src/policies/EditableMovePolicy.js
platform/core/src/actions/ActionCapability.js
platform/features/timeline/src/controllers/swimlane/TimelineSwimlaneDropHandler.js
platform/features/timeline/src/directives/MCTSwimlaneDrop.js
platform/features/timeline/test/controllers/swimlane/TimelineSwimlaneDropHandlerSpec.js

When dragging and dropping within a timeline, treat this as a move instead of a link. Addresses #679
* Remove suppression of `move` actions from `ActionCapability` such that this is available to Timelines
* Add a policy suppressing `move` actions for more general cases
* Modify logic for Timeline to pick an action based on type of drag-drop
* Use `move` for editable-to-editable drag-and-drops (presumably in the same timeline)
* Use `link` for any other drag-and-drops (although currently this is just suppressed by `ActionCapability` when dragging from tree)
* Use a no-op for the special case of self-to-self moves (reorderings); the only change necessary in this case is modifying the index of the dropped identifier, which is handled in a step subsequent to the action. …

[Timeline] Move (instead of link) when dragging and dropping within a timeline

---

platform/commonUI/browse/src/creation/AddAction.js
platform/core/bundle.js
platform/core/src/capabilities/PersistenceCapability.js
platform/core/src/models/CachingModelDecorator.js
platform/core/src/models/ModelCacheService.js
platform/core/src/services/Instantiate.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js
platform/core/test/models/CachingModelDecoratorSpec.js
platform/core/test/models/ModelCacheServiceSpec.js
platform/core/test/services/InstantiateSpec.js

Addresses #770 by removing the `.save(true)` call to the `editor` capability. This created ambiguity about which domain objects were dirty and which were not, resulting in some composition changes being lost instead of persisted.
This call had existed because newly-created domain objects were not available from the `modelService` as they had not yet been persisted. To remove the need for this, added a cache (or, more accurately, separated an existing cache out of the CachingModelDecorator) and had `instantiate` write models to this. The `persistence` capability also drops models from here such that they may be re-read from persistence later (they will get cached again due to CachingModelDecorator, but we've discussed removing this to reduce memory usage; in the absence of this secondary …

[Timeline] Fix to persistence failures after creating subactivities

---

platform/features/timeline/src/directives/MCTSwimlaneDrop.js
platform/features/timeline/test/directives/MCTSwimlaneDropSpec.js

Invoke `$apply` from `mct-swimlane-drop` and add some checks to ensure this is necessary, to avoid
triggering a ton of digest cycles while dragging.

[Timeline] Update drag-over highlights promptly

---

platform/commonUI/general/res/sass/_constants.scss
platform/commonUI/general/res/sass/_object-label.scss
platform/commonUI/general/res/sass/helpers/_wait-spinner.scss
platform/commonUI/general/res/templates/tree/wait-node.html

Fixes for #445, specifically: 
* Markup and styling related to wait-node.html template and .loading when applied to that markup;
* Normalized look of spinner between .loading and .s-status-pending;
1. Unit tests included and/or updated with changes? N, N/A

Review and integrate open445b

---

platform/features/timeline/src/controllers/swimlane/TimelineSwimlaneDropHandler.js
platform/features/timeline/test/controllers/swimlane/TimelineSwimlaneDropHandlerSpec.js

Fix reordering behavior when dragging-and-dropping within timelines; addresses #789.
Don't rely on Move action being unavailable in the reorder case (and don't bother loading actions in this case, as well, since no such action is necessary)

[Timeline] Fix reordering behavior in timelines

---

platform/features/timeline/src/directives/MCTSwimlaneDrop.js
platform/features/timeline/test/directives/MCTSwimlaneDropSpec.js
platform/representation/src/gestures/DropGesture.js
platform/representation/test/gestures/DropGestureSpec.js

...such that Firefox does not try to treat drop as a new URL
to navigate to. Addresses #688 and #527 

[Firefox] Invoke preventDefault on drop

---

platform/entanglement/bundle.js
platform/entanglement/src/policies/CopyPolicy.js
platform/entanglement/src/policies/MovePolicy.js
platform/entanglement/test/policies/CopyPolicySpec.js
platform/entanglement/test/policies/MovePolicySpec.js

Addresses #792 by adding policies which suppress Move and Duplicate actions when objects involved are non-modifiable or non-creatable, respectively.

[Entanglement] Add policies for Move, Duplicate

---

platform/features/table/src/TableConfiguration.js
platform/features/table/src/controllers/MCTTableController.js
platform/features/table/src/controllers/RTTelemetryTableController.js
platform/features/table/src/controllers/TelemetryTableController.js
platform/features/table/test/controllers/RTTelemetryTableControllerSpec.js
platform/features/table/test/controllers/TelemetryTableControllerSpec.js

Issue is occurring because no telemetry metadata is being returned from the telemetry handle. Root cause is difficult to ascertain as it's localized to WARP, and does not occur in open or VISTA.
1. Changed point in execution where telemetry metadata is retrieved to be consistent with plots which are not exhibiting the reported behavior
2. Addressed race condition whereby two subscriptions that occur in rapid succession could potentially cause reset of telemetry metadata

[Tables] Addressed issue with tables not appearing on reload

---

platform/core/bundle.js
platform/core/src/capabilities/InstantiationCapability.js
platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/InstantiationCapabilitySpec.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js

https://github.com/nasa/openmct/issues/745#issuecomment-204559209:
> Specifically, [removing from the cache on persistence](https://github.com/nasa/openmct/pull/773/files#diff-f6d9cdddbe14e455171941b3e3466e8aR152) causes this - it permits multiple instances of the same model to exist in the application. There are probably a lot of other subtle regressions lurking around this.
> Intent there was to maintain similarity with earlier implementation (for newly-created objects, get models from persistence instead of using the version created in memory.) This is poorly-reasoned (also clears the cache on _every_ persist) and unnecessary; there are not cases where an object will look different on read from persistence than it did before it was saved.

[Persistence] Don't evict models on persist

---

platform/forms/res/templates/controls/color.html

Small tweak to template for color control: Update color input to show selected color when picker is not visible:
before:
after:
2. Unit tests included and/or updated with changes? N (html only change)

[Control] Color input shows selected color

---

platform/commonUI/browse/res/templates/browse-object.html
platform/commonUI/edit/src/representers/EditRepresenter.js

1. Removed temporary markup and code from `browse-object.html` and `EditRepresenter.js` that was added to address #677 

[Timelines] #677 Removed temporary markup

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/policies/EditActionPolicy.js
platform/commonUI/edit/src/policies/EditContextualActionPolicy.js
platform/commonUI/edit/test/policies/EditActionPolicySpec.js
platform/commonUI/edit/test/policies/EditContextualActionPolicySpec.js
platform/core/src/actions/ActionCapability.js
platform/core/test/actions/ActionCapabilitySpec.js
platform/representation/bundle.js
platform/representation/src/gestures/ContextMenuGesture.js
platform/representation/test/gestures/ContextMenuGestureSpec.js

Addresses #635 and #631
1. Removed edit-specific code from ContextMenuGesture and ActionCapability
2. Created a new EditContextualActionPolicy
3. Used new policy to filter actions attached to scope in ContextMenuController

[Edit Mode] #635 Removed Edit-related concerns from ContextMenuGesture

---

platform/commonUI/general/res/sass/controls/_time-controller.scss
platform/commonUI/general/res/templates/controls/time-controller.html
platform/commonUI/general/src/controllers/TimeRangeController.js
platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js
platform/features/conductor/res/templates/time-conductor.html

* Refactor the TimeRangeController to prototype style, use controller as.
* Update outer bounds on blur (only update the one that user changes)
* Update mobile styles to format properly in given space space, hide draggable time range selector.
Resolves https://github.jpl.nasa.gov/MissionControl/vista/issues/175 as well as https://github.com/nasa/openmct/issues/318 and https://github.com/nasa/openmct/issues/493.
Sending to @VWoeltjen for review.

Time Conductor updates query on blur, mobile support

---

platform/commonUI/browse/src/creation/CreateAction.js
platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/actions/SaveAction.js
platform/commonUI/edit/src/actions/SaveAsAction.js
platform/commonUI/edit/test/actions/SaveActionSpec.js
platform/commonUI/edit/test/actions/SaveAsActionSpec.js
platform/commonUI/general/res/sass/controls/_buttons.scss

* Split SaveAction into SaveAction and SaveAsAction
* Restored disabled tests, and added new ones
I have identified two further opportunities for simplification, which I want to put out there
1. If new objects had context, the object lookups could be removed, which would simplify things a little and remove the dependency on ObjectService.
2. It would be great if we could use the `PropertiesAction` to collect user input here. The properties dialog is basically the same, except it needs a location. Either `CreateWizard` could be folded into `PropertiesDialog` with a switch based on whether to show `location` selector, or the `ActionCapability` could be passed a dialog at runtime (instead of using a require dependency). `CreateWizard` and `PropertiesDialog` already have v. similar …

[Edit mode] Simplify SaveAction

---

gulpfile.js
package.json

* In the prepublish step, run bower and gulp via node, instead of
relying on shebang interpretation. (Forward-slash path separators
appear to get normalized by node itself before executing the scripts.)
* In the gulp build, replace hard-coded *nix-style separators with
path.sep; this allows stylesheets to be output to expected locations
when building on Windows.
Addresses #827.
2. Unit tests included and/or updated with changes? N &ast;
&ast; Changes are to build only, out of scope for unit testing

[Build] Fix build on Windows

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/policies/EditContextualActionPolicy.js
platform/commonUI/edit/test/policies/EditContextualActionPolicySpec.js

* Modified EditContextualActionPolicy to check whether parent of selected object is editable
* Made blacklists bundle constants to support overriding by plugins
* Added a new test for this case

[Edit Mode] #794 Modified policy to show remove action in context for non-editable domain object types

---

demo/src/DemoInitializer.js

open #858
- Mismatch between named example layout and
reference in Hopscotch tour fixed.
@akhenry Sorry, had to fix a mismatched naming between my example layout and how it's referred to in the Hopscotch tour.
Unit tests included and/or updated with changes? N
Command line build passes? Hope so

Fix naming of 'Edit Display Layout Example'

---

platform/commonUI/general/res/sass/_global.scss

#871, #869
Cherry-picked from live_demo869. Removed bullets and set margin in ol, ul. Fixes bullets showing up and row margin problems in datetime picker, and anywhere else we will use the ul/li structure for non-textual content.
1. Unit tests included and/or updated with changes? N, N/A

Review and integrate open871

---

platform/features/table/res/sass/table.scss

Don't use table-cell displays for cells, resolves issues with zero-sized
tbody causing thead to be 100% of table size.
Fixes https://github.com/nasa/openmct/issues/809
2. Unit tests included and/or updated with changes? N (Style only change)
Assigning to @akhenry for review and integrate.

[Table] Fix headers in firefox

---

platform/commonUI/general/res/sass/user-environ/_frame.scss

z-index added to .object-top-bar .left element to allow context arrow to display on hover in frames while editing. #836

Review and integrate open836: context arrows on Layout frames while editing

---

platform/commonUI/edit/res/templates/elements.html
platform/commonUI/edit/src/controllers/ElementsController.js
platform/commonUI/edit/test/controllers/ElementsControllerSpec.js

Addresses #663 
* Have limited the search to object names. Was using Angular's default search filter - unless a property is specified this filter does a deep search on all property values, so it may have been matching on other object attributes, causing the strange results.

[Edit] Elements pool filtering displays more consistent results

---

circle.yml

Use circle's heroku integration to deploy to ensure that we deploy
a full clone of the repo and not a shallow clone, prevents build
failure in master branch.
Resolves the build failures we are currently seeing in master.
1. Changes address original issue? Y (this ticket)
2. Unit tests included and/or updated with changes?  N/A, build only change

[Build] Use Circle's heroku integration for deploy

---

platform/features/timeline/res/sass/_timelines.scss
platform/features/timeline/res/templates/resource-graph-labels.html

[Frontend] Modified .tick-labels in Timelines
open #909
- Changed markup to not use plot's .tick-label class
- Changed CSS accordingly
- Fixed alignment (clipped bottom value) by refactoring to use flex-box layout for tick labels

Review and integrate open909: fix for Timeline Resource Graph labels

---

platform/features/table/src/controllers/MCTTableController.js
platform/features/table/test/controllers/MCTTableControllerSpec.js

While the number of visible rows may not have changed, their contents may have; returning early here results in #910.

[Table] Remove length check when updating visible rows

---

platform/commonUI/browse/res/templates/browse/object-header.html
platform/commonUI/general/res/sass/controls/_controls.scss
platform/commonUI/general/res/sass/user-environ/_frame.scss

open #929 
* Label context arrows now always visible;
* Also enabled frame dragging in title/label area when editing in Display Layout;
* CSS and markup changes;

R&I open929: Label context arrow always visible; frame dragging in label area

---

build-docs.sh
circle.yml

New process is to push built docs to the openmct-website repo. This will in turn trigger a full website build and redeployment to gh-pages.
1. Do not push to gh-pages
2. Clone website repo from openmct-website
3. Build docs into openmct-website
4. Soft push openmct-website
* Step 4 will trigger a rebuild of the openmct-website repo, which will deploy to openmct/gh-pages.
I also changed the circleci deployment configuration to go back to using commands for the heroku deployment, rather than the circleci heroku support. This is due to to circle.yml not supporting both heroku and 'command' specifiers simultaneously. I did make sure to address the shallow clone issue that necessitated using the native heroku support in the first place.
2. Unit tests …

[Website] #901 Automate build process

---

circle.yml

Corrects build error introduced by #939. Command in circle.yml was missing a space. 
2. Unit tests included and/or updated with changes? __N/A__ build changes only

[Website] Fixed failed circle.yml command

---

platform/commonUI/regions/src/InspectorController.js
platform/commonUI/regions/test/InspectorControllerSpec.js
platform/representation/src/MCTRepresentation.js
platform/representation/test/MCTRepresentationSpec.js

Switching into edit mode will no longer refresh all representations of an object as it previously did. A refresh will still occur of the object view, because the template changes (to an editable version of it).
* Removed canEdit and couldEdit checks from MctRepresentation
* Removed status change listener from MctRepresentation
* Added status change listener to RegionController
* New tests

[New Edit Mode] #634 Removed edit concerns from MctRepresentation

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/actions/EditAndComposeAction.js
platform/commonUI/edit/src/policies/EditActionPolicy.js
platform/commonUI/edit/test/actions/EditAndComposeActionSpec.js
platform/commonUI/regions/src/InspectorController.js
platform/commonUI/regions/test/InspectorControllerSpec.js
platform/representation/src/MCTRepresentation.js
platform/representation/src/gestures/DropGesture.js
platform/representation/test/MCTRepresentationSpec.js

New PR supersedes previous PR #932
* Removed edit code from DropGesture, and moved it to LinkAction
* Renamed LinkAction to EditAndComposeAction to avoid confusion with the LinkAction in entanglement, and to reflect its slightly modified role
* Moved 'folder' logic to EditAndComposeAction. At first I implemented as two separate actions and used `appliesTo` to filter out action if it was a folder type object, but was a lot of additional LOC.
* Updated tests
* __Modified EditActionPolicy to remove check for `view-control` category when determining applicability of action with key `edit`. This was so that objects that do not support edit mode do not make an edit action available.__
3. Command …

[New Edit Mode] #636 Removed edit concerns from DropGesture

---

circle.yml

Added a section to circle.yml to skip the build and test process for the gh-pages branch.

[Build] Ignore gh-pages from circle-ci

---

platform/features/timeline/res/templates/tabular-swimlane-cols-tree.html
platform/features/timeline/res/templates/timeline.html
platform/representation/src/MCTRepresentation.js
platform/representation/test/MCTRepresentationSpec.js

* Ensure a `configuration` object has been placed in scope before changing templates (otherwise, timeline falls back to using an empty configuration to store resource graph selection)
* Invoke `commit` when making changes from the Timeline itself (the `commit` occurs for free when making changes from the toolbar)

[Timeline] Persist resource graph toggles

---

platform/commonUI/edit/src/representers/EditRepresenter.js
platform/features/layout/bundle.js
platform/features/layout/src/FixedController.js
platform/features/layout/src/LayoutController.js
platform/representation/src/gestures/DropGesture.js

Addresses #633 and also fixes #804
* Removed edit specific code from `LayoutController` and `FixedController`.
* Removed redundant 'setEdit' function from `EditRepresenter`
* Modified DropGesture so that resolution of scope does not occur in constructor.
2. Unit tests included and/or updated with changes? __N/A__

[New Edit Mode] #633 Remove Editing workflow concerns from FixedController, LayoutController

---

platform/features/timeline/src/controllers/TimelineController.js
platform/features/timeline/src/controllers/swimlane/TimelineSwimlanePopulator.js
platform/features/timeline/test/controllers/TimelineControllerSpec.js
platform/representation/src/MCTRepresentation.js
platform/representation/test/MCTRepresentationSpec.js

Addresses #957 by:
* Reverting changes to `mct-representation` ordering which triggered the issue originally
* Solving for #908 by instead watching for the `configuration` object when it is passed in
3. Command line build passes? N &ast;
&ast; Build has existing failures due to #952 and #956, but verification steps show no new build failures caused by these changes.

[Time Conductor] Restore missing time conductor

---

platform/commonUI/inspect/src/gestures/InfoButtonGesture.js
platform/commonUI/inspect/test/gestures/InfoButtonGestureSpec.js

Usage is unnecessary and is sensitive to initialization ordering of
representations, resulting in #948.

[Mobile] Remove usage of element.scope()

---

platform/commonUI/general/res/sass/user-environ/_layout.scss

R&I open970: hide nav-to-parent arrow when in Edit mode

---

platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js
platform/commonUI/edit/test/capabilities/TransactionalPersistenceCapabilitySpec.js

1. Added an additional check in TransactionalPersistenceCapability to determine whether the object has been persisted previously, and therefore whether it can be refreshed. In the case that it cannot be refreshed, the cancel action is essentially a noop.
2. Added an additional test for this condition.

[Edit] Fixed issue with cancel action throwing an error. Fixes #979

---

platform/features/timeline/res/templates/timeline.html
platform/features/timeline/src/controllers/TimelineController.js
platform/features/timeline/src/controllers/TimelineZoomController.js
platform/features/timeline/test/controllers/TimelineControllerSpec.js
platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js

Addresses #981 by calculating width for the scrollable area of a timeline as 25% past its right edge (or the full visible area, if the pixel width would be less.) 
This replaces the existing width calculation, which was making room for several hundred days to the right of the timeline, resulting in a scroll bar that became unusable at higher zoom levels (a small scroll would result in a big jump in time)

[Timeline] Use reasonable width for scroll area

---

platform/features/timeline/src/controllers/TimelineZoomController.js
platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js

This avoids starting with a scrollable width too small for the
initial scroll position that the zoom controller selects.
Fixes #817

[Timeline] Provide greater initial width

---

platform/features/timeline/src/controllers/TimelineZoomController.js
platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js

When TimelineZoomController updates scroll position (either to initialize and start at the left edge of the timeline, or to maintain centering when zooming), do so on a timeout. 
Contemporaneous zoom level changes also effect the width of the scrollable region, but the order at which this update occurs in the DOM is unpredictable; as such, an obsolete width may cause the scroll position to get clamped to an undesired value if scroll position and width are updated during the same digest style. Updating scroll on a `$timeout` ensures that this will take place on a subsequent digest cycle, preserving desired ordering.
Addresses #936.

[Timeline] Update scroll position on timeout

---

platform/features/table/res/templates/mct-table.html
platform/features/table/src/controllers/MCTTableController.js

Uses `mct-resize` to detect resize of element, and recalculates column widths. There are non polling alternatives to detecting resize, and we might want to consider switching mct-resize over to using them to avoid a lot of timers. eg. https://www.npmjs.com/package/element-resize-event
Event-driven resize detection methods all rely on injecting invisible elements into the DOM though, so might cause some CSS weirdness in some cases.
2. Unit tests included and/or updated with changes? N/A - basically just a markup change

[Tables] Recalculate column dimensions on resize

---

platform/entanglement/src/policies/CrossSpacePolicy.js
platform/entanglement/test/policies/CrossSpacePolicySpec.js

Fixes #1007
This was previously disallowed by policy at the time of #245:
> In that vein, a very simple option is to prevent actions between persistence stores and re-enable support for them later.
It's later! Since then, Duplicate has been refactored to instantiate objects in a manner which preserves their persistence space (in #371). Have tested cross-space duplicate with both creatable and non-creatable objects (telemetry) and observe no issues.
4. Changes have been smoke-tested?  Y

[Duplicate] Allow copy across spaces

---

platform/features/timeline/bundle.js
platform/features/timeline/src/controllers/TimelineZoomController.js
platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js

Reposition scroll bar in Timeline with RAF instead of timeout;
this ensures that scroll bar is positioned after the current
digest (updating the width) but before the results are rendered
(avoiding flicker.) Fixes #997

[Timeline] Reduce flicker

---

platform/entanglement/src/actions/CopyAction.js

Fixes #339. 
@akhenry @VWoeltjen @larkin  I can't manually invoke the exact dialog that is displayed when copying a large number of items. I think I've found it, and have added a hint message that wasn't there previously, but I have no clear way to test my changes. Also not sure if I've found all instances where this type of messaging would occur. Any thoughts?
1. Unit tests included and/or updated with changes? N/A (hopefully)

[Frontend] New message for copy in-progress dialog

---

platform/commonUI/edit/bundle.js
platform/commonUI/general/res/sass/_constants.scss
platform/commonUI/general/res/sass/_effects.scss
platform/commonUI/general/res/sass/controls/_buttons.scss
platform/commonUI/general/res/sass/user-environ/_layout.scss
platform/commonUI/themes/espresso/res/sass/_constants.scss
protractor/common/EditItem.js

For #709.
* When going from browse to edit mode, the wrapper around the object being edited will now transition in from its edges, and the edit controls toolbar will animate its height.
* There is no transition applied for going from edit to browse; to do this we'd need to mod the JS on exiting to look for the end of animation events.
* Tested in Chrome, Safari and Firefox.
* May not be smooth with very complex objects like Layouts with a large number of components.
I'm thinking lets integrate this change and discuss what's needed to allow a transition out of Edit mode.

[Frontend] Animation added to transition from browse to edit mode

---

platform/commonUI/general/res/templates/controls/datetime-field.html
platform/commonUI/general/src/controllers/DateTimeFieldController.js
platform/commonUI/general/src/directives/MCTClickElsewhere.js
platform/commonUI/general/test/directives/MCTClickElsewhereSpec.js

1. Popup can now be dismissed via the calendar button. Problem was double triggering of click events.
2. Modified `MctClickElsewhere` to trigger a digest. Popup is now instantly dismissed
3. Selecting a __valid__ date from the date picker will close picker
4. Fixed test
Was tempted to use `ClickAwayController` and do away with `MctClickElsewhere` to simplify code base. Problem is that ClickAwayController triggers a click away when you click anywhere in document. For the date picker this is not ideal. Have a slight preference for conditionally dismissing after validation of selection. Prefer MctClickElsewhere's functionality in that it ignores clicks within the element it is attached to.
3. Command …

[Date Input] Addressed issues with date selector. Fixes #1000

---

platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js

Retrieve key from identifier service for all persist operations.
Fixes https://github.com/nasa/openmct/issues/1013

[Persistence] Use identifier service to get key

---

platform/commonUI/themes/espresso/res/sass/_constants.scss
platform/commonUI/themes/snow/res/sass/_constants.scss
platform/features/timeline/res/sass/_timelines.scss

Fixes #913 
* Scrollbar now always visible in Timeline tabular right area
* Splitters tightened up to take up less space 

R&I tweaks to Timeline scrollbar and splitters

---

platform/commonUI/browse/bundle.js
platform/commonUI/browse/src/BrowseController.js
platform/commonUI/browse/src/navigation/NavigateAction.js
platform/commonUI/browse/test/BrowseControllerSpec.js
platform/commonUI/browse/test/navigation/NavigateActionSpec.js
platform/commonUI/edit/src/actions/CancelAction.js
platform/commonUI/edit/test/actions/CancelActionSpec.js
platform/features/table/src/controllers/TableOptionsController.js

* Moved navigation policy check from `BrowseController` to `NavigateAction` allowing it to be triggered from anywhere that `NavigateAction` is used (including `CancelAction`).
* Refactored `BrowseController` to use `NavigateAction`
* Updated tests

[Edit Mode] Canceling edit mode with unsaved changes now shows confirmation dialog to user

---

platform/features/table/bundle.js
platform/features/table/res/templates/historical-table.html
platform/features/table/src/controllers/HistoricalTableController.js
platform/features/table/src/controllers/RealtimeTableController.js
platform/features/table/src/controllers/TelemetryTableController.js
platform/features/table/test/controllers/HistoricalTableControllerSpec.js

1. Process large historical data sets in batches, using a setTimeout to allow UI and other processes processor time
1. Small change to TelemetryTableController to prevent unnecessary telemetry subscriptions due to angular watch initialization calls.
1. Loading spinner on historical tables
1. Added tests

[Tables] #972 When processing large data sets periodically yield thread

---

bower.json
index.html
main.js
src/MCT.js
src/api/Type.js
src/api/api.js
test-main.js
tutorials/todo/bundle.js
tutorials/todo/todo.js

* Move types from a declarative to an imperative registration style
* Make MCT an EventEmitter such that lifecycle events (e.g. `start`) can be listened to. (Replaces the `runs` category-of-extension)
Work toward #462 / #463. Note that destination branch is for API prototypes.

[API Prototype] Type registration

---

platform/commonUI/general/res/sass/_constants.scss
platform/commonUI/general/res/sass/plots/_plots-main.scss

[Frontend] Fixes to un-squish plots
Fixes #1022
- min-height added to .gl-plot element.
- Added 5px to right side of holder-plot to fend off the scroll bar when it's visible.
- Moved plot value definitions out of _plots-main and into _constants and normalized naming.
Screenshot of expected result:
Note that this fix may result in some small plot views in Layouts suddenly getting scroll bars.

R&I un-squished plots fix

---

platform/commonUI/general/res/sass/controls/_buttons.scss
platform/commonUI/general/res/sass/user-environ/_layout.scss

Fixes
* #1014: Fixed color definition in _buttons.scss.
* #1019: Removed overflow: hidden from .l-edit-controls; this was a regression due to work in #987.

R&I fixes for Snow button colors and Timeline edit Add menu

---

platform/commonUI/general/res/sass/controls/_buttons.scss

fixes #1014
* Added .key-properties to .major to color the Edit button as intended;

Emphasis styling applied to Edit button properly

---

platform/commonUI/general/res/sass/_constants.scss

Set the min height for the plot element based on user feedback for
minimum plot size that they find useful.  Plot ticks may overlap
but that is expected to be fixed in a future release.
Fixes https://github.com/nasa/openmct/issues/1048
2. Unit tests included and/or updated with changes? N/A (style only change)

[Plot] Set min height

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/actions/SaveAction.js
platform/commonUI/edit/src/actions/SaveAsAction.js
platform/commonUI/edit/src/actions/SaveInProgressDialog.js
platform/commonUI/edit/test/actions/SaveActionSpec.js
platform/commonUI/edit/test/actions/SaveAsActionSpec.js

Show a blocking dialog while the save action is being performed.
Prevents users from pressing save a second time or performing
further actions while a save is in progress.
Fixes https://github.jpl.nasa.gov/MissionControl/vista/issues/362
Never ended up with a bug report in OpenMCT, just have seen users hitting walls because of this.  Very odd behavior results when they try and take other actions while saving.

[Save] Show blocking dialog

---

platform/commonUI/general/bundle.js
platform/commonUI/general/src/controllers/TimeRangeController.js
platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js

Problem was caused by blur behaviour being invoked before digest could take place.
The [blur behavior](https://github.com/nasa/openmct/blob/open1018-new/platform/commonUI/general/src/controllers/TimeRangeController.js#L267) in `TimeRangeController` is dependent on [a watch](https://github.com/nasa/openmct/blob/open1018-new/platform/commonUI/general/src/controllers/TimeRangeController.js#L282) having been triggered first. It's not triggered because a digest hasn't occurred by the time the [blur behavior](https://github.com/nasa/openmct/blob/open1018-new/platform/commonUI/general/res/templates/controls/datetime-field.html#L25) of the field is called in code.
Rather than investing time in structural changes to the Time Conductor at this time, I've just invoked a digest manually for now.
1. …

[Time Conductor] Bounds updated when date selected from date selector fixes #1018

---

bower.json
index.html
main.js
src/MCT.js
src/api/api.js
src/api/objects/LegacyObjectAPIInterceptor.js
src/api/objects/ObjectAPI.js
src/api/objects/README.md
src/api/objects/bundle.js
src/api/objects/object-utils.js
tutorials/grootprovider/groots.js

Adds the Object API prototype and a simple provider tutorial.
TODOS:

Api tutorial/objects

---

src/api/TimeConductor.js
src/api/TimeConductorSpec.js
src/api/api.js

Fresh PR with just API proposed in meeting of 06/29/2016. Included API proposal from meeting below. Note that this PR is based on previous iterations of a notional API captured in #1002
Merge target is api-tutorials
```javascript
/*
events:
'bounds'
'follow'
'system'
'timeOfInterest'
note: A 'system' event is always followed by a 'bounds' event.
Or more precisely, once a system event has been received, views should wait for
a bounds event before updating their view.  It's probably a good time to show a
loading indicator.
Can we assume that follow "true" + bounds = you should have received data via
subscription?  Nope, but for now, for most future cases, we can.  We know
predicted data that is stored as historic data will cause issues but we think
that is better addressed in the future.
We …
```

[Time Conductor] V2 Public API

---

bower.json
gulpfile.js
index.html
main.js
platform/commonUI/general/bundle.js
src/end.frag
src/start.frag
test-api.html

Changes build process to wrap main.js as a umd module so that it can be used with AMD, commonJS, and in native browser loading.  Also changes run call so that it places zero requirements on the document which it is rendered into.
Note that some stylesheets and other dependencies are still loaded asynchronously when the application is started; may need to address this separately.

[API] UMD Packaging

---

platform/core/src/services/Contextualize.js
platform/core/test/services/ContextualizeSpec.js

Check if domain objects are in edit mode before validating against their parent's composition; if they are in edit mode, do not expect consistency (and so do not warn about it.) Addresses #624 
Notably, this adds an implicit dependency between core and edit mode. Think this will be resolved by planned longer-term API/architecture changes, particularly to how context is represented (no longer a property of the object, but part of the information passed in to actions/views/etc), after which the `contextualize` service will simply be obsolete.

[Context] Remove excessive warnings

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/actions/SaveAsAction.js
platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js
platform/commonUI/edit/src/services/TransactionManager.js
platform/commonUI/edit/src/services/TransactionService.js
platform/commonUI/edit/test/actions/SaveAsActionSpec.js
platform/commonUI/edit/test/capabilities/TransactionalPersistenceCapabilitySpec.js
platform/commonUI/edit/test/services/TransactionManagerSpec.js
platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js

When persisting changes to domain objects from Edit mode via cloning, clear out any persistence tasks from the active transaction for objects that will be represented by clones when the Save operation completes. This prevents persistence calls from being made to the pre-cloned versions of the objects (which can cause errors, as seen in #1046), while avoiding the removal of necessary persistence calls (resolving the erroneous behavior from WARP referenced in #1059)
An intermediary `transactionManager` has been introduced (as an Angular service) to mediate between the TransactionalPersistenceCapability and the TransactionService. In particular, this provides a single place of knowledge about whether domain objects are or are not scheduled for persistence in the active transaction; this …

[Persistence] Clear transactions selectively

---

platform/commonUI/edit/src/actions/SaveAsAction.js
platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js
platform/commonUI/edit/src/services/TransactionService.js
platform/core/src/capabilities/PersistenceCapability.js
platform/core/test/capabilities/PersistenceCapabilitySpec.js

Remove domain objects from the active transaction when they
are refreshed, and use this from the SaveAsAction to prevent
saving unintended changes. Fixes #1046
Still to-do:

[Edit] Undirty objects on refresh

---

platform/commonUI/general/bundle.js
platform/commonUI/general/src/controllers/ClickAwayController.js
platform/commonUI/general/test/controllers/ClickAwayControllerSpec.js

* On click trigger digest via $scope.$apply rather than via $timeout as was occurring previously. The `ClickAwayController` attaches a dismiss event via `document.on('mouseup'...`. The `search-menu` sets the `ClickAwayController` active when the user clicks anywhere inside it, but the document event is also triggered. This means it is dependent on the order in which those two events are fired. 
Using `$timeout` meant that the document event was deferred until after click event inside the menu, causing the controller to be deactivated and the menu to be dismissed. Using `$apply` instead still triggers a digest, which is needed, but retains the necessary ordering of events due to its synchronous nature.
* Updated tests
2. Unit tests included and/or …

[Search] Amended ClickAwayController to trigger digest via $apply instead of $timeout.

---

example/notifications/src/DialogLaunchController.js
platform/commonUI/dialog/src/DialogService.js
platform/commonUI/dialog/test/DialogServiceSpec.js
platform/commonUI/edit/src/actions/SaveInProgressDialog.js
platform/commonUI/edit/test/actions/SaveActionSpec.js
platform/commonUI/edit/test/actions/SaveAsActionSpec.js
platform/commonUI/general/src/controllers/BannerController.js
platform/commonUI/notification/src/NotificationIndicatorController.js
platform/commonUI/notification/test/NotificationIndicatorControllerSpec.js
platform/entanglement/src/actions/CopyAction.js
platform/entanglement/test/actions/CopyActionSpec.js

Addresses need to be able to dismiss individual dialogs rather than having a single dismiss function on the DialogService.
1. `DialogService.showBlockingMessage()` - Returns an object with a dismiss() function.
2. Refactored code that was using above function
3. Updated tests

[Dialog Service] Dismiss individual dialogs. Fixes #254

---

app.js

Using the native way for disabling it as Express developers recommend here: http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header
New HTTP response (without the header):
- Unit tests included and/or updated with changes? N
- Changes have been smoke-tested? N

[API] "X-Powered-By" Express header disabled. Fixes #1036

---

test-main.js

Load all source files when running Karma's test suite; this
ensures that code coverage metrics are not invalidated by
missing files. Fixes #1090.
2. Unit tests included and/or updated with changes? Y (well, test runner)

[Tests] Load all sources

---

README.md

Added two paragraphs to the readme mentioning the ongoing API work with a link to the tracking task. The website will also link to this.

[Documentation] Add mention of new API to README

---

platform/commonUI/general/bundle.js
platform/commonUI/general/src/controllers/ClickAwayController.js
platform/commonUI/general/src/controllers/ToggleController.js
platform/commonUI/general/test/controllers/ClickAwayControllerSpec.js
platform/search/res/templates/search-menu.html
platform/search/res/templates/search.html

1. `ClickAwayController` reverted to using `$timeout`
2. `search.html` now uses `ToggleController` to show menu on dropdown button click
3. `search-menu.html` uses `MctClickElsewhere` to hide when user clicks outside the menu
2. Unit tests included and/or updated with changes? Y - ClickAwayControllerSpec reverted
3. Command line build passes? Y 
4. Changes have been smoke-tested? Y - Tested search menu to verify that it fixes #888, tested usages of `ClickAwayController` for any regressions, tested time conductor date selector for regressions of #1000

[search] Reverted previous change to ClickAwayController and fixed search menu hiding on search option selection. Fixes #888

---

platform/commonUI/general/bundle.js
platform/commonUI/general/src/directives/MCTTree.js
platform/commonUI/general/test/directives/MCTTreeSpec.js

Simplify synchronization of selection in tree with state passed-in, letting Angular deal with more of the specifics. Fixes #1008.
It's a little unclear why this was failing to begin with; the `$watch` on `$parent` wasn't firing when I'd expect it to. That said, the reason for doing this was essentially to replicate functionality already provided by Angular for synchronizing changes between an isolate scope and its parent. I'm comfortable with say "whatever was going on here, the Angular team has encountered and solved" instead of investing further time developing our own understanding.
There's a modest cost to this change, insofar as it introduces more watches (per tree, not per node). Think this cost is incidental.
This does not address any of the UX changes proposed for #1008; just …

[Tree] Simplify synchronization

---

src/adapter/bundle.js
src/adapter/policies/AdapterCompositionPolicy.js
src/api/composition/CompositionCollection.js
src/api/composition/DefaultCompositionProvider.js

WIP for containment API.
Notes:
* Think having `canContain` on CompositionCollection makes sense; that's where it's relevant.
* Delegating to composition provider is good for the cases where custom types have a custom provider (containment will often be a related concern in these cases)
* Requiring a custom provider for containment rules is _not_ such a good thing, I think. It's overkill for cases where you want to add new object types which don't need to do anything else special with their composition. Couple of options here:
* Expose DefaultCompositionProvider so that it can be overridden (makes things reasonably easy)
* Have somewhere else (type?) that DefaultCompositionProvider can look to. Downside is that when a custom provider is used and the containment rules specified on a type …

[API] Containment

---

gulpfile.js
karma.conf.js
package.json

Supports retention of test reports, https://developer.nasa.gov/ResourceProspector/warp/issues/191
* Add JSHint reporter for lint errors
* Move all reports to `dist/reports` to simplify retaining the relevant build artifacts

[Build] Normalize reporting for QA tasks

---

platform/commonUI/general/src/directives/MCTTree.js
platform/commonUI/general/test/directives/MCTTreeSpec.js

TreeView's observers will be called when the selected domain object changes, which can occur for one of two reasons:
1. Because a new value was set externally, from `mct-tree`.
2. Because a new value was selected, by the user.
One such observer is `mct-tree` itself, which needs to update scope to match the user's selection. In the latter case a call to `$apply` is needed from this observer, but in the former it is not (and causes an error.) However, when that case occurs, the value in scope will be up to date already (it was a watch that triggered the call to `treeView.value`) so no assignment or `$apply` is necessary.
Checking if scope is already up to date before invoking `$apply` therefore fixes #1114.
2. Unit tests included and/or updated with …

[Tree] Check for change before scope.$apply

---

platform/commonUI/edit/src/creation/LocatorController.js
platform/commonUI/edit/test/creation/LocatorControllerSpec.js

...as this will trigger a refresh of the mct-representation for
the tree, which will in turn create a new mct-tree instance,
resulting in any expanded/collapsed state being lost.
Fixes #1008.
Also normalizes some whitespace in the associated spec.

[Locator] Don't reset root unnecessarily

---

gulpfile.js
package.json

Adds a run of [nsp](https://nodesecurity.io/), the Node Security Platform, to flag any known vulnerabilities associated with dependencies as part of the "verify" build step. Addresses #1130

[Build] Check dependencies for vulnerabilities

---

docs/src/tutorials/index.md

Just stumbled upon this, in the 2nd bundle.js block the diff was incomplete. It's a minor thing but it can save you a few seconds of confusion when you move through the tutorial & progressively update your code.
1. Changes address original issue? - Y
2. Unit tests included and/or updated with changes? - N/A, it's a documentation formatting fix
3. Command line build passes? - N/A
4. Changes have been smoke-tested? - N/A

[Documentation] Fix added lines in tutorial

---

docs/src/architecture/platform.md

"Framework.md" was showing a 404 error. Changed it to "framework.md", which is the actual file name.

[Documentation] Fixed typo

---

platform/search/src/controllers/SearchMenuController.js
platform/search/test/controllers/SearchMenuControllerSpec.js

* Changes address original issue?
* Yes. 'All' gets checked when all filters are unchecked.
* Unit tests included and/or updated with changes?
* Unit test for SearchMenuController has been updated to test for these changes, and succeeds when run. 
* Command line build passes?
* Yes.
* Changes have been smoke-tested?
* Yes.

[Search] 'All' checked upon no filters. Fixes #1117

---

.gitignore

I was testing this repo, and when a opened a file using my favorite editor (vim) I saw that you forgot (or don't need) to put [`swp`](http://vimdoc.sourceforge.net/htmldoc/recover.html) files into the `.gitignore`.
Changes address original issue? - N/A
Unit tests included and/or updated with changes? - N/A, it's a adding type of file to `.gitignore`
Command line build passes? - N/A
Changes have been smoke-tested? - N/A

Add .swp to git ignore

---

platform/commonUI/general/res/sass/_constants.scss
platform/commonUI/general/res/sass/_views.scss
platform/commonUI/general/res/sass/lists/_tabular.scss
platform/features/table/res/templates/historical-table.html
platform/features/table/res/templates/mct-table.html
platform/features/table/res/templates/rt-table.html

- For #1166 and #967. 
- Implements a general approach to a "control bar" element that can be included in views.
- Example markup can be found in branch open967a. 
- Required by #967.

Review and integrate generalized control-bar styling for views

---

package.json

Change version specifier for phantomjs-prebuilt to skip 2.1.12, which has several reported issues installing on Linux (and is similarly failing to install in one of our CI environments.) Fixes #1176
It would be helpful in particular if my usage of npm's [version syntax](https://docs.npmjs.com/misc/semver) is double-checked for correctness and conciseness; haven't used this kind of expression before.

[Build] Skip phantomjs-prebuilt 2.1.12

---

platform/commonUI/edit/bundle.js

Removed `window` from the `editModeBlackList`.
This allows the _New Tab_ button to be used while in edit mode.
1. Changes address original issue?
- Yes
1. Unit tests included and/or updated with changes?
- No
1. Command line build passes?
- Yes
1. Changes have been smoke-tested?
- Yes

[Context Menu] New Tab button available in edit mode. #843

---

docs/src/guide/index.md

The forms bundle contains controls that are not listed in the guide; I've added them together with some short descriptions.
Changes address original issue? - it's a documentation change - not tracked
Unit tests included and/or updated with changes? - N/A
Command line build passes? - N/A
Changes have been smoke-tested? - N/A

[Documentation] Add extra controls to developer guide

---

bower.json
main.js
test-main.js

...including changes to filename associated with that version.
Fixes #1183 

[Build] Update to es6-promise 3.3.0

---

gulpfile.js
package.json

Reverts nasa/openmct#1134
This is causing build failures on hulk because NSP servers can't be reached.
```
[10:11:13] 'nsp' errored after 53 s
[10:11:13] Error in plugin 'gulp-nsp'
Message:
(+) Error: Client request error: socket hang up
```
There's [limited value](https://github.com/nasa/openmct/issues/1130#issuecomment-241598884) to these checks, in any event.

[Build] Revert check dependencies for vulnerabilities

---

platform/commonUI/browse/src/navigation/NavigateAction.js
platform/commonUI/browse/test/navigation/NavigateActionSpec.js
platform/commonUI/edit/src/actions/EditAction.js
platform/commonUI/edit/src/services/TransactionService.js
platform/commonUI/edit/test/actions/EditActionSpec.js

Fixes #1080 
* Removed navigation listener from EditAction which previously cancelled edit mode on navigation
* Added call to `EditorCapability.cancel()' to `NavigateAction`. Although this mixes edit and browse concerns, it does not introduce a hard dependency on edit mode. Another approach I considered was a decorator for the `NavigateAction` in the edit bundle, but decorating actions is awkward in the current API, and would have added indirection that would make the code harder to follow.
* Added a new test to `NavigateActionSpec`

[Edit Mode] Fixed issue with save dialog not being displayed for new objects after mutation

---

platform/commonUI/general/res/sass/_views.scss

Removed the Export buttons from objects that support them, when that object is in a Layout. See #1202 for more info on why. 
Fixes #1202
CSS modded

[Frontend] Removed Export buttons from objects when in a Layout

---

main.js
package.json
test-main.js

It appears from MrRio/jsPDF#122 that there are (or have been) various RequireJS issues with that library. The `define` call in the minified version looks a little different, but since this is minified it's not clear what the root cause is. I'm unable to reproduce the issue when switching to the unminified version, and we put this through our own minification step, so I'm satisfied with that.
Included an intermediary commit with an intermediate version number to allow this to be tagged and included as a release; #1208 effects any version of VISTA/WARP which depends on a specific Open MCT build, so these will need a new build to …

[Build] Fix jsPDF dependency

---

bower.json

Specify jsPDF minor version to avoid updating to v1.3.0, which appears to
have problems with requirejs bundling.
Fixes https://github.com/nasa/openmct/issues/1214
@VWoeltjen this seems to fix the issue, and I'm also wondering if it renders 1208b unnecessary.  I'm going to see if we can back that change out and still have this work.  But I can't just straight revert it because of the version changes.
Not yet ready for integration.

[Bower] specify jspdf minor version

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/res/templates/edit-action-buttons.html
platform/commonUI/edit/src/controllers/EditActionController.js

Went back to the edit menu cause it felt like I left the prev issue unfinished. Fixes https://github.com/nasa/openmct/issues/1198
There's a bit of a logic change. This here:
`ng-class="{ major: $index === 0 && saveActions.length === 0 }"`
Was not kept. Used to be `major: $index === 0` before the save button dropdown changes, but back then there was no separation between save actions and other actions, so I'm almost certain that it was just so that the save button shows up as major. 
Now that the save buttons show up as major anyway and are first in the menu, this doesn't seem to be useful anymore. It can only be useful if we have an edit context where we don't allow the user to save changes (no save actions available), which is something that doesn't make much sense (unless we add …

[Edit] Switch other edit actions to mct-control

---

index.html

Enable example bundles in the default build. Addresses regression in development environments introduced by #1212, wherein Sine Wave Generator became an unknown object type.
1. Changes address original issue? PR is self-reporting of issue
2. Unit tests included and/or updated with changes? N/A (changes out of scope for unit test)

[API] Enable example bundles

---

API.md
index.html
platform/core/bundle.js
platform/features/my-items/bundle.js
src/api/objects/ObjectAPI.js
src/api/objects/RootObjectProvider.js
src/api/objects/RootRegistry.js
src/api/objects/test/RootObjectProviderSpec.js
src/api/objects/test/RootRegistrySpec.js
src/defaultRegistry.js

Sets up for the  expectation that all roots should be opt-in configuration items by disabling the "my items" root by default and removing the `removeRoot` method from the public API.  Also adds support for asynchronous definition of roots by passing a function to `addRoot`.  Updated API documentation which was previously inaccurate.  
@VWoeltjen decided not to add an interface for RootProvider at this time.  Main use case was for ordering down the road which currently can be controlled by careful registration.  Will see how this works for now.
Added tests around root registration to verify implementation.
Sending to @VWoeltjen for …

Async root registration

---

platform/commonUI/general/res/sass/controls/_menus.scss

Update the z-index of the save drop-down element so that it is always in front.
Fixes #1205 
**Changes address original issue?** Yes
**Unit tests included and/or updated with changes?** N/A
**Command line build passes?** Yes
**Changes have been smoke-tested?** Yes

[Frontend] Ensure stacking order of save drop-down Fixes #1205

---

platform/core/bundle.js
platform/core/src/models/RootModelProvider.js
platform/core/test/models/RootModelProviderSpec.js

For #1264, the legacy RootModelProvider was removed, as functionality for roots was being provided by the new API and/or in the adapter layer.
However, the important functionality of the RootModelProvider (getting initial versions of object models before anything else has been persisted) is not actually replicated by the new adapter components. As a consequence, when running Open MCT without an existing version of My Items persisted, this comes up as a missing object instead, #1284. Restoring RootModelProvider resolves that issue.

[Roots] Restore legacy root provider

---

gulpfile.js

Remove 'install' step from gulp develop task, instead
run 'stylesheets' to build stylesheets.  Result is much
faster execution of gulp develop as is expected for
a development tool.
Fixes https://github.com/nasa/openmct/issues/1268.
2. Unit tests included and/or updated with changes? N/A, build only.

[Dev] develop with stylesheets

---

src/adapter/bundle.js
src/adapter/services/MissingModelCompatibilityDecorator.js
src/api/objects/ObjectAPI.js

Implements an adapter to ensure that objects registered via the new API can be fetched via the model service.  Resolves a bug where objects provided via the new API would not be included in search results.
The changes here to the ObjectProvider `get` signature bring us back in line with API docs, but I need to look at the WARP code and see if this will cause a regression with the new provider.

Add modelService compatibility adapater

---

API.md
src/MCT.js
src/api/Type.js
src/api/api.js
src/api/types/Type.js
src/api/types/TypeRegistry.js

Adds adapter behavior to support type registration via the new API, addressing #1294, and fixes some documentation, addressing #1295.
2. Unit tests included and/or updated with changes? No, but see #1218

[API] Fix type registration

---

docs/src/tutorials/index.md

`ExampleTelemetryProvider` references `ExampleTelemetrySeries` module. It is actually located in the same src folder.

[Documentation] Fixed module reference

---

platform/core/src/services/Topic.js
platform/representation/src/MCTRepresentation.js
platform/representation/test/MCTRepresentationSpec.js
src/api/objects/LegacyObjectAPIInterceptor.js

Listen for mutation instead of watching the `modified` timestamp for a given domain object. This causes changes on separate model instances to be correctly reflected by legacy views, fixing #1303.

[Views] Update representations on mutation

---

platform/features/fixed/bundle.js
platform/features/layout/src/FixedController.js
platform/features/layout/test/FixedControllerSpec.js

Previously users would see blank values for grid size
even though a default was applyied.  Users will now
see default values for grid size which should prevent
them from accidentally changing grid size.
Fixes https://github.com/nasa/openmct/issues/1285
2. Unit tests included and/or updated with changes? N/A (config only
Sending to @akhenry for R&I.

[Fixed] Specify default layout grid

---

platform/commonUI/general/res/sass/_global.scss
platform/commonUI/general/res/sass/_main.scss

Fixes #1315
For https://developer.nasa.gov/ResourceProspector/warp/issues/219
In general, the CSS expects .s-status-missing to be applied to mct-representations that enclose elements that display a glyph icon. Tree/search items, object-header, grid items and Inspector path elements have all been handled. Here's the sass in _global.scss with notes as to specific applications.
.s-status-missing {
// Labels. Expects .s-status-missing to be applied to mct-representation that contains
// .t-object-label
.t-object-label .t-item-icon:before {
content: $glyph-icon-object-unknown;
}
// Item, grid item. Expects .s-status-missing to be applied to mct-representation that contains .item.grid-item
.item .t-item-icon-glyph:before {
content: $glyph-icon-object-unknown;
}
// Object header. Expects …

Add styling for .s-status-missing

---

gulpfile.js
package.json

Records any style violations to `dist/reports/checkstyle`. Note that `jscs-html-reporter` doesn't allow file path/name to be specified, so an explicit move is triggered after the reporting step is finished.

[Build] Output JSCS reports

---

platform/features/conductor-v2/conductor/bundle.js
platform/features/conductor-v2/conductor/res/templates/time-conductor.html
platform/features/conductor-v2/conductor/src/ui/TimeConductorController.js
platform/features/conductor-v2/conductor/src/ui/TimeConductorControllerSpec.js
platform/features/plot/src/PlotController.js
platform/features/plot/test/PlotControllerSpec.js

Currently large delta with master due to it being based on open1193 / #1287 which has not been merged yet. Should either change base to open1193 for review, or wait until #1287 is merged.

[Time Conductor] Persist Time Conductor state in URL

---

platform/commonUI/browse/src/BrowseController.js

In `BrowseController`, `$scope.treeModel` [was being initialized](https://github.com/nasa/openmct/blob/6a32c53d0571193288e5f0862b798bfc2e248c6d/platform/commonUI/browse/src/BrowseController.js#L55) to an invalid default object. This caused issues downstream [in TreeNodeView](https://github.com/nasa/openmct/blob/6a32c53d0571193288e5f0862b798bfc2e248c6d/platform/commonUI/general/src/ui/TreeNodeView.js#L106) when valid `domainObject` methods like `getCapability` were invoked. 
I have changed `BrowseController` to initialize `$scope.treeModel` to `undefined`. [Existing guard code in TreeNodeView](https://github.com/nasa/openmct/blob/6a32c53d0571193288e5f0862b798bfc2e248c6d/platform/commonUI/general/src/ui/TreeNodeView.js#L106) prevents `getCapability` from being invoked on undefined objects. …

[Navigation] Fix errors appearing in console on application load

---

platform/commonUI/edit/test/actions/SaveAsActionSpec.js

This fixes https://github.com/nasa/openmct/issues/1361
After https://github.com/nasa/openmct/commit/2708562872aa2f8e78450fb408ebaabb449bc0b0 the cloned object is being used for more than passing around so I've mocked it separately in the spec.
- Unit tests included and/or updated with changes? Y
- Changes have been smoke-tested? No runtime behavior altered, tests pass.

[Test Fix] Mock cloned object in SaveAsActionSpec

---

platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/representers/EditRepresenter.js
platform/commonUI/edit/test/representers/EditRepresenterSpec.js

Set key on represent so that commit function can properly persist
configuration per object type.
At the same time, rewrote EditRepresenter to remove some unused dependencies and added tests (previously there were none).
Fixes https://github.com/nasa/openmct/issues/1367
Sending to @VWoeltjen.

[Edit] Set key on represent

---

API.md
src/MCT.js
src/plugins/plugins.js

Expose functions for registering useful legacy plugins using the current plugin API. This allows simple inclusion of these common features in both application variants and in tutorials.
1. Changes address original issue? Partial (see above)
2. Unit tests included and/or updated with changes? No (see #1218)

[Plugins] Expose plugin functions

---

platform/telemetry/src/TelemetryHandle.js
src/api/telemetry/LegacyTelemetryProvider.js

Updates the legacy provider and the telemetry subscription to use series.getDatum when it is available instead of recreating datums manually.  
2. Appropriate unit tests included? N/A, no tests for legacy adapters.

Use series.getDatum when available

---

API.md
src/api/objects/LegacyObjectAPIInterceptor.js
src/api/objects/MutableObject.js
src/api/objects/ObjectAPI.js

Address API review followup items from #1122:
> - Look at renaming `mainViews` to `views` at making it [more like a namespace](https://github.com/nasa/openmct/pull/1212#discussion_r81480468)
Considered, but don't see a strong reason for this, felt that the "more namespace-like" approach might be confusing.
> - [Link to](https://github.com/nasa/openmct/pull/1212#discussion_r81480528) documentation for using default solution for composition (the `composition` property)
Added and linked to this documentation
> - [Normalize references](https://github.com/nasa/openmct/pull/1212#discussion_r81658898) to `openmct` 
Appears to have been completed under maintenance
> - Remove global singleton [objectEventEmitter](https://github.com/nasa/openmct/pull/1212#discussion_r81882085)
Done
> - Return …

[API] Address review followup items

---

docs/src/guide/index.md
platform/features/plot/README.md
platform/features/timeline/bundle.js
platform/features/timeline/res/templates/resource-graphs.html
platform/features/timeline/src/chart/Canvas2DChart.js
platform/features/timeline/src/chart/GLChart.js
platform/features/timeline/src/chart/MCTTimelineChart.js
platform/features/timeline/src/controllers/graph/TimelineGraph.js
platform/features/timeline/src/controllers/graph/TimelineGraphRenderer.js
platform/features/timeline/test/chart/Canvas2DChartSpec.js
platform/features/timeline/test/chart/GLChartSpec.js
platform/features/timeline/test/chart/MCTTimelineChartSpec.js

Make a separate chart directive for drawing resource graphs in timelines.  This
is in preparation for a new plot bundle which will make a large number of
changes to the drawing API to support new features.  By separating
code, there will be no impact to the timeline when the new plot features are
added.
1. Changes address original issue? (as stated here)
Assigning to @akhenry for review & integrate.

[Reorg] Make timeline-specific chart directive

---

docs/src/tutorials/index.md

`glyph` properties were still mentioned in the explanations. I'm not sure the custom font set part still applies; if it does let me know and I'll bring it back.

[Tutorial] Replace glyph mentions with cssclass

---

docs/src/architecture/framework.md

Fixed file name "Platform.md" to "platform.md". "Platform.md" was giving a 404 error when clicked, in github and in the official site as well.
Unit tests included and/or updated with changes? N/A - documentation changes only

[Documentation] Fixed filename

---

platform/features/table/src/TableConfiguration.js
platform/features/table/test/TableConfigurationSpec.js

Temporary fix for #1382. no longer attempts to persist table configuration for non-editable objects.
A more permanent fix requires reconsideration of the method used to communication object configuration changes between views as per [discussion in #1382](https://github.com/nasa/openmct/issues/1382#issuecomment-271383505).
* Unit tests included and/or updated with changes? Y - Fixed existing unit tests. No new tests defined due to small scope of change, and mutation being removed in future as per #1382

[Tables] Do not persist column configuration for non-editable objects

---

src/api/objects/LegacyObjectAPIInterceptor.js
src/api/objects/MutableObject.js

Fixes some small bugs in the object api where it was using the incorrect key properties.
1. Changes address original issue? N/A (as reported here)

[API] Use proper key format

---

gulpfile.js

Skip optimize in dev environment to speed up project rebuilds.  Very helpful
when integration testing openmct.js build artifact.
This came out of the api-tutorial sprint, by setting NODE_ENV=development you can cut down rebuild times.
1. Changes address original issue? N/A, reported in this PR
2. Unit tests included and/or updated with changes? N/A, build only change

[Build] Skip optimize in dev environment

---

platform/framework/src/Constants.js
platform/framework/src/FrameworkInitializer.js
platform/framework/src/FrameworkLayer.js

Stop application from requesting bundles.json at first load.  This was
confusing to some external developers who would see an error in the
log and not know the cause.
1. Changes address original issue? N/A no original issue
2. Unit tests included and/or updated with changes? Y (still work)

Stop loading bundles.json

---

platform/commonUI/edit/src/capabilities/TransactionCapabilityDecorator.js
platform/core/src/capabilities/CoreCapabilityProvider.js
platform/persistence/queue/src/QueuingPersistenceCapabilityDecorator.js
platform/persistence/queue/test/QueuingPersistenceCapabilityDecoratorSpec.js
src/adapter/capabilities/APICapabilityDecorator.js
src/adapter/runs/AlternateCompositionInitializer.js
src/adapter/services/Instantiate.js
src/api/telemetry/LegacyTelemetryProvider.js
src/api/telemetry/TelemetryAPI.js
src/api/telemetry/TelemetryValueFormatter.js

A set of new-api fixes pulled out of the api-tutorial-sprint.  Updates Telemetry Provider API to separate support checks for historical and realtime, updates metadata handling, removes unused code, and ensures that the legacy provider is won't prevent utilization of new-style telemetry providers.
2. Unit tests included and/or updated with changes?  N/A, deferred.

Api updates

---

platform/search/res/templates/search-item.html

Fix search item so that navigation occurs after clicking on
a search result, while still properly preventing navigation
when required.
Related to #1366
1. Changes address original issue? (as reported here)

[Search] Allow navigation from results

---

platform/features/table/src/controllers/TelemetryTableController.js
platform/features/table/test/controllers/TelemetryTableControllerSpec.js

* Replaced `getDomainObjects()` with a member function called `getTelemetryObjects()`. Moved `filterForTelemetry` that encapsulates the logic for deciding what to subscribe to / request telemetry for.
* Renamed `newObject` to `domainObject`, 
* Added some tests for specific issue to catch regressions.

[Tables] Subscribe to parent if a telemetry object, or children, but not both

---

platform/features/conductor/utcTimeSystem/src/UTCTimeSystem.js
src/plugins/plugins.js

This addresses the weirdness seen in #1434 which was due to default bounds being cached and not re-calculated based on 'now()'. There are a number of other issues at play, which have been added to the original issue and will be addressed subsequently.

[Time Conductor] Removed caching of UTC Time System defaults

---

platform/features/autoflow/plugin.js
platform/features/autoflow/res/templates/autoflow-tabular.html
platform/features/autoflow/src/AutoflowTableLinker.js
platform/features/autoflow/src/AutoflowTabularController.js
platform/features/autoflow/src/MCTAutoflowTable.js
platform/features/autoflow/test/AutoflowTableLinkerSpec.js
platform/features/autoflow/test/AutoflowTabularControllerSpec.js
platform/features/autoflow/test/MCTAutoflowTableSpec.js
src/plugins/plugins.js

Brings the autoflow tabular view over to open source. Not installed/enabled by default. Can be installed like so -
```javascript
openmct.install(openmct.plugins.AutoflowView());
```
In WARP it was uniquely associated with the `warp.packet` type. For now I've removed the type restriction, so it applies to any object with telemetry to make it usable for the demo. I'm not sure how useful it is as a general purpose telemetry view though, especially as the selected view is not persisted with objects. 
We probably want to define a new 'autoflow' object type, as we did with fixed position? That said, it's not really radically different to a fixed position display, but with fewer options...
It would be a good default view for a generic 'telemetry group' type, but this doesn't exist :)

[Features] Added Autoflow Tabular to open source features. Fixes #1469

---

platform/features/conductor/core/res/sass/_time-conductor-base.scss

For #1415: adds grab/pan affordance (for Fixed Time mode only) UI elements to Time Conductor ticks area.
Grippys always display
Highlight on hover

Add grab affordance to Time Conductor ticks

---

src/MCT.js

Removed exposed API classes from the public API. Question mark about whether we should be exposing API that doesn't work / isn't final right now though?

[API] Removed API classes from Open MCT prototype. Fixes #1293

---

docs/src/guide/index.md
platform/commonUI/edit/bundle.js
platform/commonUI/edit/src/creation/CreateWizard.js
platform/commonUI/edit/src/policies/EditPersistableObjectsPolicy.js
platform/commonUI/edit/test/creation/CreateWizardSpec.js
platform/commonUI/edit/test/policies/EditPersistableObjectsSpec.js
platform/containment/bundle.js
platform/containment/src/ComposeActionPolicy.js
platform/containment/src/CompositionModelPolicy.js
platform/containment/src/CompositionMutabilityPolicy.js
platform/containment/src/CompositionPolicy.js
platform/containment/src/PersistableCompositionPolicy.js
platform/containment/test/ComposeActionPolicySpec.js
platform/containment/test/CompositionModelPolicySpec.js
platform/containment/test/CompositionMutabilityPolicySpec.js
platform/containment/test/CompositionPolicySpec.js
platform/containment/test/PersistableCompositionPolicySpec.js
platform/entanglement/src/services/CopyService.js
platform/entanglement/src/services/LinkService.js
platform/entanglement/src/services/MoveService.js
platform/entanglement/test/services/CopyServiceSpec.js
platform/entanglement/test/services/LinkServiceSpec.js
platform/entanglement/test/services/MoveServiceSpec.js
platform/features/layout/src/LayoutCompositionPolicy.js
platform/features/layout/test/LayoutCompositionPolicySpec.js
src/adapter/policies/AdapterCompositionPolicy.js

This work is in support of the updated live demo, but also meets a wider need to support non-editable displays and other objects. 
Adds two new policies - the `EditPersistableObjectsPolicy` prevents editing of objects if they cannot be persisted, and `PersistableCompositionPolicy` which prevents composition of objects if they are not persistable. This means for example that objects like folders in non-editable persistence spaces cannot be selected as a save destination in the locator.

[Persistence] Prevent editing of objects that cannot be saved. Fixes #1483

---

platform/entanglement/src/actions/AbstractComposeAction.js
platform/entanglement/src/actions/CancelError.js
platform/entanglement/src/actions/CopyAction.js
platform/entanglement/test/actions/AbstractComposeActionSpec.js
platform/entanglement/test/actions/CopyActionSpec.js
platform/entanglement/test/actions/LinkActionSpec.js
platform/entanglement/test/actions/MoveActionSpec.js

Small follow-on to @BogdanAlexandru's PR #1457 (uses a subclass of Error instead of an ad hoc object to differentiate errors) addressing #1456 

[Duplicate] Differentiate between user cancellation and other errors

---

CONTRIBUTING.md

Around line 143, gave "constants" its own bullet point. Although it is a form of variable or field, it does form a separate style element with a different guideline. It's also easier to find when skimming this way.
Author Checklist:
Changes address original issue? N/A
Command line build passes? N/A
Changes have been smoke-tested? N/A

[Documentation] Edit for clarity and style

---

platform/core/src/capabilities/PersistenceCapability.js
platform/core/src/runs/TransactingMutationListener.js

Prevents unnecessary persistence after model refresh.
Also rejects calls to `PersistenceCapability.refresh` if no model is returned.

[Edit] Only persist on mutation if model has actually changed locally

---

platform/features/table/src/TableConfiguration.js
platform/features/table/test/TableConfigurationSpec.js
platform/features/table/test/controllers/TelemetryTableControllerSpec.js

Use formatter to parse format datum such that source remapping
is properly handled.  Otherwise, tables would read incorrect fields and in the case of the tutorial, a lot of data would be removed as duplicate when it wasn't duplicate.
To andrew for review and integrate.

[Table] parse/format with datum

---

src/api/composition/DefaultCompositionProvider.js

Track the updated composition of an object before notifying any
listeners.  Otherwise, any composition listener that mutates the
object would cause an infinite loop.
Detected in implementation of the new plot.
1. Changes address original issue? Y (as reported here)
2. Unit tests included and/or updated with changes? N, new API tests deferred.

[API] track composition before notifying listeners

---

platform/commonUI/browse/src/BrowseController.js

When no path is specified, don't throw error.  Navigate
to default, as expected.
When navigating to root, navigate to the last child
of root instead.  This handles cases where DEFAULT_PATH
is not found (e.g. deployments without "mine").
@akhenry small change to reduce console errors.
1. Changes appear to address issue? Y (as reported here)
2. Appropriate unit tests included? Y

[Browse] Handle missing path and nav to root

---

API.md
example/generator/plugin.js
src/api/types/Type.js
src/api/types/TypeRegistry.js

Change label to name, log a warning to console if a typeDef
is registered with a label.
Fixes https://github.com/nasa/openmct/issues/1568.
2. Unit tests included and/or updated with changes? N/A, issues exist for API test backfill

[Types] label -> name

---

src/plugins/timeConductor/plugin.js

Anchor tag in the "you need some options" error message for Time Conductor is not quite correct.
1. Changes address original issue? N/A (PR documents issue)
2. Unit tests included and/or updated with changes? N/A (changes to link only)

[Time Conductor] Fix link in error message

---

src/api/telemetry/TelemetryAPI.js

Ensure telemetry request options always have a certain number
of fields-- start, end, and domain.  This allows telemetry providers
to implement necessary filtering for these types of requests.
These properties were not consistently applied, so was running into problems implementing new telemetry adapters with new APIs.  Previously this was added by the conductor compatibility decorator.
@VWoeltjen sending your way for feedback.
1. Changes address original issue? As represented here, yes
2. Unit tests included and/or updated with changes? N/A, deferred currently.

[Telem] ensure request has minimum fields

---

platform/commonUI/formats/src/UTCTimeFormat.js
src/adapter/actions/ActionDialogDecorator.js
src/adapter/capabilities/AlternateCompositionCapability.js
src/adapter/directives/MCTView.js
src/api/composition/CompositionCollection.js
src/api/telemetry/TelemetryAPI.js
src/plugins/utcTimeSystem/LocalClock.js

Hey, I was trying to understand the code base. I feel instead of `jshint` we can use [`eslint`](http://eslint.org) or [`standardjs`](https://standardjs.com/). And have a pre-commit hook that can fix linting issues automatically whenever possible (including spaces, etc).
I tried both eslint and standard and found a bunch of errors. With this PR I am intending to remove unused variables from the codebase, with two exceptions, because I wasn't sure, should I do that or not? If yes, the I will incorporate that as well in the PR.
```
DefautlComposotionProvider.js
Line 154: 'childId'
Line 171: 'child'
```
``` 
LegacyObjectAPIInterceptor.js
Line 82: 'object'
```
Also, I saw that `four spaces` is defined in `CONTRIBUTING.md`. And as I understand, generally `two spaces` is a convention instead. …

chore: Remove unsed variables from codebase

---

platform/search/bundle.js
platform/search/src/services/GenericSearchProvider.js
platform/search/test/services/GenericSearchProviderSpec.js

Use private parts of new composition API for generic search indexer
so that all objects are properly accessible in search results.
Also prevent ROOT object from getting indexed but still traverse
composition.  That way, "The root object" no longer shows in search
results.
Updated tests to cover changes.
Fixes #1579

[Search] Use new composition in search

---

README.md

Since protractor was removed, remove references in readme.

[README] Remove reference to protractor

---

gulpfile.js
src/about.frag
src/start.frag

Small follow-on to #1598; removes obsolete comment from `start.frag`, moves version header into a separate file.
1. Changes address original issue? Y (completes work on #1541)

[Build] Remove/reorganize version headers

---

index.html

Supports #1550 (using this change for debugging there)
Now that Time Conductor is more consistently in use, I think it would be useful to have it enabled by default in dev environments - it's the more common case.
1. Changes address original issue? N (but supports various Time-related issues)
2. Unit tests included and/or updated with changes? N (changes out of scope for unit tests)

[Time Conductor] Enable time conductor in dev environment

---

platform/commonUI/general/res/sass/controls/_messages.scss
platform/commonUI/general/res/sass/user-environ/_layout.scss

For #1603, removes processor intensive CSS keyframe animations:
- Removed animations associated with transitioning from browse to edit mode.
- Removed border-color animation used during edit mode. Chose not to reimplement animation via other means at this time.
- Other keyframe animations (such as .pulse used in the Play/Pause button) were left alone: they animate opacity of an object and weren't creating any processor issues when inspected via top.
1. Changes have been smoke-tested? Y, via inspection of Chrome CPU via top running in terminal

Review and merge no-keyframe-anims branch

---

platform/search/res/templates/search.html

Fixes #1569
The fix here involves tabindex. The search input has been set to a very high tabindex value, which will allow it to still be tabbable, but after other elements on screen, most notably form elements in the overlay. 
When Time Conductor is enabled, those form fields will be tabbed into after the elements in the overlay dialog. There does not appear to be any pure CSS way to limit tab indexing to a given container or context; most solutions I saw involve using JavaScript to "redirect" the tab target when leaving a given field. Here's an interesting article: https://bitsofco.de/accessible-modal-dialog/

Fixed tabbing in overlay forms

---

example/imagery/plugin.js
platform/features/imagery/src/controllers/ImageryController.js
platform/features/imagery/test/controllers/ImageryControllerSpec.js

Adds a historical and lad imagery provider to the example imagery source so that @prestonjcrowe can develop his historical view against this provider.
Updates the standard imagery view to request lad telemetry, and updates specs to cover this case.
1. Changes address original issue? Y (as reported here)
@VWoeltjen your way for integration.

Example historical imagery

---

docs/src/guide/index.md
platform/commonUI/general/res/sass/_global.scss
platform/commonUI/general/res/sass/controls/_controls.scss
platform/commonUI/general/res/sass/user-environ/_tool-bar.scss
platform/forms/README.md
platform/forms/bundle.js
platform/forms/res/templates/controls/numberfield.html

Adds a "numberfield" input to mct-control, similar to "textfield". Supports min, max and step properties.
@larkin If we could get this into master soon, that'd be great so that @adoubekk can use it in his work.

Review and integrate new Number input for mct-control

---

bower.json
openmct.js
platform/commonUI/general/res/sass/controls/_controls.scss
platform/features/clock/bundle.js
platform/features/clock/src/controllers/ClockController.js
platform/features/clock/test/controllers/ClockControllerSpec.js
platform/forms/bundle.js
platform/forms/res/templates/controls/autocomplete.html
platform/forms/src/controllers/AutocompleteController.js
platform/forms/test/controllers/AutocompleteControllerSpec.js
test-main.js

Addresses #1273 
- Added `autocomplete` control. To use it just need to pass `options` as either an array of strings or an object with `name` and `value`.
- User will be able to set timezone via autocomplete control. Default timezone is UTC.

[CLOCK] Allow clock to set timezone with autocomplete dropdown option.

---

platform/features/fixed/bundle.js
platform/features/layout/res/templates/elements/line.html
platform/features/layout/src/FixedController.js
platform/features/layout/src/FixedDragHandle.js
platform/features/layout/src/FixedProxy.js
platform/features/layout/src/elements/BoxProxy.js
platform/features/layout/src/elements/ElementProxy.js
platform/features/layout/src/elements/ImageProxy.js
platform/features/layout/src/elements/LineHandle.js
platform/features/layout/src/elements/LineProxy.js
platform/features/layout/src/elements/ResizeHandle.js
platform/features/layout/src/elements/TelemetryProxy.js
platform/features/layout/src/elements/TextProxy.js
platform/features/layout/src/elements/UnitAccessorMutator.js
platform/features/layout/test/FixedControllerSpec.js
platform/features/layout/test/FixedDragHandleSpec.js
platform/features/layout/test/FixedProxySpec.js
platform/features/layout/test/elements/ElementProxySpec.js
platform/features/layout/test/elements/LineHandleSpec.js
platform/features/layout/test/elements/LineProxySpec.js
platform/features/layout/test/elements/ResizeHandleSpec.js
platform/features/layout/test/elements/UnitAccessorMutatorSpec.js

Addresses issue #1405 
In the toolbar for the fixed position layout, adds x, y position and height/width inputs for box, image, text, and telemetry, and endpoint coordinate inputs for lines. Incorporates new numberfield controls. Currently works in terms of grid units only, no option to spectify size in pixels.

[Fixed Position] Add numerical inputs for size and position of elements

---

platform/commonUI/general/src/directives/MCTResize.js
platform/commonUI/general/test/directives/MCTResizeSpec.js

Prevent MCTResize from triggering a callback after the scope has been destroyed.
Fixes https://github.com/nasa/openmct/issues/1509
Note that circleci is still broken (#1639), working on a fix, but this does validate locally.

[Resize] don't trigger callback after being destroyed

---

platform/commonUI/browse/src/BrowseController.js
platform/features/conductor/core/res/templates/mode-selector/mode-menu.html
platform/features/conductor/core/src/ui/TimeConductorController.js
src/adapter/runs/TimeSettingsURLHandler.js
src/adapter/runs/TimeSettingsURLHandlerSpec.js

Updates the Time Controller UI and Time Settings URL Handler; They're now a little smarter about observing the state of the time API and not causing excessive changes.  Should reduce the number of bounds events triggered by regular usage.
Resolves #1636.  Also resolves a bug with bookmark based navigation where certain changes would not apply.  Still retains functionality where navigating to a bookmark that does not have any time information in the URL will use the current time conductor state.
Note that there is another option for handling this-- the Time API itself could only emit events when changes occur.  Unfortunately, this would prevent the Time API from forcing all views to resynchronize by rebroadcasting the current bounds (unless some other semaphore is added), so I didn't …

[Time API] Only change time when changed

---

platform/framework/src/register/ServiceCompositor.js
platform/framework/test/register/ServiceCompositorSpec.js
platform/telemetry/src/TelemetryCapability.js
platform/telemetry/test/TelemetryCapabilitySpec.js

Modified the ServiceCompositor and TelemetryCapability to prevent sending warning messages to the console and send information messages instead. [nasa/openmct/issues/1641](https://github.com/nasa/openmct/issues/1641)
@larkin please take a look

[Open 1641] Change warnings to info messages

---

platform/commonUI/general/res/sass/features/_imagery.scss
platform/commonUI/themes/espresso/res/sass/_constants.scss
platform/commonUI/themes/snow/res/sass/_constants.scss
platform/features/imagery/bundle.js
platform/features/imagery/res/templates/imageryTimeline.html
platform/features/imagery/src/controllers/ImageryController.js
platform/features/imagery/src/policies/ImageryViewPolicy.js
platform/features/imagery/test/controllers/ImageryControllerSpec.js

1. Changes address original issue: N/A, don't have an issue to point to
3. Command line build passes? Y 
Adds a new view to imagery objects that displays historical and realtime imagery in a timeline strip.  Re-queries historical data on bounds change and autoscrolls when scrollbar is at right-most position. If image ordering is reversed while testing, run `gulp stylesheets`. @luisschubert @adoubekk would appreciate another set of eyes if you guys get a chance.

[Historical imagery] [WIP]: Add historical view for image telemetry

---

src/adapter/runs/TimeSettingsURLHandler.js
src/adapter/runs/TimeSettingsURLHandlerSpec.js

When loading the application and no time system is set,
the url handler should not cause multiple errors to be
logged, and the url fragment for the time system would 
have no time system set.  Reloading the application with
this broken url would cause problems, particularly if the 
time conductor was installed.
This adds a test for the case and then fixes the issue.
Fixes bugs as reported here.

[Time] Handle missing time system gracefully

---

example/generator/generatorWorker.js
example/imagery/plugin.js

Update example telemetry providers to limit the number of
datums generated so that queries for long time ranges will
not cause undesired behavior in demos.
This is for example bundles (which don't have tests) so no tests were updated.  It works around some issues with sine wave generators and example imagery when the time conductor is set to a very large time range.
1. Changes appear to address issue? Y (as reported here)
2. Appropriate unit tests included? N/A (example code)
@dtailor90 or @psarram please R&I this branch when you have time.

[Example] Limit telemetry responses to 5000 records

---

.gitignore
platform/commonUI/browse/res/templates/browse.html
platform/commonUI/general/bundle.js
platform/commonUI/general/src/directives/MCTSplitPane.js
platform/commonUI/general/src/directives/MCTSplitter.js
platform/commonUI/general/test/directives/MCTSplitPaneSpec.js
platform/commonUI/general/test/directives/MCTSplitterSpec.js

Made changes as requested. Kept all logic regarding localStorage on MCTSplitPane, update localStorage when user drags MCTSplitter to new position.

persist user preference width for MCTSplitPanes issue #1646

---

.gitignore
package.json
platform/commonUI/browse/bundle.js
platform/commonUI/browse/res/templates/browse.html
platform/commonUI/browse/src/InspectorPaneController.js
platform/commonUI/browse/src/PaneController.js
platform/commonUI/browse/src/windowing/NewTabAction.js
platform/commonUI/browse/test/InspectorPaneControllerSpec.js
platform/commonUI/browse/test/PaneControllerSpec.js

1. Added ability for users to add the following parameters to the url:
a. hideTree = true
b. hideInspector = true
These params will enable users to hide the tree and/or inspector. 
Params will automatically be removed once the PaneController state is triggered. 
2. Changed the way PaneController state is controlled when opening a new tab. Previously we were only checking if new tab is opened, now (newTabOpened=true) param is added to url to act as a trigger to hide Tree and Inspector by default.

Fix for Pane controller issue#1670

---

platform/telemetry/src/TelemetryCapability.js
src/api/telemetry/TelemetryAPI.js
src/api/telemetry/TelemetryAPISpec.js

Updates the subscription interface to combine subscriptions for the same point-- by implementing this behavior in one place, we prevent every plugin author from having to implement it.
Add some improvements for various telemetry types and ensure that telemetry requests always have reasonable defaults applied.
Also adds some tests to the telem api (where previously there were none).
Fixes #1594.

[Telemetry API] many subscribes -> one provider subscribe

---

index.html
platform/exporters/ExportService.js
platform/forms/bundle.js
platform/forms/res/templates/controls/file-input.html
platform/forms/src/FileInputService.js
platform/forms/src/MCTFileInput.js
platform/forms/test/FileInputServiceSpec.js
platform/forms/test/MCTFileInputSpec.js
platform/import-export/bundle.js
platform/import-export/src/actions/ExportAsJSONAction.js
platform/import-export/src/actions/ImportAsJSONAction.js
platform/import-export/test/actions/ExportAsJSONActionSpec.js
platform/import-export/test/actions/ImportAsJSONActionSpec.js
src/plugins/plugins.js

Addresses issue #593 
Adds context actions for importing and exporting JSON representations of domain objects as well as a File Input service and form control.
@larkin @luisschubert @adoubekk
Unit tests included and/or updated with changes? N

[Import/Export] [WIP] Allows for import and export of domain objects

---

platform/telemetry/src/TelemetryCapability.js
platform/telemetry/test/TelemetryCapabilitySpec.js

Provide domains and ranges when converting from current telemetry API to the legacy telemetry capability used by plot and other views. Partially fixes #1684 (see comments in that issue)
1. Changes address original issue? Y (partially)

[Telemetry] Provide legacy domains/ranges

---

platform/commonUI/general/res/sass/features/_imagery.scss
platform/commonUI/general/res/sass/user-environ/_frame.scss
platform/features/imagery/res/templates/imagery.html

The Pause/Play button is hidden in when an Imagery object is added to a Layout. This change fixes that and slightly improves the layout of the Imagery frame. Please review and merge if alg.
@dtailor90 FYI

Review and merge fix for hidden Imagery controls

---

platform/commonUI/general/res/sass/controls/_controls.scss
platform/commonUI/general/res/sass/user-environ/_frame.scss
platform/features/hyperlink/res/templates/hyperlink.html

Fixes #1710. Minor HTML and CSS mods.
- Converted to span to confine clickable area to text only
- Link now uses `overflow: hidden` in frame
- Normalized font-size when .s-button

Review and merge fixes for Hyperlinks

---

example/generator/GeneratorProvider.js
platform/features/plot/bundle.js
platform/features/plot/src/policies/PlotViewPolicy.js
platform/features/plot/test/policies/PlotViewPolicySpec.js

Fixes #1705 and #1713.
There still appears to be a bug causing plots not to occur for the openmct-tutorial, don't have time to debug right now.  These changes are a good starting point.
1. Changes address original issue?  Y
Ready for review by anyone available.

Plot telem fixes

---

platform/features/plot/src/policies/PlotViewPolicy.js
platform/features/plot/test/policies/PlotViewPolicySpec.js

Check for telemetry delegation before attempting to interrogate Telemetry Panel objects for telemetry metadata; they're not going to have any. Fixes #1728 

[Plot] Handle telemetry panels from plot policy

---

platform/import-export/bundle.js

Fixes #1695. Updated to use new glyphs.

Review and integrate usage of new Import/Export glyphs

---

platform/commonUI/browse/res/templates/browse/object-header.html
platform/commonUI/browse/src/ObjectHeaderController.js
platform/commonUI/browse/test/ObjectHeaderControllerSpec.js

Added a check for existence of the 'creation' feature to allow inline-editing. Also, removed the unused edit() function.  
Fixes #1746
@larkin @VWoeltjen Please review when you get a chance. If it looks ok, I'll add a test.

Allow inline-editing for editable objects only

---

platform/commonUI/general/res/sass/_widgets.scss

Added margin to the delete button style.
#1762 

[Summary Widget] Added margin to the delete button (#1762)

---

platform/commonUI/browse/src/ObjectHeaderController.js
platform/commonUI/browse/test/ObjectHeaderControllerSpec.js

@VWoeltjen This should fix the issue with inline editing. Please review. I'll have to fix/modify the tests.

[Edit] Prevent blur to update the model after return key is pressed 

---

src/adapter/directives/MCTView.js

Clear regions when a view is destroyed. This causes a view's destroy method to be correctly invoked, allowing views to do cleanup. Used by NSS heatmap view for sprint Alice, https://github.com/nasa/openmct/projects/1
1. Changes address original issue? Y (as reported in this PR)
2. Unit tests included and/or updated with changes? N (no tests to update)

[Views] Clear regions on destroy

---

platform/forms/res/templates/controls/composite.html

Pass the item to child controls inside of a composite instead of
the row object.   Thus, options are correctly passed to children.
Fixes #1785.

[Controls] pass item as structure

---

platform/features/listview/bundle.js
platform/features/listview/src/controllers/ListViewController.js
platform/features/listview/test/controllers/ListViewControllerSpec.js

This provides consistency with other times and dates in the user interface,
and also provides a meaningful sort order due to the use of ISO formats for
standard date/time presentation. Fixes #1730.

[List] Use standard format for modified/persisted times

---

platform/features/layout/src/LayoutController.js

Clear the selection only if the selected object is no longer in the composition and there's no newly dropped object.
Fixes # 1790

[Layout] Fix regression in selecting object when it's dropped

---

platform/features/layout/src/FixedController.js
platform/features/layout/test/FixedControllerSpec.js

Fixes #1740.
The issue here was that the fixed position display was expecting all telemetry to specify a 'range', which imagery telemetry does not (quite correctly). I've modified the fixed pos display to be a bit more flexible here. It will preferentially attempt to show a 'range' value if one is defined in the metadata, but it will fall back to showing the highest priority non-domain value if no range is available.
In future we might consider allowing the user to select which telemetry value a fixed position display shows for a given telemetry point. Thoughts?

[Fixed Position] Fixed position displays now show image URLs

---

src/api/objects/ObjectAPI.js

The fix in #1796 failed because it only updated the identifier used to fetch the provider, but then it still used the keystring to get the provider.  The provider would fail because it expected an identifier but got a keystring.
That said `.get(keyString)` works without this change, albeit inconsistently.  That it works is due to the MissingModelCompatibilityDecorator.  That it works inconsistently is due to a race condition in the larger system.
**It works:**  The fallback object provider tries to get the keyString from the model service, the MissingModelCompatibilityDecorator sees that it's not available, converts the keyString to an identifier, performs objects.get, and returns the result.
**inconsistently...** to prevent an infinite loop between the fallback object provider and the …

[API] get with keystring, fix transitional race condition

---

platform/commonUI/edit/src/capabilities/EditorCapability.js
platform/commonUI/edit/test/capabilities/EditorCapabilitySpec.js

Removed redundant call to editorCapability.finish(), which resulted in console error.

[persistence] uncaught in promise error fix for issue #1593

---

platform/features/table/src/controllers/TelemetryTableController.js
platform/features/table/test/controllers/TelemetryTableControllerSpec.js

This avoids losing rows during table sorting, which fixes #1738 

[Table] Retain rows in scope

---

platform/features/imagery/src/controllers/ImageryController.js
platform/features/imagery/test/controllers/ImageryControllerSpec.js

If there is no immediately new imagery incoming, forward to latest image in history on un-pause (ImageryController#paused)

[imagery] fix for issue #1799

---

API.md
src/plugins/URLIndicatorPlugin/URLIndicator.js
src/plugins/URLIndicatorPlugin/URLIndicatorPlugin.js
src/plugins/URLIndicatorPlugin/URLIndicatorSpec.js
src/plugins/plugins.js

Adds URLIndicator to the build, testable adding
```js
openmct.install(new openmct.plugins.URLIndicatorPlugin({
url: 'http://localhost:8080/',
icon: 'check',
interval: 15000,
label: 'Localhost'
}))
```
to the openmct file.

[BUILD] Adds URLIndicator

---

openmct.js

Fixes #1821 after regression introduced by changing dependency in #1808. (The previous dependency fixed a [module naming issue](https://github.com/eligrey/FileSaver.js/issues/383), but got DMCA'd, so shim instead!)
2. Unit tests included and/or updated with changes? N/A (changes at configuration level only)

[Export] Add shim config for saveAs

---

platform/commonUI/general/res/templates/controls/datetime-field.html

Added `autocorrect` and `spellcheck` attributes to the datetime-field template.  Addresses #1682.
2. Unit tests included and/or updated with changes? No

[DateTime Field] Disabled autocorrect and spellcheck for datetime fields

---

platform/features/table/src/TelemetryCollection.js
platform/features/table/src/controllers/MCTTableController.js
platform/features/table/src/controllers/TelemetryTableController.js
src/api/telemetry/TelemetryValueFormatter.js

This includes potential improvements to table performance with large datasets. (~161k rows, many duplicate values in the sort column).
There are three different changes in this PR:
A. defer dupe check
B. shortcut insertion check
C. remove format/parse cache
test case | processData elapsed
--- | --- 
baseline | 87s 
A | 26s 
A+B | 16s 
A+B+C | 13s 
I'd consider the 3 seconds to maintain the format/parse cache a non-negligible hit; let this be a lesson to myself as to why premature optimization is bad.  The bulk of the remaining performance hit is moment date parsing.
Note that there's also 45-60 seconds of network latency loading this table.
@akhenry would love your insights on these changes before I update tests.

Table perf improvements

---

platform/commonUI/formats/src/UTCTimeFormat.js
src/plugins/plugins.js
src/plugins/telemetryMean/plugin.js
src/plugins/telemetryMean/src/MeanTelemetryProvider.js
src/plugins/telemetryMean/src/MeanTelemetryProviderSpec.js
src/plugins/telemetryMean/src/MockTelemetryApi.js
src/plugins/telemetryMean/src/TelemetryAverager.js

Introduces simple averaging telemetry filter. Uses a sliding window of customizable size (default 10) to produce values for a given telemetry point
Includes a change to `UTCTimeFormat` from the demo branch that supports passing a `number` to the `parse` function.
Currently the telemetry point is entered manually as an ID. A better control is required here. The current locator could be used, but implementation of that is deferred for now in favor of a new filtered locator control.

[Feature] Telemetry mean filter

---

platform/features/layout/res/templates/layout.html
platform/features/layout/src/LayoutController.js
platform/features/layout/test/LayoutControllerSpec.js

...since ids may be invalid class names. Instead, use a data attribute. Fixes #1846

[Layout] Don't use class name to query by id

---

src/plugins/summaryWidget/src/SummaryWidget.js
src/plugins/summaryWidget/test/SummaryWidgetSpec.js

Use objectUtils to get a proper legacy id so that namespaces are
properly handled.  Fixes https://github.com/nasa/openmct/issues/1858

Summary widget identifiers 1858

---

platform/commonUI/edit/src/controllers/EditObjectController.js
platform/commonUI/edit/test/controllers/EditObjectControllerSpec.js

Fix as described by @larkin on issue #1838.
- Removed isDirty check, which results in blocking popup showing up every time we try to leave edit mode. 
- Fix corresponding tests.

Edit issue #1838

---

gulpfile.js
package.json

Rationale
This PR adds [v8-compile-cache](https://github.com/zertosh/v8-compile-cache) to speed up development scripts. Ran it on `gulp test` and it went from `~4.1s` to `~3.3s` locally. Other scripts are also using this module, so performance get's better on things like linting etc too
Author Checklist
Changes address original issue?
N/A
Unit tests included and/or updated with changes?
N/A
Command line build passes?
Y
Changes have been smoke-tested?

[BUILD] Add v8-compile-cache to improve script performance

---

docs/src/guide/security.md

Add a security guide to address #1833. Handled this as a separate document, rephrasing the concerns identified in that document for an audience of plugin developers and system administrators.

[Documentation] Add security guide

---

platform/commonUI/edit/src/controllers/ElementsController.js
platform/commonUI/edit/test/controllers/ElementsControllerSpec.js

Listen for mutation and refresh composition so that elements pool is updated when selected object's composition changes. 
Fixes #1869.
2. Unit tests included and/or updated with changes? Yes

[Inspector] Refresh the elements pool after removing an item

---

src/api/composition/CompositionCollection.js

All views are expected to implement dynamic composition handling
by listening for the "add" and "remove" events and then calling
"collection.load()" when they are ready to handle these events.
However, it does not make sense that every composition provider will
be dynamic, so implementing support for dynamic composition should
not be a requirement.  This commit removes that requirement, without 
changing the interface of the Composition Collection.
Fixes #1914
2. Appropriate unit tests included? N/A, issues exist for API test backfill.
I am currently backfilling tests for the Composition API and will be opening a separate pull request for those tests.

[API] provider support for dynamic composition is optional

---

platform/commonUI/edit/src/controllers/ElementsController.js
platform/commonUI/edit/test/controllers/ElementsControllerSpec.js
platform/features/layout/src/FixedController.js

The fixed view should be selected if it's not inside a layout.
Also, make sure domain object is defined to listen on mutation to fix the TypeError.
Fixes #1909 and #1912

[Layout] Select fixed position view only if the parent is not selected

---

src/api/composition/CompositionAPISpec.js

This adds Specs for the Composition API, default providers, and verifies that API accepts both "static providers" and "dynamic providers".  
It adds a disabled spec for add/remove via default provider.  Marked as TODO to change when add remove gets added.

Tests for Composition API providers

---

package.json

PR to update version number for release. I've bumped the version from 0.12.0 to 0.13.1 because this was the second sprint of a new release (assuming it's zero-indexed and x.x.0 is sprint 1? I read the versioning doc, but I wasn't entirely clear on whether a x.x.0 release was the first sprint of a new release, or the last sprint [ie the most stable] of a prior release?).
PR is needed because of commit-hook that requires at least one review.
* Changes address original issue? N/A

Version bump - 0.12.0 -> 0.13.1

---

platform/commonUI/general/res/sass/controls/_menus.scss

It looks like some styles were consolidated as part of bc7d92ee0d64aa63769d7bb534f251c14d253c88.  I'm not sure if the intention was to completely replace `.s-menu` with `.menu` but I've added the styles which were removed.
The datetime-picker template still references the `.s-menu` class.
2. Unit tests included and/or updated with changes? N/A (changes relate to styles)
Addresses #1872

[DateTimePicker] Time Conductor Date Picker menu is missing background

---

package.json

Older versions of node-sass do not have binaries for newer versions of Node. Smoke tested it by building the app and checking everyone looks ok. Also tested with gulp-develop.
* Changes address original issue? N/A - No associated issue
* Unit tests included and/or updated with changes? N/A - build config change

Updated version range of gulp-sass to allow later versions

---

bower.json

Lock filesaver version as there have been a large number of broken
builds from what should be non-breaking version increases.
Fixes currently broken build, and hopefully prevents this from breaking for the umpteenth time.
Given our history with this plugin we may have to find a more stable alternative....
https://github.com/eligrey/FileSaver.js/issues/409
1. Changes appear to address issue? Y, as reported here.
2. Appropriate unit tests included? N/A

Lock filesaver version to prevent ongoing instability

---

example/generator/GeneratorProvider.js

Allow SWG properties of zero to be used instead of overwriting
them with defaults.  This used to work because properties were strings, but now that we're using a number input they're numbers.
1. Changes address original issue? Y, as reported here
2. Unit tests included and/or updated with changes? N/A, example code

Allow property values of zero.

---

src/plugins/plot/src/chart/MCTChartController.js
src/plugins/plot/src/chart/MCTChartDirective.js
src/plugins/plot/src/configuration/PlotConfigurationModel.js
src/plugins/plot/src/draw/Draw2D.js
src/plugins/plot/src/draw/DrawLoader.js
src/plugins/plot/src/draw/DrawWebGL.js
src/plugins/plot/src/plot/MCTPlotController.js

This fixes #1976, #1935, #1945.  It also fixes a typo which meant you'd get webgl for the first 16 plots and then everything else would be 2d until you reloaded Open MCT... oops.
For contextlost, waiting for webglcontextrestored does not work when the webgl limit has been reached, and I didn't have a good way to quickly determine when the limit had been hit.  So went with fallback-to-2d whenever the webgl context is lost.
More notes in commit messages.
2. Unit tests included and/or updated with changes? N, issue exists for test backfill.

[plot] cleanup alarms, don't error on mutate, fallback on context lost

---

API.md
src/plugins/summaryWidget/plugin.js
src/plugins/summaryWidget/src/ConditionManager.js
src/plugins/summaryWidget/src/TestDataItem.js
src/plugins/summaryWidget/src/TestDataManager.js
src/plugins/summaryWidget/src/input/ObjectSelect.js
src/plugins/summaryWidget/src/telemetry/EvaluatorPool.js
src/plugins/summaryWidget/src/telemetry/EvaluatorPoolSpec.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetCondition.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetConditionSpec.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetEvaluator.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetMetadataProvider.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetRule.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetRuleSpec.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetTelemetryProvider.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetTelemetryProviderSpec.js
src/plugins/summaryWidget/src/telemetry/operations.js
src/plugins/summaryWidget/src/views/SummaryWidgetView.js
src/plugins/summaryWidget/src/views/SummaryWidgetViewProvider.js
src/plugins/summaryWidget/src/views/summary-widget.html
src/plugins/summaryWidget/test/ConditionManagerSpec.js

This is a WIP (based off #1941) for improvements to summary widgets.  Opening for visibility and initial feedback.
TODO:
3db94bc28b0abe95274a499e1963ad28a280af39, 3/9/2018: implements metadata and telemetry providers for summary widgets so they can be used as telemetry sources in other displays (including other summary widgets).
https://github.com/nasa/openmct/pull/1943/commits/752b7c1210ac3b8b80bbe5ae592aaa352312a31a 3/21/2018: implements all providers and code, just waiting to complete tests.  Ready for testathon.

Summary widget telemetry provider

---

circle.yml

Bumps node version on CircleCI to 8.11 LTS.  This fixes CircleCI build failures.   Though we need to figure out which underlying library change caused this to start failing.
2. Appropriate unit tests included? N/A (CI only change)

Bump Node Version

---

src/plugins/summaryWidget/SummaryWidgetViewPolicy.js
src/plugins/summaryWidget/plugin.js
src/plugins/summaryWidget/test/SummaryWidgetViewPolicySpec.js

Adds a view policy for the summary widget to prevent any view other than the summary widget view.  This reduces user confusion about plot and table views of summary widget.
1. Changes address original issue? Y (as reported here)

don't allow plot or table view of summary widget

---

platform/features/clock/src/controllers/TimerController.js
platform/features/clock/test/controllers/TimerControllerSpec.js

Fixes regression documented in #1895. Looks like it was introduced in https://github.com/nasa/openmct/commit/5aa93ba50c61258b294cceff3ca37450c2b26f75 cleanup. I kept the original class names, and added some basic tests as well.
Thanks @charlesh88 @akhenry for the pointers in the right direction on the issue!

[Timer] Fix regression in timer visual indication and add tests

---

platform/commonUI/general/res/sass/_mixins.scss
platform/commonUI/general/res/sass/_views.scss
platform/features/table/res/templates/mct-table.html

Fixes #1878. Adds overflow scrolling to .l-view-section
- Add overflow: auto;
- Better naming of $overflow arg;
- Fixed and unit tested in plots and tables;

Review and merge overflow fix for plots and tables

---

platform/commonUI/edit/res/templates/elements.html

Added ng-if to look at length of composition. Fixes #2053

Only include grippy when there's more than one element

---

app.js

Security aside, it also reinforces that app.js is a development server only, and should not be used in production.
* Changes address original issue? N/A

Modified Express startup so that it only binds to loopback by default

---

example/notifications/res/dialog-launch.html
example/notifications/res/notification-launch.html
example/styleguide/res/templates/status.html
platform/commonUI/general/res/sass/_main.scss
platform/commonUI/general/res/sass/_status.scss
platform/commonUI/general/res/sass/controls/_indicators.scss
platform/commonUI/general/res/sass/controls/_messages.scss
platform/commonUI/general/res/sass/user-environ/_layout.scss
platform/commonUI/general/res/templates/angular-indicator.html
platform/commonUI/general/res/templates/bottombar.html
platform/commonUI/notification/res/notification-indicator.html
platform/commonUI/themes/espresso/res/sass/_constants.scss
platform/commonUI/themes/snow/res/sass/_constants.scss
platform/features/clock/src/indicators/ClockIndicator.js
platform/features/clock/src/indicators/FollowIndicator.js
platform/persistence/couch/src/CouchIndicator.js
platform/persistence/couch/test/CouchIndicatorSpec.js
platform/persistence/elastic/src/ElasticIndicator.js
platform/persistence/local/src/LocalStorageIndicator.js
platform/persistence/local/test/LocalStorageIndicatorSpec.js
src/api/indicators/IndicatorAPI.js
src/api/indicators/IndicatorAPISpec.js
src/api/indicators/SimpleIndicator.js
src/api/indicators/res/indicator-template.html
src/plugins/URLIndicatorPlugin/URLIndicator.js
src/plugins/URLIndicatorPlugin/URLIndicatorSpec.js

Passes `npm test` and recently merged with master. 
- Markup and CSS greatly simplified. 
- Indicators now use "infobubble" hover instead of expand/collapse:
- Better styling for `<a>` tags and s-button elements in Indicators:
- More statuses and colors added.
- Style Guide content added.

Indicators api styling

---

platform/import-export/bundle.js
platform/import-export/src/actions/ExportAsJSONAction.js
platform/import-export/test/actions/ExportAsJSONActionSpec.js
src/api/objects/ObjectAPI.js

Addresses issues found in #2042
The main fix here is to deal only with a single instance of an object, rather than a mix of duplicate and original objects. This was causing the wrong objects to be updated with new object Ids, and resulted in export files that had a mix of duplicated and original objects.
Have refactored `ExportAsJSONAction` to use new-style objects as this made a few things a little easier.
Note that it also includes a [small change to the Object API](https://github.com/nasa/openmct/blob/976bf5ce60ad2e5af01f81c32e1570584b6cc483/src/api/objects/ObjectAPI.js#L214). I think that usage of `makeKeyString` on object-utils is common enough to justify adding it to the API to avoid the convoluted dependency.
* Unit tests included and/or updated …

Json export fix

---

example/generator/StateGeneratorProvider.js

Fixes a small bug in the example state generator which was not using the correct state duration for historical requests.  Was reported by @charlesh88.
2. Unit tests included and/or updated with changes? N/A, example code

use correct duration for historical states

---

example/eventGenerator/bundle.js
platform/features/table/res/templates/telemetry-table.html
platform/features/table/src/TableColumn.js
platform/features/table/src/TableConfiguration.js
platform/features/table/src/TelemetryCollection.js
platform/features/table/src/controllers/TelemetryTableController.js
platform/features/table/test/TableConfigurationSpec.js
platform/features/table/test/controllers/TelemetryTableControllerSpec.js
src/plugins/localTimeSystem/LocalTimeFormat.js

Addresses [issues with tables](https://github.com/nasa/openmct/issues/2027) discovered during testathon as well as during subsequent testing.
1. Merge time columns that are in the active time system. This fixes performance issues observed during testathon that were due to attempts to do a sorted insert with undefined values.
2. Only provide values where the telemetry object supports them. Previously behavior was the formatter for a column would attempt to provide a value for a datum irrespective of whether that telemetry point actually provided that data.
3. Fixed an issue where telemetry data was not being evicted correctly after table was sorted. This was due to a fairly brittle requirement that the scope.rows array instance does not change, [but it …

[Tables] Address performance issues observed in testathon

---

platform/features/notebook/bundle.js
platform/features/notebook/src/actions/NewEntryContextual.js
platform/features/notebook/src/controllers/NotebookController.js
platform/features/notebook/src/directives/MCTSnapshot.js

Use the object-holder for snapshot instead of the entire overlay. Fixes majority of the issues reported in #2110

[Notebook] Snapshot overlay - fixes issues #2098 #2102 #2108  #2110

---

platform/features/table/src/TableColumn.js

Check limit status for all values, not just ranges.  This allows
limit evaluators to apply styling to additional columns if
desired by developers.
Have added a note to #1664 to consider changes to limit evaluators to better support color-coding, which is a requirement in VISTA and this pull request is necessary to support that.
2. Unit tests included and/or updated with changes? N, they work as is.

[Table] Check limit for all values

---

src/plugins/plot/plugin.js
src/plugins/plot/res/templates/plot-options-edit.html
src/plugins/plot/src/configuration/PlotSeries.js
src/plugins/plot/src/configuration/SeriesCollection.js
src/plugins/plot/src/inspector/PlotLegendFormController.js
src/plugins/plot/src/inspector/PlotModelFormController.js
src/plugins/plot/src/inspector/PlotOptionsController.js
src/plugins/plot/src/inspector/PlotSeriesFormController.js
src/plugins/plot/src/inspector/PlotYAxisFormController.js
src/plugins/plot/src/telemetry/PlotController.js

Updates plot options to support dynamic re-ordering of items without mutating the wrong properties.  Fixes #2101.
Also updates plot options to allow a zero value for y axis min/max.
2. Unit tests included and/or updated with changes? N, issue exists for backfill.

Plot composition re-ordering support

---

src/plugins/plot/res/templates/mct-plot.html

Update limit variable name in template so that styles are properly
applied when hovering over plot.  Fixes #2084.

[Plot] Update limit variable name

---

platform/features/table/src/controllers/MCTTableController.js

Cache styles on the scroll event to prevent a forced reflow during the requestAnimationFrame, which saves about 60ms per frame while scrolling.
1. Changes address original issue? Y, as reported here
2. Unit tests included and/or updated with changes? N, tests still pass and table refactor imminent.

[Table] prevent forced reflow on scroll

---

src/plugins/plot/src/telemetry/PlotController.js

Bounds change triggers a clearing of plot history, which triggers
a user interaction change, which was triggering a second query.
This change sets a flag to prevent the requery from the user interaction on
bounds change.  This flag could potentially be reused elsewhere, e.g. if we
wanted to prevent requery when not utilizing a minmax data source.
fixes #2126
2. Unit tests included and/or updated with changes? N/A, issue exists for backfill

[Plot] Prevent duplicate query on bounds change

---

src/plugins/plot/src/configuration/PlotSeries.js
src/plugins/plot/src/configuration/SeriesCollection.js
src/plugins/plot/src/inspector/PlotOptionsController.js

When a new series is added to a plot, a plot series form controller
is instantiated and passed in a domain object via scope that it will
mutate upon changes.  If a mutation results in a composition add, then
the plot series form controller needs to get a version of the domain
object with the updated composition array, which it was not previously
doing.
This fixes #2120.

[Plot] Update formDomainObject on mutate

---

platform/import-export/src/actions/ExportAsJSONAction.js
platform/import-export/src/actions/ImportAsJSONAction.js
platform/import-export/test/actions/ImportAsJSONActionSpec.js

Issue was twofold. 
1. Export was exporting objects with a composition array consisting of [identifier objects](https://github.com/nasa/openmct/blob/9582fb2b06bb656ef3a2298deec8434d9bc8f39b/platform/import-export/src/actions/ExportAsJSONAction.js#L134), and/or [key-strings](https://github.com/nasa/openmct/blob/9582fb2b06bb656ef3a2298deec8434d9bc8f39b/platform/import-export/src/actions/ExportAsJSONAction.js#L136). Corrected to only export object identifiers.
2. Import was [expecting object IDs as strings](https://github.com/nasa/openmct/blob/9582fb2b06bb656ef3a2298deec8434d9bc8f39b/platform/import-export/src/actions/ImportAsJSONAction.js#L84).
Import was also [adding newly instantiated objects back to their parent](https://github.com/nasa/openmct/blob/9582fb2b06bb656ef3a2298deec8434d9bc8f39 …

Fixes Import / Export to work correctly with links and contained objects.

---

platform/commonUI/edit/src/actions/RemoveAction.js
platform/commonUI/edit/test/actions/RemoveActionSpec.js
platform/core/src/actions/ActionCapability.js
platform/entanglement/src/services/MoveService.js
platform/entanglement/test/services/MoveServiceSpec.js

do not show warning dialog when user moves an object from one location to another

---

platform/features/table/res/sass/table.scss

Fixes #2132
- flex styles carefully applied;
- CSS gently reorganized for better DRY;
- CSS fixes the height of `<tr>`'s at 18px so that `<td>`'s won't collapse when all cells of a row have empty values. This can occur when columns that have data are hidden in a Telemetry Table leaving only columns that _don't_ have data visible.

Change table row layout to use flex

---

platform/features/layout/src/FixedController.js

Fixes issue #2125
force a click on the fixed position element after initialize to initialize Fixed Position controller on the selection API.
While fixing this issue I found out that the 'change' event listener on the selection API is not cleared on destroy. Filling a separate issue for that (#2130). 

[Fixed Position] Cannot add on objects when creating Fixed Position for the first time

---

README.md

Remove paragraph about the new API being unstable. Our documented API is mostly interface-stable now, and has been used for long enough now that it should be largely bug free.
Our updated documentation will feature new API features that should be considered experimental, but will be clearly indicated as such.
Skipping author checklist as it's a small documentation change.

Updated README to remove misleading references to instabilities in API.

---

platform/commonUI/edit/src/policies/EditActionPolicy.js
src/exporters/CSVExporter.js
src/plugins/telemetryTable/TelemetryTableRow.js
src/plugins/telemetryTable/TelemetryTableViewProvider.js
src/plugins/telemetryTable/collections/SortedTableRowCollection.js
src/plugins/telemetryTable/components/table-row.vue
src/plugins/telemetryTable/components/table.vue

A few followup items from the [Vue table refactoring](https://github.com/nasa/openmct/pull/2154).
*  Introduces a small change to view providers API. The 'editable' property on view providers may now optionally be a function. This allows for editability to be determined based on properties of a given object, rather than being a fixed property of the view itself. eg. you want table objects to be editable, but not a table view of a telemetry object.
* CSVExporter now only exports visible columns. Also updated CSVExporter to ES6 exports / imports
* Shortcut sorted insert if value is outside of first or last value in collection
* Added table view icon

Vue tables followup work.

---

API.md
platform/commonUI/themes/espresso/README.md
platform/commonUI/themes/snow/README.md
platform/features/my-items/README.md
platform/import-export/README.md
platform/persistence/couch/README.md
platform/persistence/elastic/README.md
platform/persistence/local/README.md
src/plugins/URLIndicatorPlugin/README.md
src/plugins/autoflow/AutoflowTabularPlugin.js
src/plugins/autoflow/README.md
src/plugins/plot/README.md
src/plugins/staticRootPlugin/README.md
src/plugins/summaryWidget/README.md

Adds some rudimentary docs to our various plugins. These docs will be linked from the plugins cards on the plugins section of the website. In cases where documentation is minimal (eg. the themes) they do at the very least provide example code for installing them.
Since doing this I've decided not to include plots as a plugin listed on the plugins page, as it's core functionality of Open MCT. I've left the basic docs in place anyway.
* Unit tests included and/or updated with changes? N/A - docs only

Added brief readmes for all plugins.

---

src/plugins/plot/src/inspector/PlotYAxisFormController.js

Mutate correct path on object for axis range.  Fixes #2182.
This was a mistake in earlier plot refactors, I confirmed that all other properties were properly migrated.  
2. Unit tests included and/or updated with changes? N/A, issue exists for backfill

Mutate correct path for plot range

---

src/api/composition/CompositionCollection.js

Ensures that composition loads in a consistent order.  Cherry picks a change from topic-core-refactor and converts it to legacy JS for support in master build.
This fixes a bug reported by users via email: stacked plots don't always load in the same order.  The composition collection does not guarantee that loading will occur in a consistent order (different objects can take longer to load than others).

Consistent composition order

---

platform/commonUI/edit/src/actions/RemoveDialog.js
platform/commonUI/edit/src/policies/EditContextualActionPolicy.js
src/MCT.js
src/api/composition/CompositionCollection.js
src/plugins/folderView/components/GridItem.vue
src/plugins/folderView/components/ListItem.vue
src/plugins/folderView/components/ListView.vue
src/plugins/folderView/components/composition-loader.js
src/ui/components/controls/ObjectLabel.vue
src/ui/components/layout/mct-tree.vue
src/ui/components/layout/tree-item.vue
src/ui/components/mixins/context-menu.js
src/ui/components/mixins/object-link.js

wip for context menus using a wrapper around old style context menus, which is implemented as a mixin.  Works but not quite ready for merge.
Adds context menu to tree, list view, and grid view.  Refactors list view and grid view to use components and better reactivity.
TODO:

context menu and shared object link generation

---

platform/core/bundle.js
platform/core/src/runs/TransactingMutationListener.js
platform/core/test/runs/TransactingMutationListenerSpec.js

This is the fix for #1468.  The mutationTransactionListener needs to be using the transactionManager for addToTransaction so that the persistence refresh properly clears transactions for any temporary objects.  Prevents openmct creating extraneous objects on the back end.
TODO:

Save As clears transaction while undirtying

---

src/plugins/displayLayout/components/TelemetryView.vue

Display a title for telemetry elements that identifies the chosen field type.

[Display Layout] Show field name as title for telemetry items

---

API.md

Hey, I fixed some typos in the `API.md`  
Changes:
- `y axis` -> `y-axis`
- `lastest `-> `latest`
- `to experiement` -> `to experiment` (https://en.oxforddictionaries.com/definition/experiment)
- `by simple providing` -> `by simply providing`

Grammar fixes in API.md

---

src/plugins/folderView/FolderGridView.js
src/plugins/folderView/FolderListView.js
src/plugins/folderView/components/ListView.vue
src/plugins/folderView/components/composition-loader.js

- [?]  Why show the empty table with sortable columns when the folder is empty? Perhaps a message to add content to the folder is more helpful. (Up for discussion)

Pending fixes for Grid and List Folder views

---

src/api/Editor.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/plugins/flexibleLayout/components/container.vue
src/plugins/flexibleLayout/components/dropHint.vue
src/plugins/flexibleLayout/plugin.js
src/plugins/notebook/src/controllers/EntryController.js
src/plugins/notebook/src/controllers/NotebookController.js
src/plugins/tabs/components/tabs.vue
src/ui/components/ObjectLabel.vue
src/ui/components/ObjectView.vue

* Edit mode is initiated by capture event now, to ensure it always happens happens before any view-specific drop behavior
* Compose only occurs if composition is allowed on object.

Drag and drop fixes

---

src/plugins/displayLayout/components/DisplayLayout.vue
src/plugins/flexibleLayout/components/container.vue
src/plugins/notebook/src/controllers/EntryController.js
src/plugins/notebook/src/controllers/NotebookController.js
src/plugins/tabs/components/tabs.vue
src/ui/components/ObjectLabel.vue

Drag and drop events now serialize the object path instead of the object. The serialized object path is now available on the event data transfer object as `domain-object-path` which replaces the previous `domain-object`.
Also changes boolean usage of `event.dataTransfer.getData(...)` to use the more appropriate `event.dataTransfer.getData.types.includes(...)` instead

Change domain-object event transfer data to domain-object-path

---

src/plugins/displayLayout/DisplayLayoutToolbar.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/plugins/displayLayout/plugin.js
src/ui/toolbar/Toolbar.vue

Add a toolbar control for moving layout items above or below other items.
Also, modify the toolbar API to support function as alternative for property path.

[Display Layout] support ordering items

---

src/plugins/displayLayout/DisplayLayoutToolbar.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/plugins/flexibleLayout/toolbarProvider.js
src/plugins/folderView/components/ListItem.vue
src/plugins/folderView/components/ListView.vue
src/plugins/notebook/res/templates/notebook.html
src/plugins/plot/res/templates/plot-options-edit.html
src/plugins/telemetryTable/components/table.vue
src/styles-new/_constants-espresso.scss
src/styles-new/_constants-maelstrom.scss
src/styles-new/_constants-snow.scss
src/styles-new/_controls.scss
src/styles-new/_mixins.scss

- Toolbar sanding and polishing
- Button order tweaked to place stack order (layering) near X, Y, etc. inputs;
- Improved spacing between items themselves and separators;
- Enable all sub-object views in Display Layout to use numeric inputs for x, y, width and height;
- Change 'toggle'-style toolbar buttons to reflect current state, rather than what the setting will be once clicked. E.g. when frame is hidden, button displays the frame-hidden icon, and tooltip says 'Frame hidden';
- Styling for custom selects
- New cleaner styling approach;
- New cSelect and appearanceNone mixins;
- Converted selects in Notebook, plot-options-edit;
- List View fixes
- Ellipsizing now works;
- Better icon and text alignment;
- Telemetry table headers now have hover effects when editing;
- Remove …

R&I Misc UI 4b

---

platform/commonUI/dialog/res/templates/message.html
platform/commonUI/notification/src/NotificationIndicatorController.js

This partially reverts a previous change that removed options from notifications as they were not being used. A side effect of this was to make notifications non-dismissible from the notifications list.

Quick compatibility fix to support dismissing notifications from legacy notifications list overlay

---

src/plugins/displayLayout/components/DisplayLayout.vue

Update isTelemetry logic to ignore Imagery so that when added to a layout, it appears as Imagery and not alphanumeric.

[Display Layout] Show Imagery as Imagery when added to a layout

---

src/api/objects/ObjectAPI.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/ui/components/ObjectLabel.vue

This prevents a layout from being added to itself.
Display layouts [define their own dragover behavior](https://github.com/nasa/openmct/compare/topic-core-refactor...no-self-composition?expand=1#diff-0bd189e6e0f41c38b19fc752fe4b96f4R273) to short cut the composition policy check that occurs as part of drag-and-drop composition. This change adds an additional check on dragover so that [the default behavior is only shortcut if the layout already contains the dragged object](https://github.com/nasa/openmct/compare/topic-core-refactor...no-self-composition?expand=1#diff-0bd189e6e0f41c38b19fc752fe4b96f4R281), otherwise the normal composition rules will apply. This supports duplication of telemetry points.
The w3c drag-and-drop API prevents inspection of dataTransfer items during dragOver, so …

Prevent self-composition in layouts

---

src/ui/toolbar/components/toolbar-input.vue

Listen for ‘input’ event when input type is number. The ‘input’ event is triggered when the spinner up/down arrow is clicked as well as when a number is manually typed in the number input.

Toolbar number input

---

platform/commonUI/edit/src/services/TransactionManager.js
platform/commonUI/edit/test/services/TransactionManagerSpec.js
platform/core/src/runs/TransactingMutationListener.js
platform/core/test/runs/TransactingMutationListenerSpec.js

Fixes #2277
Previously, [guard code in `TransactionManager`](https://github.com/nasa/openmct/compare/persist-latest?expand=1#diff-32c72e698ab122107a9cd49de97320deL81) would ensure that an object is only persisted once for a given transaction.
Changes introduced to bridge old and new API cause [a new version of a given object to be instantiated each time it's mutated](https://github.com/nasa/openmct/blob/master/src/adapter/services/LegacyObjectAPIInterceptor.js#L47). Due to [a closure referencing a stale object instance](https://github.com/nasa/openmct/blob/master/platform/persistence/queue/src/QueuingPersistenceCapability.js#L43), this resulted in a stale object being queued for persistence.
This change ensures that the object model being persisted is not stale by only committing the most …

Only persist latest mutated model.

---

src/plugins/timeConductor/Conductor.vue

This fixes an error that prevented switching modes in the time conductor.
* No longer attempts to clear validation messages of hidden inputs
* Clearing of validation messages is done right before mode switch, rather that right after.

Conductor bug tcr

---

platform/commonUI/dialog/bundle.js
platform/commonUI/dialog/res/templates/message.html
platform/commonUI/dialog/res/templates/notification-message.html
platform/commonUI/dialog/res/templates/overlay-message-list.html

Legacy dialogs were broken by a previous change for notifications. The problem occurred because both notifications and dialogs were sharing an Angular template - [message.html](https://github.com/nasa/openmct/blob/topic-core-refactor/platform/commonUI/dialog/res/templates/message.html). This template [had been updated due to notification model changes](https://github.com/nasa/openmct/commit/6f1b5b4ae36af1b8bed84ace7a3f6a9aa0651ab8#diff-47312eef541e28ca00f5a22e616629d0), which broke legacy dialogs. For now I have just split message.html into two templates - one for notifications and one for dialog messages, which has been reverted to the old version of the template.

Legacy dialogs fix

---

src/plugins/displayLayout/DisplayLayoutToolbar.js
src/plugins/flexibleLayout/toolbarProvider.js

remove is editing checks from toolbar providers since is editing is being checked by layout.vue

Fix toolbar regression that prevented toolbar from showing

---

src/plugins/telemetryTable/TelemetryTable.js
src/plugins/telemetryTable/collections/BoundedTableRowCollection.js
src/plugins/telemetryTable/collections/SortedTableRowCollection.js

* Maintain stable sort (VISTA DEFECT-590)
* Parse telemetry date values to raw values before comparing them to bounds. There was a problem in VISTA where dates are represented as strings. Bounds are always a number, so this was resulting in invalid comparisons.
* Re-fetch historical data on time system change.

Fix various table bugs

---

src/plugins/telemetryTable/components/table.vue

- Extremely minor style tweak to support legacy mct-tables in VISTA; required by VISTA branch `legacy-mct-table`

Fix legacy tables

---

src/ui/inspector/Elements.vue

- Moved drag handling from grippy to pool__item element to allow better drag ghost image;
- Very simple approach for now: when dragging, pool elements dim down to give user better sense of drop result;

Better drag reordering affordance in Elements pool

---

src/plugins/telemetryTable/TelemetryTable.js
src/plugins/telemetryTable/components/table.vue

Implements persistence of table column sort for editable table options. 
Will allow sorting in browse mode, but will not persist and changes.

Persist table sort options

---

src/ui/router/ApplicationRouter.js

Routing failed completely if deployed to anything other the root of a webserver. This was all down to a missing '/' in the router code that seems to be getting stripped by the location-bar library.

More robust routing

---

src/plugins/objectMigration/Migrations.js
src/plugins/objectMigration/plugin.js

* Migrates legacy table configuration to the TCR table configuration format.
* Also fixes an issue that must have occurred in refactoring, where "openmct" was not available to some of the migration scripts.
The diff looks worse than it is by default - it shows Migrations.js having changed massively, when it's mostly indentation due to wrapping the code in an extra function. __Strongly__ advise checking "Hide Whitespace Changes" in Diff Settings when reviewing.

Table migration

---

src/plugins/remove/RemoveAction.js

Fixes an issue that prevented the remove action from appearing in the context menu if the selected object was non-editable.

Fix remove action

---

src/adapter/runs/LegacyTelemetryProvider.js

A small fix that addresses an issue with legacy telemetry providers. If no legacy telemetry service available, return noop unsubscribe function.

do not return null unsubscribe function

---

index.html
src/MCT.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/plugins/displayLayout/plugin.js
src/plugins/telemetryTable/TelemetryTableViewProvider.js

Allows some customization in different Open MCT apps. This is not the long term solution to this problem though - it should eventually be addressed by other means.

Optionally provide list of object types to show as views rather than telemetry in Display Layouts

---

platform/commonUI/dialog/src/OverlayService.js

Should prevent uncompiled templates from briefly appearing when properties dialogs are displayed.

Force digest on compilation of overlay template

---

src/MCT.js
src/ui/router/Browse.js

This restores the previous default behavior of Open MCT when no explicit object path is defined - that is, it will navigate to the last root object.
This removes the hard-coded default route of 'mine', which will only work in deployments where the 'My Items' plugin is installed.

Default routing

---

platform/commonUI/dialog/bundle.js
platform/commonUI/dialog/src/OverlayService.js
platform/commonUI/dialog/test/OverlayServiceSpec.js

Addresses the issue with properties dialogs briefly showing angular template using a $digest instead of $apply.

Use  instead of  to avoid double digest issue

---

src/adapter/services/LegacyObjectAPIInterceptor.js
src/api/objects/MutableObject.js

event emitter uses keystring instead of key, to avoid broadcasting to all domainObjects that share the same key

Fixes issue where all objects with same key update at the same time

---

src/api/composition/CompositionCollection.js

This fixes a major issue with composition. Because the composition collection is not getting an updated domainObject, composition changes would cause a stale object model to be emitted.
May have also caused some of the other random behavior we were seeing with composition and remove.

Added a mutation listener to CompositionCollection

---

src/plugins/telemetryTable/TelemetryTable.js

Makes tables a little more resilient to errors in the telemetry adapter. Will cancel the loading spinner if promise is rejected.

Remove wait spinners when error occurs in tables

---

src/styles-new/_controls.scss
src/ui/components/ObjectLabel.vue
src/ui/layout/mct-tree.vue
src/ui/layout/tree-item.vue
src/ui/mixins/object-link.js

Some small changes that improve tree performance
1. Removes the transition on the expand/collapse arrow 
2. Reduces the number of times that the navigation path to a tree object is recalculated.

Tree Performance Fixes

---

src/plugins/telemetryTable/components/table.vue

Fixes an issue with tables where rows would disappear in two situations -
1. When a table in a display layout was viewed large
2. When a table in a flexible layout column that was then reordered.
Issue is because these two events, for whatever reason, sometimes result in the table's 'scrolltop' being reset to 0 without a scroll event being triggered. Tables rely on scroll events to draw the correct rows.
Fix is to retain scrollTop on resize.

Retain scrolltop on resize

---

src/api/Editor.js
src/ui/layout/BrowseBar.vue

This fixes an issue where if composition changes were made to an object, and then cancelled, the object could in some cases return to a previous version of the object, not not necessarily the persisted version.
This change ensures that the object view is refreshed with the persisted model on cancellation.

Cancel editing bug

---

src/styles-new/_status.scss

- Icons added for red and yellow limits without upr/lwr classes;
- When `is-limit--upr` and `is-limit--lwr` present, those icons trump the red/yellow icons;
- Styles for table tr's, and everything else;
- Unit tested in telem tables, LAD tables and plot legend; also in VISTA locally.

Alarm icons and limits enhancements

---

platform/commonUI/edit/src/actions/PropertiesDialog.js
platform/commonUI/edit/src/creation/CreateWizard.js

This was causing Datasets to not persist URLs sometimes. It resulted in a HORRIBLE bug whereby sometimes object type definition keys would be overwritten with an index, resulting in properties defined in a properties dialog being saved on the object using an index instead of a key.
`Object.create` creates a new object instance and sets the prototype to the object passed in. With basic objects with properties this works fine, overwriting properties values (such as `key`) overwrites it on the child, and not on the prototype object (the original object).
With a Vueified object, you're actually calling a setter function when you set a value. These setter functions are defined on the parent object and inherited by any children. So, the code below was calling Vue reactive handling which seemed …

Do not use Object.create() with Vueified objects

---

src/plugins/flexibleLayout/components/flexibleLayout.vue
src/plugins/flexibleLayout/components/frame.vue
src/plugins/flexibleLayout/toolbarProvider.js
src/ui/toolbar/Toolbar.vue

- Modify toolbar to support items with no applicableSelectedItems property.
- Remove calls to Selection API's private methods and click the element directly instead.

Toolbar issues in Flexible layout

---

src/ui/inspector/Properties.vue

Display a message in the Properties section in the inspector when a single non-domain object (eg. drawing object) is selected instead of "Title" and "Type".

Properties section for single select non-domain object

---

src/plugins/flexibleLayout/toolbarProvider.js

Avoid using the same object when adding separators to toolbar

Flex layout toolbar separators

---

src/plugins/summaryWidget/src/ConditionManager.js
src/plugins/summaryWidget/src/telemetry/SummaryWidgetTelemetryProvider.js
src/plugins/summaryWidget/src/views/SummaryWidgetView.js

This fixes two issues in summary widgets:
- Subscription handle was not being cleaned up when an object was removed from a summary widget, which resulted in an error when the view was destroyed due to the view calling the subscriber twice.
- The summary widget telemetry provider would sometimes return an 'undefined' value, which would result in an error when rendering of the rule was attempted.

Summary widget unsubscribe

---

src/ui/layout/BrowseBar.vue

This fixes an issue in flex layouts with selecting something previously deleted and then restored via cancellation of editing.

Reset selection on cancel

---

src/plugins/filters/components/FiltersView.vue
src/plugins/filters/filtersInspectorViewProvider.js
src/plugins/remove/RemoveAction.js
src/plugins/telemetryTable/TelemetryTable.js

* If removing the currently navigated object, leave edit mode (by saving changes)
* Filter view should not mutate domain object with out of date object model. This causes erroneous composition events.
* Fixes a race condition in TelemetryTables where a child can be removed in between when telemetry is requested, and when it is received.

Fixes some issues relating to removal of objects

---

src/api/Editor.js
src/ui/components/ObjectView.vue

Change to drag-and-drop to edit logic -
1. Moved from Editor API to objectView so that it has access to the current view provider
2. Checks if current view is editable.

Only switch into edit mode if view is editable

---

src/ui/layout/mct-tree.vue

Fixes an issue where clicking on a search result would not navigate to the selected object.

Resolve object paths properly for search results

---

src/adapter/actions/LegacyContextMenuAction.js

Fixes a bug where the locator would sometimes only show a single root object tree, rather than all available root object trees when linking an object.

Add root object to object path for legacy context menu actions

---

platform/commonUI/edit/src/services/TransactionManager.js
platform/commonUI/edit/test/services/TransactionManagerSpec.js
platform/core/src/runs/TransactingMutationListener.js
platform/core/test/runs/TransactingMutationListenerSpec.js

Brings across some fixes from Master that address persistence errors when creating a new object, with an object selected that has a non-editable namespace.
To reproduce the original issue:
1. Select the styleguide
2. Create a new summary widget
3. Observe that an error message occurs in the notifications area.
4. Save the summary widget. Summary widget is saved successfully, but error message persists in the notifications list.
Rather than merging from Master, bringing changes in isolation to minimize risk.

Bring across fixes for #1468 and #2277 into TCR

---

src/plugins/objectMigration/Migrations.js

When migrating old display layouts, convert telemetry point objects to overlay plot.

[Migration] convert telemetry points to overlay plot

---

platform/commonUI/dialog/res/templates/notification-message.html
src/api/overlays/components/OverlayComponent.vue
src/styles-new/_about.scss
src/styles-new/core.scss
src/ui/layout/AboutDialog.vue

Required by VISTA branch `fix-overflow-3` https://github.com/akhenry/VISTA/pull/46
- Fix Chrome 73 bug in overlay __contents-main element;
- Fixed messages by including erroneously missing _legacy-messages.scss file;
- Better layout for messages in notification overlay list;
- Fix About screen for better compatibility with VISTA;
- Better logo sizing in About splash element;

Misc Fixes 3

---

platform/commonUI/edit/src/capabilities/EditorCapability.js

This is causing excessive warnings in plots making debugging difficult.
The issue stems from the fact that the markup for plots includes a check to see if the object is being edited that involves a function call, so it is checked on every digest. The `TickerService` associated with clocks causes digests to happen at one second intervals.

Remove deprecation warnings

---

src/plugins/objectMigration/Migrations.js

Handle case where configuration attribute of objects is undefined. These objects seem to be being created by perspective import scripts.

Migrations fix

---

src/api/composition/CompositionAPISpec.js
src/api/composition/CompositionCollection.js
src/api/composition/DefaultCompositionProvider.js
src/plugins/displayLayout/components/DisplayLayout.vue
src/ui/components/ObjectView.vue

Addresses bug where objects could not be duplicated to same location
* Removes policy preventing composition containing duplicates. 
* Duplicate composition is prevented separately, via a check in the DefaultCompositionProvider. This and the above change bring TCR into line with how Master functions.
* Implements `add` in the composition API

Remove duplicate policy

---

src/plugins/plot/src/configuration/Collection.js
src/plugins/plot/src/configuration/SeriesCollection.js
src/plugins/plot/src/configuration/configStore.js
src/plugins/plot/src/inspector/PlotOptionsController.js
src/plugins/plot/src/plot/MCTPlotController.js
src/plugins/plot/src/telemetry/PlotController.js

1. Fixes bug where plots were not getting discarded properly.
2. Fixes issue where user can zoom into plots when there is no plot rendered, which was causing errors.

Plots issues for 4.1.1

---

src/plugins/telemetryTable/collections/BoundedTableRowCollection.js
src/plugins/telemetryTable/collections/SortedTableRowCollection.js
src/plugins/telemetryTable/components/table.vue

Fixes an issue where telemetry data that has string formatted dates caused tables not to discard telemetry that fell outside of the conductor's bounds.
Also fixes an unrelated issue in tables where filtering would not cause the table to resize vertically.
Also fixes some code formatting issues, so recommend ignoring whitespace changes when reviewing.

Discard old telemetry values in tables when date is formatted as a string

---

src/plugins/summaryWidget/src/Condition.js
src/plugins/summaryWidget/src/ConditionEvaluator.js
src/plugins/summaryWidget/src/ConditionManager.js
src/plugins/summaryWidget/src/input/OperationSelect.js
src/plugins/summaryWidget/src/telemetry/operations.js

Displays a drop-down menu with available options when an enum field is selected in a condition. 
Fixes an existing issue where condition didn't get evaluated properly when operation was switched from `isDefined` to something like `equalTo` and back to `isDefined`. 
Also, fixes issue #2405.

[Summary Widget] support enum fields

---

src/plugins/telemetryTable/TelemetryTable.js
src/plugins/telemetryTable/TelemetryTableColumn.js
src/plugins/telemetryTable/TelemetryTableConfiguration.js
src/plugins/telemetryTable/TelemetryTableRow.js
src/plugins/telemetryTable/TelemetryTableViewProvider.js
src/plugins/telemetryTable/components/table-cell.vue
src/plugins/telemetryTable/components/table-configuration.vue
src/plugins/telemetryTable/components/table-row.vue
src/plugins/telemetryTable/components/table.vue
src/plugins/telemetryTable/table-row.html
webpack.config.js

1. Migrates some changes from VISTA tables to Open MCT Telemetry Tables that make them more extensible eg. 
* `getRowLimitClass` is just `getRowClass` now so that it can be used more generally to apply styling to rows, 
* Tables now have a factory function for create table rows and columns so that instance types can be overridden by extending classes.
* Table cells are now a Vue component in order to support custom cell content
2. Minor change to Webpack build config to support webpack builds for VISTA.

Vista table sync

---

src/plugins/filters/components/FilterObject.vue
src/plugins/filters/components/FiltersView.vue
src/plugins/telemetryTable/components/TelemetryFilterIndicator.vue

- Update the filters object properly when both checkboxes are deselected.
- Check composition before loading to prevent typeError when viewing a telemetry object as a table.
- Modify logic for mixed filters so that when a new object is added to the table the indicator's label  updates correctly. Also, fixes a case where the Mixed label was not updated correctly when a filter was set initially.

[Filters] various bugs in telemetry table filters

---

src/api/overlays/components/OverlayComponent.vue

Was able to reproduce in Open / TCR with example notifications, and verified fix with same. Needed for VISTA issue 635. Tested in Chrome and Firefox.
1. In Open, add 'example/notifications' and run.
1. Create a bunch of notifications, then view Messages overlay dialog.
1. Note: no overflow problem.

Fixes scrolling messages overflow problem

---

package.json
src/plugins/displayLayout/plugin.js
src/plugins/telemetryTable/TelemetryTable.js
src/plugins/telemetryTable/components/table.vue
src/styles-new/sass-base.scss

This PR introduces some minor to tables and build dependencies refactors
* Open MCT tables now allow derived screens to insert custom buttons into the markup.
* New functions that allow derived screens to do custom processing of data on receipt
* Adds missing dependency that prevents building in new environments
* Fixed case error in import which prevents building in linux

Minor table refactoring

---

src/plugins/plot/res/templates/mct-plot.html
src/plugins/plot/src/plot/MCTPlotController.js

1. In some instances, the y axis label was not populated, causing the label to show up as 'none'.
2. A regression caused the zoom out button to call a wrong function.

Plot y axis label fix

---

package.json

Fixes #2447
An issue with one of Painterro's dependencies (ismobilejs) was causing the RequireJS optimizer to bomb out during the optimization phase of the build. I've locked painterro to 0.2.65 for now in Master. This issue does not occur with Webpack, so the long term remediation here is to just get topic-core-refactor merged into Master.

Locked painterro version to 0.2.65. 

---

index.html
src/MCT.js

remove LADTables from default registry to optionally installed in index.html

[Plugins] LAD Tables plugin should not be installed by default

---

src/ui/layout/BrowseBar.vue

Fixes Issue #2457 - Prevents empty strings, and updates domainObject when any property is changed.

prevents users from using empty strings as names

---

src/plugins/telemetryTable/components/table.vue

Applies a `v-if` if the `allowFiltering` flag is false. This used to work but was lost at some point.

Support no filtering in tables

---

src/styles/_legacy-plots.scss
src/ui/layout/Layout.vue
src/ui/toolbar/components/toolbar-toggle-button.vue

Issues found during VISTA informal testing, plus a couple tweaks.
- Fixes icon-gear margin for configurable Y axis plot labels for #2477;
- Now applies mixed visual style to toggle frame visibility button in Layout toolbar for #2460;
- Change Status area Indicators to right-justify;
- Adjust Status area collapse toggle button margin;

UI Various 2

---

platform/import-export/src/actions/ImportAsJSONAction.js
src/plugins/plugins.js

This fix adds support for namespaces as well as heterogenous identifier types to the Import as JSON plugin. Fixes 
1. Apply namespace of new parent object in all `namespace:key` style object identifiers.
2. Apply parent namespace and new key in all `identifier:{...}` style object identifiers.
3. Fixes the CouchDB plugin which was broken in TCR

[Import JSON] Support namespaces

---

src/plugins/summaryWidget/src/SummaryWidget.js

TODO:
1. SummaryWidget.updateDomainObject triggers action to 'SummaryWidgetEvaluator.updateRules'
2. but domainObject.configuration.ruleConfigById[ruleId] is undefined
3. which actually adds in SummaryWidget.initRule.
So basically step 2 and 3 order is incorrect.

[Summary Widget] Adding a rule without setting anything in the rule causes error #2401

---

src/plugins/filters/components/GlobalFilters.vue
src/plugins/telemetryTable/components/table.vue
src/styles/_controls.scss
src/styles/_legacy.scss

A number of UI-related fixes to handle issues found during VISTA testing.
- Fixed `is-selected` styling so that it overrides table row EVR, limit styling;
- Fix indent in Global filters UI: #2488;
- Fix Summary Widget grippys #2494;
- Fix Summary Widget overflow problem: #2495;
- Added new `c-input-number--no-spinners` class for https://github.jpl.nasa.gov/MissionControl/vista/issues/673. This is required to support a fix for that issue.

VISTA Fixes 4

---

src/plugins/telemetryTable/TelemetryTable.js

This is necessary in order to force the table to be redrawn. Otherwise it waits until the next Vue tick which results in unexpected behavior with the Clear All Data action.

Emit refresh event when data cleared

---

src/ui/layout/status-bar/Indicators.vue

Status indicator bubbles now right-align.

Fix status bubbles

---

platform/import-export/src/actions/ImportAsJSONAction.js

* Removes the `persisted` timestamp from new models on JSON import. The presence of this timestamp was causing objects to be created rather than updated in persistence providers.
* Command line build passes? N/A

Create rather than update new objects in JSON import

---

src/plugins/flexibleLayout/components/container.vue
src/selection/Selection.js
src/ui/layout/Layout.vue

Fixes
https://github.com/nasa/openmct/tree/issue-2472
Change
Elements can be selectable or not depending on view context, ie. selectable during layout view but not selectable in preview view. Change to make selectable explicit, by adding the data-attribute 'data-selectable' to layouts in which elements can be selected. Selectable click event handlers will not be attached to elements that are not in selectable layouts.
Checklist
Unit tests included and/or updated with changes? No existing unit tests

Issue 2472 Disable selection in layouts when previewing

---

app.js

This solves #2543 and includes documentation for the `--host` flag in the help dialog.

[Startup] Stop using -h for aliasing --host

---

platform/commonUI/edit/src/actions/SaveInProgressDialog.js
src/api/overlays/ProgressDialog.js
src/api/overlays/components/DialogComponent.vue
src/api/overlays/components/ProgressDialogComponent.vue
src/ui/components/ProgressBar.vue
src/ui/layout/BrowseBar.vue

Save and Finish blocking modal dialog Refactor and Styles #2500

---

platform/import-export/bundle.js

Since making it a default plugin, we needed to enable the plugin from legacyRegistry as well.

[Import-Export] Enable plugin path

---

src/plugins/plot/src/configuration/PlotSeries.js
src/plugins/plot/src/telemetry/PlotController.js

Moved the check for linestyle to plot series. This allows us to override the strategy directly in the fetch function if linestyle is none. 
TODO - In VISTA, we will have to make a change that will override strategy when filters are being used (most of the logic is there already). Conversation with @akhenry - We should not force usage of minmax in openmct when using filters. Because telemetry providers have access to filters, which they can use to make a decision. But in the case of plot line styles, we have to force a strategy through openmct.

Filters vs MinMax bug fix

---

src/plugins/flexibleLayout/components/flexibleLayout.vue

Fixes #2602 for vista-4.3.0 build
In flexible layouts, dragging an object onto another object, and not a valid drop zone, resulted in object not getting added to layout but being added to composition.
Fix by adding default behavior - if drop zone not specified, add to layout at end of container.
| | |

By default add new frame to end of container

---

src/plugins/plot/src/configuration/PlotSeries.js

When telemetry points with filter metadata are added to overlay plots, plots will send a request for historical telemetry (which is fine), but then filters will be initialized causing a mutation on the domainObject and will trigger another request for telemetry. This causes issues when multiple telemetry points are added to overlay plots, plots will request *2 for every telemetry point. This PR fixes this issue. 

[Plots] Sending duplicate fetch requests when filters are initialized

---

src/plugins/plot/src/configuration/PlotSeries.js

When telemetry points with filter metadata are added to overlay plots, plots will send a request for historical telemetry (which is fine), but then filters will be initialized causing a mutation on the domainObject and will trigger another request for telemetry. This causes issues when multiple telemetry points are added to overlay plots, plots will request *2 for every telemetry point. This PR fixes this issue.

Check if filters are not equal before refetching

---

src/ui/layout/tree-item.vue

Provide persistence to the user's current state in the object navigation tree. On page load/refresh, the initial state will be the last state the navigation tree was in.
- Save expanded state to local storage
- Save navigated state to local storage
| | |

[Navigation Tree] save current state of navigation tree

---

src/plugins/condition/components/Condition.vue
src/plugins/condition/components/ConditionCollection.vue

Found two issues. Input name field required a blur handler to call persist() and name property was duplicated as a property of condition and condition.configuration. Removed the top level property as it was not being used.
Resolves issue: Change of condition name not persisting #2676

Condition clone name persistance

---

src/plugins/condition/components/Condition.vue
src/plugins/condition/components/ConditionCollection.vue
src/plugins/condition/components/condition-set.scss

Added disabled prop to Add Condition button and default condition input fields. Added is-disabled class to button and condition collection. When telemetry is added disabled prop evaluates false and class is removed. Instructions note is also conditional.
Resolves issue: #2681

Condition disable adding or editing conditions without telemetry

---

src/plugins/condition/components/Condition.vue

FF requires that an element to be draggable must contain data. Added a call to dataTransfer.setData to dragStart method.

Add setData on dragStart for FF support

---

src/plugins/condition/Condition.js
src/plugins/condition/ConditionManager.js
src/plugins/condition/criterion/TelemetryCriterion.js
src/plugins/condition/criterion/TelemetryCriterionSpec.js

- latest timestamp is updated with each incoming telemetry datum
- use latest available timestamp for providing telemetry with each new condition calculation
- on new incoming telemetry datum
- on changes to condition configuration (ie. removing criteria)
- historical requests to be done in separate PR
| | |
| Unit tests included and/or updated with changes? | Y |

[Conditions] Use latest incoming telemetry timestamp for providing telemetry

---

src/plugins/plot/src/configuration/PlotSeries.js

A fix for a bug introduced during a fix for issue #2381.
The typo in minmax was causing providers not to recognize when to use the minmax strategy. Reported by S6/SWOT on 3/6/2020

Revert minMax to minmax

---

src/plugins/condition/ConditionManager.js
src/plugins/condition/ConditionSetTelemetryProvider.js
src/plugins/condition/components/Criterion.vue

Addresses comments in #2747
- move ConditionManager observe logic out of telemetry provider and into ConditionManager
| | |

[Conditions] ConditionManager should observe its own mutations

---

src/plugins/condition/ConditionManager.js
src/plugins/condition/components/ConditionCollection.vue
src/plugins/condition/components/ConditionSet.vue

ConditionSet view listens to an event from conditionCollection to display current output.

Remove telemetry subscription from conditionSet edit view
