nasa/openmct

- example/generator/GeneratorProvider.js
- example/generator/generatorWorker.js
- example/generator/plugin.js
Adds a new 'randomness' parameter to Sine Wave Generator objects. This is a user-definable factor that will be applied to values generated by thee Sine Wave Generator. A value of `0` (the default) will apply no randomness. A value of `1` will add a random number to each generated value with a maximum equal to the amplitude of the sine wave.
* Unit tests included and/or updated with changes?
* Command line build passes?
* Changes have been smoke-tested?
> Adds customizable randomness factor to sine wave generator

- src/plugins/condition/ConditionSetMetadataProvider.js
- src/plugins/condition/ConditionSetViewPolicy.js
- src/plugins/condition/ConditionSetViewProvider.js
- src/plugins/condition/plugin.js
- src/plugins/condition/pluginSpec.js
Addresses #2743
- allow condition set nodes to be dropped into overlay plots, and display plotted outputs
- suppress plot view when viewing condition set nodes
| | |
| Unit tests included and/or updated with changes? | Y |
> [Conditions] Enable dropping Condition Sets into overlay plots

- src/plugins/telemetryTable/TelemetryTable.js
When a time system is changed, it emits a timeSystem update as well as a bounds update, this caused telemetry table to request data twice when users changed time systems
This PR fixes that by checking outstanding requests before requesting again.
> [Telemetry Tables] Duplicate requests when users change time system

- src/plugins/plot/src/configuration/PlotSeries.js
make a copy of filters before checking isEqual
- to prevent using same pointer
> Global Filters not re-requesting on value change

- src/plugins/LADTable/components/LADTable.vue
- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/components/inspector/conditional-styles.scss
- src/plugins/condition/utils/operations.js
- src/plugins/displayLayout/DisplayLayoutToolbar.js
- src/plugins/plot/res/templates/plot.html
- src/plugins/plot/res/templates/stacked-plot.html
- src/plugins/telemetryTable/components/table.scss
- src/styles/_constants.scss
- src/styles/_controls.scss
- src/styles/_legacy-plots.scss
- src/styles/_legacy.scss
- src/styles/_table.scss
- src/ui/layout/mct-tree.scss
- Fixes #2756, #2778 and multiple items in #2772;
- Fix missing wrapping markup, convert empty span to template;
- Add INPUT_TYPES object to allow proper setting of 'text' input type;
- Fix padding on `<selects>` for better inline alignment with other input types;
- Legacy wrapper fixes to allow color styling to be applied as expected;
- New `$mainViewPad` constant;
- Fix `c-control-bar` element spacing in plots;
- Better `is-style-invisible` css for `c-style-thumbs`;
- Remove styling toolbar icons in Display Layouts;
- Fix regression error in tree items that was only allowing clicks on the name to navigate;
> Misc Conditionals fixes

- src/api/telemetry/TelemetryMetadataManager.js
metadataManager should check for a values array before calling map on it
> [Metadata] Fails when trying to apply reasonable defaults to an undefined values array

- src/plugins/condition/ConditionSetTelemetryProvider.js
- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/components/inspector/ConditionalStylesView.vue
- src/plugins/condition/criterion/TelemetryCriterion.js
Handles remove telemetry from condition set - this resets criterion properties
Handles remove condition from a condition set that's being used in a conditional style.
Fixes a small bug with stye rule manager request lad results
Resolves part of #2772 
> Remove telemetry and remove conditions from condition set

- src/plugins/condition/components/Criterion.vue
Problem was that clearDependentFields wasn't being called for a change in the field selector.
Result was that previous input(s) remained but with undefined type. Also, the comparison selector had no selected option so appeared blank. When clearDependentFields is called it knows which selector was changed and makes appropriate changes to downstream fields. In this case it removes any input fields and returns comparison selector to its default state of "-Select Comparison-".
Issue tracked here: https://github.com/nasa/openmct/issues/2803
Testathon2 issues: https://github.com/nasa/openmct/issues/2796
> Criterion field change causing incorrect input type

- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/utils/operations.js
Issues addressed:
1) When user has entered values in one or more input fields for a given criteria, and then the comparison selector is changed, inputs along with their data are removed and new empty input(s) are rendered as appropriate for the comparison type. This causes user provided data to be lost.
2) Description for between and not between is incorrect. The first input value is shown as both input values separated by a comma, such as: 
`between 1,2 and 2` instead of
`between 1 and 2`
Issue 1 is fixed by changes updateOperations() and clearDependentFields() in Criterion.vue
Issue 2 is fixed by changes to between and notBetween objects in operations.js 
Issue tracked here: https://github.com/nasa/openmct/issues/2805
Testathon2 issues: https://github.com/nasa/openmct/issues/2796
> Preserve user input when changing criterion comparison

- src/plugins/condition/ConditionManager.js
- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/Criterion.vue
Two issues:
1) Cloned criteria were not deep clones. Updating the values of cloned input fields resulted in reflected updates in source input fields and vise-versa.
2) Cloned conditions were also not deep clones. The same behavior was observed as in issue 1.
Use of lodash cloneDeep method solves both issues. A lighter weight approach is to use JSON serialization: `let clonedObj = JSON.parse(JSON.stringify(sourceObj);` 
This approach has some limitations (from https://stackoverflow.com/questions/38416020/deep-copy-in-es6-using-the-spread-syntax): 
"...solution using JSON serialization has some problems. By doing this you will lose any Javascript property that has no equivalent type in JSON, like Function or Infinity. Any property that’s assigned to undefined will be ignored by …
> Clone condition, criteria issues

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionSetCompositionPolicySpec.js
- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/ConditionDescription.vue
- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/utils/constants.js
- src/plugins/condition/utils/evaluator.js
- src/plugins/condition/utils/evaluatorSpec.js
- src/plugins/imagery/ImageryViewProvider.js
> Adds NOT and XOR triggers for conditions

- src/plugins/telemetryTable/TelemetryTableColumn.js
- src/plugins/telemetryTable/TelemetryTableRow.js
- src/plugins/telemetryTable/collections/SortedTableRowCollection.js
Tables in the past were using raw data to sort values. This caused issues when all data coming from a server was sent as strings.
Solution: User formatter parsed values to sort.
> [Tables] Use parsed data to sort

- src/plugins/displayLayout/DisplayLayoutToolbar.js
Removed 'image' property from DIALOG_FORM and removed getURLButton method and call to same from DisplayLayoutToolbar.js
Issue tracked here: https://github.com/nasa/openmct/issues/2808
Testathon2 issues: #2796
> Removed image properties button from display layouts toolbar

- src/ui/router/Browse.js
We have a bug where, if a user edits a domainObject with more than one view, and then saves and switches the view, the new view will receive an outdated domainObject.
This fixes it by fetching the latest domainObject before switching views.
> When view params change, get a new copy of the domainObject

- src/plugins/tabs/components/tabs.vue
- src/ui/components/ObjectFrame.vue
- src/ui/components/object-label.scss
- src/ui/layout/BrowseBar.vue
Object labels appear in multiple locations in the application. This mod uses the `c-object-label` CSS tag more consistently and simplifies associated markup. Changes here were cherry picked into the new Notebook in `notebook-ver2` branch.
> More consistent Object Labels

- src/plugins/condition/components/Criterion.vue
Addresses #2847
- if metadata format exists, use to determine operation format
- use number as fallback instead of string
| | |
> [Conditionals] Improve logic for Operation Format chooser

- src/plugins/condition/ConditionManager.js
Addresses #2831
- note side effect is that requests for LAD in telemetry table view will return a row with no timestamp and default output
Fix involves
- requesting LAD even if we know it isn't there and letting evaluation default to... (wait for it...) default.
| | |
> request LAD for default condition

- platform/persistence/couch/src/CouchIndicator.js
- platform/persistence/elastic/src/ElasticIndicator.js
- src/plugins/URLIndicatorPlugin/URLIndicator.js
- src/plugins/URLIndicatorPlugin/URLIndicatorSpec.js
- src/styles/_status.scss
Fixes #2878
- Remove background from `elementStatusColors` mixin;
- Change Indicators to use more correct style of `.s-status-on`;
> Fix `.s-status-ok` styling

- src/plugins/condition/ConditionManager.js
- src/plugins/condition/criterion/AllTelemetryCriterion.js
Remove telemetry data cache if a telemetry endpoint is removed
> Removing telemetry from conditionSet with any/all telemetry criterion breaks condition set output

- src/plugins/condition/criterion/AllTelemetryCriterion.js
Addresses #2961
- use correct id for data cache
- separate request and subscription any/all telemetry data cache
- use latest timestamp for any/all telemetry requests
| | |
> [Conditionals] fix #2961 in vista-r4.4

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetMetadataProvider.js
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
Addresses
- data is normalized on historical requests
- do not pass unnecessary telemetry object data in options to telemetry requests
- change output metadata to state (enum) and value (string)
| | |
> [Conditionals] evaluation fixes in vista-r4.4

- src/plugins/plot/src/configuration/PlotSeries.js
- src/plugins/plot/src/configuration/YAxisModel.js
- src/plugins/plot/src/plot/MCTPlotController.js
1. Prevent plots from breaking when more than one NaN or undefined value is added
2. Fix Y axis label issue where the label was not showing up correctly.
> Bug fixes for plots

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionSpec.js
Resolves issue #3037 
Don't compute the result of a condition if telemetry datum is not being used by that condition.
Testing instructions: See #3037
> Fixes computation of result when telemetry is not used by an object

- index.html
- src/api/time/TimeAPI.js
- src/plugins/localTimeSystem/LocalTimeSystem.js
- src/plugins/timeConductor/Conductor.vue
- src/plugins/timeConductor/ConductorAxis.vue
- src/plugins/timeConductor/ConductorHistory.vue
- src/plugins/timeConductor/ConductorMode.vue
- src/plugins/timeConductor/conductor-axis.scss
- src/plugins/timeConductor/conductor.scss
- src/styles/_constants-espresso.scss
- src/styles/_constants-maelstrom.scss
- src/styles/_constants-snow.scss
- src/styles/_controls.scss
Addresses  #2430, Supercedes #2552
- change pan axis to require alt key press and hold
- add zoom axis
- drag to select a range within current bounds to "zoom" in to
- zoomed range becomes new bounds
- visually highlight  on pan and on zoom
- time conductor history
- records recently used times based on current time system
- saves time history on bounds change
- saves time history on time system change
- configurable presets (ex. last hour, last day)
- configurable number of previous history records
- persists history for all used time systems in local storage
| | |
> [Time Conductor] add history and select range features  to vista-r4.4.1

- src/plugins/notebook/components/notebook-embed.vue
1. Switch to realtime mode
2. Create a new notebook
3. Drag a SWG into the first entry
4. Click on the SWG embed link
5. Notification says changed to fixed-time mode but still in real time mode **(fixed)**
> [Notebook] Clicking on an embed in a notebook entry does not result i…n bounds change #3034

- src/MCT.js
- src/MCTSpec.js
- src/plugins/condition/pluginSpec.js
- src/plugins/telemetryTable/pluginSpec.js
Fixes https://github.com/nasa/openmct/issues/3064
Adds a new startup option to Open MCT to start it without the UI. This slightly improves performance for testing purposes.
The new headless mode can be invoked using:
```
openmct.startHeadless()
```
Instead of
```
openmct.start(element)
```
Where appropriate, specs that need to test UI features should just load the relevant sections of UI in isolation (eg. an object view). Where the full Open MCT UI is required for testing, `.start()` can still be called.
This PR also updates two test specs to use the new headless mode, and removes some boilerplate code that was previously necessary to create a container element for the application.
Note that Angular still requires __some__ element for bootstrapping purposes. For this, [a throwaway div is …
> Added headless mode start option

- src/plugins/telemetryTable/components/table-configuration.vue
- src/plugins/telemetryTable/components/table.vue
This is for VCP-0034.
Testing Notes:
1. Create a Telemetry Table
2. Add some telemetry (eg sine wave) 
3. Notice the new option in the inspector for hide headers
4. Toggle the option and verify the table headers are toggled with the checkbox. 
Fixes #3086
> Give users the option to hide table headers

- src/plugins/condition/components/inspector/StylesView.vue
- src/plugins/condition/pluginSpec.js
Fixes static styling issue found in testathon 
Resolves #3076
When multiple items are selected in a layout, allow them to be styled conditionally as well as statically.
- Unit tests included and/or updated with changes? Yes.
> Fix static styles bug - adding null checks. 

- src/plugins/URLTimeSettingsSynchronizer/URLTimeSettingsSynchronizer.js
Fixes https://github.com/nasa/openmct/issues/3088 testing issues.
Adds a new check to prevent bounds changes that occur due to clock ticks from updating the URL. These regular tickets were pre-empting the URL change event from realtime to fixed time mode.
> Do not respond to bounds tick changes

- src/plugins/condition/components/ConditionDescription.vue
- src/plugins/notebook/components/notebook-embed.vue
- src/plugins/notebook/components/snapshot-template.html
This PR fixes #3122 
Testing Instructions:
1. Take a snapshot of a view.
2. Click on 'show' on then snapshot indicator
3. Click on the snapshot image to see 'large'
4. Notice the new buttons on the top right (png and jpg)
5. Click on both and verify the downloaded image.
6. Celebrate!
> [Snapshots] Add download as PNG and JPG buttons

- src/plugins/plot/src/plot/MCTPlotController.js
Addresses #3163 #3052 #2320 #3164
In plot view, try to break pan (alt+click+drag) and marquee (click+drag) using combinations of the following issues.
see #3164 for context click testing instructions
see #3052 for releasing alt while panning testing instructions
see #3163 (also #2320) for alt-tab in windows
| | |
| Unit tests included and/or updated with changes? | N/A (won't add more plot tests) |
> [Plots] Better Pan/Marquee handling

- src/plugins/displayLayout/components/telemetry-view.scss
- src/plugins/tabs/components/tabs.vue
- src/styles/_mixins.scss
Fixes #3194. Fixes related to `is-missing` including fixes for Display Layout alphanumeric views and Tabs view tabs. Testing notes in #3194.
> Fix `is-missing` layout problem #3194

- src/ui/components/ObjectView.vue
When checking if an object can be in edit mode also check if it's locked
Also, use capture phase for onDragOver so that we can check for locked state before any children can handle that event.
Resolves #3204 
Resolves NIRVSSOMCT-179
- Testing instructions included? Yes
> Disallow editor Edit mode when object is locked

- platform/commonUI/edit/src/policies/EditPersistableObjectsPolicy.js
- platform/commonUI/edit/test/policies/EditPersistableObjectsSpec.js
- platform/containment/src/PersistableCompositionPolicy.js
- platform/containment/test/PersistableCompositionPolicySpec.js
- platform/core/bundle.js
- platform/core/src/capabilities/PersistenceCapability.js
- platform/core/test/capabilities/PersistenceCapabilitySpec.js
- src/adapter/services/LegacyObjectAPIInterceptor.js
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
This addresses a current gap in the Open MCT API and enables object providers to implement persistence without having to use legacy API.
* Implemented the `save` method in the Object API
* Refactored the legacy API, and the legacy object adapter layer to work with the new save method
* Fixed failing legacy tests
* Added tests for new API
5. Testing instructions included?
> Enable persistence operations from Object Providers

- src/plugins/notebook/components/notebook-snapshot-container.vue
- src/styles/_controls.scss
- src/styles/_legacy-plots.scss
- src/ui/components/object-frame.scss
- src/ui/components/object-label.scss
- src/ui/inspector/inspector.scss
- src/ui/layout/status-bar/indicators.scss
- Fix Inspector `__content` to properly use flex column layout;
- Change `u-angular-object-view-wrapper` to `display: contents`;
- Fix `gl-plot` to properly use `flex: 1 1 auto` instead of width and height;
- Fix collapsed Status area indicators width problem;
See #3192 for testing notes.
> Fix Safari display issues for #3192

- index.html
- src/plugins/clearData/plugin.js
Addresses #3212
We need to make the indicator an option install to allow VISTA to create its own Clear Data Indicator that will include a global staleness message.
Changes address original issue? No Issue filed
Testing instructions included? N/A
> Make Clear Data Indicator an optional install

- karma.conf.js
- package.json
Resolves #3214
- Removes use of ChromeHeadless for test coverage runs
- Using FirefoxHeadless instead for test coverage runs 
- Added npm dependency for karma-firefox-launcher
- Increased browserNoActivityTimeout to 90000 in karma config
2. Unit tests included and/or updated with changes? N/A This is a build fix.
> Removing use of ChromeHeadless and using FirefoxHeadless for Circle CI builds

- platform/commonUI/dialog/res/templates/overlay.html
- src/api/overlays/components/OverlayComponent.vue
- src/api/overlays/components/overlay-component.scss
- src/plugins/displayLayout/components/LineView.vue
- src/plugins/displayLayout/components/box-and-line-views.scss
Fixes #3221.
- Added min-width and min-height to Display Layout lines to allow easier selection and move when line is purely vertical or horizontal;
- Fixed spacing, size and icon of overlay close button;
> UI enhancement fixes

- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
Creates a closure for telemetryObject so that requests can resolve correctly even if the telemetryObject is destroyed
Resolves VIPEROMCT-16
- Testing instructions included? Yes
> [VIPEROMCT-16] Handle delayed telemetry requests correctly for conditions

- src/plugins/displayLayout/components/LayoutFrame.vue
- src/plugins/displayLayout/components/LineView.vue
- src/plugins/displayLayout/components/layout-frame.scss
- src/ui/components/ObjectView.vue
- src/ui/components/object-frame.scss
- src/ui/preview/Preview.vue
More fixes for problems found from `ui-enhance-3176`.
- Fixed incorrect CSS naming: `c-frame-edit__move` changed to `c-frame__move-bar`;
- Fixed `display: contents` that was erroneously applied to `u-angular-object-view-wrapper` and preventing styling from being applied to plots, renamed class to `.l-angular-ov-wrapper`;
- Removed commented CSS;
> UI enhancement fixes 2

- src/plugins/imagery/components/ImageryViewLayout.vue
Fixing issue in imagery plugin where realtime data was being parsed based specifically on the current time system as opposed to parsing the datum itself and letting the telemetry api handle figuring out the details.
Closes #3234 
> Realtime Imagery Timestamp Parsing Issue

- src/plugins/displayLayout/components/DisplayLayout.vue
Having these keys in the duplicate causes persistence providers to think that the object was already persisted in the past, causing 404 not found (because they are new domainObjects that never existed in the persistence store).
Testing instructions included? N/A
> Remove the modified and persisted keys from duplicates

- src/plugins/notebook/components/notebook-embed.vue
- src/plugins/notebook/utils/notebook-entries.js
- src/ui/preview/preview-header.vue
1. Build a display layout, add a few items.
2. Take a snapshot and save it in the snapshots container.
3. Make changes and save to display layout that you created in Step 1.
4. Navigate away from the display layout.
5. Click on the preview action from the snapshot in the snapshot container.
6. Notice the preview is of the time the snapshot was taken, not the current domainObject state
Check | Passed
-- | --
Changes address original issue? | Y 
Unit tests included and/or updated with changes? | N/A 
> [Snapshots] Are holding on to outdated domainObjects when clicking on preview #3078

- src/styles/_controls.scss
- src/styles/plotly.scss
- Fixed Plotly axis label title font sizing;
- Fixed Plotly axis vertical line color;
- Removed styling that caused `c-button` within `h-local-controls--overlay-content` to be background on background
color;
> Fixes for NIRVSS Spectral Plot view

- src/ui/layout/mct-tree.vue
Fixes 3 issues found during testathon on 08/24.
1. issue where switching to new tree clashes with old local storage information (removed old info, added new local storage key)
2. closes #3321 created a backup check that covers race conditions (which is what I suspect the problem was) as well as new items being added to the tree after initial composition load
3. closes #3320 cleared the visibleItems array (one populating children) then added vue's nextTick to ensure ghost image is gone before new children slide in
Testing instructions are still valid in #3060
> [MCT Tree] Testathon Fixes

- src/ui/layout/mct-tree.vue
There were some cases where the tree is still loading, and the "No Items" notification was showing (seems related to dictionaries). Added a special flag for hiding the no items text, as the isLoading was not reliable in that respect.
Closes #3320 
> [Navigation Tree] Prevent showing "no items" while still loading

- src/api/objects/RootObjectProvider.js
- src/api/objects/test/RootObjectProviderSpec.js
Changed the default root object name from "The Root Object" to "Open MCT". Makes things a bit nicer for fresh installs of Open MCT that have more than one root child. The root name is still about to be changed using the DefaultRootName plugin.
closes #3349 
> [Open MCT] Changing Default Root Object Name

- platform/commonUI/edit/src/creation/CreateWizard.js
Fixes https://github.com/nasa/openmct/issues/3363
Have made a minor change to the CreateWizard to update the namespace of newly created objects after the save location is selected.
2. Unit tests included and/or updated with changes? N/A - tests are disabled for CreateWizard
5. Testing instructions included?
> Update namespace of object after location selected

- src/ui/layout/mct-tree.vue
This PR fixes 3 issues:
1. "No Items" and "Loading" indicators showing at the same time.
2. Padding for "Loading" indicator.
3. Locking navigation while loading (previously if loading was taking a while, you could navigate up or down the tree or even sync to the currently viewed object, which would be jarring as those requests would happen right after the original navigation request was finished loading)
closes: #3320 
closes: #3370 
Testing instructions included? Yes (in #3320)
> [Navigation Tree] Animation fixes

- index.html
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/plugins/displayLayout/components/DisplayLayout.vue
- src/plugins/newFolderAction/newFolderAction.js
- src/plugins/newFolderAction/pluginSpec.js
Resolves #3371 
This change defers legacy mutation/persistence of the object till after it is created via the objects.save api.
> Defers legacy mutation of object till after a creation happens.

- src/api/objects/ObjectAPI.js
- src/plugins/persistence/couch/pluginSpec.js
Resolves #3389 
A domain object's persisted timestamp should not depend on it's modified timestamp. Especially during creation of the object.
> [#3389] Set the persisted timestamp of objects to date.now while saving it

- src/adapter/services/LegacyPersistenceAdapter.js
Updated LegacyPersistenceAdapter's readObject method to handle the possibility of receiving the key string in pieces and if so, assembling it before creating an identifier.
related: NIRVSSOMCT-216
verify legacy items are being indexed correctly (currently will not be)
Changes have been smoke-tested? N/A
> [Legacy Persistence Adapter] readObject to handle possibility of two arguments

- src/ui/layout/mct-tree.vue
Previously, we were not tracking ancestors for deletions. Now we are observing ancestors locations and if they are stet to null (removed from tree) then we navigation up to the next ancestor in the tree.
closes #3382
Unit tests included and/or updated with changes? No current tree spec, pending
> [Navigation Tree] Handling deleted ancestors correctly

- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
Seems readystate was already set to complete before the tree-item was loaded. Because of that, it was not pulling in the itemHeight correctly and it was hanging on load. 
Currently checking for readystate complete before registering event and handling accordingly.
closes #3429 
Unit tests included and/or updated with changes? pending navigation tree tests
> [Navigation Tree] Race condition on checking document readystate

- src/adapter/services/LegacyPersistenceAdapter.js
- src/plugins/persistence/couch/plugin.js
- src/plugins/persistence/couch/pluginSpec.js
Resolves #3425 
Sends new style object to the object API for save when calling it from legacy persistence adapter
> Cancelling out of edit reverts the object correctly

- platform/core/src/capabilities/PersistenceCapability.js
- platform/core/test/capabilities/PersistenceCapabilitySpec.js
- src/adapter/services/LegacyObjectAPIInterceptor.js
- src/plugins/persistence/couch/plugin.js
- src/plugins/persistence/couch/pluginSpec.js
For new object providers, we call openmct.objects.get when we revert changes made to an object
For legacy persistence providers, we ensure that the defaultSpace they were registered with is honored when we 'get' objects.
Resolves #3425 
> Reverting when cancelling out of edits works for both legacy and new object providers

- src/ui/layout/mct-tree.vue
Put in tracking for syncing tree navigation. The duplicate ancestor issue was happening during navigation tree sync. Now, when syncing the tree, we block reseting to another folder in the tree and also syncing again. This will prevent duplicate ancestors from being added to the ancestor. Loading does not block tree navigation, just syncing the tree.
closes #3450
Unit tests included and/or updated with changes? Pending tree test creation
> [Navigation Tree] Fix duplicate ancestor issue in tree (stemming from syncing navigation)

- src/plugins/condition/components/inspector/StylesView.vue
- src/plugins/condition/pluginSpec.js
Addresses #3472
Assume that if a subobject cannot be created, it can't be saved. Use this logic to determine if styles should be saved to the object or a layout.
> Save subobject styles to container/layout if the object cannot be persisted

- src/plugins/notebook/components/NotebookEntry.vue
- src/styles/_controls.scss
- src/styles/_mixins.scss
- src/styles/notebook.scss
- Hovering over entries now displays a subtle background change, and only displays the 'inline input' look when clicked into;
- Changed default styling and behavior to not apply default text content: new entries now start with a blank entry, and do not include 'placeholder' formatting;
- Refactored styles associated with `c-input-inline`, `c-ne__input` and `reactive-input` mixin;
- New mixin `inlineInput`;
- Removed unused CSS classes, general cleanups;
> Notebook fixes for NT10 'click-to-edit entry'

- src/plugins/imagery/components/ImageryViewLayout.vue
Resolves #3465 
Prevent default and stop propagation of the drag start event if imagery filter controls are being used.
Unit tests included and/or updated with changes? N
> Intercept drag start event for imagery filter controls

- src/ui/layout/mct-tree.vue
Changed calculate heights function to return a promise ONCE all heights (over 0) have been returned. This way the tree will wait til it has the appropriate information to proceed.
close #3492 
Unit tests included and/or updated with changes? Separate issue
> [Navigation Tree] Fix tree loading issue

- src/plugins/condition/components/conditionals.scss
- src/plugins/folderView/components/grid-view.scss
- src/plugins/imagery/components/imagery-view-layout.scss
- src/styles/notebook.scss
- src/ui/components/object-frame.scss
- src/ui/layout/layout.scss
Overview and testing notes in #3505. We need to expedite this for the VERVE team.
- Many instances of `height: 100%` converted or amended to include `flex: 1 1 auto`;
- Some high-use containers like `c-so-view__object-view` converted to use flex layout;
- Views fixed generally for sub-object view, and specifically for Conditionals, Folder grid view and Imagery;
- Imagery background image holder converted to use absolute positioning;
> Fix Imagery for VERVE #266

- platform/commonUI/general/res/templates/label.html
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/displayLayout/components/telemetry-view.scss
- src/plugins/folderView/components/GridItem.vue
- src/plugins/folderView/components/ListItem.vue
- src/plugins/folderView/components/grid-view.scss
- src/plugins/folderView/components/status-listener.js
- src/plugins/plot/res/templates/mct-plot.html
- src/plugins/tabs/components/tabs.vue
- src/styles/_legacy-plots.scss
- src/styles/_mixins.scss
- src/ui/components/ObjectFrame.vue
- src/ui/components/ObjectLabel.vue
- src/ui/components/object-frame.scss
- src/ui/components/object-label.scss
- src/ui/inspector/ObjectName.vue
- src/ui/layout/BrowseBar.vue
- src/ui/layout/layout.scss
- Significant refactoring of CSS classing: `is-missing` is now `is-status--missing` and `is-missing__indicator` is now simply `is-status__indicator`, allowing the wrapping `is-missing--*` class to control what is displayed;
- New SCSS mixin `@isStatus`, and changes to mixin `@isMissing` to support new `is-status--suspect` class;
- Changed titling for missing objects from 'This item is missing' to 'This item is missing or suspect'. **IMPORTANT NOTE** This is temporary and should be replaced with a more robust approach to titling that allows title strings to be defined in configuration and dynamically applied;
- Refactored computed property `statusClass` across multiple components to return an empty string when status is undefined - this was previously erroneously returning `is-undefined` …
> CSS and markup refactoring to support addition of 'suspect' telemetry

- src/ui/inspector/ObjectName.vue
Check if selected object is a domainObject before getting status or listening for status changes. 
Closes #3535
> [Object Label] Check if selected object is a domainObject

- src/styles/_controls.scss
- src/ui/components/object-frame.scss
Closes #3532  - see issue for testing notes. Stems from #3298 and #3325.
- Increased opacity of `c-icon-button` labels;
- Fixed CSS selector targeting no-icon menu items;
- Hide overflow in `c-so-view` header element to prevent icons extending outside very small layout frames;
> Sanding and polishing 3 Dot Menu

- src/plugins/displayLayout/components/TelemetryView.vue
Closes #3549. Applied missing `u-style-receiver` class to markup. Testing notes in #3549.
> Fixed problem preventing alphanumerics from being font styled

- CONTRIBUTING.md
There was a missing semi-colon in a code example (oops!) and incorrect capitalization of the `const` keyword (overzealous word processor).
1. Changes address original issue? N/A this is a two character change to docs
2. Unit tests included and/or updated with changes? N/A docs only
3. Command line build passes? N/A Changed docs only
4. Changes have been smoke-tested? N/A Docs only
5. Testing instructions included? N/A
> Fixed minor issues in Code Guidelines

- src/plugins/imagery/components/ImageryViewLayout.vue
Replaced missing "js-imageryView-image" class on main image wrapper div.
Check | Passed
-- | --
closes #3602
> [Verve Imagery] Missing JS imagery class

- src/ui/layout/BrowseBar.vue
Non creatable object names are currently able to be "edited" in the browse bar. Nothing happens as they are unable to be persisted, but it throws a persistence error.
closes #2634
Check | Passed
-- | --
> [Browse Bar] Object names editable, even if object itself is not

- karma.conf.js
- src/plugins/performanceIndicator/README.md
- src/plugins/performanceIndicator/plugin.js
- src/plugins/performanceIndicator/pluginSpec.js
- src/plugins/plugins.js
Adds a "performance indicator" which shows Frames Per Second(FPS). FPS is a useful proxy measurement for the number of view updates that Open MCT can perform based on current load. An fps value of 60 would indicate that Open MCT can in theory update a telemetry display 60 times per second.
This also serves as a proof of concept for global performance monitoring, which could be used to dynamically throttle displays to ensure that the application remains responsive under load.
Fixes #3623
> Adds a simple indicator to display FPS

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/StyleRuleManager.js
Resolves #3523 Don't apply styles on destroy as destroy should not have any side effects
Resolves #3326 Don't display undefined when conditions are loading
Resolves #3143 Force recalculation of condition set result if telemetry is removed.
Check | Passed
-- | --
> Various Conditionals bug fixes

- src/ui/layout/mct-tree.vue
When a navigation request is made in the tree a temporary set of ancestors is populated (and show) so the old set of ancestors can be reused if another navigation request is made before the first has finished. When the page loads however, there are NO ancestors yet, only temporary ones built (and show in tree). If a nav up the tree request is made (only type available at this point) the ancestors never get set from the temporary ancestors. This fixes this scenario, by check if there are ANY ancestors to utilize, if not it's the edge case condition and the temporary ancestors are used instead.
closes #3629
Check | Passed
-- | -- …
> [Navigation Tree] Fixes initial load navigation request breaks if children haven't loaded in yet

- src/ui/components/ObjectLabel.vue
- src/ui/layout/tree-item.vue
Capturing events on the tree item itself (not just object label) and passing those on to object label so the whole tree item is responsive to clicks and context clicks.
closes #3627 
Check | Passed
-- | --
> [Navigation Tree] Whole tree item clickable

- example/styleguide/bundle.js
- index.html
- src/MCT.js
- src/ui/layout/BrowseBar.vue
Added NonEditableFolder plugin as a default install. Updated styleguide to use it (can be used for testing too). Updated browse bar to not show input box on hover for objects that aren't createable.
closes #2634 
Check | Passed
-- | --
Command line build passes? | Maybe
Changes have been smoke-tested? | Yes
Testing instructions included? | Updated
> [NonEditable Folder Plugin] Default Install, Browse Bar Update, StyleGuide Use

- src/plugins/imagery/components/Compass/Compass.vue
- src/plugins/imagery/components/Compass/CompassHUD.vue
- src/plugins/imagery/components/Compass/CompassRose.vue
- src/plugins/imagery/components/Compass/utils.js
- src/plugins/imagery/components/ImageryViewLayout.vue
* Flatten HUD (not intended for horizon line)
* Lock bezel should lock to camera FOV, not rover heading
* Lock bezel should persist for imagery view lifetimed
> Improvements to Compass Rose and HUD

- src/plugins/plot/src/plot/MCTPlotController.js
Use wheel event + ctrl key to identify a pinch gesture and invert the zoom direction.
Resolves: #3631
> Pinch to zoom and wheel zoom work the same way

- src/plugins/notebook/components/PageCollection.vue
Looks like an array find was being treated as a filter, was resulting in the first page's entry of a section being deleted no mater what page was removed.
Check | Passed
-- | --
closes #3753
> [Notebook] Fix incorrectly deleting page from sidebar

- platform/forms/res/templates/controls/file-input.html
- platform/import-export/src/actions/ImportAsJSONAction.js
- src/plugins/plan/plugin.js
- src/styles/_forms.scss
resolves:  #3761
Check | Passed
-- | --
> "Import as JSON" dialog is not intuitive #3761

- src/api/menu/MenuAPI.js
- src/api/menu/MenuAPISpec.js
- src/api/menu/components/Menu.vue
- src/api/menu/components/SuperMenu.vue
- src/api/menu/menu.js
- src/plugins/timeConductor/ConductorHistory.vue
- src/plugins/timeConductor/ConductorMode.vue
- src/plugins/timeConductor/ConductorTimeSystem.vue
- src/ui/inspector/styles/FontStyleEditor.vue
- src/ui/inspector/styles/constants.js
- src/ui/layout/CreateButton.vue
- src/ui/layout/create-button.scss
- src/ui/mixins/context-menu-gesture.js
resolves: #3607
Identified following menus:
1. Tree right click context menu (already done)
1. Notebook Snapshot menu (already done)
1. View Change menu (already done)
1. Display layout alphanumeric context click menu (already done)
1. Display layout Object frame three-dot-menu (already done)
1. Flex layout Object frame three-dot-menu (already done)
1. LAD table row (already done)
1. Telemetry table row (already done)
1. BrowseBar three-dot-menu (already done)
1. Preview header three-dot-menu (already done) 
Check | Passed
-- | --
> [Menu API] All our drop down menus should use the new menu api #3607

- src/plugins/condition/Condition.js
- src/plugins/condition/criterion/TelemetryCriterion.js
When new telemetry data arrives only evaluate criteria that use that telemetry endpoint.
Resolves [VIPEROMCT-41]
5. Testing instructions included? Y (See VIPEROMCT-41)
> [VIPEROMCT-41] Criteria evaluation when telemetry data arrives

- package.json
- src/api/objects/MutableDomainObject.js
- src/plugins/filters/components/FiltersView.vue
- src/plugins/plot/src/configuration/PlotSeries.js
- src/plugins/plot/vue/single/configuration/PlotSeries.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/TelemetryTableConfiguration.js
- src/selection/Selection.js
The Selection API was removing mutable listeners when the inspector view was dismissed even if it didn't create the mutable. This was resulting in the mutables not staying in sync.
The Selection API now only destroys mutables if it creates one. While this works, it is likely a localized fix and the MutableDomainObject.$destroy API probably needs to be looked at again. (See comments in the file)
Resolves #3789 
> [#3789] Destroy mutable objects only if needed

- src/api/objects/ObjectAPI.js
Ensure the cached promise returned for 'get' calls includes any post-fetch treatment.
Resolves #3861
> Return promise correctly for get calls

- src/plugins/imagery/components/Compass/Compass.vue
- src/plugins/imagery/components/Compass/CompassRose.vue
- src/plugins/imagery/components/Compass/compass.scss
Fixes #3742. See issue for testing notes.
- Compass rose now sizes and positions proportionally to the containing image, with min and max sizes;
- Refactored computed `compassDimensionsStyle` as `sizedImageDimensions` for reusability;
- Tweaked sizing of compass ordinals text and North arrow for better legibility;
- Minor tweaks to element positioning and opacity for better legibility;
- Per discussion, automated testing not added at this time due to other issues with Imagery failing automated tests;
- Smoke tested locally and on hulk/dev
1. Unit tests included and/or updated with changes? N
> Dynamic sizing for compass rose based on image size

- src/plugins/LADTable/LADTableSetViewProvider.js
- src/plugins/LADTable/components/LADRow.vue
- src/plugins/LADTable/components/LADTable.vue
- src/plugins/LADTable/components/LadTableSet.vue
Fixes #3869
[The objectPath is now being passed as a property](https://github.com/nasa/openmct/commit/92737b43aff7ce35c5ed6fba9b199280d27f66b3#diff-c81b5971bfc1744860f666d448e5be2aac414b8e60d5f3e6e75f5fdc8b8fdfd7R58), rather than being injected into LAD Rows. This caused an issue in LAD Table Sets which include LAD Rows directly.
Fixed it by passing the objectPath to the included LADRows as a prop, instead of injecting it.
Also did some general tidying in the interests of code clarity.
2. Unit tests included and/or updated with changes? N/A - Small change, does not warrant new automated tests.
> Pass objectPath as property to LAD rows

- src/plugins/imagery/components/Compass/compass.scss
Simple fix to allow browser context-clicking to download imagery. Fixes #3756.
- `pointer-events: none` added to `c-compass` wrapper (which was blocking the image from catching mouse events), and `pointer-events: all` added to `c-direction-rose` element;
- Unit tested locally in main view and both types of layouts;
- Fixed indention spacing in file;
> Allow browser-based context-click to download Imagery

- src/plugins/condition/StyleRuleManager.js
Resolves #3943
The issue here was not a problem with Plan views. It was a side effect of the style rule manager listeners not being removed when destroyed.
> Bind method to 'this' so that its listeners are correctly unbound on destroy

- src/plugins/duplicate/DuplicateAction.js
This fixes the issue of canceling a duplicate action from the dialog throwing an error in console by catching it.
closes #3944
> catching any errors from a user canceling from dialog

- src/api/objects/ObjectAPI.js
- src/ui/router/Browse.js
Fixes https://github.com/nasa/openmct/issues/3964
This was caused by `openmct.objects.destroyMutable()` being called twice for the same object. Don't call `openmct.objects.destroyMutable()` twice for the same object.
> Fix navigation errors

- src/plugins/plot/MctPlot.vue
> In local clock mode, if we're panning or zooming, don't purge older records

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
> Update description for condition set only when necessary, saving persistence calls to CouchDB.

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement-request.md
This enables the use of two more issue templates: type:enhancement and a link to our Github discussions page.
Note: this PR was generated with the Github Issues WYSIWYG editor
> Add Enhancement request template

- src/plugins/hyperlink/HyperlinkProvider.js
Issue: https://github.com/nasa/openmct/issues/4056
The change from this PR will remove the edit mode from hyperlink to meet the expected behavior.
For tests please refer to https://github.com/nasa/openmct/pull/4062
> remove can edit from hyperlink

- src/ui/preview/preview-header.vue
fixed issue where large imagery view opens only once.
resolves #3582
> [Imagery] Click on image to get a large view

- src/plugins/plot/MctPlot.vue
Set the yKey value on the series when it's changed. This should emit the required events for downstream side effects.
Resolves #4079
> Set the yKey option to the series rather than emitting an event for it.

- src/ui/preview/preview-header.vue
fixed issue where large imagery view opens only once.
> [Imagery] Click on image to get a large view #3582

- src/exporters/ImageExporter.js
resolves: https://github.com/nasa/openmct/issues/2942
Notes:
Images can be captured if, 
1. with `access-control-allow-origin` prop as * ,
1. with `access-control-allow-origin` prop has same domain (eg: if openmct is on hulk, then value should include `hulk.ndc.nasa.gov` etc)
images:
Space force: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Seal_of_the_United_States_Space_Force.svg/1200px-Seal_of_the_United_States_Space_Force.svg.png
Nasa logo:
https://www.nasa.gov/sites/all/themes/custom/nasatwo/images/nasa-logo.svg
> [Notebook] Example Imagery doesn't capture images #2942

- src/plugins/plot/MctPlot.vue
Fixes #4121 
Set the offsetWidth of the plot on initial load so that the handleWindowResize method doesn't re-load data.
> Prevent extra loading of plots data

- src/ui/layout/mct-tree.vue
Changed from window resize event to ResizeObserver on tree element to handle tree size calculations. This should fix the issue where the snapshots banner wasn't triggering the tree to calculate heights.
closes #3929
> [Tree] More granular size tracking

- .circleci/config.yml
It's still not clear which jobs pass/fail on tests. This change will update the name of the job which is run to be more explicit that it only pass/fails on the build step
> Update job names to be more explicit

- src/plugins/condition/components/inspector/StylesView.vue
> Check if creatable is true as a string or a boolean.

- src/plugins/imagery/mixins/imageryData.js
Resolves #2977 
Resolves #4235
Use timeFormatter.parse to get the timestamp of imagery since the sou…rce could be something other than key
> Imagery time source could be something other than key

- src/api/telemetry/TelemetryCollection.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/timeConductor/ConductorInputsFixed.vue
Fixes a couple issues, all in the title.
closes: #4167 
closes: #4202
> [Table/Collection Fixes] Clearing correctly, no mutating options, no duplicate requests

- src/plugins/plot/MctPlot.vue
- src/plugins/plot/pluginSpec.js
> Resume plot if no pan, zoom, or drag action is taken (#4138)

- src/plugins/charts/BarGraphCompositionPolicy.js
> mct4269 - disallowing overlay plots for bar charts

- src/plugins/condition/components/inspector/ConditionalStylesView.vue
- src/plugins/condition/components/inspector/StylesView.vue
- src/plugins/licenses/Licenses.vue
- src/plugins/plot/barGraph/BarGraphCompositionPolicy.js
- src/plugins/plot/chart/MctChart.vue
- src/plugins/tabs/tabs.js
- src/ui/inspector/styles/StylesInspectorView.vue
- src/ui/layout/AppLogo.vue
Fixes #4315 
* you-dont-need-lodash-underscore warnings were not fixed
* [n/a] Unit tests included and/or updated with changes?
> Fix leftover lint errors/warnings

- src/plugins/conditionWidget/components/condition-widget.scss
- src/styles/_controls.scss
Fixes #3961 and #4334.
- Better CSS selectors.
- Hide local control for Condition Widget and Hyperlink buttons when no-frame in layout.
> Condition Widgets multiple fixes

- codecov.yml
After further reading, this will configure codecov to run in informational mode.
> Run Codecov in informational mode

- .circleci/config.yml
- README.md
- karma.conf.js
- package.json
Addresses parts of: https://github.com/nasa/openmct/issues/4389
Since we have codecov.io integrated, we don't need to generate and archive a html view of our codecov metrics. This should save us considerable time.
> [CI] Disable html unit test reporting to increase CI Speed

- .github/dependabot.yml
Need to use ruby regex matching. Added more dependencies to monitor.
Fixes https://github.com/nasa/openmct/issues/4399
> [CI] Update dependabot regex to use ruby rules

- .circleci/config.yml
This will attempt to close https://github.com/nasa/openmct/issues/2449 by running npm audit and failing if we are failing at the lowest threshold. This is preferable to failing on PR because the ruleset for npm audit changes independent of packaging changes.
> [CI] Add npm audit to the nightly

- index.html
- src/api/objects/ObjectAPI.js
- src/api/objects/Transaction.js
- src/plugins/notebook/plugin.js
- src/plugins/notebook/utils/notebook-migration.js
- src/plugins/persistence/couch/pluginSpec.js
* When transaction is active, objects.get should search in dirty object first.
Co-authored-by: Andrew Henry <akhenry@gmail.com>
> Transaction fix (#4421)

- src/plugins/displayLayout/components/TelemetryView.vue
Along with LAD Update this is a part of #4339 
Added RequestAnimationFrame to Alphanumeric views in Display Layouts. This increases performance almost 2 fold during high CPU usage.
> [Display Layout Alphanumerics] Using RAF on updating view for performance increase

- src/plugins/LADTable/components/LADRow.vue
- src/plugins/LADTable/pluginSpec.js
Using RequestAnimationFrame to render new values in the template.
> [LAD Tables] Use RAF for updating template

- .github/dependabot.yml
Github Checks are broken because dependabot cannot be configured to run two checks against the same package library. This PR combines the two checks into a single reference
> Dependabot cannot run two different npm scans

- .circleci/config.yml
Per Playwright team:
> playwright - library, installs browsers by default. with @playwright/test we walked away from it because people did not want all browsers by default, so you need to npx playwright install . You can npx playwright install chromium for bots that only run Chromium tests, etc.
> Always check and/or install latest e2e browsers

- .github/workflows/e2e-visual.yml
Percy needs to reference the PERCY_TOKEN stored in github
> Missing Percy Token

- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/mixins/imageryData.js
Closes #4328 
Solution maintains the previous image object and compares it against the updated imageHistory array. If the item is found, the index is updated and reference to the original focused image is maintained. If the previous image no longer exists in the updated bounds, the focused image will be set to the last item in the `imageHistory`.
> 4328 - Maintain reference to a focusedImage if the bounds change

- codecov.yml
Fixes https://github.com/nasa/openmct/issues/4549
At the moment, codecov is reporting on missing coverage in Spec.js files, themselves. This should ignore the test files from line coverage patch notes like https://github.com/nasa/openmct/pull/4522/checks?check_run_id=4436987606
> Ignore tests in codecov

- codecov.yml
Fixes #4549 
need to specify these lines as strings https://docs.codecov.com/docs/ignoring-paths
> String in our yaml

- .circleci/config.yml
This PR is the second refactor of our CircleCI script. It's designed to make our test results more stable and CI easier to troubleshoot. It cleans up a lot of the unused optimizations we made on the last refactor
Closes https://github.com/nasa/openmct/issues/4559 and https://github.com/nasa/openmct/issues/4560 and https://github.com/nasa/openmct/issues/4575
> [CI] CircleCI refactor for stability and to simplify troubleshooting

- src/api/objects/TransactionSpec.js
- src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
> Trasactions tests are ids equal fix 1.8.2

- src/plugins/exportAsJSONAction/ExportAsJSONAction.js
fixes: https://github.com/nasa/openmct/issues/4577
> "Export as JSON" yielding corrupted data

- src/plugins/charts/BarGraphCompositionPolicy.js
> Bar graph composition policy fix to allow condition set creation.

- src/plugins/imagery/ImageryView.js
- src/plugins/imagery/components/ImageryTimeView.vue
- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/pluginSpec.js
> Use image timestamp instead of image index to show large view

- .github/dependabot.yml
This should properly pick up anything with dependencies that don't begin with the package titles
> Update the regex detection on dependabot

- webpack.common.js
> webpack stats changed to 'errors-warnings'

- src/ui/mixins/object-link.js
* [] Unit tests included and/or updated with changes?
> use relative path for imports in object-link.js

- src/api/objects/ObjectAPI.js
- src/plugins/notebook/components/Notebook.vue
- src/plugins/notebook/utils/notebook-entries.js
> Notebook Snapshotting to the default Notebook isn't working

- src/ui/components/ObjectView.vue
- src/ui/inspector/details/Properties.vue
Resolves #4681 
Also ensure that the property being displayed in Properties is actually a part of the domainObject.
> Check for ref when trying to get the style receiver.

- src/plugins/linkAction/LinkAction.js
> Fix Link Action to accept the right input for validation

- src/plugins/notebook/components/Notebook.vue
Saving config for timeframe and sort for notebook entries.
closes: #4319
> [Notebook] Persist timeframe and sort configuration

- e2e/playwright-ci.config.js
- e2e/playwright-local.config.js
Comments out ipad support until we can address it in build 7. File the ticket here https://github.com/nasa/openmct/issues/4728
Adds project profiles to local testing
> [e2e] Add projects to local config and comment out ipad

- .github/dependabot.yml
This updates the PR to include a "safe word" for pr cop to ignore PRs opened by the dependabot user. The Dependabot PRs will not follow our issue template requirements because they strictly modify dependencies (which fall out of our traditional testing notes requirements)
> [CI] Dependabot and PR Cop have conflicts

- package.json
Closes: #4778 
This catches a node 12.18 and 12.19 bug which was fixed in node 12.20+. This will cause an WARN to be thrown if the node 12 version is note >12.20.1. (12.22.9 is the latest as of this writing)
> [Build] Update minimum node12 version

- src/plugins/flexibleLayout/components/frame.vue
- src/plugins/notebook/components/Notebook.vue
Closes: https://github.com/nasa/openmct/issues/4773
* Modifies the "Frame" component of Flexible layouts to fetch a MutableDomainObject if possible, instead of a regular domain object. This will allow the sub object view to react to asynchronous mutation events.
* Fixes a bug that would cause a JavaScript error if no default notebook was set at all.
> Observe changes to sub-objects in flexible layouts.

- src/plugins/timeConductor/ConductorInputsFixed.vue
- src/plugins/timeConductor/ConductorInputsRealtime.vue
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
Closes: #4722 #4772
Use the domain object identifier to check if the domain object being referenced in independent time conductor has changed.
Change the time context for independent time conductor, fixed and real time inputs if the domain object changes.
> Follow domain object changes for Independent time conductor

- src/plugins/plot/chart/MctChart.vue
Closes: VIPEROMCT-80
When the WebGL context fails (browsers typically limit to 8 or 16 contexts) we fallback to 2D. In this case, we need a template with a `main` and `overlay` canvases to render the plot. The template that was specified was `undefined`. This change ensures that the right template is used so that the canvas elements can be used for rendering.
> fix typo when using fallback template

- .github/workflows/e2e-pr.yml
Closes #4541 
github action triggers are currently not working across forks because of some homerolled script assumptions around owner and repo. I've hardcoded them to nasa/openmct.
> [CI] Update github actions automation to work across forks

- package.json
Closes #4800 
npm run clean is designed to clean the dist and node_modules folder. With the current implementation, it uses a relative path for ./dist but an absolute path /node_modules . Effectively, this means that node_modules are not cleaned on personal devices.
This PR corrects that mistake
> [Build] npm run clean uses absolute path instead of relative for node_modules

- src/plugins/plot/MctPlot.vue
- src/plugins/timeConductor/ConductorInputsFixed.vue
- src/plugins/timeConductor/ConductorInputsRealtime.vue
Closes #4777 
Update display bounds when switching between time conductor modes. Which in turn re-requests data.
Also add some null checks.
> Request data when switching between real time and fixed.

- .npmrc
- package.json
Closes https://github.com/nasa/openmct/issues/4845
Adds a flag in npmrc to enforce engine rules
> [Build] Enforce engine at build time

- package.json
- webpack.common.js
Closes https://github.com/nasa/openmct/issues/3966
* Bumps version numbers of webpack, vue, and vue-template compiler which fixes the issue we were seeing where Open MCT builds would hang after successful compilation on Node 16+
* Updates `engines` attribute in `package.json` to bump minimum supported Node version to 12.22.0 due to incompatibility with vue-eslint-parser library
* Removes maximum supported Node version
> Bumped dependency versions to fix build issues in Node 16 and later

- .github/workflows/pr-platform.yml
Closes #4909 
This adds the quiet flag to the `npm run lint` when run as a part of the pr:platform workflow. This prevents output from the cli being generated and attached to the 'Files' in-line help.
> [CI] Remove warning output for eslint on platform workflow

- src/plugins/plan/util.js
Closes #4882
The VIPER planning tool team has changed the structure of the JSON they post to couchDB. In order to not change the current model for plans in Open MCT, we're introducing a sourceMap option where JSON properties can be mapped to expected json properties. For example:
`object.sourceMap = {
start: 'start_time',
end: 'end_time',
activities: 'items',
groupId: 'group_name'
};`
> Add source maps to map plan properties to expected properties

- src/plugins/CouchDBSearchFolder/plugin.js
- src/plugins/CouchDBSearchFolder/pluginSpec.js
- src/plugins/linkAction/LinkAction.js
- src/plugins/remove/RemoveAction.js
Closes #4951 
Fixes a small bug related to the implementation of https://github.com/nasa/openmct/issues/4899
> Link action fix

- src/plugins/viewLargeAction/viewLargeAction.js
Closes #4401
Example of performance.mark for measure UserTiming(). It then becomes available in devtools as:
> Add Performance Mark to View Large action

- .circleci/config.yml
Temporarily disable e2e-ci checks on release/2.0.2 due to https://github.com/nasa/openmct/issues/5029
> [Temp] Remove e2e-ci until percy fix

- package.json
Closes: https://github.com/nasa/openmct/issues/5029 and https://github.com/nasa/openmct/issues/5034
Pins percy to a working version by overriding the depenency resolution
We did this a few months ago for core-js https://github.com/nasa/openmct/pull/4795/files#r794604908
Here is some more info https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
> [Build] Update broken transitive percy package and override core-js

- src/plugins/imagery/components/ImageryView.vue
Closes #4850 
Scroll to focused image when view resizes - this will force scrolling to focused image when going to/from view large mode
> Handle scrolling to focused image on resize/new data

- src/plugins/displayLayout/components/TelemetryView.vue
Closes #5130  
Added Telemetry Collections to Alphanumeric Telemetry Views. There was a logic error that was preventing Alphanumeric views from loading the rest of the telemetry in a view with extended end offsets when switching from local to fixed time. This not only fixes that, but let's the view use the Telemetry Collection to handle all the bounds logic.
> [Alphanumeric Telemetry View] Using Telemetry Collections

- src/MCT.js
- src/api/telemetry/TelemetryCollection.js
- src/plugins/gauge/GaugePluginSpec.js
- src/plugins/gauge/GaugeViewProvider.js
- src/plugins/gauge/components/Gauge.vue
- src/plugins/gauge/components/GaugeFormController.vue
- src/plugins/gauge/gauge.scss
- src/plugins/telemetryTable/collections/TableRowCollection.js
- src/plugins/telemetryTable/components/table.vue
Closes #5117 
- Refactored markup approach to dial-type Gauge to enable usage of SVG's proportional resizing capabilities. Significant changes to Filled Dial and Needle Dial gauge types' markup and CSS. Markup structure and CSS have both been simplified.
- New approach to filled dial graphic value and limit display elements to reduce usage of clip-paths as a consequence of SVG approach noted above, with new utility functions.
- Test hooks added.
> Dynamic dial-type Gauge sizing by height and width

- src/plugins/plot/MctTicks.vue
- src/plugins/plot/tickUtils.js
Closes https://github.com/nasa/openmct/issues/2297 (specifically addresses https://github.com/nasa/openmct/issues/2297#issuecomment-1112724445 but unfortunately restores https://github.com/nasa/openmct/issues/2297#issuecomment-1109114296 for now). The former is a blocker, the latter, while not ideal, is not. 
We need to address log scale ticks to arrive at a solution that works in all cases which will take a little more work.
Reverts _some_ of the changes made in https://github.com/nasa/openmct/pull/5119 , but leaves the fix for the error in place.
> Reverts forced precision for log plots axis labels

- e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
- src/api/telemetry/TelemetryCollection.js
- src/plugins/imagery/components/ImageryView.vue
> Use navigator platform to display separate for Linux OS - 4848

- src/plugins/persistence/couch/README.md
Modified the instructions to reference the homebrew location of `local.ini`
Closes https://github.com/nasa/openmct/issues/5164
> Update the path of local.ini for homebrew installs

- e2e/tests/plugins/timeConductor/timeConductor.e2e.spec.js
Closes 
#4914 
Created test: Time conductor input fields real-time mode
The test Clicks on realtime "Local Clock" mode and updates the start offset and the preceding offset time in seconds. The test validates the new expected offset times. 
* [ x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ x] Changes address original issue?
* [ x] Has this been smoke tested?
* [ x] Testing instructions included in associated issue?
> Time conductor real time 4914

- e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
- src/plugins/imagery/components/ImageryView.vue
Closes  #5068 and Closes #5149
~~- [ ] The orange "paused" border and icon should only be displayed when the view is in real-time mode AND the view is in a paused state.~~ [Currently the system works that way without change]
> Pan/Zoom persistence and pause handling improvements - 5068

- src/plugins/imagery/components/ImageryView.vue
Fixes VIPEROMCT-112
Rebased on `release/2.0.4`
* Removed the condition of `Invalid Date` appearing after clearing data. This was caused by NaN being assigned to `this.numericDuration` when `this.parsedSelectedTime` was undefined. Remedied this by checking for type of Integer and adding an else clause to mark numericDuration undefined so the N/A text would properly appear.
* Add an extra integer check in formattedDuration to clear the sticking duration
1. Navigate to Example Imagery
2. Select Local clock
3. Activate the Clear Data action
4. Observe that the Freshness Indicator says N/A instead of Invalid Date
> Eliminate NaN conditions and clear stale duration in Freshness Indicators

- e2e/tests/visual/default.visual.spec.js
Add coverage for broken Display Layout Icon in Create Menu. Implicitly tests the Create Menu Layout.
> Add visual test for create menu and display layout icon

- src/plugins/imagery/mixins/imageryData.js
Closes issue with images being removed if they matched the previous set of data.
Side effect of a fix for: #5274
> Imagery validation fix

- e2e/fixtures.js
Closes #5273 
Create a separate assert for every `ConsoleMessage` received so it's more clear why tests fail due to console error detection. Additionally, adds a helper function which converts the `ConsoleMessage` to a string in order to provide additional information such as file location, line, and column numbers.
> [e2e] Add clarity to console.error failures

- src/plugins/imagery/pluginSpec.js
Closes https://github.com/nasa/openmct/issues/5319
Adds a single test for imagery filter change / reset. A little coverage bump!
> Add test for imagery filter reset

- src/plugins/imagery/components/FilterSettings.vue
- src/plugins/imagery/components/ImageControls.vue
Get the imagery slider drag fix into 2.0.5! #5326 
Code was previously reviewed/merged into master in #5342
> Fix imagery filter slider drag in flexible layouts

- e2e/tests/persistence/persistability.e2e.spec.js
- e2e/tests/plugins/gauge/addInitGauge.js
- e2e/tests/plugins/notebook/restrictedNotebook.e2e.spec.js
- e2e/tests/visual/addInit.visual.spec.js
Covers #5323 
Adds a visual test for gauges using the addInit method to inject a non-default plugin.
> Replacement for Visual Test for Gauge PR

- e2e/tests/plugins/timer/timer.e2e.spec.js
- src/api/actions/ActionCollection.js
- src/plugins/timer/actions/PauseTimerAction.js
- src/plugins/timer/actions/RestartTimerAction.js
- src/plugins/timer/actions/StartTimerAction.js
- src/plugins/timer/actions/StopTimerAction.js
- src/plugins/timer/components/Timer.vue
Closes #4313 
When clicking Timer actions in a 3dot menu, the available actions now update appropriately.
My initial approach was to observe all changes to the given `domainObject`, and refresh the `actionCollection` once any change was observed. However, this led to a lot of weird issues and edge cases such as menu options disappearing if the `actionCollection` was refreshed in a view/large view. Also, the Timer is unique in that it refreshes itself on every tick in order to remain in sync across browser instances. This approach meant triggering re-renders on every tick if working with a Timer.
I settled on a hybrid approach to action availability in regards to the Timer:
- If the actions are within a viewless context menu (such as right clicking on the Timer in the tree view), then the …
> [Timer] Update 3dot menu actions appropriately

- example/generator/plugin.js
- src/plugins/gauge/GaugePluginSpec.js
- src/plugins/gauge/components/Gauge.vue
- src/plugins/gauge/gauge.scss
- Significant work refactoring SVG markup and CSS for dial gauge;
- Fixed missing `v-if` to control display of units for #5325;
- Fixed bad `.length` test for limit properties;
- Fixed cross-browser problems with current value display in dial gauge;
- Added "out of range" indicator (yellow arrows) and hover tooltip;
- Range text (purple arrows) now dynamically sizes to fit based on character length;
Closes #5323 
Closes #5325
Closes #5139
> Gauge fixes for Firefox and units display

- src/api/telemetry/TelemetryCollection.js
Closes #5419  
When  `options.strategy = 'latest'` for a request, we should only hold onto one value... the latest one within the current time bounds. This fix adds logic for processing new telemetry to only take the latest one within the new telemetry and bounds. Also, on ticks, old telemetry is discarded and any future bound telemetry is then checked for latest values.
> [Telemetry Collections] Respect "Latest" Strategy Option

- src/MCT.js
- src/plugins/plot/configuration/Model.js
Closes VIPEROMCT-89
Defines the `openmct` object in such a way that its properties will not be reactified by Vue if the `openmct` object itself is assigned to a reactive property on a Vue model accidentally. Note that this does not entirely prevent specific APIs or their products (eg telemetry) from being reactified if they are separately assigned to a reactive property.
Also introduces a small change to the `Model` class used in the Plots code to prevent some of the inner workings of EventEmitters becoming reactified. Together, these two fixes prevent a recursion event with Vue reactivity that was causing the UI to freeze when viewing numerical telemetry from a map layer.
> Lock model

- src/plugins/imagery/mixins/imageryData.js
Closes VIPEROMCT-141
Don't use utc key to compare time based data. Use the timeKey instead.
> Use timeKey for time comparison of imagery datum

- src/api/objects/ObjectAPI.js
- src/plugins/persistence/couch/CouchDocument.js
- src/plugins/persistence/couch/CouchObjectProvider.js
Closes #5441 #5472
Handle no response on bulk get requests to couchdb:
* set couchdb status to disconnected 
* skip applying interceptors.
Also, only set the created date on document creation.
> Fix couchdb no response

- src/ui/layout/search/ObjectSearchResult.vue
Closes #5439 
Getting rid of `ROOT` in the URL makes the URL match what the tree viewer is expecting.
> 5439 clicking on a search entry does not navigate to entry in tree release

- package.json
Related to #5491  
Temporarily remove `exampleImagery` suite from CI as it is consistently flaky and needlessly blocking PRs. Flakiness to be addressed as part of #5491
> [e2e] Remove flaky `exampleImagery` suite from CI

- e2e/README.md
- e2e/appActions.js
- e2e/pluginFixtures.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/framework/exampleTemplate.e2e.spec.js
- e2e/tests/framework/pluginFixtures.e2e.spec.js
- e2e/tests/functional/branding.e2e.spec.js
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js
- e2e/tests/functional/plugins/timer/timer.e2e.spec.js
Closes #5571 
Contributes towards #5513 
- Allows `createDomainObjectWithDefaults` to create multiple domain objects in a row
- Updates some test suites to use `createDomainObjectWithDefaults`
- Generalizes references to `My Items`/`Shared Items`
- Disables / updates docs for fixtures which are WIP and not meant to be used currently
- Adds a new `@2p` annotation for tests involving multi-user interactivity
- Updates some selectors to be more deterministic
> [e2e] More VIPER compatibility fixes

- e2e/appActions.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/framework/exampleTemplate.e2e.spec.js
- e2e/tests/framework/generateVisualTestData.e2e.spec.js
- e2e/tests/functional/example/eventGenerator.e2e.spec.js
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
- e2e/tests/functional/plugins/timer/timer.e2e.spec.js
- e2e/tests/visual/addInit.visual.spec.js
- e2e/tests/visual/default.visual.spec.js
- e2e/tests/visual/search.visual.spec.js
- src/api/objects/ObjectAPI.js
Contributes towards #5513  
- Adds `getHashUrlToDomainObject` which utilizes the Open MCT API to generate a navigable url to the given object or telemetry
- Adds `getFocusedObjectUuid` which gets the UUID of the currently focused object
- Updates `createDomainObjectWithDefaults` to utilize these methods
- Updates documentation
- Updates usages of `createDomainObjectWithDefaults` to be compatible with the new API
- Adds `setLocalClockMode` and `setFixedClockMode` for switching between modes using hash url navigation
> [e2e] Improve appActions

- src/plugins/timelist/Timelist.vue
Closes https://github.com/nasa/openmct/issues/5605
Ensures the `sourcemap` gets passed to the `getValidatedData` function. The plan schema changed at some point and the `sourceMap` supports mapping from the new schema to the schema supported by Open MCT.
The absence of the source map was causing `undefined` to be passed into `moment` which for inexplicable reasons is the equivalent of doing `Date.now()`.
> Fix time list

- package.json
- src/api/objects/ObjectAPI.js
Closes #4915 
The initial issue was that some items in the composition array were key strings instead of objects with a key/namespace. Folders were not being removed because it couldn't find the matching identifier. This is a fix for a bug with the areIdsEqual util. This resolved the issue with the folders being removed with either the key string or object.
I couldn't duplicate the initial issue stated above when exporting and importing JSON. This might have already been fixed.
> Add parsing for areIdsEqual util to consistently remove folders

- .github/dependabot.yml
Closes #5653 
This adds `@playwright/test` to the ignore list of dependabot and establishes the pattern of ignoring certain dependencies
Drive-by: remove unused label and re-order existing labels to get past gh api bug
> [CI] Update dependabot ignore list for dependencies which will always fail

- e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
- src/plugins/condition/criterion/TelemetryCriterion.js
* Check telemetry is defined before using makeKeyString util
* Add optional chaining in the check
* Add e2e test
* Add check for undefined
* 
Back merging condition set fix.
> [Condition Set] Add check for empty string being passed to the makeKeyString util by TelemetryCriterion (#5636)

- e2e/tests/functional/couchdb.e2e.spec.js
- e2e/tests/functional/search.e2e.spec.js
- src/api/objects/InMemorySearchProvider.js
- src/ui/layout/search/GrandSearchSpec.js
Closes #5690 
Only index new objects if they don't have a search provider
> Only index if provider does not support search - mct5690

- .circleci/config.yml
- e2e/playwright-visual.config.js
- package.json
Closes #5742 
- Downgrades `percy/cli` from 1.10.0 --> 1.7.2. This is the version we were on before we started seeing a marked increase in visual test timeouts
- Limit visual test runs to 1 worker in CI
- Increase visual test timeout slightly from 1 min to 1.5 min
- Increase the Percy logLevel to 'debug' to make visual test logs more informative (in regards to percy)
> [e2e] Fix intermittent visual test timeouts

- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/plugins/flexibleLayout/components/frame.vue
Closes #5389 
This change set the draggable property on the panes to false when in browse mode to prevent drag and drop while not editing.
> [Flexible Layout] Fix draggable status for layout items while in browse mode

- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/flexibleLayout/components/frame.vue
- src/plugins/timeline/TimelineObjectView.vue
Closes #5682 
When you create a child element under a domain object, Open MCT navigates to that object. When this happens, Vue sends out a `destroy` call to the parent's children so that it can change the current view to show the child element. 
In this case, it tries to destroy the child element before it is done mounting (and this setting the domain object).
> Don't destroy mutable if the domain object is not ready yet

- e2e/.percy.yml
- e2e/playwright-visual.config.js
- package.json
Addresses https://github.com/nasa/openmct/issues/5742 , does not close it
Addresses some flakiness from the percy/cli
> A couple of fixes for percy flakiness

- .github/dependabot.yml
Addresses  https://github.com/nasa/openmct/issues/5760
Drive-by to reduce the frequency of https://github.com/nasa/openmct/pull/5758
> [Build] Add @babel/eslint-parser to ignore list

- .github/dependabot.yml
Addresses https://github.com/nasa/openmct/issues/5760
Ignores patch releases for this linter
> Ignore patch of eslint-plugin-vue

- src/api/indicators/IndicatorAPI.js
- src/api/indicators/IndicatorAPISpec.js
- src/api/indicators/SimpleIndicator.js
- src/plugins/URLIndicatorPlugin/URLIndicatorPlugin.js
- src/plugins/operatorStatus/operatorStatus/OperatorStatusIndicator.js
- src/plugins/operatorStatus/pollQuestion/PollQuestionIndicator.js
- src/plugins/performanceIndicator/plugin.js
- src/plugins/persistence/couch/plugin.js
Reverts nasa/openmct#5729
Saving the yKey to each series of the plot
> Revert "#5621 for O4M 4.10 release"

- src/plugins/plot/MctPlot.vue
- src/plugins/plot/pluginSpec.js
Closes #5785 
Saving the yKey to each series of the plot
> [Plot] Set yKey on each plot series

- src/plugins/timeConductor/ConductorHistory.vue
No related issue 
Adds an `aria-label` to the Time Conductor History button. [A test was added recently using this as a selector](https://github.com/nasa/openmct/blob/1c00f1a731263cd7573f02e0a8f1591b634d2298/e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js#L182), but this change didn't make it in somehow (whoops :eyes:).
> Add `aria-label` for Time Conductor History button

- webpack.dev.js
Closes #5832 
Have the `webpack-dev-server` write to disk the external assets we're using, including CSS files.
> Have webpack-dev-server write webpack assets to disk

- src/plugins/persistence/couch/CouchChangesFeed.js
Closes #5406 
In certain scenarios (such as receiving a 4xx or 5xx HTTP response code), the Couch changes feed `EventSource` can become closed. This means that the status indicator will no longer receive live updates, since the `EventSource` cannot receive messages from couch, and is not actively trying to reconnect.
This PR adds a keep-alive timer which will attempt to reconnect to the most recently used `changesFeedUrl` if the `EventSource` has become closed for whatever reason.
> [CouchDB] Re-establish feed connection if EventSource is closed due to error

- src/plugins/plan/README.md
Adds documentation and JSON format for Plans views and domain objects.
> Plan documentation

- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/configuration/PlotSeries.js
Closes [#190](https://github.com/akhenry/openmct-yamcs/issues/190)
Fetch limits after we've loaded the data, and then ask the plot to paint them.
> Fix timing issue where limits weren't painting

- src/api/objects/MutableDomainObject.js
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/plugins/notebook/components/Notebook.vue
Closes https://github.com/nasa/openmct/issues/5919
Changes when the persisted timestamp is evaluated to avoid issues with timing ambiguity. The persisted timestamp is now always calculated _after_ the last modification.
> Fix persistence timestamp

- src/ui/layout/mct-tree.vue
Closes #5976 
Due to some issues with yamcs, we're seeing duplicate items with the same key in the VIPER dictionary. Making the tree item key unique allows duplicates to render without breaking.
> Make the tree item key unique for Vue

- webpack.prod.js
Closes #6005
Change prod source map strategy to `source-map`
> Use `source-map` strategy in prod builds

- README.md
Closes https://github.com/nasa/openmct/issues/6006
* Removes link to retired live demo
* Replaces screenshot from live demo because people like screenshots.
> Remove link to retired live demo

- src/ui/components/TimeSystemAxis.vue
Closes #5629
The time system axis time stamp uses the open mct clock's current value to show the now marker
> Use the current clock's timestamp to show the now line in the timestrip

- src/ui/inspector/PlotElementsPool.vue
Closes #6096 
Enable dragging of series elements directly into YAxis buckets within the PlotElementsPool
> feat(MultiYAxis): allow drag/drop of series directly into YAxis buckets

- src/plugins/plot/MctPlot.vue
- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/stackedPlot/pluginSpec.js
> [Multiple Y-Axis] Fix pan/zoom/history for multiple-y axis

- src/plugins/plot/MctPlot.vue
- src/plugins/plot/chart/MctChart.vue
Closes #6157 
- Get the correct bounding box for annotations for a telemetry endpoint (series) based on which y axis it belongs to - for both creation of annotations and when showing existing annotations.
- Handle addition of telemetry to plots after annotations have been saved before.
- Handle removal of telemetry from plots after annotations have been saved.
> Mct6157 creating annotations for plots on multiple yaxes

- src/plugins/plot/chart/MctChart.vue
Closes #6163 
Gets the yRange for the specific yAxis that the series belongs to instead of using the main yAxis's range every time.
> fix(multiYAxis): get yRange for yAxis of the series

- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- src/plugins/plot/configuration/SeriesCollection.js
Closes #6182 
Short-circuits some logic that runs on collection load in the case of a legacy overlay plot with no yAxisId value set.
> fix: skip if no yAxisId exists on persistedConfig

- src/ui/inspector/elements.scss
- translation: remove the baby scroll bars from element item groups
> cherry-pick(#6171): fix(elementItemGroup): 🚫👶📜📊

- src/plugins/plot/chart/MCTChartAlarmLineSet.js
- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/configuration/PlotConfigurationModel.js
- src/plugins/plot/inspector/forms/YAxisForm.vue
- src/plugins/plot/pluginSpec.js
Closes #6106 
- Ensure limit lines for both the old and new y axes are redrawn when a… series moves from one y axis to another
- Optimize initialization of Plot configuration
- Ensure the the y axis form correctly saves any changes to the configuration Fix excluded limits test
> Fix limit line rendering for overlay plots, especially with multiple y axes.

- e2e/appActions.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/functional/moveAndLinkObjects.e2e.spec.js
- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- e2e/tests/functional/tree.e2e.spec.js
- e2e/tests/visual/components/tree.visual.spec.js
- src/api/forms/components/controls/Locator.vue
- src/styles/_controls.scss
- src/ui/layout/Layout.vue
- src/ui/layout/mct-tree.vue
Closes #5994 
- Adds `visibility` css attributes to the `.c-disclosure-triangle` on the object tree, so that we can better locate expandable tree items within Playwright.
- Adds an appAction for expanding the entire object tree
> Make tree items more actionable and add AppAction for expanding the object tree

- e2e/appActions.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/functional/moveAndLinkObjects.e2e.spec.js
- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- e2e/tests/functional/tree.e2e.spec.js
- e2e/tests/visual/components/tree.visual.spec.js
- src/api/forms/components/controls/Locator.vue
- src/styles/_controls.scss
- src/ui/layout/Layout.vue
- src/ui/layout/mct-tree.vue
* style: add `visibility` to tree expand triangles
- The purpose of this is so that Playwright can perform actionability checks on the tree items. This will make operations involving expanding tree items much easier to perform in e2e.
* feat(e2e): Add AppAction to expand the entire tree
* fix: wait for loading indicator
* test: add test for `expandEntireTree`
* test: update `expandEntireTree` and tree selectors
- Use dynamic aria-label for different tree implementations
- Get rid of CSS ids which are only for testing
- Update percy tree scope selector
* chore(lint): remove unused variable
* refactor(e2e): update tree locators
Co-authored-by: John Hill <john.c.hill@nasa.gov>
> cherry-pick(#5997): Make tree items more actionable and add AppAction for expanding the object tree

- src/plugins/move/MoveAction.js
Closes #6197 
Eliminates a codepath whereby the MoveAction might not save its current transaction if the item being moved is not a child of the currently focused object. This set off a chain of events that caused madness to ensue, and Open MCT to get into a really wacky state.
> fix: ensure MoveAction always saves transaction

- e2e/appActions.js
Closes #6225 
Adds a hard wait of 200ms to the `expandEntireTree` appAction to stabilize tests that utilize this method. This is a temp fix until we have a better way to listen to Vue events (the flake is due to a race condition with Vue rendering).
> fix(e2e): temp fix for appAction test flake

- src/api/objects/MutableDomainObject.js
Closes #6236
Replaces usage of `structuredClone` with `JSON.parse` to support functions in imagery metadata. `structuredClone` throws an error when trying to clone an object with function attributes.
> Replace structuredClone with JSON.parse

- e2e/tests/functional/recentObjects.e2e.spec.js
- src/ui/components/ObjectPath.vue
Closes #6151  
Provides a `navigateToPath` to `ObjectLabel` so that navigation from a breadcrumb works correctly. Previously, the navigationPath generated by the `ObjectLink` mixin was also including params, which navigates correctly but sometimes fails to update the URL hash due to logic within the Router. Params are set after navigation, and unless they're being changed (or we're opening a link in a new tab), there's no reason to include these in the navigation path.
> fix: Navigating from Recent Objects breadcrumb correctly updates the URL hash

- e2e/tests/functional/plugins/plot/logPlot.e2e.spec.js
- src/plugins/plot/MctPlot.vue
- src/plugins/plot/MctTicks.vue
- src/plugins/plot/axis/XAxis.vue
- src/plugins/plot/axis/YAxis.vue
- src/plugins/plot/configuration/PlotSeries.js
- src/plugins/plot/configuration/YAxisModel.js
- src/plugins/plot/legend/PlotLegend.vue
- src/plugins/plot/stackedPlot/StackedPlot.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
Issue #6166 #6147
* Ensure enabling log mode does not reset series that don't belong to that yaxis. propagate both left and right y axes widths so that plots can adjust accordingly
* Revert code Handle second axis resizing
* Fixes issue where logMode was getting initialized incorrectly for multiple y axes
* Get the yAxisId of the series from the model.
* Address review comments - rename params for readability
* Fix number of log ticks expected and the tick values since we reduced the number of secondary ticks
* Fix log plot test
* Add guard code during destroy
* Add missing remove callback
> cherry-pick(#6204): Fix multiple y axis issues

- example/generator/SinewaveStalenessProvider.js
- src/plugins/LADTable/components/LadTableSet.vue
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/plot/Plot.vue
- src/plugins/telemetryTable/TelemetryTable.js
Issue #6160 
* fixing error from plots when removing swg and making methods and props private for swg staleness provider
* removing unsubscribes from destroy hooks if the item has been removed already and reverting an unneccesary change
* checking for undefined staleness response
* removed un-neccesary code
> cherry-pick(#6241): [Staleness] Fix removed object error and clean up

- e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js
- src/styles/_legacy-plots.scss
Closes #6267 
Removes a seemingly unnecessary [1px padding to plot legend items](https://github.com/nasa/openmct/pull/6108/files#diff-2dbf1e2d399ba036135dbc9d1c8e86d1cb7ae10cf340420eee0d60b66505d3f1R667) that was squishing our plot and causing our snapshot tests to fail. Re-enables the autoscale snapshot tests.
Here is the plot legend item without 1px padding:
..and with:
@charlesh88 thoughts? is this ok to remove or should we regenerate snapshots?
> fix: remove 1px padding and re-enable autoscale snapshot test

- src/plugins/imagery/components/Compass/CompassRose.vue
Closes #6257
- Moved rotation styling into new `<g>` element that holds both cam FOV and `vrover` element.
- Removed `this.north` from `camGimbalAngleStyle` computed value.
- Code cleanup.
Closes
> Compass rose rotation fixes

- e2e/tests/functional/recentObjects.e2e.spec.js
- src/ui/components/ObjectPath.vue
- src/ui/layout/RecentObjectsList.vue
- src/ui/layout/RecentObjectsListItem.vue
Closes #6150 
Adds tests for Recent Objects to cover the following:
- Basic smoke test
- Object renames are reflected
- Object deleted are reflected
- Clicking on object path navigates and updates url hash
- Persists on refresh
- Displays objects and aliases uniquely
- Clicking on target button scrolls object into view and highlights it
- Enforces a limit of 20 objects
> test(e2e): Add tests for Recent Objects

- src/ui/inspector/Inspector.vue
Closes #6287 
Adds optional chaining to handle the case where parentless objects such as shapes and lines would be selected in the displayLayout. Previously this was failing as a check to determine if the selected object was an Overlay Plot was expecting the parentObject to be defined.
> fix: DisplayLayout shapes can be selected and manipulated again

- src/ui/inspector/Inspector.vue
fix: handle case where parentObject is undefined
- Fixes manipulation of parentless display layout objects such as shapes and lines
Issue #6287
> cherry-pick(#6289): fix: DisplayLayout shapes can be selected and manipulated again

- example/generator/SinewaveStalenessProvider.js
- src/plugins/LADTable/components/LadTableSet.vue
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
* add handling for composition items (ex overlay plot) in stacked plots, fix swg staleness provider isStale method response
* typo
* removing staleness listeners when ladtable is remove
* addressing pr comments for this component
* address changes requested for lad table sets
* had to update is-stale for the row since we used combined keys in lad table sets now
Issue: #6265
> cherry-pick(#6281): [Staleness] Handle Overlay Plots in Stacked Plots and removing LAD Tables from LAD Table Sets

- src/api/time/IndependentTimeContext.js
- src/api/time/independentTimeAPISpec.js
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
Reverted a change where if a plot has it's own context, it would never be cleared out.
Closes #6107
> [TimeAPI] Fix independent time context check

- src/plugins/notebook/components/NotebookEntry.vue
Closes #6312
- Set entry inputs to `tabindex="-1"` to prevent tabbing into them.
> Prevent tabbing into Notebook entries

- e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
- src/api/time/IndependentTimeContext.js
- src/api/time/TimeAPI.js
- src/api/time/independentTimeAPISpec.js
Closes VIPEROMCT-259 and #6107
When independent time context is enabled for a view, it sends a `refreshContext` event. In response to this event, any other the views bing displayed re-calculate their `upstreamContext`. 
When there are multiple views on the viewport, the `refreshContext` call resets the time context of all but the last view to the global time context if the `objectPath` of those views has only one item.
The fix for this is to check if the first item in the `objectPath` has it's own context and return `undefined` as the `upstreamContext`
This fix then breaks the logic to _remove_ the independent context for views, because we cannot set the upstream context for the view `this.hasOwnContext()` will cause a `undefined` return.
So we now need to decouple the removal of a view's …
> Decouple removal of independent time context for a view from refreshing context for other views

- src/api/time/IndependentTimeContext.js
- src/api/time/independentTimeAPISpec.js
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
Issue https://github.com/nasa/openmct/issues/6107
* Fix independent time context to check first object in path (self) for upstream content instead of last object in path
* Revert changes that don't allow unregistering independent time context
> cherry-pick(#6308): [TimeAPI] Fix independent time context check

- e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
- src/api/time/IndependentTimeContext.js
- src/api/time/TimeAPI.js
- src/api/time/independentTimeAPISpec.js
Issue #6107 
* Decouple removing the context for a view from refreshing the context of views to get their upstream contexts
* Add test for clicking on an item in the elements pool for a preview
* Add test to ensure independent time context for items with no parents works as expected
> cherry-pick(#6334): Decouple removal of independent time context for a view from refreshing context for other views

- src/api/telemetry/TelemetryCollection.js
- src/plugins/imagery/mixins/imageryData.js
Closes VIPEROMCT-190
When data comes out of order (timestamps) is handled by the Telemetry Collection, it internally correctly sorts and stores the items. In addition to that, also emit the indices of added items so that consumers of the telemetry collection (like imagery views and telemetry tables) can act on the change accordingly.
In the imagery data mixin, handle indices of added telemetry provided by the telemetry collection.
> Emit indices of out of order telemetry collection items

- package.json
> chore: bump version to `2.1.6`

- src/plugins/imagery/components/ImageryView.vue
Closes  #6300 
Added logic to prevent element focus on mouseover events when the view is composed in layouts. The original intent of the focus mouseover is maintained when imagery is not in a layout view.
> Ignore focus mouseover event when composed in layout

- src/styles/_table.scss
Closes VIPERGC-87
Constrained the LAD tables to behave more like telemetry tables by fixing the table layout and by hiding overflows. This will prevent unwanted jiggling of columns with large character counts like those that return stringified arrays.
> Set table to fixed layout and ellipted overflowing cells

- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/components/inspector/StylesView.vue
Closes #6444 #5925 
When going from Edit mode to view only mode, reset the selection so that only the computed condition set styling is applied.
Don't initialize the selected condition style when a view is loaded. Allow the condition set computed output to determine what the selected style should be.
> Don't initialize the selected condition style when a view is loaded

- src/ui/layout/mct-tree.vue
Closes #6488
- Splits the parent and child navigationPaths into arrays of keystrings and then checks to ensure that every keystring in the parent path is included in the child path (is a subset)
- Array.includes is not only more performant than String.includes, but will do an exact match against array elements instead of checking for substrings.
This fixes the edge case of siblings being removed if their keystring includes a substring of the collapsing tree item's keystring (e.g.: collapsing `Science` folder removes sibling `ScienceSimData` folder)
> fix(#6488): better determination of child tree items when collapsing a parent

- .circleci/config.yml
- .github/workflows/pr-platform.yml
- package.json
> [Build]Remove Node14LTS from supported versions and update our pipelines

- e2e/baseFixtures.js
- e2e/pluginFixtures.js
- e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
- e2e/tests/functional/plugins/notebook/restrictedNotebook.e2e.spec.js
- src/api/actions/ActionsAPI.js
- src/plugins/exportAsJSONAction/ExportAsJSONAction.js
- src/plugins/importFromJSONAction/ImportFromJSONAction.js
- src/plugins/notebook/actions/ExportNotebookAsTextAction.js
- src/plugins/notebook/utils/notebook-entries.js
Closes #6534 #6535
Add Restricted Notebook to allowed objects for the action. Change initialization of `user` in Notebook to null. Check for blank strings when exporting markdown of Notebook.
> Allow Restricted Notebooks to export text

- .github/dependabot.yml
Part of https://github.com/nasa/openmct/issues/5760
moment-timezone is becoming noisy when adding small new timezone changes. Let's ignore the patches
> [CI] Stop taking patch releases for moment-timezone

- package.json
We're not detecting Safari version in our es-plugin-compat package. Let's explicitly add Safari as well as iOS.
Fix logic to be >=16
> Add safari as well as iOS safari browserlist check

- src/plugins/exportAsJSONAction/ExportAsJSONAction.js
Closes #6566
Ensure that exporting works when: 
Exported objects have composition only
Exported objects have object references only
Exported objects have composition OR object references
Exported objects have composition AND object references
Exported objects have no composition and no object references
> Only decrement and save if there is composition but no child object reference

- .github/dependabot.yml
Runs dependabot weekly instead of hourly so that we can reduce the PRs which are using up our CI minutes
Driveby: Move the order of `pr:daveit` to see if the order affects whether PRCop is skipped
> Move Dependabot to weekly to reduce frequency of changes and reduce CI Bill

- .github/dependabot.yml
Addresses (but does not close) #5760 
Adds types/lodash to dependabot ignore list to only detect major changes
> Add @types/lodash to dependabot semver ignore list

- e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
No related issue. 
Fix a long-standing test flake with an Overlay Plot e2e test. Wait for the plots to be drawn before making assertions.
> test(e2e): fix overlay plot element preview test flake

- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-pr.yml
No related issue.
Updates the e2e-couchdb GHA to remove the `pr:e2e:couchdb` label on run completion (if label is present).
> fix: remove `pr:e2e:couchdb` label on run completion

- e2e/tests/visual/ladTable.visual.spec.js
- src/ui/layout/BrowseBar.vue
- src/ui/layout/pane.vue
Closes #6639
Added title attributes to actions in the browse bar that will pull from the action names, like we do elsewhere in the code. Added a visual test for LAD Table column sizing fix in: #6636
> [LAD Table][Browse Bar] Visual test and title attributes for actions

- e2e/tests/functional/planning/ganttChart.e2e.spec.js
- e2e/tests/visual/planning.visual.spec.js
- src/plugins/plan/components/Plan.vue
Closes #6641 VIPEROMCT-303 
The Gantt Chart view was not respecting / displaying the draft status of a Plan if it was in its composition. This updates the logic to set the status when a domainObject is added in composition.
> fix: Gantt Chart displays draft status of Plan in composition

- src/plugins/linkAction/LinkAction.js
- src/plugins/move/MoveAction.js
Closes #6654
- Corrected form builder configurations.
Closes
> Fix Locator in Move and Link dialogs

- package.json
> chore: bump version to `2.2.4-SNAPSHOT`

- package.json
Remove snapshot from release version
> Fix release 2.2.3 version

- src/plugins/inspectorViews/annotations/AnnotationsInspectorView.vue
Closes #6689 
Stops listeners from stacking up when clicking through to view multiple annotations.
TODO: CouchDB / YAMCS quickstart regression test
> fix: unlisten to annotation event beforeDestroy

- package.json
> chore: bump version to `2.2.5-SNAPSHOT`

- package.json
Buffer in place until we can formally support https://github.com/nasa/openmct/issues/6732
`[node_modules/@achrinza/node-ipc](https://github.com/achrinza/node-ipc/issues/45)` has a version range up to 20 and is failing builds for folks using 20. We should be more explicit in our deps and tackle node20 holistically.
Until then, we should be preventing installs on node20.
> [Build] Update package engine version range to block on node 20

- package.json
> chore: bump version to 2.2.6-SNAPSHOT

- src/plugins/imagery/components/AnnotationsCanvas.vue
Closes #6749 
Fixes race condition between loading the image annotations and drawing them on canvas.
> Fix race condition in image annotations loading and drawing them on the canvas

- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-pr.yml
- .github/workflows/pr-platform.yml
- e2e/playwright-ci.config.js
- Fixes the `pr:e2e:couchdb` trigger to register more frequently
- Updates the workflows to run on pushes to master and nightly
- Driveby: reduce confusion with the github annotation reporter
> [CI] Fix couchdb e2e trigger and run nightly, part 3

- package.json
Removes snapshot from version for the release.
> chore: bump version to `2.2.5`

- .github/workflows/e2e-couchdb.yml
- e2e/tests/framework/baseFixtures.e2e.spec.js
Closes https://github.com/nasa/openmct/issues/6741
and ignores https://github.com/nasa/openmct/issues/6785
Updates Github Actions to combine deploysentinel PR reports
driveby: Skip test.fail testcase
> [CI] Update Github Actions to combine deploysentinel PR reports and driveby

- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/persistence/couch/pluginSpec.js
Closes VIPEROMCT-345
Implements persistence batching via debouncing for the Couch `create` action which in the case of Import From JSON can result in a very large number of POST requests to the Couch server.
> Batch Couch DB create calls

- src/plugins/notebook/actions/ExportNotebookAsTextAction.js
- src/plugins/notebook/components/NotebookEntry.vue
- src/plugins/notebook/utils/notebook-entries.js
Closes  #6664 
Dependent on #6706 for `openmct.user.getActiveRole`.
Capture the active role at when an entry is modified and created. Altered the export as text action to include the additional values when available.  Fixed a bug where modified username was not being exported only `Unknown`.
> Add role attribution to notebook entries and export

- src/plugins/CouchDBSearchFolder/plugin.js
- src/plugins/CouchDBSearchFolder/pluginSpec.js
- src/plugins/viewLargeAction/viewLargeAction.js
- src/plugins/webPage/WebPageViewProvider.js
- src/ui/components/components.js
Closes VIPEROMCT-62 and #6794
Adds unique identifiers for couchdbsearchfolder since multiple instances of the folders was overwriting the original with a hardcoded name
> Fix couchdbsearchfolder and allow clocky reports

- src/plugins/userIndicator/components/UserIndicator.vue
Closes https://github.com/nasa/openmct/issues/6801
Checks if any roles are returned by the user provider. If none, then do not prompt the user to select a role.
> Suppress role selection if no roles available

- package.json
> chore: bump version to `3.0.0-SNAPSHOT`

- .circleci/config.yml
Temporarily disable some tests to avoid CI minutes being wasted
> [CI] Temporarily disable some tests

- e2e/tests/functional/planning/timelist.e2e.spec.js
- src/plugins/timelist/Timelist.vue
Closes #6797 
Use the current timestamp from the global clock
Use mode changes to set if the view is fixed time or real time
> Use the current timestamp from the global clock

- src/plugins/plan/components/Plan.vue
- src/plugins/timeline/TimelineViewLayout.vue
- src/ui/components/TimeSystemAxis.vue
Closes #6296 
Use the width and height of the container of the plan to set the activity widths and now markers
TimeSystemAxis always uses the value of global clock now()
> Plan rendering inside a timestrip

- src/plugins/LADTable/components/LadTableSet.vue
Closes #6854 
Declare and initialize `this.compositions` in the `created()` hook rather than `data()` so that objects added to it do not become reactive, and thus can access their own private class methods.
> fix(#6854): [LADTableSet] prevent compositions from becoming reactive

- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
Closes #6838 
Composition listeners should only be removed if the item has been deleted or its parent has been collapsed. Both are handled by `mct-tree` already, so doing this additionally when tree-items unmount is redundant.
In addition to that, any time the `visibleTreeItems` array changes, all tree-items will unmount, so this just doesn't work as intended-- it will unregister all composition listeners whenever the tree changes!
This recently started cropping up because of [a typo I had fixed in tree-item.vue](https://github.com/nasa/openmct/blob/42b545917c5555f0201688edaa5d41d9c79855bf/src/ui/layout/tree-item.vue#L194), so this was never firing before-- otherwise we would have caught this issue way sooner.
> fix: remove `tree-item-destroyed` event

- src/plugins/displayLayout/components/LineView.vue
Closes #6846
Check if we're in edit mode before showing frame edit for line view
> Don't allow editing line more when not editing display layout

- src/api/telemetry/TelemetryAPI.js
- src/api/telemetry/TelemetryCollection.js
- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js
Closes #6813
Reset and re-request telemetry only after receiving bounds following a mode change
> Wait for bounds change to reset telemetry collection data

- src/plugins/plot/chart/MctChart.vue
* fix: update to `defineComponent` from `Vue.extend()`
* fix: unwrap Proxy arg before WeakMap.get()
* refactor: `defineComponent` not needed here
Issue #6823
Issue #6867
> cherry-pick(#6868): fix: toggling markers, alarm markers, marker style + update `Vue.extend()` usage to Vue 3

- src/plugins/plot/chart/MctChart.vue
Closes VIPEROMCT-387
Ensure that when setting the series for limits on the map, it is not proxied by Vue3.
> Set the raw series limits so that we can get the raw series limits

- src/plugins/timer/components/Timer.vue
- src/utils/throttle.js
#6880 
* created a throttle util and using it in timer plugin to throttle refreshing the timer domain object
* Simplify timer logic
* Clarify code a little
* refactor: lint:fix
* Fix linting issue
> cherry-pick(#6885): Synchronize timers between multiple users

- package.json
> Remove snapshot

- .github/workflows/e2e-couchdb.yml
Closes #6890 
Continues on error for the docker login step which only caches the images. This should only mean that PRs for users are about 30s slower
> [CI] Update docker login step to work across forks and non-nasa-users

- e2e/appActions.js
- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/performance/tagging.perf.spec.js
- src/plugins/plot/MctPlot.vue
- src/plugins/plot/chart/MctChart.vue
Closes #6893 
Relates to #6822 
Cherry picks commit from master in 3.0.1 branch
> cherry-pick(#6866): Only load annotations in fixed time mode or frozen

- src/plugins/duplicate/DuplicateTask.js
check for null before checking before hasOwnProperty
Issue #6900
> cherry-pick(#6904): Check for null in DuplicateAction

- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
Closes #6928
Send in the timeContext as request options for lad requests from condition sets. Some providers (like Yamcs) use the information from the timeContext (realtime vs fixed timespan mode etc.).
> Condition sets now provide the timeContext they're using when sending requests

- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/plugins/flexibleLayout/flexibleLayoutViewProvider.js
- src/plugins/flexibleLayout/pluginSpec.js
Closes #6942 
Fixes reactivity issues with toggling toolbar options tied to domainObject configuration in the Flexible Layout (Row/Column Layout and Frame Visibility).
Also adds a regression test and cleans up the Flexible Layout suite a tiny bit.
> fix(#6942): Toggling FlexibleLayout toolbar options reflects immediately in the view

- e2e/appActions.js
- e2e/tests/functional/plugins/plot/tagging.e2e.spec.js
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
Closes #6931 
Closes #6932 
Stabilizes the ITC e2e tests by waiting for the ITC popup to be present in the Viewport before continuing. Also moves the ITC initialization logic to the `created()` hook since it does not have to wait until the component is rendered before doing the setup (no $refs needed). Adds some JSDocs as well.
> fix(e2e): Stabilize ITC tests

- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/plugins/flexibleLayout/flexibleLayoutViewProvider.js
- src/plugins/flexibleLayout/pluginSpec.js
* fix: restore reactivity of config settings
- move initialization steps to `created()` hook
- remove unnecessary `:key` binds
- fix comments
* refactor: clean up
* refactor: clean up
* refactor: lint:fix
* test(e2e): add regression test and cleanup suite
* refactor: consistency is key!
* test(fix): fix unit tests, further cleanup
Issue #6942
> cherry-pick(#6943): fix(#6942): Toggling FlexibleLayout toolbar options reflects immediately in the view

- package.json
> fix(package.json): add author

- src/plugins/remoteClock/RemoteClock.js
* If there are no listeners for this clock then don't bother subscribing after getting the domain object details
* Comment explaining the fix
VIPEROMCT-394
> cherry-pick(#6919): Fix remote clock subscription

- e2e/appActions.js
- e2e/tests/functional/recentObjects.e2e.spec.js
- e2e/tests/functional/renaming.e2e.spec.js
- e2e/tests/functional/tree.e2e.spec.js
- src/api/forms/components/FormRow.vue
- src/api/forms/components/controls/TextField.vue
- src/plugins/inspectorViews/properties/DetailText.vue
- src/plugins/inspectorViews/properties/Location.vue
- src/plugins/inspectorViews/properties/Properties.vue
- src/ui/components/ObjectPath.vue
- src/ui/inspector/ObjectName.vue
- src/ui/layout/RecentObjectsList.vue
- src/ui/layout/mct-tree.vue
- src/ui/router/Browse.js
Closes #6818 
Cherry pick this into `release/3.0.1`
> cherry-pick(#6927): Recent objects do not update when object names are changed

- src/api/objects/ObjectAPI.js
- src/api/tooltips/ToolTipAPI.js
- src/api/tooltips/components/tooltip-component.scss
> cherry-pick(#6916): [Tooltips] Fixes for dictionary objects and self-referential objects

- src/plugins/charts/scatter/plugin.js
- src/plugins/clearData/plugin.js
- src/plugins/gauge/GaugePlugin.js
- src/plugins/imagery/components/ImageryTimeView.vue
- src/plugins/notebook/components/NotebookSnapshotIndicator.vue
- src/plugins/notebook/plugin.js
- src/plugins/notificationIndicator/plugin.js
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/plugins/userIndicator/plugin.js
Closes VIPEROMCT-392
For dynamically created Vue component instances, make sure the destroy method on the mount utility is called (which in turn triggers the Vue unmount lifecycle hook).
**Note:** I noticed that there is no API to `remove` indicators in the Indicator API. Is this by design? Some indicator components are created dynamically and should be destroyed but there is no hook to destroy them. I guess the hope here is that they will unmount when Open MCT is unloaded.
> Ensure that dynamically created vue components are destroyed.

- src/ui/components/progress-bar.scss
Closes #6516 
Added Minimum height to progress bar, bar
I added `<progress-bar :model=" {progressPerc: 74}" />` to Webpage.vue (don't forget `import ProgressBar from '../../../ui/components/ProgressBar.vue'` right after <script> and `components: {
ProgressBar
},` before inject)
> Progress Bar Display

- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
> cherry-pick(#6929): Condition sets now provide the timeContext they're using when sending requests

- src/plugins/charts/scatter/plugin.js
- src/plugins/clearData/plugin.js
- src/plugins/gauge/GaugePlugin.js
- src/plugins/imagery/components/ImageryTimeView.vue
- src/plugins/notebook/components/NotebookSnapshotIndicator.vue
- src/plugins/notebook/plugin.js
- src/plugins/notificationIndicator/plugin.js
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/plugins/userIndicator/plugin.js
> cherry-pick(#6948): Ensure that dynamically created vue components are destroyed

- package.json
Closes #6974
Makes pkg json better
> chore(package.json): add fields

- .npmrc
Closes #6973
I noticed you don't save the lockfile in git, so I added a restriction in npmrc to not generate one.
> chore(npm): dont generate lockfile

- src/plugins/autoflow/AutoflowTabularRowController.js
- src/plugins/gauge/components/Gauge.vue
> cherry-pick(#6960): Add strategy latest and timeContext to auto flow tabular and gauge views

- src/plugins/imagery/components/ImageryView.vue
Closes #6266 
Set layer visibility to false if layer visibility cannot be persisted
> Imagery layer checkbox should match layer visiblity

- src/plugins/imagery/components/ImageryView.vue
> cherry-pick(#7003): Imagery layer checkbox should match layer visibility

- README.md
> fix(readme): note sections

- README.md
The padding in the get started section was weird.
> fix(readme): indent correctly

- e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js
- src/plugins/userIndicator/components/UserIndicator.vue
Closes #6978
Dont show description in role dialog
> fix(dialog): empty description

- src/plugins/staticRootPlugin/README.md
Closes #7005
Updates the StaticRootPlugin README to be accurate
> docs: update staticRootPlugin README

- .cspell.json
- e2e/README.md
- e2e/appActions.js
- e2e/tests/functional/plugins/timer/timer.e2e.spec.js
- src/api/forms/components/controls/Datetime.vue
- src/plugins/charts/bar/BarGraphPlot.vue
- src/plugins/charts/bar/BarGraphViewProvider.js
- src/plugins/charts/bar/pluginSpec.js
- src/plugins/plot/Plot.vue
- src/plugins/plot/inspector/PlotOptionsEdit.vue
- src/plugins/plot/legend/PlotLegend.vue
- src/plugins/plot/overlayPlot/pluginSpec.js
- src/plugins/plot/pluginSpec.js
- src/plugins/plot/stackedPlot/pluginSpec.js
- src/plugins/summaryWidget/test/ConditionManagerSpec.js
- src/plugins/summaryWidget/test/ConditionSpec.js
- src/plugins/summaryWidget/test/SummaryWidgetSpec.js
- src/plugins/timeline/pluginSpec.js
- src/plugins/timelist/pluginSpec.js
- src/plugins/timer/actions/StartTimerAction.js
- src/plugins/timer/components/Timer.vue
- src/ui/inspector/InspectorStylesSpec.js
- src/ui/layout/LayoutSpec.js
- src/ui/layout/pane.vue
- src/ui/layout/search/GrandSearchSpec.js
- src/utils/testing.js
Issue #7016 
Issue #7019 
Note: Merge #7051 first
> cherry-pick(#6990): Fix and re-enable disabled unit test suites

- src/plugins/inspectorDataVisualization/DataVisualization.vue
- src/plugins/inspectorDataVisualization/Imagery.vue
- src/plugins/inspectorDataVisualization/InspectorDataVisualizationComponent.vue
- src/plugins/inspectorDataVisualization/InspectorDataVisualizationViewProvider.js
- src/plugins/inspectorDataVisualization/NumericData.vue
- src/plugins/inspectorDataVisualization/TelemetryFrame.vue
- src/plugins/inspectorDataVisualization/inspector-data-visualization.scss
- src/plugins/inspectorDataVisualization/plugin.js
- src/plugins/plugins.js
- src/styles/vue-styles.scss
Cherry pick https://github.com/nasa/openmct/pull/7052 to address https://github.com/nasa/openmct/issues/7041
> cherry-pick(#7052): Allow Data Visualization in inspector based on current selection

- .github/release.yml
Closes #7091
Adds a basic `release.yml` that we can use to auto-generate release notes. Leverages our current labels in order to logically separate the different changes. This also adds a "Contributors" section, and properly notes when a new contributor has made their first contribution to Open MCT!
> chore: add `release.yml`

- .github/release.yml
> cherry-pick(#7090): chore: add `release.yml`

- .github/release.yml
Configuration for automated release notes generation.
> cherry-pick(#7096): Catchall for bug fix PRs and add performance category

- src/plugins/importFromJSONAction/ImportFromJSONAction.js
- src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
- src/plugins/localStorage/LocalStorageObjectProvider.js
- src/plugins/localStorage/pluginSpec.js
- src/utils/sanitization.js
Closes #7089
remove `__proto__` when parsing JSON from import action
> Protect against prototype pollution in import action

- API.md
Closes #6799 
Updated docs to reflect added/removed functionality.
> [Documentation] Time API docs update new/deprecated functionality

- package.json
Closes #7109 
Adds the `--quiet` flag to our `lint:spelling` script in order to reduce log bloat from `cspell` output.
> chore(`cspell`): use `--quiet` flag

- src/plugins/LADTable/components/LadTable.vue
- src/plugins/LADTable/components/LadTableSet.vue
- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/components/ConditionSet.vue
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/gauge/components/Gauge.vue
- src/plugins/plot/Plot.vue
- src/plugins/plot/legend/PlotLegendItemCollapsed.vue
- src/plugins/plot/legend/PlotLegendItemExpanded.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/components/Table.vue
- src/ui/components/ObjectView.vue
- src/ui/mixins/staleness-mixin.js
- src/utils/staleness.js
> cherry-pick(#7088): [Staleness] Fix staleness on clock change

- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- src/plugins/imagery/components/AnnotationsCanvas.vue
Closes #7083 
If the height or width are negative due the user dragging back and to the left, or forward and up, handle this properly when adding to the flatbush index.
> Handle negative height & width in image annotations

- src/ui/components/ObjectView.vue
> [Staleness] Fix issue with object view staleness styles not being reset on clock change

- src/plugins/importFromJSONAction/ImportFromJSONAction.js
Cherry picks #7121 to fix https://github.com/nasa/openmct/issues/7089
> cherry-pick(#7121):  Do not store state in singleton action

- e2e/tests/functional/plugins/faultManagement/faultManagement.e2e.spec.js
- src/plugins/charts/bar/inspector/BarGraphInspectorViewProvider.js
- src/plugins/charts/bar/pluginSpec.js
- src/plugins/faultManagement/FaultManagementInspectorViewProvider.js
- src/plugins/faultManagement/pluginSpec.js
- src/plugins/plot/pluginSpec.js
- src/plugins/telemetryTable/TableConfigurationViewProvider.js
Closes #7135
Renamed outlier tabs to `Config`
Fixed associated unit tests
> Rename all configuration tabs to `Config`

- .webpack/webpack.prod.js
- src/plugins/plot/configuration/PlotSeries.js
Related: https://github.com/NASA-AMMOS/openmct-mcws/issues/15
Put a check in to see if the value to be plotted can be handled by a `Float32Array` and if not handling as we handle other non-plottable values.
> [Plots] Fix Plots breaking on exceptionally large values

- .eslintrc.js
- package.json
- src/plugins/flexibleLayout/components/FrameComponent.vue
- src/plugins/plot/chart/MctChart.vue
- src/plugins/summaryWidget/src/Condition.js
- src/plugins/summaryWidget/src/Rule.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/plugins/summaryWidget/src/input/Palette.js
- src/plugins/summaryWidget/src/views/SummaryWidgetView.js
- src/plugins/summaryWidget/src/views/summary-widget.html
- src/utils/template/templateHelpers.js
Closes #7143 
- Applies a number of `eslint` rules from `eslint-plugin-no-sanitize` to catch bad usage of `.innerHTML`.
- Refactors all bad usage of `innerHTML` out of our codebase.
> fix(#7143): add `eslint-plugin-no-sanitize` and fix errors

- .eslintrc.js
- package.json
- src/plugins/flexibleLayout/components/Frame.vue
- src/plugins/plot/chart/MctChart.vue
- src/plugins/summaryWidget/src/Condition.js
- src/plugins/summaryWidget/src/Rule.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/plugins/summaryWidget/src/input/Palette.js
- src/plugins/summaryWidget/src/views/SummaryWidgetView.js
- src/plugins/summaryWidget/src/views/summary-widget.html
- src/utils/template/templateHelpers.js
> cherry-pick(#7144): fix(#7143): add `eslint-plugin-no-unsanitized` and fix errors

- src/plugins/telemetryTable/collections/TableRowCollection.js
- src/plugins/telemetryTable/pluginSpec.js
Closes https://github.com/akhenry/openmct-yamcs/issues/384
When updating a row in place, we need to be sure to bump the `incomingRowIndex` so we don't have an infinite loop.
> Prevent infinite loop when updating a table row in place

- src/api/objects/ObjectAPI.js
Removed the trailing brace in an Error from the Object API.
> Removed errant brace in ObjectAPI Error

- README.md
> docs: add related repos section to README.md

- API.md
> docs: add warning about deploying devServer to prod environment

- .github/dependabot.yml
Closes #7217
Dependabot is rebasing on every dependency change which is adding up. This disables to automatic rebasing
> [CI] Dependabot skip rebasing on every merge

- e2e/tests/functional/plugins/flexibleLayout/flexibleLayout.e2e.spec.js
- src/plugins/flexibleLayout/components/ContainerComponent.vue
- src/plugins/flexibleLayout/components/FrameComponent.vue
- src/plugins/flexibleLayout/components/ResizeHandle.vue
- src/plugins/flexibleLayout/toolbarProvider.js
> fix(#7234): Fix frame deletion in Flexible Layouts

- src/plugins/LADTable/LADTableView.js
- src/plugins/LADTable/components/LadRow.vue
- src/plugins/LADTable/pluginSpec.js
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/displayLayout/plugin.js
- src/plugins/displayLayout/pluginSpec.js
- src/plugins/gauge/GaugePluginSpec.js
- src/plugins/gauge/GaugeViewProvider.js
- src/plugins/gauge/components/GaugeComponent.vue
- src/plugins/imagery/pluginSpec.js
- src/plugins/plot/MctPlot.vue
- src/plugins/plot/PlotViewProvider.js
- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/overlayPlot/OverlayPlotViewProvider.js
- src/plugins/plot/overlayPlot/pluginSpec.js
- src/plugins/plot/pluginSpec.js
- src/plugins/plot/stackedPlot/StackedPlot.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/plugins/plot/stackedPlot/StackedPlotViewProvider.js
- src/plugins/plot/stackedPlot/pluginSpec.js
- src/plugins/telemetryTable/TelemetryTableView.js
- src/plugins/telemetryTable/components/TableComponent.vue
- src/plugins/telemetryTable/pluginSpec.js
- src/ui/components/ObjectView.vue
- src/ui/preview/PreviewContainer.vue
- src/utils/testing.js
- src/utils/visibility/VisibilityObserver.js
> cherry-pick((#7241) Provide visibility based rendering as part of the view api

- e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
- src/plugins/telemetryTable/components/TableComponent.vue
Closes #7239 
Sets the debounce to affect the filtering of the telemetry table, not the setting of the input value.
> Prevent rubber-banding in Telemetry Table filter input

- .circleci/config.yml
- .github/workflows/pr-platform.yml
- package.json
Closes: #6732 
Adds node20 to our support matrix
Removes node16 from our support matrix (EOL last september)
Ensures node 18 is the default (per @akhenry )
> [Build] Update to Node 20 and remove 16 (EOL)

- src/plugins/flexibleLayout/components/frame.vue
- src/plugins/plot/chart/MctChart.vue
- src/plugins/summaryWidget/src/Condition.js
- src/plugins/summaryWidget/src/Rule.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/plugins/summaryWidget/src/input/Palette.js
- src/plugins/summaryWidget/src/views/SummaryWidgetView.js
- src/plugins/summaryWidget/src/views/summary-widget.html
- src/utils/template/templateHelpers.js
Closes 
Applying these changes: https://github.com/nasa/openmct/pull/7144 to the base version of Open MCT used in OMM.
Functionality to Verify:
- Flexible Layouts
- can you drag and drop items into the layout
- Plots
- Overlay, Stacked, Standalone need regression tests
> Refactors all bad usage of innerHTML out of our codebase

- API.md
Closes #7259 
Update API documentation for Visibility-Based Rendering
> Update API documentation for Visibility-Based Rendering

- package.json
N/A 
Fixes warning about url during `npm publish`. npm automatically updates the repository url to this before publish. This is the result of running `npm pkg fix` to resolve the warning.
> chore(package.json): fix warning during npm publish

- e2e/tests/functional/plugins/tabs/tabs.e2e.spec.js
- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/draw/DrawWebGL.js
- src/utils/visibility/VisibilityObserver.js
Closes #7202 
Add an intersection observer to destroy the canvas when we've detected we're not visible.
> Destroy canvas in plots if not visible

- src/api/annotation/AnnotationAPI.js
- src/api/objects/ObjectAPI.js
- src/ui/components/ObjectPath.vue
- src/ui/layout/search/GrandSearch.vue
- src/ui/layout/search/GrandSearchSpec.js
Closes #7264 
- When building the search results, return them as soon as we can, and asynchronously build the paths incrementally as we receive them.
- Asynchronously search for tags
- Pass abort controllers to search for more details about objects. For ObjectPath, if we've been dismounted, abort the original path search.
> When searching, build the path objects asynchronously while returning the results

- package.json
> chore: bump version to `3.3.0-next`

- e2e/tests/functional/search.e2e.spec.js
- src/api/objects/ObjectAPI.js
- src/plugins/objectMigration/Migrations.js
Closes #7275 
1. Check to see if request was aborted and the domain object is null before blindly applying get interceptors
2. Ensure migrations can handle a null returned domain object due to a request abort.
> Handle aborted get requests and null domain objects when using ObjectAPI

- src/plugins/inspectorDataVisualization/NumericDataInspectorView.vue
Fixes #7283
Provide `renderWhenVisible` function to plot object
> Provide own renderWhenVisible function since manually creating an object view

- src/plugins/plot/chart/MctChart.vue
- src/plugins/plot/draw/DrawWebGL.js
Closes #7294 
This is a subset of @scottbell 's changes in #7202 
It's basically just a null check to prevent the 2D fallback code from failing.
> fix: 2d canvas fallback logic

- API.md
Closes #7284 
Updated API documentation to indicate `renderWhenVisible` function is optional
> Update API Readme to indicate `renderWhenVisible` function is optional

- package.json
Closes #7297 
Define `main` in `package.json` so we can `import openmct from 'openmct'` out of the box!
> fix: define main entry point in `package.json`

- .circleci/config.yml
- Driveby: Removed unneeded parameterization
- Increase parallelism
- split up performance tests
> [CI] Remove unneeded parameterization and increase parallelism

- e2e/README.md
- e2e/playwright-watch.config.js
- package.json
Closes: #7323 
- Adds a watch mode config to specify hot module reloading and the ability to run visual tests
> chore: watch mode improvements

- src/api/objects/object-utils.js
- src/plugins/autoflow/AutoflowTabularPlugin.js
- src/plugins/conditionWidget/components/ConditionWidget.vue
- src/plugins/hyperlink/HyperlinkLayout.vue
- src/plugins/timer/components/TimerComponent.vue
- src/plugins/webPage/components/WebPage.vue
- src/ui/router/ApplicationRouter.js
Cleanup PR from #7029 to convert a few more modules to ESM, and to stop using `require`.
> fix: cleanup from #7029

- e2e/tests/functional/plugins/styling/stackedPlotStyling.e2e.spec.js
- src/plugins/plot/PlotView.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/plugins/plot/stackedPlot/pluginSpec.js
Closes #7338  
Styles weren't being applied to StackedPlotItems correctly because we would manually mount them (using `Vue.createApp`). This PR updates `StackedPlotItem` to use `Plot`s directly in the template (since only `Plots` end up in StackedPlots anyway, we don't need to do anything dynamic).
Also fixes a small inconsistency where staleness styling wasn't being applied over custom border color styles for Stacked Plot Items.
> fix(#7338): Persisted styles correctly apply to `StackedPlotItem`s on mount

- .webpack/webpack.common.js
- e2e/tests/functional/clearDataAction.e2e.spec.js
- e2e/tests/functional/plugins/plot/logPlot.e2e.spec.js
- example/imagery/plugin.js
- src/api/menu/MenuAPI.js
- src/api/overlays/Overlay.js
- src/api/overlays/OverlayAPI.js
- src/api/overlays/ProgressDialog.js
- src/api/overlays/components/ProgressDialogComponent.vue
- src/exporters/CSVExporter.js
- src/exporters/ImageExporter.js
- src/exporters/JSONExporter.js
- src/plugins/exportAsJSONAction/ExportAsJSONAction.js
- src/plugins/exportAsJSONAction/ExportAsJSONActionSpec.js
- src/plugins/localStorage/LocalStorageObjectProvider.js
- src/plugins/notebook/actions/ExportNotebookAsTextAction.js
- src/ui/components/ProgressBar.vue
- src/ui/inspector/InspectorStylesSpec.js
- src/utils/testing/mockLocalStorage.js
Closes #7367 
Closes #7380 
Adds a ProgressBar to asynchronous Export as JSON actions (such as with external persistence i.e. CouchDB).
Also a few refactors and minor fixes:
- Updates the URLs for example imagery
- Updates `LocalStorageProvider` to use the actual `localStorage` api (`getItem()` and `setItem()`, etc).
- Updates `ExportAsJSONAction` to use private methods
- Refactors out the `model` prop object in ProgressDialog-- use individual props instead
https://github.com/nasa/openmct/assets/9259993/a4d4ef59-1423-41de-bc95-a72cee737909
> feat(#7367): ProgressBar for `ExportAsJSONAction`

- e2e/tests/functional/plugins/inspectorDataVisualization/numericData.e2e.spec.js
- e2e/tests/functional/plugins/lad/lad.e2e.spec.js
- e2e/tests/functional/plugins/lad/ladSet.e2e.spec.js
- src/plugins/LADTable/LadTableSetView.js
- src/plugins/LADTable/components/LadRow.vue
- src/plugins/LADTable/components/LadTableConfiguration.vue
- src/plugins/LADTable/pluginSpec.js
- src/plugins/inspectorDataVisualization/TelemetryFrame.vue
Closes #7383 #7382
- Ensure we provide `renderWhenVisible` to LadTableSets (and thus to child LadTables)
- Ensure TelemetryFrame always provides a telemetry keyString when opening a new tab
- Ensure `ladTelemetryObjects` is actually initialized before adding objects to it
- Wrote first (!) LadTableSet e2e test to ensure they work in the future
> Provide `renderWhenVisible` to LadTableSets

- src/plugins/imagery/components/ImageryView.vue
Closes #7404. Note that this is critical in order to be in parity with the same display in VERVE.
Title says it all.
> Change Imagery positional freshness label from 'POS' to 'ROV'

- .circleci/config.yml
- .github/workflows/e2e-perf.yml
- e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
- e2e/tests/visual-a11y/imagery.visual.spec.js
- Moves performance tests to GHA to speed up commits and lower quota
- Adds visual test for imagery for upcoming imagery change
- Skips a test due to a flaky app
> move performance tests to GHA

- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- src/plugins/displayLayout/components/TelemetryView.vue
Closes #7400 
Remove errant action!
> Fix actions menu on display layout alphanumerics

- .cspell.json
- e2e/tests/visual-a11y/planning.visual.spec.js
- src/ui/layout/PaneContainer.vue
Closes #7455  
- Adds 2 visual tests covering Gantt Charts w/ unclipped activity names in draft and non-draft status modes.
- Small a11y fix for the inspector pane expand/collapse button
- Add additional dictionaries to cspell that we weren't using
> test(visual): add unclipped activity names visual tests + a11y fixes

- src/plugins/plan/util.js
- src/plugins/timelist/inspector/FilteringComponent.vue
Closes #7389 
Use the value of a property for filtering metadata as a string if it is not undefined.
> Filter values as a string not an object

- e2e/tests/functional/missionStatus.e2e.spec.js
- e2e/tests/visual-a11y/missionStatus.visual.spec.js
- example/exampleUser/ExampleUserProvider.js
- src/api/overlays/components/DialogComponent.vue
- src/plugins/folderView/components/GridView.vue
- src/plugins/userIndicator/components/MissionStatusPopup.vue
- src/plugins/userIndicator/components/UserIndicator.vue
Closes #7461 
- Add e2e and visual test suites for Mission Status
- Add a11y wherever needed
- Enable the ExampleUser to set Mission Status so we can test the feature
> test(e2e): add e2e and visual tests for Mission Status (plus a11y)

- e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/api/objects/Transaction.js
- src/ui/toolbar/components/ToolbarColorPicker.vue
Closes #7233
When canceling a transaction, we call `refresh` on the object, this in turn calls `get`, which by default can use a cached/dirty version of the object. This isn't very helpful as the cached object is the dirty object we're trying revert! To fix this, we instead use `forceRemote` on the `get` to get the untouched version of the object.
> Bypass cache/dirty when canceling transaction

- openmct.js
Closes 
Adds type information for the `setAssetPath` method.
> [CLA Approved] Add openmct type hints

- src/plugins/operatorStatus/operatorStatus/OperatorStatus.vue
Closes #7508 
Add a simple check to make sure the incoming status matches our role.
> Check role when receiving status updates in the Operator Status Indicator

- .circleci/config.yml
- e2e/README.md
- e2e/playwright-ci.config.js
- e2e/playwright-local.config.js
- e2e/playwright-mobile.config.js
- e2e/playwright-watch.config.js
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/functional/plugins/notebook/notebookSnapshotImage.e2e.spec.js
- e2e/tests/functional/plugins/plot/previews.e2e.spec.js
- e2e/tests/functional/plugins/telemetryTable/preview.e2e.spec.js
- e2e/tests/mobile/smoke.e2e.spec.js
- package.json
- src/plugins/DeviceClassifier/src/DeviceMatchersSpec.js
- src/ui/components/search.scss
- src/ui/layout/layout.scss
- src/ui/layout/search/SearchResultsDropDown.vue
- src/ui/layout/search/search.scss
Closes https://github.com/nasa/openmct/issues/7349
- Adds status area back into mobile with some modifications
- Adds grand search into status area
- Makes changes to grand search's actions to be mobile-friendly.
- In mobile portrait mode, the search bar is collapsed until a user clicks on it. This PR includes an animation that expands the search bar when the search is active. 
-
> [Mobile] Add Global Search to Mobile 

- e2e/tests/functional/plugins/plot/overlayPlot.e2e.spec.js
- src/api/composition/CompositionProvider.js
- src/api/composition/DefaultCompositionProvider.js
- src/api/objects/MutableDomainObject.js
- src/api/objects/ObjectAPI.js
- src/api/objects/RootRegistry.js
- src/api/objects/TransactionSpec.js
- src/api/objects/object-utils.js
- src/api/objects/test/object-utilsSpec.js
- src/api/telemetry/TelemetryAPI.js
- src/plugins/importFromJSONAction/ImportFromJSONAction.js
- src/plugins/inspectorViews/elements/ElementItem.vue
- src/plugins/inspectorViews/elements/PlotElementsPool.vue
- src/plugins/notebook/utils/notebook-storage.js
- src/plugins/staticRootPlugin/StaticModelProvider.js
- src/plugins/summaryWidget/src/ConditionManager.js
- src/plugins/summaryWidget/src/input/ObjectSelect.js
- src/plugins/summaryWidget/src/telemetry/EvaluatorPool.js
- src/plugins/summaryWidget/src/telemetry/SummaryWidgetEvaluator.js
- src/plugins/telemetryMean/src/MeanTelemetryProvider.js
- src/ui/components/ObjectLabel.vue
- src/ui/components/ObjectView.vue
- src/ui/composables/edit.js
- src/ui/mixins/staleness-mixin.js
Closes #7456 
The StalenessMixin assumes that it will always be passed a `domainObject` when looking to unsubscribe from staleness. However, in the case of Overlay Plots, it receives an Identifier directly, causing an error. This modifies that logic to check if its an Identifier first before attempting to extract an Identifier from the object.
- Refactors `objectUtils` to have ESM exports of individual helper functions
- Refactors usage of `objectUtils` helper functions to use ESM imports
- Refactors some Vue anti patterns out of PlotElementsPool.vue
> fix(#7456): allow children of Overlay Plots to be removed

- e2e/tests/visual-a11y/displayLayout.visual.spec.js
- src/ui/layout/PaneContainer.vue
- src/ui/layout/pane.scss
Closes #7036.
- CSS fix to prevent toolbar overrun of main view area.
- Added `overflow: hidden` to __pane-main > .l-pane__contents.
- Added visual test for toolbar overflow
Closes
> Fix visible toolbar overflow

- e2e/playwright-mobile.config.js
- e2e/tests/mobile/smoke.e2e.spec.js
- src/api/overlays/components/OverlayComponent.vue
- src/api/overlays/components/dialog-component.scss
- src/api/overlays/components/overlay-component.scss
Closes  https://github.com/nasa/openmct/issues/7347
- Add code to classes that are used for _only_ confirmation dialogs such that the text and buttons for such messages are centered, rather than floating to the top. This will improve overall mobile UX.
> [Mobile] Center Confirmation Dialog Texts

- .github/workflows/e2e-flakefinder.yml
> [CI] Temp disable flakefinder as we it's generating too many GHA minutes

- .webpack/webpack.coverage.js
Closes #7015 
Turns out you need source maps to be generated if you want to generate coverage metrics. Who'dathunkit
> fix(#7015): Generate source maps for generating code coverage metrics

- .webpack/webpack.prod.js
- e2e/appActions.js
- e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
- e2e/tests/visual-a11y/imagery.visual.spec.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/TelemetryTableType.js
- src/plugins/telemetryTable/components/TableComponent.vue
- src/plugins/telemetryTable/components/TableFooterIndicator.vue
- src/plugins/telemetryTable/components/TableRow.vue
- src/styles/_controls.scss
Closes #7268
Fix exporting from Limited Mode: https://github.com/nasa/openmct/issues/7268#issuecomment-1935055534
Fix UI issues: https://github.com/nasa/openmct/issues/7268#issuecomment-1935060009
Apply configuration changes made in Edit Properties.
> [Telemetry Table] Address issues found during testing Table Performance

- e2e/tests/visual-a11y/planning.visual.spec.js
- src/ui/components/TimeSystemAxis.vue
Closes #7587 
Ensure element isn't null for the resize observer, and that we're *deeply* watching the size.
> Resize plans properly

- e2e/tests/functional/plugins/timeConductor/datepicker.e2e.spec.js
- src/plugins/timeConductor/DatePicker.vue
- src/plugins/timeConductor/TimePopupFixed.vue
- src/plugins/timeConductor/conductor.scss
- src/styles/_mixins.scss
Closes  https://github.com/nasa/openmct/issues/7594
- Add and change CSS classes such that calendar popups do not open up in a way that get cut off. 
- Add code to ITC such that calendar popup opens up from the bottom, rather than the top
> [TC Popup] Fix Calendar so it is not cutoff

- e2e/appActions.js
- src/plugins/timeConductor/TimePopupFixed.vue
- src/plugins/timeConductor/TimePopupRealtime.vue
Closes #7614
The submit button(s) in the realtime and fixed time popups trigger network requests (right now).
Also created an issue to perform a noop if there are no changes when submit button is clicked in the time popup here: 
#7616
> For the setTimeConductorMode, use the close time popup button rather than the submit button to dismiss time popup

- e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
- index.html
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
- src/plugins/condition/pluginSpec.js
- src/plugins/notebook/pluginSpec.js
Closes #7484 
When subscribing to telemetry in a Condition Set, we need to ensure we request telemetry in addition to a simple subscribe. This is because on telemetry like operator status, the Telemetry API may already have a subscription (due to the poll widget), and thus not create a new subscription, and thus not immediately fire a callback.
> Ensure a request for telemetry happens in Condition Sets

- .circleci/config.yml
Closes #7615 
Originally, the intent of this ticket was to make sure we only had one worker per shard. Upon investigation, I discovered that we were already setting workers to 1.
This ticket improves runtime by running the tests in parallel
> [CI] Parallelize visual test runs

- e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
- src/plugins/condition/ConditionManager.js
> fix: 🤖 beep boop beep, you forgot an `await` 🤖

- e2e/tests/functional/plugins/lad/ladTable.e2e.spec.js
- src/plugins/LADTable/components/LadTable.vue
Closes #7633
- Adds back missing `await`
- Adds regression test
> fix(#7633): add missing `await`

- e2e/tests/functional/plugins/telemetryTable/preview.e2e.spec.js
- src/ui/preview/PreviewContainer.vue
- src/ui/preview/PreviewHeader.vue
Closes #7158 
In Preview mode, we weren't pulling the same cached copy of the `ActionsCollection`, and thus weren't picking up any state changes from the View.
> For an existing View in a Preview, ensure we pull the same `ActionCollection`

- .webpack/webpack.coverage.mjs
- e2e/baseFixtures.js
- e2e/playwright-ci.config.js
- e2e/playwright-local.config.js
- e2e/playwright-mobile.config.js
- e2e/playwright-performance-dev.config.js
- e2e/playwright-performance-prod.config.js
- e2e/playwright-visual-a11y.config.js
- e2e/playwright-watch.config.js
Closes #7657 
Allow specifying the path to output `.nyc_output` raw code coverage *.json in playwright config so we can ensure the e2e coverage is generated against the correct sourcemap paths
> fix(e2e): specify `.nyc_output` path as custom config setting

- src/plugins/persistence/couch/CouchObjectProvider.js
Closes #7655 
Removed line that adds metadata
> Do not add unused created attribute to metadata of couch documents on create

- .webpack/webpack.prod.mjs
- e2e/helper/hotkeys/clipboard.js
- e2e/helper/hotkeys/hotkeys.js
- e2e/helper/notebookUtils.js
- e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
- src/plugins/notebook/components/NotebookEntry.vue
Closes #7686
- `paste text outside text area`: no-op
- `paste text inside text area (editing)`: default paste event behavior
- `paste image outside text area`: image attached
- `paste image inside text area (editing)`: image attached (FEATURE, DEFINITELY NOT A BUG: this persists the notebook entry, including any text edits made prior to the image paste, and leaves the entry in edit mode. If you want the entry to be committed on image paste, not in edit mode, or something else entirely, let me know @charlesh88 )
> Handle paste events for images and text properly

- src/plugins/importFromJSONAction/ImportFromJSONAction.js
- src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
Closes #7612 
Instead of using `JSON.parse`, `JSON.stringify`, and Regex, walk the tree instead. This speeds up the import considerably. I also added a progress bar so the user can see the status of the import.
> Improve performance of JSON import and add progress bar

- src/api/time/IndependentTimeContext.js
Closes #7687 
Woops. Missed one.
> refactor: remove the final `.bounds()` call

- .webpack/webpack.common.mjs
> chore(webpack): destruct version from pkgJson

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- .github/workflows/e2e-pr.yml
- e2e/package.json
- package-lock.json
> chore: bump playwright to v1.44.0

- e2e/appActions.js
- e2e/tests/functional/staleness.e2e.spec.js
- example/generator/SinewaveStalenessProvider.js
- src/ui/components/ObjectView.vue
Closes #7670
Clearing any existing staleness subscriptions before showing a new object.
Adding a new test to make sure this doesn't regress.
~~Added new functionality to `createDomainObjectWithDefaults` to be able to set toggles when creating test objects.~~
Using new timeAPI methods in SWG Staleness provider.
> fix(#7670): Ensure objects unsubscribe from staleness when destroyed

- e2e/tests/functional/plugins/plot/plotRendering.e2e.spec.js
- src/plugins/plot/MctPlot.vue
Closes #7729 
Use setMode API to set the time span as well as the bounds instead of the old bounds time API.
> Ensure time conductor mode is set when synchronizing time range

- .circleci/config.yml
- e2e/avpFixtures.js
- e2e/helper/useDarkmatterTheme.js
- e2e/playwright-visual-a11y.config.js
- e2e/pluginFixtures.js
- e2e/tests/visual-a11y/a11y.visual.spec.js
- e2e/tests/visual-a11y/components/header.visual.spec.js
- e2e/tests/visual-a11y/components/inspector.visual.spec.js
- e2e/tests/visual-a11y/notebook.visual.spec.js
- e2e/tests/visual-a11y/planning.visual.spec.js
- src/plugins/inspectorViews/annotations/tags/tags.scss
- src/styles/_constants-darkmatter.scss
- src/styles/_constants-espresso.scss
- src/styles/_constants-maelstrom.scss
- src/styles/_constants-snow.scss
- src/styles/_mixins.scss
- src/styles/notebook.scss
- src/ui/layout/status-bar/indicators.scss
Addresses #7421 (does not close it)
Closes https://github.com/nasa/openmct/issues/7317
We disabled a11y checks to get build9 out the door. This re-enables most of them, but leaves the PLAN failures alone.
> chore: re-enable a11y checks in visual suite-- minus planning tests

- e2e/tests/visual-a11y/components/timeConductor.visual.spec.js
Closes #7775 
Add a `fixme` to skip the flaky visual test. The test flakes due to content shifting after the initial DOM has loaded. This seems to be caused by loading Open MCT icons. You may have noticed blank icons in some of the snapshots, and I think this issue has the same cause. The icons are not being preloaded and thus load well after the initial DOM content has loaded. Will file a separate issue to fix this and link it here
> test(visual): skip flaky visual test

- e2e/package.json
package.json in e2e and root metadata should be identical.
> fix(package.json): consistent props

- .github/codeql/codeql-config.yml
Closes #7783 
Skip scanning for e2e/ folder as it is a non-functional package and not included in our distribution
> chore: disable codeql scanning for `e2e/` folder

- e2e/appActions.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/framework/generateLocalStorageData.e2e.spec.js
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/functional/plugins/plot/logPlot.e2e.spec.js
- e2e/tests/functional/plugins/telemetryTable/telemetryTable.e2e.spec.js
- e2e/tests/functional/plugins/timeConductor/timeConductor.e2e.spec.js
- e2e/tests/visual-a11y/imagery.visual.spec.js
- src/plugins/timeConductor/ConductorInputsFixed.vue
- src/plugins/timeConductor/TimePopupFixed.vue
Closes #7791 
Reverts some changes that caused the `dismiss` action on the fixed mode time conductor popup to submit changes. Does some "safe" refactoring of the component to make it slightly more maintainable.
* Updates `setTimeConductorBounds` to be more robust
* Update usage of `setTimeConductorBounds` in existing tests
* Adds a regression test
> fix(#7791): tc form shouldn't submit bounds changes on dismiss

- .circleci/config.yml
- e2e/.eslintrc.cjs
- e2e/tests/functional/forms.e2e.spec.js
- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
- e2e/tests/functional/search.e2e.spec.js
- e2e/tests/functional/tree.e2e.spec.js
- e2e/tests/performance/contract/imagery.contract.perf.spec.js
Closes #7807
Closes #7808 
Fixes a locator in the perf tests which was broken after the merge of #7581 (e2e refactor + linting)
> chore: re-enable perf/mem tests on PR + fix broken locator in imagery perf test

- .circleci/config.yml
- e2e/.eslintrc.cjs
- e2e/tests/functional/forms.e2e.spec.js
- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
- e2e/tests/functional/search.e2e.spec.js
- e2e/tests/functional/tree.e2e.spec.js
- e2e/tests/performance/contract/imagery.contract.perf.spec.js
cherry-picks #7806 (Issues #7807 #7808) into `release/4.0.0`
> cherry-pick(#7806): chore: re-enable perf/mem tests on PR + fix broken locator in imagery perf test

- package-lock.json
Partially addresses https://github.com/nasa/openmct/issues/7828
We cannot modify the package.json directly without running `npm install` in our release process @ozyx 
Additionally, I'm wearing adding the `npx browserlist update` command to our build process outside of a release automation step. I've run it once in this PR to clear it.
> [Build] Update package lock to reference correct version of package and also update the browserlist

- tsconfig.json
Addresses: VIPEROMCT-547
This solves 2 separate issues specifically when building `openmct` as a submodule from the root dir (using `npm install --prefix openmct`):
1. `tsc` by default targets ES5, which doesn't support the `#private` syntax.
2. The `module` setting by default is CommonJS if we're using ES5 which, since it's not specified, the target option defaults to.
Then something about the consuming project not having its own `tsconfig.json` causes even more build inconsistency and weirdness, because `tsc` has to infer which options to use based on the calling environment.
So if the consuming project (as a submodule, because this works with regular npm package resolution since its already built) has no `tsconfig.json` specified, and is using `openmct` as a submodule, AND is building …
> [Build] Update tsconfig to explicitly set `target` and `module` options

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- e2e/helper/faultUtils.js
- e2e/tests/functional/plugins/faultManagement/faultManagement.e2e.spec.js
- example/faultManagement/exampleFaultSource.js
- example/faultManagement/utils.js
- package-lock.json
- package.json
- src/api/faultmanagement/FaultManagementAPI.js
- src/plugins/faultManagement/FaultManagementListItem.vue
- src/plugins/faultManagement/FaultManagementView.vue
Closes #7853
Closes #5814 
- Adds a new, optional method `getShelveDurations()` to the Fault Management API that allows providers to define their own shelve durations. If no method is defined, a default list of shelve durations will be provided.
- Adds some additional docs and JSDoc types for Fault Management API
- Refactors the Fault Management e2e suite to use web-first assertions and locators
- Build: removes the `codecov` npm package dependency as it has been deprecated for some time.
> feat(Fault Management): allow fault providers to define shelve durations

- src/plugins/telemetryTable/collections/TableRowCollection.js
Closes VIPERGC-643
When adding sorted arrays to the beginning of the table rows, make sure to insert them in the order of occurrence and not accidentally reverse them (by using unshift) while inserting.
> Fix table sorting in descending order

- example/imagery/plugin.js
- src/utils/random.js
> test(visual): Stabilize compass per timestamp

- src/api/faultmanagement/FaultManagementAPI.js
- src/plugins/faultManagement/FaultManagementView.vue
- src/plugins/faultManagement/constants.js
Closes VIPERGC-574
Closes #7853 
- Fixes faulty logic which was preventing the selected shelve duration from being used in the request to the fault provider
- Renames default shelve duration from 'Indefinite' to 'Unlimited'
- Removes an unused const
> fix(vipergc-574): Use selected shelve duration for fault management

- src/plugins/plan/components/PlanView.vue
Closes VIPERGC-652
Since the plan view is used by both objects of type `plan` and `gantt chart`, use the plan object to get swim lane order.
This will ensure that both views work correctly.
> Fix gantt chart swimlane order

- e2e/helper/planningUtils.js
- e2e/tests/visual-a11y/planning-gantt.visual.spec.js
- e2e/tests/visual-a11y/planning-timestrip.visual.spec.js
- e2e/tests/visual-a11y/planning-view.visual.spec.js
- src/plugins/plan/components/PlanView.vue
- src/ui/components/TimeSystemAxis.vue
Closes #7892
Initialize alignment offset to 0. (it was undefined). This fixes the `now` line issue.
Also handle a small bug with swimlane configuration not getting replaced when the plan used by a gantt chart was changed
> fix(#7892): restore "now" (marcus bains) line to planning views

- src/plugins/charts/bar/BarGraphView.vue
Closes VIPERGC-660
Fixes an issue causing Graphs to not plot any data until the "Config" inspector tab was opened.
> fix(vipergc-660): identify axis keys upon adding object to composition

- e2e/tests/functional/plugins/conditionSet/conditionSetOperations.e2e.spec.js
- src/plugins/condition/components/ConditionItem.vue
Closes VIPERGC-670
Move the disabled attribute from the (invalid) `div` element to the `button` element.
Note that [this CSS ](https://github.com/nasa/openmct/blob/master/src/styles/_global.scss#L379) was likely causing the `div` to be perpetually disabled.
> Use the disabled attribute on a valid element - the button.

- e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js
- example/generator/GeneratorMetadataProvider.js
- example/generator/GeneratorProvider.js
- example/generator/StateGeneratorProvider.js
- src/api/telemetry/TelemetryAPI.js
- src/plugins/filters/README.md
> [Telemetry API] Prevent Subscriptions with different options from overwriting each other

- e2e/appActions.js
- e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
- e2e/tests/functional/renaming.e2e.spec.js
- src/ui/layout/BrowseBar.vue
- src/ui/router/Browse.js
Closes #7943 7943
In Browse.js instead of just watching the name of the domain object to update the page title, we watch the whole object and update the whole object, while also updating the page title if necessary.
> [Notebook] Browse Bar holding onto stale model, reverts changes

- src/plugins/timelist/TimelistComponent.vue
Closes: [VIPERGC-700](https://mmoc-jira.amn.nasa.gov:8443/browse/VIPERGC-700)
Closes 
If an activity is out of bounds, but in progress, display it in the currently visible list.
In progress status is checked by comparing the activity-states map for the given activity and comparing it's value with `in-progress`
> In progress activities that are out of bounds are shown

- e2e/tests/functional/plugins/plot/plotControlsCompactMode.e2e.spec.js
- src/plugins/plot/MctPlot.vue
- src/plugins/plot/PlotView.vue
Closes #7968 #7969
Allow highlights and locking highlight points for plots in compact mode.
Cursor guides and grid lines for stacked plots also fixed.
Synchronized cursor guides and grid lines in compact mode will be done in #7960.
Still disallow pan and zoom in compact mode - this will be handled in #7958.
> Don't disallow mouse events when in compact mode for plots

- e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
- src/api/time/IndependentTimeContext.js
- src/api/time/TimeAPI.js
- src/plugins/plot/MctPlot.vue
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
Closes #7737
Ensure that the mode set when independent time conductor is enabled/disabled is propagated correctly.
Also ensure that global time conductor changes are not picked up by the independent time conductor when the user has enabled it at least once before
> Independent time conductor related handling for plot synchronization.

- e2e/tests/functional/planning/timestrip.e2e.spec.js
- src/ui/components/TimeSystemAxis.vue
Closes #7817 
- Account for right y-axis when calculating now line position
- Don't show the now line if "now" is out of bounds of the start/end timestamps.
- Add tests for now line visibility
> Time strip marcus banes line "now line" fix for right y-axis and when now is out of bounds

- codecov.yml
- e2e/.eslintrc.cjs
- e2e/baseFixtures.js
- e2e/tests/functional/search.e2e.spec.js
- e2e/tests/performance/memory/navigation.memory.perf.spec.js
- src/api/composition/CompositionCollection.js
- src/api/composition/CompositionProvider.js
- src/api/composition/DefaultCompositionProvider.js
- src/api/objects/ObjectAPI.js
- src/plugins/CouchDBSearchFolder/plugin.js
- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/persistence/couch/CouchSearchProvider.js
- src/plugins/persistence/couch/pluginSpec.js
- src/plugins/persistence/couch/setup-couchdb.sh
- src/ui/layout/search/GrandSearch.vue
PR: https://github.com/nasa/openmct/pull/8037
Issue: VIPERGC-644
> cherry-pick VIPERGC 659 couch search indexes

- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/persistence/couch/CouchSearchProvider.js
Closes https://github.com/nasa/openmct/issues/8046
Changes how search strings are added to couch queries to support special characters that would otherwise be double escaped by JSON.stringify
> Fix partial matches

- e2e/tests/functional/plugins/conditionSet/conditionSetOperations.e2e.spec.js
- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/components/ConditionItem.vue
- src/plugins/condition/components/TestData.vue
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
* Fixes https://github.com/nasa/openmct/issues/7992
* Fixes https://github.com/nasa/openmct/issues/8060
Fixes a bug in Condition Sets that sometimes caused incorrect output. There are two things that are important to know about condition sets in order to understand what's going wrong here:
1. Condition sets use short-circuit evaluation as a performance optimization, meaning that if a condition evaluates to true, subsequent conditions in the condition set will not be evaluated.
5. Criteria are only evaluated when a new telemetry value is received. Their evaluation result is cached, and the cached value used for evaluation of the condition set to which they belong. This is another performance optimization, if the telemetry value didn't change, then don't bother re-evaluating any criteria …
> Condition Sets can incorrectly evaluate telemetry objects that update infrequently

- src/plugins/condition/ConditionManager.js
Closes https://github.com/nasa/openmct/issues/7992
Fixes an issue in createNormalizedDatum that was causing problems. This role of this function is primarily to map from source to key so that other sections of the code don't have to do that boilerplate repeatedly. It was modified in an effort to fix a failing test. That test was in fact [also fixed another way](https://github.com/nasa/openmct/pull/8041/files#diff-d3770aa9488c5c41f2fe3a00e3ee49f821205a1815506ce08a024cbccf5cfd73R133), but the code change in createNormalizedDatum was not reverted.
> Condition sets failing to evaluate telemetry where source and key do not match in metadata

- src/plugins/condition/ConditionManager.js
PR: https://github.com/nasa/openmct/pull/8065
Issue: https://github.com/nasa/openmct/issues/7992
> Cherry pick 8065 - Condition sets failing to evaluate telemetry where source and key do not match in metadata

- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
- src/plugins/persistence/couch/Questions for Vickie.md
- src/plugins/persistence/couch/Stay Interview notes.md
Closes VIPERGC-816
* [Renamed function argument](https://github.com/nasa/openmct/pull/8084/files#diff-008fb4357e97030be1f4fd71c7e1449c4a0d7713709068d75b2d36238a154881R180) for clarity.
* [Code should default to a Map](https://github.com/nasa/openmct/pull/8084/files#diff-008fb4357e97030be1f4fd71c7e1449c4a0d7713709068d75b2d36238a154881R181) and not an associative array. Just create one once, don't initialize a new object every time we receive telemetry.
* Use Map getter function, not associative array key [here](https://github.com/nasa/openmct/pull/8084/files#diff-008fb4357e97030be1f4fd71c7e1449c4a0d7713709068d75b2d36238a154881R187) and [here](https://github.com/nasa/openmct/pull/8084/files#diff-008fb4357e97030be1f4fd71c7e1449c4a0d7713709068d75b2d36238a154881R195)
* Remove superfluous call …
> All telemetry criteria bug
