nasa/openmct

- platform/commonUI/browse/bundle.json
- platform/commonUI/browse/src/BrowseController.js
- platform/commonUI/browse/src/navigation/NavigationService.js
- platform/commonUI/browse/src/windowing/WindowTitler.js
- platform/commonUI/browse/test/navigation/NavigationServiceSpec.js
- platform/commonUI/browse/test/suite.json
- platform/commonUI/browse/test/windowing/WindowTitlerSpec.js
Integrates open1200 into master.
Integration checklist:
> [Integration] Window Titling

- platform/commonUI/general/res/css/tree.css
- platform/commonUI/general/res/sass/search/_search.scss
Hide link icons in search results to temporarily fix issue #84 while #83 is still in progress. 
1. Changes address original issue? Y (for now)
5. Project-specific information isolated to appropriate branches? Y
> [Search] Hide link icons in search results

- platform/commonUI/general/res/css/theme-espresso.css
- platform/commonUI/general/res/sass/_main.scss
- platform/commonUI/general/res/sass/features/_imagery.scss
- platform/commonUI/general/res/sass/themes/_theme-espresso.scss
- platform/commonUI/general/res/sass/tree.scss
- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/features/imagery/res/templates/imagery.html
Based on mobile branch in order to grab the latest CSS. Very minor CSS and markup changes to improve the layout of "top-bar" elements.
> Review and integrate open93

- platform/core/src/capabilities/CoreCapabilityProvider.js
- platform/core/test/capabilities/CoreCapabilityProviderSpec.js
Fix logic error which caused an inaccurate warning to
be logged when capabilities are overridden by priority.
Addresses #49.
> [Capabilities] Avoid erroneous logging

- platform/commonUI/browse/res/templates/browse.html
> [Mobile] Suppress Create button on mobile

- platform/commonUI/general/src/controllers/TimeRangeController.js
- platform/commonUI/general/test/controllers/TimeRangeControllerSpec.js
Enforce minimum durations in time conductor, as described in #151, when user input changes either inner or outer bounds of the control.
Additionally, adds some missing test cases to TimeRangeController.
> [Time Conductor] Enforce minimum bounds

- platform/commonUI/general/res/sass/controls/_controls.scss
- platform/commonUI/general/res/sass/controls/_time-controller.scss
- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/commonUI/general/res/templates/controls/time-controller.html
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
- platform/features/conductor/src/ConductorRepresenter.js
Styling for time-controller and domain selector per #180. Note that "platform/features/conductor" must be added to bundles.json to enable the Time Controller.
> Review and integrate open180

- Procfile
Remove the example/localstorage bundle from the procfile.
Fixes #153.
2. Unit tests included and/or updated with changes? (N/A) Demo configuration change.
> [CI] Remove non-existent bundle from procfile

- docs/footer.html
- docs/gendocs.js
- docs/header.html
Styles documentation using externally-available stylesheet.
1. Changes address original issue? N/A (follow-up to #111)
2. Unit tests included and/or updated with changes? N/A (changes are external to client code & build)
> [Documentation] Add styling

- docs/src/index.html
- docs/src/process/index.md
Addresses #223, documents sprint process/structure.
2. Unit tests included and/or updated with changes? N/A &ast;
&ast; Changes are to documentation only, out of scope for unit testing
> [Documentation] Document process

- example/generator/src/SinewaveTelemetrySeries.js
- platform/features/plot/src/PlotController.js
- platform/features/plot/test/PlotControllerSpec.js
- platform/telemetry/src/TelemetrySubscription.js
Opening up pull request early for visibility, early feedback, to-do tracking.
Addresses #218 by responding to user selection of domains/ranges.
To-do:
> [Plot] Support domain/range switching

- docs/src/guide/index.md
- platform/execution/src/WorkerService.js
- platform/execution/test/WorkerServiceSpec.js
Support an additional flag in the  extension category
such that SharedWorkers may be used. nasa/openmctweb#308.
> [Workers] Allow web workers to be shared

- platform/entanglement/src/policies/CrossSpacePolicy.js
- platform/entanglement/test/policies/CrossSpacePolicySpec.js
Allow links across spaces; only disallow move or copy.
Addresses WTD-1587
> [Entanglement] Allow cross-space linking

- platform/entanglement/bundle.json
- platform/entanglement/src/actions/SetPrimaryLocationAction.js
- platform/entanglement/test/actions/SetPrimaryLocationActionSpec.js
- platform/entanglement/test/actions/SetPrimaryLocationSpec.js
- platform/entanglement/test/suite.json
> [Entanglement] Add "Set Primary Location" action

- platform/commonUI/general/bundle.json
- platform/commonUI/general/src/UnsupportedBrowserWarning.js
- platform/commonUI/general/test/UnsupportedBrowserWarningSpec.js
- platform/commonUI/general/test/suite.json
- platform/commonUI/mobile/src/AgentService.js
- platform/commonUI/mobile/test/AgentServiceSpec.js
Show a notification when Open MCT Web is used with a browser other than our test-to browsers. (Chrome on desktop, Safari on mobile.)
> Show warning for unsupported browsers

- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
open #199
open #278
Hides Create button when s-status-editing applied;
Adds margin to search-bar input element when
Create button is hidden per above;
> Review and integrate open199f

- platform/representation/src/TemplatePrefetcher.js
Rephrase parameter type to something JSDoc can parse.
https://github.com/nasa/openmctweb/issues/411
> [Documentation] Fix type declaration

- platform/commonUI/general/res/sass/user-environ/_frame.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
Fixes bug as reported in #341: added discrete z-index definition for frame.child-frame.panel. 
> Review and integrate open341

- platform/entanglement/src/services/CopyTask.js
- platform/entanglement/test/services/CopyTaskSpec.js
This addresses [an issue](#428) where multiple references to the same object (via links) would result in incorrect substitutions in model references.
* idMap is no longer global, but instead scoped to each parent in the object hierarchy. This avoids the previous situation where only one map could be stored per ID, resulting in incorrect substitutions in the model of parent objects.
* Added a test case to validate the change in the scenario described in #428 
> [Copy] Duplication of layouts does not retain position and size of all elements. #428

- platform/commonUI/general/res/sass/_autoflow.scss
- platform/commonUI/general/res/sass/_effects.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
See https://trunk.arc.nasa.gov/jira/browse/WTD-1619. Filing an issue here as there were open platform mods to CSS that should be integrated.
> Review and integrate open-warp1596

- platform/entanglement/src/services/CopyTask.js
- platform/entanglement/test/services/CopyTaskSpec.js
> Fixed bug in copying #428

- platform/commonUI/general/res/sass/_autoflow.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
open #425
[Frontend] Hiding filter input in auto-flow element when in Layout
(cherry picked from commit 119613e)
Author checklist: 
- It'll work, what could go wrong: Y
> Review and integrate open-warp1596b

- platform/features/layout/test/FixedControllerSpec.js
- platform/features/plot/test/PlotControllerSpec.js
- platform/features/plot/test/elements/PlotLimitTrackerSpec.js
- platform/features/plot/test/suite.json
- platform/telemetry/test/TelemetrySubscriptionSpec.js
Adds test cases to cover open source code pertaining to display of limit state (where not covered by existing test changes)
1. Changes address original issue? Partially &ast;
&ast; Remaining changes will occur in closed-source branch
> [Limits] Add test cases for limits

- platform/commonUI/browse/res/templates/browse-object.html
- platform/commonUI/general/res/sass/_inspector.scss
- platform/commonUI/general/res/sass/edit/_editor.scss
- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/commonUI/general/res/sass/user-environ/_top-bar.scss
- platform/commonUI/general/res/templates/object-inspector.html
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
- platform/features/timeline/res/sass/_activities.scss
- platform/features/timeline/res/sass/_timeline-thematic.scss
See commit notes in nem468 and #468.
> Review and integrate nem468

- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
[Frontend] Fixed z-index of .primary-pane
open #470
> Review and integrate nem470

- platform/commonUI/general/res/sass/forms/_selects.scss
- platform/commonUI/general/res/sass/plots/_plots-main.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
- platform/features/plot/res/templates/plot.html
See notes in #342 for changes. 
> Review and integrate open342

- pom.xml
Addresses #483; updates includes/excludes in pom.xml to reflect directory structure and content changes associated with imperative bundle registration.
> [Build] Update includes/excludes

- platform/commonUI/general/res/sass/_object-label.scss
- platform/commonUI/general/res/sass/helpers/_wait-spinner.scss
- platform/commonUI/themes/espresso/res/css/theme-espresso.css
- platform/commonUI/themes/snow/res/css/theme-snow.css
- platform/features/plot/res/templates/plot.html
open #445
Mods and simplifications to wait-spinner classes to allow spinner to work and position properly in Linux Chrome; 
Simplification and cleanup in plot.html to use loading class instead of hide/show DOM element;
> Review and integrate open445

- gulpfile.js
Reinstantiate compass wrapper for each task execution.  Allows stylesheets
task to be run multiple times by watch.  
Fixes a bug reported by @charlesh88 where `gulp watch` fails to run the stylesheets task more than once.
2. Unit tests included and/or updated with changes? N/A (build only change)
> [Build] reinstantiate compass per task execution

- gulpfile.js
Log errors in SCSS processing but don't crash watch process.
Fixes https://github.com/nasa/openmctweb/issues/696
2. Unit tests included and/or updated with changes? N (build change)
> [Build] Gracefully handle scss errors

- platform/representation/src/MCTRepresentation.js
- platform/representation/test/MCTRepresentationSpec.js
Reduces severity of #732 
1. Changes address original issue? Y &ast;
&ast; At least partially.
> [Representation] Remove false-negative in unchanged check

- platform/commonUI/browse/res/templates/view-object.html
open #718
Removed class from markup;
> Review and integrate open718

- platform/commonUI/inspect/src/services/InfoService.js
- platform/commonUI/inspect/test/services/InfoServiceSpec.js
Remove line which erroneously clobbers correctly-determined arrow positioning classes for info bubble, addressing #716
> [Info Bubble] Fix bug with arrow positioning

- platform/commonUI/general/src/ui/TreeNodeView.js
- platform/commonUI/general/test/ui/TreeViewSpec.js
> [Tree] Add status classes during editing

- platform/commonUI/formats/src/UTCTimeFormat.js
- platform/commonUI/formats/test/UTCTimeFormatSpec.js
> [Time Formats] Display UTC with milliseconds

- platform/commonUI/general/res/sass/forms/_elems.scss
- platform/commonUI/general/res/sass/overlay/_overlay.scss
- platform/commonUI/themes/espresso/res/sass/_constants.scss
- platform/commonUI/themes/snow/res/sass/_constants.scss
- platform/features/timeline/bundle.js
- platform/features/timeline/res/templates/tabular-swimlane-cols-tree.html
- platform/features/timeline/res/templates/timeline.html
- platform/forms/res/templates/form.html
Provides fixes for #750 and #772. Markup, CSS and JS config modified to effect:
* Tooltips in Timeline interface (#750)
* New "controls-under" layout option in form-row (#772)
* New theme constants and better coloring approach to form .hint elements
> Review and integrate 755a

- platform/features/table/src/TableConfiguration.js
- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/src/controllers/RTTelemetryTableController.js
- platform/features/table/src/controllers/TelemetryTableController.js
- platform/features/table/test/controllers/RTTelemetryTableControllerSpec.js
- platform/features/table/test/controllers/TelemetryTableControllerSpec.js
This reverts commit f49552779af8494f5317e56acd5ea0d7e53b3419, reversing
changes made to e068173f3e628ba8fdccd0a1a2b22caa41ce1e28.
Removes changes made in open793, reverts changes made to fix #793 as they were not effective.
> Revert "Merge remote-tracking branch 'origin/open793'"

- platform/features/timeline/bundle.js
Add default values to model, such that editing which occurs
before user supplies these properties does not cause errors
to occur. Directly addresses #717, indirectly addresses
remaining errant behavior associated with #790.
2. Unit tests included and/or updated with changes? N &ast;
&ast; Changes are to bundle metadata, out-of-scope for current unit test suite.
> [Timeline] Add default values to model

- docs/src/process/cycle.md
- docs/src/process/index.md
- docs/src/process/version.md
Migrate relevant information from existing version guide in closed-source wiki;
add instructions for incrementing versions per #725
2. Unit tests included and/or updated with changes? N/A (changes are documentation-only)
> [Documentation] Add Version Guide

- docs/src/guide/index.md
- platform/features/table/bundle.js
- platform/features/table/res/sass/table.scss
- platform/features/table/res/templates/historical-table.html
- platform/features/table/res/templates/mct-table.html
- platform/features/table/res/templates/rt-table.html
- platform/features/table/src/TableConfiguration.js
- platform/features/table/src/controllers/HistoricalTableController.js
- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/src/controllers/RealtimeTableController.js
- platform/features/table/src/controllers/TableOptionsController.js
- platform/features/table/src/controllers/TelemetryTableController.js
- platform/features/table/src/directives/MCTTable.js
- platform/features/table/test/TableConfigurationSpec.js
- platform/features/table/test/controllers/HistoricalTableControllerSpec.js
- platform/features/table/test/controllers/MCTTableControllerSpec.js
- platform/features/table/test/controllers/RealtimeTableControllerSpec.js
- platform/features/table/test/controllers/TableOptionsControllerSpec.js
Minor fix to ordering in columns. Addresses issue with how empty column values were treated in ordering and makes ordering generally a little more robust.
> [Tables] Fix to correct sorting in realtime tables

- demo/res/css/hopscotch.css
- demo/src/DemoInitializer.js
Updated Hopscotch tour content and styling.
2. Unit tests included and/or updated with changes? N
3. Command line build passes? Hope so
> Review and integrate live_demo858

- platform/commonUI/general/res/sass/_global.scss
open #869
Removed bullets and set margin in ol, ul. Fixes bullets showing up and row margin problems in datetime picker. 
1. Unit tests included and/or updated with changes? N, N/A
> Review and integrate live_demo869

- index.html
- main.js
...such that they are not compiled into the Open MCT that
is used as the basis for non-example applications.
Addresses #835 
2. Unit tests included and/or updated with changes? N &ast;
&ast; Changes to application initialization; out of scope for unit testing.
> [Examples] Move examples out of main.js

- app.js
2. Unit tests included and/or updated with changes? __N/A__ Change to app.js - doesn't warrant tests
>  #885 added command line option --directory -D to specify base directory

- circle.yml
Doc generation removed from CI config to prevent clobbering deployed website.
2. Unit tests included and/or updated with changes? __N/A__ CI config change only
4. Changes have been smoke-tested? __N/A__
>  #899 updated circle.yml to deploy to live_demo and remove doc generation

- docs/footer.html
- docs/header.html
Updated the stylesheet in the generated documentation. Now using a customized stylesheet that is consistent with the website.
2. Unit tests included and/or updated with changes? __N/A__ - markup change only
> [documentation] #898 updated stylesheet reference

- platform/commonUI/general/test/directives/MCTPopupSpec.js
...to resolve build failure preventing merge, https://github.com/nasa/openmct/pull/922#issuecomment-218588876
Note: This merge targets branch `open889` (and not `master`) to resolve build failures on #922
> [Popup] Add method to jqlite mocks

- docs/src/tutorials/index.md
Updating for now to use interim bundle registration mechanism so that we have working tutorials online. Should be updated again when 1.0 API is finalized.
2. Unit tests included and/or updated with changes? __N/A__ documentation only
> [Tutorials] Updated tutorials to use newer bundle registration mechanism

- example/msl/src/RemsTelemetryModelProvider.js
Addresses #890
Changes:
* Added location property to all MSL/REMS objects
2. Unit tests included and/or updated with changes? __N/A__ - No unit tests associated with this example
> [Example] REMS heirarchy appear as links

- platform/commonUI/general/test/directives/MCTPopupSpec.js
I broke the build by incorrectly resolving a merge conflict.  This updates the code accordingly.
Add spy method, fix a merge conflict that was improperly resolved
in https://github.com/nasa/openmct/pull/922
> Resolve build conflict from #922

- circle.yml
- platform/representation/src/gestures/DropGesture.js
* Add a `gulp checkstyle` post-test task to `circle.yml`, such that code style gets verified by CircleCI
* Tried specifying `gulp verify` (runs test, checkstyle, and lint tasks) as the test step instead, to reduce replication, but for some reason Karma on CircleCI does not like to run this way (https://circleci.com/gh/nasa/openmct/1981)
* Fix a whitespace error that was causing code style check to fail (but which had gone undetected due to the above)
1. Changes address original issue? N/A (follow-up work for #142)
2. Unit tests included and/or updated with changes? N/A (changes to white space and CI config only)
> [Code Style] Run code style checks on CircleCI

- platform/commonUI/edit/bundle.js
- platform/commonUI/edit/test/creation/CreateActionSpec.js
Addresses #959
2. Unit tests included and/or updated with changes? __N/A__ minor code style changes only
4. Changes have been smoke-tested? __N/A__ minor code style changes only
> [Style] Fixed style issues introduced by #954

- platform/features/timeline/res/sass/_activities.scss
- platform/features/timeline/res/sass/_timeline-thematic.scss
- platform/features/timeline/res/sass/_timelines.scss
- platform/features/timeline/res/templates/activity-gantt.html
open #913 
open #768 
open #965
* Bottom position of holder divs adjusted
* Cursor properties modified
> R&I open913: various Timeline fixes

- platform/commonUI/edit/bundle.js
open #747
* Modified "unsaved changes" message for greater clarity.
> R&I open747: refined "unsaved changes" dialog message

- platform/features/timeline/bundle.js
- platform/features/timeline/src/controllers/TimelineZoomController.js
- platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js
> [Timeline] Update scroll position on timeout

- platform/features/timeline/bundle.js
- platform/features/timeline/src/controllers/TimelineZoomController.js
- platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js
> Revert "[Timeline] Update scroll position on timeout"

- platform/features/timeline/src/controllers/TimelineZoomController.js
- platform/features/timeline/test/controllers/TimelineZoomControllerSpec.js
> Revert "[Timeline] Provide greater initial width"

- platform/features/timeline/res/templates/activity-gantt.html
...before attempting to calculate a width based on it. Fixes #978.
2. Unit tests included and/or updated with changes? N/A (changes to markup only)
3. Command line build passes? Y 
> [Timeline] Check for existence of timespan

- platform/commonUI/edit/test/actions/CancelActionSpec.js
- platform/core/test/objects/DomainObjectProviderSpec.js
- platform/features/conductor/test/ConductorRepresenterSpec.js
- platform/features/table/test/DomainColumnSpec.js
- platform/representation/src/gestures/DropGesture.js
- platform/representation/test/gestures/DropGestureSpec.js
Addresses #629 
- Restored disabled tests, updating them where necessary
- Removed redundant tests
> [Edit Mode] #629 restored or rewrote tests disabled as part of NEM prototype

- platform/features/table/res/templates/rt-table.html
- platform/features/table/src/controllers/RealtimeTableController.js
- platform/features/table/test/controllers/RealtimeTableControllerSpec.js
Enables auto-scroll behavior for all real-time tables
> [Tables] Enabled auto-scroll by default fixes #1040

- app.js
Added logging statement, so the user knows when the app is up and running.
N/A
Yes
Yes
Yes
***
- Needs signed CLA agreement & review
> [Functionality] Log app instance to the console

- README.md
Added Apache license
N/A
Yes
Yes
Yes
***
> [Branding] Added Apache license to README.md

- main.js
- src/MCT.js
- src/adapter/bundle.js
- src/adapter/directives/MCTView.js
- src/api/Type.js
- src/api/View.js
- src/api/api.js
- tutorials/todo/bundle.js
- tutorials/todo/todo-task.html
- tutorials/todo/todo.html
- tutorials/todo/todo.js
Okay, I _really really_ chose `api-tutorials` as the base branch this time.
> [API Prototype] Support imperative view registration

- src/MCT.js
- src/adapter/directives/MCTView.js
- src/adapter/templates/edit-object-replacement.html
- src/ui/Dialog.js
- src/ui/dialog.html
- src/ui/overlay.html
- tutorials/todo/todo-dialog.html
- tutorials/todo/todo-toolbar.html
- tutorials/todo/todo.js
Adds a toolbar. The "remove" button is not functional; working on selection state
> [API Prototype] Add toolbar

- platform/commonUI/edit/bundle.js
- platform/commonUI/edit/src/actions/SaveAsAction.js
- platform/commonUI/edit/src/services/TransactionService.js
- platform/commonUI/edit/test/actions/SaveAsActionSpec.js
Squashed version of #1050, addressing #1046
> [Edit] Clear transactions on Save As

- main.js
- platform/features/fixed/bundle.js
* Defined a new bundle platform/features/fixed
* Bundle defines a new type and a new view (based on the existing 'fixed' view). Fixed type is associated with only one view, and vice-versa.
2. Unit tests included and/or updated with changes? N/A - bundle definition only, no code changes
> [Fixed] Create new object type based on Telemetry Panel 'Fixed' view

- platform/commonUI/browse/bundle.js
- platform/commonUI/browse/res/templates/browse.html
- platform/commonUI/browse/src/InspectorPaneController.js
- platform/commonUI/browse/test/InspectorPaneControllerSpec.js
> [Browse] Inspector shown when object switched to edit mode. Fixes #1031

- API.md
Adds documentation for `mct.selection`
> [API] Add documentation for selection state

- build-docs.sh
> [Documentation] Updated docs build script to push documentation to the correct directory on the website

- docs/src/tutorials/index.md
Stumbled upon this while following the tutorial, the code block in Telemetry Adapter-Step 1 was not indented as a code block.
Is this "blocked" by this other issue, though? https://github.com/nasa/openmct/issues/1128
> [Documentation] Fix code formatting

- demo/src/DemoInitializer.js
Author Checklist
Changes address original issue? Yes. See #1137 
Unit tests included and/or updated with changes? No need to update. All are passing.
> [Hopscotch] Fix alignment of 'Edit Button' hopscotch. Fixes #1137

- protractor/UI/DragDrop.js
> Suppress commented code on the github repository

- tutorials/todo/todo.js
...to expect new domain object API (instead of explicitly
wrapping it.)
> [API] Update todo tutorial

- example/plotOptions/bundle.js
- platform/commonUI/edit/src/creation/CreateWizard.js
- platform/commonUI/general/res/sass/_inspector.scss
- platform/commonUI/general/res/sass/forms/_elems.scss
- platform/commonUI/general/res/sass/mobile/overlay/_overlay.scss
- platform/entanglement/src/actions/AbstractComposeAction.js
- platform/entanglement/src/actions/CopyAction.js
- platform/entanglement/src/services/LocationService.js
- platform/entanglement/test/actions/AbstractComposeActionSpec.js
- platform/entanglement/test/actions/CopyActionSpec.js
- platform/entanglement/test/actions/LinkActionSpec.js
- platform/entanglement/test/actions/MoveActionSpec.js
- platform/features/fixed/bundle.js
- platform/features/layout/bundle.js
- platform/features/layout/src/elements/ElementFactory.js
- platform/forms/res/templates/form.html
Fixes #1118 and #1108. Sorry about the commit history: I rebased this onto master as so much time had passed between initial work and now, and I even tried deleting the remote branch and re-pushing it. Let me know if there are issues.
- Implements flex-box layout in forms to allow the overlay's Save In tree browser to use the maximum amount of space available to it. Work done for both desktop and mobile views.
- Fixed input sizing for #1108.
1. Unit tests included and/or updated with changes? Y
> Review and integrate improved dialog layout

- docs/src/architecture/index.md
- docs/src/architecture/platform.md
- docs/src/design/proposals/APIRedesign.md
- docs/src/design/proposals/APIRedesign_PeteRichards.md
- docs/src/guide/index.md
- docs/src/process/testing/plan.md
Made changes to 6 different files to fix typos, grammatical errors and formatting. Refer to the commit message and description to see why those changes were made.
2. Appropriate unit tests included? N/A - No code changes
3. Code style and in-line documentation are appropriate? N/A
EDIT: [Contributor License Agreement](https://nasa.github.io/openmct/contributing/ind-cla-open-mct.pdf) has been completed, signed and sent to appropriate email address and cc-ed to arc-dl-openmct@mail.nasa.gov.
> [Documentation] Fixed typos, grammars

- app.js
Addresses issue #1158
Doesn't impact/require any tests that I can see...
> [proxyUrl] pass URL parameters to proxied URL

- docs/src/tutorials/index.md
minor change & please let me know if I can help with anything else
Changes appear to address issue? Y
Appropriate unit tests included? N/A - No code changes
Code style and in-line documentation are appropriate? N/A
Commit messages meet standards? N
EDIT: [CLA](https://nasa.github.io/openmct/contributing/ind-cla-open-mct.pdf) has been completed, signed and sent to appropriate email address and cc-ed to arc-dl-openmct@mail.nasa.gov.
> [Documentation] Updated from OpenMCTWeb to OpenMCT

- index.html
- platform/forms/res/templates/controls/color.html
- platform/forms/res/templates/controls/composite.html
- platform/forms/res/templates/toolbar.html
- replace tabs by 4 spaces
- move `lang` attribute from `head` to `html`
- `doctype` and `charset` are case insensitive
- `type="text/javascript"` is default
Thanks
> [Frontend] Tweak markup

- app.js
Reverts nasa/openmct#1159
@VWoeltjen 
2. Unit tests included and/or updated with changes? N/A (server only change)
> Revert "[proxyUrl] pass URL parameters to proxied URL"

- README.md
Mitigates #1151.
1. Changes address original issue? Partially &ast;
2. Unit tests included and/or updated with changes? N (documentation only)
&ast; Original issue primarily effects developers building locally and using the dev server; issue is not addressed, but a workaround/warning is conveyed to that audience
> [README] Warn about root installation issues

- platform/commonUI/dialog/res/templates/overlay.html
- platform/commonUI/dialog/src/DialogService.js
- platform/commonUI/edit/src/actions/SaveInProgressDialog.js
- platform/commonUI/general/res/sass/_constants.scss
- platform/commonUI/general/res/sass/overlay/_overlay.scss
> [Frontend] Delay visibility of progress bar

- platform/commonUI/general/res/sass/controls/_controls.scss
- platform/core/bundle.js
- platform/forms/bundle.js
- platform/forms/res/templates/controls/textarea.html
Still needs CSS love mentioned by @charlesh88 in #1184.
> [Frontend] Add notes property to all item types

- bower.json
- main.js
- platform/features/plot/bundle.js
- platform/features/plot/res/templates/plot.html
- platform/features/plot/src/PlotController.js
- platform/features/plot/src/services/ExportImageService.js
- platform/features/plot/test/PlotControllerSpec.js
- platform/features/plot/test/services/ExportImageServiceSpec.js
- test-main.js
Remove pdf export with extreme prejudice due to issues with build process.
Fixes https://github.com/nasa/openmct/issues/1217
> [export] remove pdf export

- platform/features/timeline/bundle.js
- platform/features/timeline/src/capabilities/GraphCapability.js
- platform/features/timeline/test/capabilities/GraphCapabilitySpec.js
Issue #1185 
I didn't see a help wanted label on this but was interested to learn more about how activity modes work. Hope it's cool to make pull requests on non-help wanted labeled issues.
> [Timeline] Add battery starting state-of-charge

- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/test/controllers/MCTTableControllerSpec.js
> [Tables] Fixed table scroll by modifying selection of scrollable element. Fixes #1216

- platform/commonUI/browse/bundle.js
- platform/commonUI/general/bundle.js
- platform/commonUI/general/src/StyleSheetLoader.js
- platform/commonUI/general/test/StyleSheetLoaderSpec.js
- platform/execution/src/WorkerService.js
- platform/features/table/bundle.js
- platform/representation/src/gestures/GestureProvider.js
- platform/search/bundle.js
Adds miscellaneous platform updates to include templates
via the RequireJS text plugin; to support modification of
asset paths; and to support priority order for gestures.
Supports integration of new API, #1124.
Submitting as a separate PR to simplify diff in #1212
> [API] Miscellaneous platform updates

- src/end.frag
Require the openmct module so that distributed files work properly.
Related to #1212
2. Unit tests included and/or updated with changes? N/A, build only change.
> [Build] require correct module

- build-docs.sh
- docs/src/index.md
- package.json
2. Unit tests included and/or updated with changes? N/A - build changes only
> [Documentation] Changed build location of docs so that API docs are pushed to website

- platform/commonUI/general/res/sass/controls/_buttons.scss
- platform/features/plot/res/templates/plot.html
Fixes #1235
Sass and markup mods; changes to .l-btn-set and related classes
> [Frontend] Fixes to Export buttons

- src/adapter/policies/AdapterCompositionPolicy.js
...as this had fallen out-of-date with existing APIs. Fixes #1257.
2. Unit tests included and/or updated with changes? No, but accounted for by #1218 
> [Composition] Fix adapter composition policy

- src/adapter/bundle.js
- src/adapter/capabilities/AdapterCapability.js
- src/adapter/controllers/AdaptedViewController.js
- src/adapter/directives/MCTView.js
- src/adapter/policies/AdaptedViewPolicy.js
- src/adapter/templates/adapted-view-template.html
- src/api/objects/object-utils.js
Repairs incompletely-implemented view registries, #1307
> [Views] Repair view registry for mainViews

- index.html
- src/defaultRegistry.js
...except for the dev instance of Open MCT run from index.html.
Fixes #1270
2. Unit tests included and/or updated with changes? N/A (changes out of scope for unit testing)
> [Build] Don't enable local storage by default

- demo/src/DemoInitializer.js
- demo/src/Tour.js
2. Unit tests included and/or updated with changes? N/A - Demo tour does not have unit tests defined
> [Live Demo] Don't launch tour for object opened in new tab

- src/api/composition/DefaultCompositionProvider.js
> [Composition] Modified call to object utils to provide identifier correctly

- docs/src/tutorials/index.md
Updated existing tutorials to fix some outstanding issues. Does not update to demonstrate new API, but does fix compatibility issues that were preventing tutorials from being functional.
Fixes #1336, #1309, and #1163 
2. Unit tests included and/or updated with changes? N/A - tutorials do not have unit tests
> [Documentation] Fixed non-functioning telemetry tutorial, updated glyphs.

- platform/features/my-items/bundle.js
Define a model for my items to be used when the model
is not found in a storage provider.
Fixes https://github.com/nasa/openmct/issues/1284
2. Unit tests included and/or updated with changes? N/A, config only change
> [MyItems] Load via static model provider

- platform/commonUI/notification/res/notification-indicator.html
This addresses and closes #1239
changes are out of scope for unit testing
yes
yes
> Make notification icon clickable

- platform/core/src/runs/TransactingMutationListener.js
2. Unit tests included and/or updated with changes? N/A - No tests affected, new behavior does not warrant unit test
* Note that this change was previously pushed directly to master (as 7dda85cc5f2783c2665ee2c65ce8bdc6a8adccce ) by accident but reverted immediately.
> [Edit Mode] Fix issue with navigation not triggering unsaved changes warning

- platform/commonUI/browse/bundle.js
- platform/commonUI/browse/src/BrowseController.js
- platform/commonUI/browse/src/BrowseObjectController.js
- platform/commonUI/browse/src/InspectorPaneController.js
- platform/commonUI/browse/test/BrowseControllerSpec.js
- platform/commonUI/browse/test/BrowseObjectControllerSpec.js
- platform/core/src/capabilities/InstantiationCapability.js
- platform/core/test/capabilities/InstantiationCapabilitySpec.js
- platform/features/conductor/core/bundle.js
- platform/features/conductor/core/src/ui/TimeConductorController.js
- platform/features/conductor/core/src/ui/TimeConductorControllerSpec.js
> [Time Conductor] Prevent route change when time conductor values change

- platform/features/conductor/core/src/ui/TimeConductorController.js
- platform/features/conductor/core/src/ui/TimeConductorControllerSpec.js
> [Time Conductor] Fixed issue with zoom slider appearing for time systems that do not support it.

- src/start.frag
...to match name of module. Fixes #1356
2. Unit tests included and/or updated with changes? N/A (changes outside of scope of testing)
> [Build] Change global namespace name

- platform/features/imagery/src/directives/MCTBackgroundImage.js
2. Unit tests included and/or updated with changes? N/A changes do not warrant additional tests
> [Images] Filters not working in older Chrome installs. Fixes #1358.

- .jshintrc
- src/MCT.js
- src/api/telemetry/LegacyTelemetryProvider.js
- src/api/telemetry/TelemetryAPI.js
- src/api/telemetry/TelemetryMetadataManager.js
- src/api/telemetry/TelemetryValueFormatter.js
- src/api/telemetry/bundle.js
- src/defaultRegistry.js
3. Command line build passes? Err...it does now!
> [Telemetry] Added legacy provider to expose old style telemetry providers to users of the new telemetry API

- example/scratchpad/bundle.js
- example/taxonomy/bundle.js
- package.json
Update example bundles to reflect changes to root registration from 73b3ae72649a56366583a119e8f1bb3a57b82b2a
@charlesh88 - this pull request also serves as an example for addressing the style guide plugin issues from #1384
2. Unit tests included and/or updated with changes? N/A (changes to declarative examples only)
> [Roots] Update examples

- API.md
- index.html
- src/defaultRegistry.js
- src/plugins/plugins.js
Fixes #1398. Still needs testing, esp. for CouchDB and ElasticSearch configuration
> [Plugins] Adapt legacy plugins

- platform/commonUI/dialog/bundle.js
- platform/commonUI/dialog/src/DialogService.js
- platform/commonUI/dialog/test/DialogServiceSpec.js
> [Dialogs] Close dialogs by pressing the ESC key

- platform/commonUI/general/res/sass/overlay/_overlay.scss
> [Overlay] Remove max-height and max-width from overlay CSS

- docs/src/tutorials/index.md
Adds code examples with linting
> [DOCUMENTATION] Add linting to tutorial section

- platform/commonUI/dialog/src/DialogService.js
- platform/commonUI/dialog/test/DialogServiceSpec.js
Fixes code style bugs missed in review of #1374.  For some reason CIRCLECI never ran checks on that branch.
> [Style] Fix style bugs introduced in #1374

- example/msl/bundle.js
Fixes #1386 
Changes are limited to example/msl only in this branch; I'll merge this branch into my styleguide branch.
> [Config] Fixes for example/msl

- README.md
This is for issue 1403 https://github.com/nasa/openmct/issues/1403
> adding MCT name to README

- platform/commonUI/browse/src/navigation/OrphanNavigationHandler.js
- platform/commonUI/browse/test/navigation/OrphanNavigationHandlerSpec.js
Switch orphan checking to use capability instead of model.
This ensures that new-style composition providers work as intended.
> Orphan check uses capability not model

- platform/features/table/test/controllers/TelemetryTableControllerSpec.js
@akhenry this fixes tests in master.  Sending your way for review and integrate.
> Add hasCapability to mock

- index.html
- src/plugins/plugins.js
* Changes have been smoke-tested?
> All builtin plugins now standardized as functions

- index.html
- openmct.js
- platform/features/conductor/core/bundle.js
- platform/features/conductor/core/res/templates/time-conductor.html
- platform/features/conductor/core/src/ui/TimeConductorController.js
- platform/features/conductor/core/src/ui/TimeConductorControllerSpec.js
- platform/features/conductor/utcTimeSystem/bundle.js
- platform/features/conductor/utcTimeSystem/src/UTCTimeSystem.js
- src/plugins/plugins.js
Defaults conductor to real-time mode when not included / visible.
> [Conductor] Allow configuration of conductor defaults

- platform/commonUI/general/res/sass/startup-base.scss
- platform/commonUI/themes/espresso/res/sass/theme-espresso.scss
- platform/commonUI/themes/snow/res/sass/theme-snow.scss
- platform/features/conductor/core/res/sass/time-conductor-espresso.scss
- platform/features/conductor/core/res/sass/time-conductor-snow.scss
- platform/features/timeline/res/sass/timeline-espresso.scss
- platform/features/timeline/res/sass/timeline-snow.scss
- platform/features/timeline/res/sass/timeline.scss
Addresses #1432 
2. Unit tests included and/or updated with changes? N/A build only
> [Build] Installed sound suppression system for Bourbon deprecation messages.

- platform/features/table/src/TelemetryCollection.js
- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/src/controllers/TelemetryTableController.js
- platform/features/table/test/TelemetryCollectionSpec.js
- platform/features/table/test/controllers/MCTTableControllerSpec.js
> [Tables] Maintain correct insertion order with duplicates. Fixes #1465

- platform/commonUI/general/res/sass/_inspector.scss
> [Frontend] .form-row cleanups for Inspector

- example/imagery/src/ImageTelemetry.js
Brought these across from the old live demo - https://openmct-demo.herokuapp.com/#/browse/mine/88a26104-8bd5-445d-8b57-10b567d2823d/b8858147-8e4f-4249-badb-b4031dba90f9?view=imagery
> [Example] Update images to be more rovery. Fixes #1484

- API.md
- src/api/types/TypeRegistry.js
* Unit tests included and/or updated with changes? N/A - Docs only
* Changes have been smoke-tested? N/A - Docs only
Since these haven't been reviewed by @VWoeltjen yet (as far as I know), assigning to you.
> [Docs] Replace existing API documentation with V1 public API docs

- platform/features/pages/bundle.js
Fixes #1507
2. Unit tests included and/or updated with changes? N/A (changes in bundle, out of scope for unit tests)
> [Web Page] Allow dashes in domains

- example/msl/bundle.js
- example/msl/src/RemsTelemetryServerAdapter.js
> Modified MSL data source to use a single cached connection

- karma.conf.js
- src/MCTSpec.js
Adds test coverage for MCT.js (implementation of the `openmct` object.) Will [file issues](https://github.com/nasa/openmct/issues/1218#issuecomment-255844611) for test coverage for remainder of new API
> [Testing] Add test coverage for MCT.js

- platform/commonUI/general/res/sass/controls/_buttons.scss
[Frontend] Removed button selector - too broad
Fixes #1485
> [Live demo] Remove CSS selector for `button`

- bower.json
- karma.conf.js
- openmct.js
- package.json
- platform/features/conductor/core/src/ui/ConductorAxisController.js
- platform/features/conductor/core/src/ui/ConductorAxisControllerSpec.js
- test-main.js
#1224 
Size of D3 dependency was reduced from 211KB to 78KB. Not as much as I think, because d3-scale dependency need a another 8 d3 depencencies.
> [Optimization] Reduce D3 dependency size

- .jshintrc
- platform/features/layout/bundle.js
- platform/features/layout/src/FixedController.js
- platform/features/layout/test/FixedControllerSpec.js
- platform/features/table/src/TelemetryCollection.js
There were also some pre-existing issues around adding and removing objects that have been resolved.
> [Fixed Position] Updated fixed position view to use new Telemetry API

- openmct.js
* Unit tests included and/or updated with changes? N/A - code style fix
* Changes have been smoke-tested? N/A
> [Style] Fixed build error in master due to extra comma in array

- LICENSES.md
Extended main copyright to 2017 on line 3 of LICENSES.md - contributes to fixing #1517.
Author Checklist:
Changes address original issue? YES
Command line build passes? N/A
Changes have been smoke-tested? N/A
> [Documentation] Include 2017 in copyright

- README.md
Link to correct tutorial in readme.
Fixes https://github.com/nasa/openmct/issues/1535
2. Appropriate unit tests included? N/A
@akhenry @VWoeltjen first one to review and merge gets it!
> [Docs] Link to correct tutorial

- platform/telemetry/src/TelemetryCapability.js
- platform/telemetry/test/TelemetryCapabilitySpec.js
This fix is needed for the tutorials and live demo to work correctly.
* Unit tests included and/or updated with changes? N
> [Telemetry] Use the 'source' metadata field to retrieve telemetry metadata, if available.

- example/msl/src/MSLDataDictionary.js
- example/msl/src/RemsTelemetryServerAdapter.js
Brings across functionality from the old live demo.
> [Example] Add units to MSL example. 

- src/api/telemetry/TelemetryMetadataManager.js
we don't depreciate... we deprecate code.
Fixes typo in latest deprecation warning.
> [Typo] Fix deprecation warning

- platform/features/conductor/core/src/ui/TimeConductorController.js
https://github.com/nasa/openmct/pull/1583 actually broke the clock menu, additionally there were problems when changing clocks with an unsupported time system selected.  This resolves those bugs.
> [TC] Fix clock option selection

- platform/features/conductor/core/src/ui/TimeConductorController.js
Update the format when the timesystem changes.
Fixes https://github.com/nasa/openmct/issues/1585
2. Unit tests included and/or updated with changes? N, #1560 exists for backfill
> [TC] Update format on timesystem change

- gulpfile.js
- package.json
> [Build] Include version information in openmct.js

- platform/search/res/templates/search.html
> [Frontend] Fixed markup to allow scroll of results

- src/adapter/runs/TimeSettingsURLHandler.js
- src/adapter/runs/TimeSettingsURLHandlerSpec.js
Fixes nasa/openmct-tutorial#14
> [Time] Tolerate unset Time API properties from URL handler

- index.html
- platform/commonUI/general/res/sass/features/_imagery.scss
- platform/commonUI/themes/espresso/res/sass/_constants.scss
- platform/commonUI/themes/snow/res/sass/_constants.scss
- platform/features/imagery-timeline/bundle.js
- platform/features/imagery-timeline/res/css/timeline.css
- platform/features/imagery-timeline/res/templates/timeline.html
- platform/features/imagery-timeline/src/controllers/ImageryTimelineController.js
@prestonjcrowe opening a pull request so I can leave inline feedback for you.
I did a rebase here to clean some stuff up, check your email for more deets on that.
> Historical imagery 

- platform/commonUI/browse/res/templates/browse.html
- platform/commonUI/general/src/directives/MCTSplitPane.js
- platform/commonUI/general/src/directives/MCTSplitter.js
Fixed issue regarding non persistence of MCTSplitPane widths after user increases or decreases width.
> persist user preference width for MCTSplitPanes issue #1646

- platform/commonUI/general/res/sass/controls/_controls.scss
- platform/commonUI/general/res/sass/user-environ/_frame.scss
- platform/features/hyperlink/bundle.js
- platform/features/hyperlink/res/templates/hyperlink.html
- platform/features/layout/res/templates/frame.html
Markup and CSS fixes for Hyperlinks
> Hyperlink styling

- example/styleguide/bundle.js
- example/styleguide/res/sass/_style-guide-base.scss
- example/styleguide/res/templates/mct-example.html
- example/styleguide/res/templates/status.html
- example/styleguide/src/ExampleStyleGuideModelProvider.js
- platform/commonUI/general/res/sass/_glyphs.scss
- platform/commonUI/general/res/sass/_limits.scss
- platform/commonUI/general/res/sass/_main.scss
- platform/commonUI/general/res/sass/_status.scss
- platform/commonUI/general/res/sass/controls/_messages.scss
- platform/commonUI/themes/espresso/res/sass/_constants.scss
- platform/commonUI/themes/espresso/res/sass/_mixins.scss
- platform/commonUI/themes/snow/res/sass/_constants.scss
- platform/commonUI/themes/snow/res/sass/_mixins.scss
CSS class changes and additions to make limits classes more flexibly usable, add "status-" classes to support WARNING_HI, DIAGNOSTIC, etc. Also includes Style Guide updates covering these changes and additions. Stems from #1677 and #1558.
> Review limit and status CSS classes

- API.md
Omitting checklist since change is to documentation only
> [Documentation] Fix typo

- platform/commonUI/general/res/sass/_archetypes.scss
Fixes #1685. In use SASS commented out, not sure why. Restored, fixes the issue. @VWoeltjen Let's get this merged into master so anyone working on Timeline-related stuff can use this interface.
> Fix Selector Pool Control

- platform/commonUI/general/res/sass/_constants.scss
- platform/commonUI/general/res/sass/features/_imagery.scss
- platform/commonUI/general/src/directives/MCTSplitPane.js
- platform/features/imagery/bundle.js
- platform/features/imagery/res/templates/imagery.html
- platform/features/imagery/res/templates/imageryTimeline.html
- platform/features/imagery/src/controllers/ImageryController.js
- platform/features/imagery/test/controllers/ImageryControllerSpec.js
Add imagery history view.
Allow users to select image from history.
Add splitter between history view and larger image view.
Allow users to resize and persist imagery pane heights.
> Imagery issue #1676

- platform/telemetry/src/TelemetryCapability.js
- platform/telemetry/test/TelemetryCapabilitySpec.js
Update the Legacy Telemetry Adapter to handle source remapping
for telemetry which has it.
fixes https://github.com/nasa/openmct/issues/1724
@VWoeltjen @psarram @dtailor90 can one of you review and integrate if it passes your review?
> [Telemetry] Legacy adapter handles source remap

- platform/commonUI/edit/res/templates/create/create-button.html
- platform/commonUI/edit/res/templates/create/create-menu.html
- platform/commonUI/general/res/sass/controls/_controls.scss
- platform/commonUI/general/res/sass/controls/_menus.scss
- platform/commonUI/general/res/sass/overlay/_overlay.scss
- platform/commonUI/themes/espresso/res/sass/_constants.scss
- platform/commonUI/themes/snow/res/sass/_constants.scss
- platform/features/conductor/core/res/templates/mode-selector/mode-menu.html
- platform/features/conductor/core/res/templates/mode-selector/mode-selector.html
- platform/features/conductor/core/src/ui/TimeConductorController.js
- src/plugins/utcTimeSystem/LocalClock.js
For #1729. Create menu and TC mode selector menu fixes and enhancements:
- Height dynamically scaled up to a max of the following:
- Number of list items OR
- Area needed to display the description OR
- Proportion of viewport height
- Finessed scrollbars, padding, etc. for more finished look
> Review and integrate super-menu fixes and enhancements

- platform/commonUI/general/src/controllers/ObjectInspectorController.js
- platform/commonUI/general/test/controllers/ObjectInspectorControllerSpec.js
Added a mutation listener to update inspector metadata when object properties are changed.
> Inspector issue 1276

- platform/features/layout/src/LayoutController.js
- platform/features/layout/test/LayoutControllerSpec.js
Compare the current and previous compositions and deselct the removed object.
Fixes # 1731
> [Layout] Deselect object after removal

- platform/commonUI/general/res/sass/_iframe.scss
Removes iframe borders. Was cherry-picked into branch demo-2017.1, no great hurry on reviewing this PR.
Fixes #1776
> [Frontend] Review and integrate the death of iframe borders

- circle.yml
* Removed the push to Heroku - no longer necessary and seems to cause circle-ci build failures in master
* Also removed the live_demo build branch. Live demo resides in a separate repository these days.
* Unit tests included and/or updated with changes? N/A - build config changes only
* Command line build passes? N/A - Circle-ci specific build config, can't test from CLI
* Changes have been smoke-tested? N/A - See above
> [Build] Remove unused steps from circleci configuration

- platform/commonUI/general/res/sass/_status.scss
- platform/commonUI/general/res/sass/controls/_messages.scss
- platform/features/clock/bundle.js
- platform/features/clock/src/actions/FollowTimerAction.js
- platform/features/clock/src/indicators/FollowIndicator.js
- platform/features/clock/src/services/TimerService.js
- platform/features/clock/test/actions/FollowTimerActionSpec.js
- platform/features/clock/test/indicators/FollowIndicatorSpec.js
- platform/features/clock/test/services/TimerServiceSpec.js
- platform/features/timeline/bundle.js
- platform/features/timeline/res/sass/_timeline-thematic.scss
- platform/features/timeline/res/sass/_timelines.scss
- platform/features/timeline/res/sass/timeline-espresso.scss
- platform/features/timeline/res/sass/timeline-snow.scss
- platform/features/timeline/res/sass/timeline.scss
- platform/features/timeline/res/templates/timeline.html
- platform/features/timeline/src/controllers/TimelineTOIController.js
- platform/features/timeline/src/controllers/TimelineZoomController.js
- platform/features/timeline/test/controllers/TimelineTOIControllerSpec.js
Work-in-progress for #1688; still to-do:
> [Timers] Follow timers from timelines

- bower.json
- openmct.js
- test-main.js
Fixes #1808
2. Unit tests included and/or updated with changes? N/A (changes to build configuration only)
> [Build] Update file-saver dependency

- platform/features/timeline/bundle.js
- platform/features/timeline/res/sass/_timelines.scss
- platform/features/timeline/res/templates/timeline.html
- platform/features/timeline/src/directives/MCTResourceGraphDrop.js
- platform/features/timeline/test/directives/MCTResourceGraphDropSpec.js
Adds test cases and resolves merge conflicts for #1195 from @hudsonfoo, which fixes #599.
> [Timeline] Add resource graphs by drag-and-drop

- example/generator/WorkerInterface.js
* Unit tests included and/or updated with changes? N/A - No unit tests in example code
> [Examples] Memory leak in SWG

- src/api/objects/MutableObject.js
- src/plugins/summaryWidget/src/Condition.js
- src/plugins/summaryWidget/src/Rule.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/plugins/summaryWidget/src/TestDataItem.js
- src/plugins/summaryWidget/src/TestDataManager.js
- src/plugins/summaryWidget/src/eventHelpers.js
- src/plugins/summaryWidget/src/input/KeySelect.js
- src/plugins/summaryWidget/src/input/OperationSelect.js
- src/plugins/summaryWidget/src/input/Palette.js
- src/plugins/summaryWidget/src/input/Select.js
Fixes a memory leak that prevented the Summary Widget view, and all of its associated objects from being garbage collected.
* Changes address original issue? N/A - No associated issue.
* Unit tests included and/or updated with changes? N/A - No functional changes.
> Summary widgets ml

- platform/features/clock/src/indicators/FollowIndicator.js
- platform/features/clock/test/indicators/FollowIndicatorSpec.js
...by expecting new-style instead of legacy domain objects.
Fixes #1836 
3. Command line build passes? 
> [Timers] Fix bug in FollowIndicator

- platform/features/timeline/res/templates/timeline.html
Stop the event as a temporarily workaround until timeline is modified to use the new Selection API.
Fixes # 1842
- Changes have been smoke-tested? Y
> [TIMELINE] fix selection regression in timeline

- src/plugins/summaryWidget/src/ConditionEvaluator.js
- src/plugins/summaryWidget/test/ConditionEvaluatorSpec.js
Add appropriate tests
Fix for isUndefined, which was not working as intended
> add isDefined condition to condition Evaluator which fixes Issue#1860

- README.md
- circle.yml
- docs/src/guide/index.md
- package.json
* https://docs.npmjs.com/misc/scripts#prepublish-and-prepare 
This PR removes one less warning in the console, which is better for developer experience.
N/A
N/A
Y
Y
> [BUILD] Replace Prepublish with Prepare

- platform/commonUI/inspect/src/services/InfoService.js
add offsetX to popupService instance in infoService, to prevent bubble from appearing under the mouse pointer, which causes interminent calls to the callback.
> fixes issue #1830

- platform/commonUI/edit/src/controllers/ElementsController.js
- platform/commonUI/edit/src/representers/EditToolbarSelection.js
- platform/commonUI/general/res/sass/user-environ/_frame.scss
- platform/commonUI/general/res/sass/user-environ/_selecting.scss
- platform/commonUI/regions/src/InspectorController.js
- platform/features/layout/bundle.js
- platform/features/layout/res/templates/fixed.html
- platform/features/layout/src/FixedController.js
- platform/features/layout/src/FixedDragHandle.js
- platform/features/layout/src/elements/ElementProxy.js
- platform/features/layout/test/FixedControllerSpec.js
- src/selection/Selection.js
Fixes #1848
- Unit tests included and/or updated with changes? Not yet
- Changes have been smoke-tested? Y
@VWoeltjen @larkin I'll have to update the unit tests but the changes are ready for review. 
@charlesh88 Elements can now be selected in browse mode and so some style updates might be needed.
> [Fixed Position] Modify fixed position to use the Selection API

- .jshintrc
Fixes #1885 
* Unit tests included and/or updated with changes? N/A - config change only
> [Code Style] Allow late definition of functions

- src/plugins/summaryWidget/src/Condition.js
- src/plugins/summaryWidget/src/ConditionEvaluator.js
- src/plugins/summaryWidget/src/Rule.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/plugins/summaryWidget/src/TestDataItem.js
- src/plugins/summaryWidget/src/input/KeySelect.js
- src/plugins/summaryWidget/src/input/Select.js
Quick fix for Summary Widgets performance issues. As well as capping updates at 60Hz, removes one unnecessary html eval.
ToDo:
> Summary Widgets performance enhancements

- platform/features/plot/src/PlotController.js
- platform/features/plot/src/services/ExportImageService.js
- platform/features/plot/test/services/ExportImageServiceSpec.js
- add parameter for background color, only change color when parameter is passed in (export image service is used in notebook which needs the background color not changed
- added tests
> Add color parameter to render, to prevent changing background color when not required

- openmct.js
- test-main.js
d3 changed the location of this file, npm install fails when trying new builds.
> d3 selection filepath changed

- platform/commonUI/browse/res/templates/browse/object-properties.html
Fix navigation via inspector breadcrumbs.
Fixes https://github.com/nasa/openmct/issues/1927
2. Unit tests included and/or updated with changes? N, html only change.
> Restore navigation via breadcrumbs

- platform/features/layout/src/FixedController.js
- platform/features/layout/test/FixedControllerSpec.js
Fixed usage of Telemetry API, use hints to get valueMetadata, use valueMetadata to get formatter.
> Fixes Issue #1938 - Fixed Positon should display enumarated value

- package.json
* Changes address original issue? N/A no associated issue
* Unit tests included and/or updated with changes? N/A version bump only
> Eagle sprint release

- src/plugins/plot/src/telemetry/PlotController.js
Plot waits for element to have width before loading.  Otherwise,
it may make a minmax request with an invalid size parameter.
Fixes https://github.com/nasa/openmct/issues/1974
2. Unit tests included and/or updated with changes? N/A, issue exists for backfill.
> [Plot] Wait for width before loading

- package.json
This is the release of Enterprise (0.13.3) and the opening of sprint Galactica (0.14.0).
Updated version numbers, etc.
* Changes address original issue? N/A
> Enterprise-galactica

- platform/commonUI/general/src/ui/TreeLabelView.js
Remove previous icon class name before adding the new class name
> fixes issue #1973 and #1911

- platform/features/imagery/src/controllers/ImageryController.js
- platform/features/imagery/test/controllers/ImageryControllerSpec.js
Added a force update of values to latest image in history
> [Imagery] Issue #1962 - History shows oldest image

- example/styleguide/res/sass/_style-guide-base.scss
- platform/commonUI/general/res/sass/_animations.scss
- platform/commonUI/general/res/sass/_archetypes.scss
- platform/commonUI/general/res/sass/_icons.scss
- platform/commonUI/general/res/sass/_inspector.scss
- platform/commonUI/general/res/sass/_mixins.scss
- platform/commonUI/general/res/sass/_object-label.scss
- platform/commonUI/general/res/sass/_widgets.scss
- platform/commonUI/general/res/sass/controls/_controls.scss
- platform/commonUI/general/res/sass/controls/_messages.scss
- platform/commonUI/general/res/sass/features/_imagery.scss
- platform/commonUI/general/res/sass/forms/_channel-selector.scss
- platform/commonUI/general/res/sass/forms/_elems.scss
- platform/commonUI/general/res/sass/forms/_filter.scss
- platform/commonUI/general/res/sass/helpers/_wait-spinner.scss
- platform/commonUI/general/res/sass/items/_item.scss
- platform/commonUI/general/res/sass/mobile/_layout.scss
- platform/commonUI/general/res/sass/mobile/_tree.scss
- platform/commonUI/general/res/sass/overlay/_overlay.scss
- platform/commonUI/general/res/sass/plots/_plots-main.scss
- platform/commonUI/general/res/sass/search/_search.scss
- platform/commonUI/general/res/sass/user-environ/_frame.scss
- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/features/conductor/core/res/sass/_time-conductor-base.scss
- platform/features/conductor/core/res/sass/_time-of-interest.scss
- platform/features/timeline/res/sass/_timeline-thematic.scss
- platform/features/timeline/res/sass/_timelines.scss
Details of change and testing notes in #1891. This should be thoroughly Testathoned for regressions before releasing.
> Review SCSS refactoring for to-be-deprecated Bourbon functions

- circle.yml
- karma.conf.js
- openmct.js
- package.json
- platform/features/notebook/res/templates/annotation.html
- platform/features/notebook/src/actions/AnnotateSnapshot.js
- platform/representation/src/MCTInclude.js
- test-main.js
* Unit tests included and/or updated with changes? N/A No spec to update
> Painterro verification

- platform/commonUI/general/src/services/UrlService.js
Open in New Tab will preserve TC settings
> [TimeConductor] Fixes issue #1955

- platform/features/table/res/templates/telemetry-table.html
- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/src/controllers/TelemetryTableController.js
add dynamic name(object name) to exportAsCSV filename
> fixes issue #1999 - Use Object name as default export filename

- app.js
- index.html
- platform/commonUI/browse/bundle.js
- platform/commonUI/browse/src/PaneController.js
- platform/commonUI/general/bundle.js
- platform/commonUI/general/res/sass/_constants.scss
- platform/commonUI/general/res/sass/features/_imagery.scss
- platform/commonUI/general/res/sass/mobile/_layout.scss
- platform/commonUI/general/res/sass/startup-base.scss
- platform/commonUI/general/res/sass/user-environ/_layout.scss
- platform/commonUI/general/src/directives/MCTDrag.js
- platform/commonUI/general/test/directives/MCTDragSpec.js
- platform/commonUI/mobile/src/DeviceClassifier.js
- platform/features/conductor/core/res/sass/_time-conductor-base.scss
- platform/features/conductor/core/res/templates/time-conductor.html
- platform/features/timeline/res/sass/_timelines.scss
- platform/representation/src/gestures/ContextMenuGesture.js
> Review and integrate mobile-2008

- platform/commonUI/mobile/src/AgentService.js
> Recognize difference between android tablet and phones

- platform/commonUI/general/res/sass/user-environ/_frame.scss
- platform/features/notebook/res/templates/notebook.html
- platform/features/notebook/src/controllers/NotebookController.js
allows user to select caret position in notebook entries while in layout
> fixes issue 2041

- platform/commonUI/general/res/sass/user-environ/_frame.scss
[Frontend] Significant mods to fluid-layouts
- Restructure code to make better use of mixins;
- Added .fl-mobile-only selector;
- Simplified layout logic for column/row/wrap styles;
> Merge fluid-layouts-3 into hq-demo

- platform/commonUI/dialog/res/templates/message.html
- platform/commonUI/notification/src/NotificationService.js
- platform/entanglement/src/actions/AbstractComposeAction.js
- platform/entanglement/src/actions/CopyAction.js
- platform/entanglement/test/actions/CopyActionSpec.js
-Added timestamps to all notifications
-Added object name to copy success notification
-Fixes issue #331
> [Notifications] Added timestamp and object name to copy notifications

- platform/commonUI/formats/src/UTCTimeFormat.js
- platform/features/table/src/controllers/MCTTableController.js
- platform/features/table/src/controllers/TelemetryTableController.js
- platform/features/table/test/controllers/TelemetryTableControllerSpec.js
Fixes #2027. Also fixes assorted error messages in tables that have been reported as #1884 and #1817.
> Build columns from union of telemetry value metadata. 

- platform/features/listview/src/controllers/ListViewController.js
- platform/features/listview/test/controllers/ListViewControllerSpec.js
-List view data takes long time to display, has to do with the Angular digestive cycle not being triggered immediately when switching between views
-Resolved issue by explicitly triggering the digestive cycle
-Fixes issue #2067
> [Folder] List view load fix

- platform/features/conductor/core/bundle.js
- platform/features/conductor/core/src/ui/StringFormat.js
> Add a string formatter

- example/generator/GeneratorMetadataProvider.js
- karma.conf.js
- openmct.js
- package.json
- src/api/telemetry/TelemetryValueFormatter.js
- test-main.js
This is one last thing to take into consideration w.r.t. telemetry metadata: formatstring support.
The solution currently implemented here works, but I don't really like it.  Opening this as a placeholder for more thought.
> Basic sprintf support

- platform/commonUI/general/res/sass/search/_search.scss
> Fixes for main search input

- src/api/types/Type.js
- src/ui/components/controls/CreateButton.vue
Generate Create Menu Items using openmct.types
Todo:
1. Add click handler
2. Check how to select correct menu items
> Dynamically generate create menu items

- src/MCT.js
- src/plugins/notebook/res/templates/embed.html
- src/plugins/notebook/res/templates/entry.html
- src/plugins/notebook/res/templates/notebook.html
- src/plugins/notebook/src/actions/AnnotateSnapshot.js
- src/styles-new/_constants-snow.scss
- src/styles-new/_controls.scss
- src/styles-new/_global.scss
- src/styles-new/legacy-styles.scss
- src/styles-new/notebook.scss
- src/ui/components/controls/search.vue
> Notebook vue styling

- src/plugins/notebook/res/templates/notebook.html
- src/plugins/notebook/src/controllers/NotebookController.js
- src/plugins/telemetryTable/components/table.vue
- src/ui/components/controls/search.vue
Integrated into main layout already; added to table.vue and Notebook.
> Custom search input component integrated

- src/adapter/views/LegacyViewProvider.js
- src/plugins/summaryWidget/src/views/SummaryWidgetViewProvider.js
- src/ui/registries/ViewRegistry.js
Implements priority sorting for the new view selector
* Command line build passes? N/A
> Sort views by priority

- src/plugins/timeConductor/Conductor.vue
- src/plugins/timeConductor/ConductorAxis.vue
- src/styles-new/_constants-espresso.scss
- src/styles-new/_constants-snow.scss
- src/styles-new/_mixins.scss
Significant fixes in Conductor markup and styling:
- Restore RT update time field;
- Better mobile layout;
- Markup/CSS simplified and clearer;
- Better coloring in both Themes;
- Better separation for axis UI element in RT mode;
- Fixed hover and focus styles on inputs;
> Conductor fixes

- src/plugins/timeConductor/Conductor.vue
- src/plugins/timeConductor/ConductorAxis.vue
It fixes the conductor warnings.
> Fix code to remove warnings in conductor

- README.md
Update email address to match website, fix #2202 
2. Unit tests included and/or updated with changes? N/A, doc only change
> [readme] fix email address

- LICENSE.md
* Changes address original issue? N/A
* Changes have been smoke-tested? N/A
> Should say License instead of Licenses

- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/plugins/flexibleLayout/components/frame.vue
- src/plugins/flexibleLayout/plugin.js
- src/ui/components/utils/frameHeader.vue
- Object view now displays objects;
- FL frame header fixed;
- Fixed grippy look and positioning for now;
> Fixes for Flex Layout in TCR

- src/ui/components/controls/viewControl.vue
- src/ui/components/layout/tree-item.vue
- src/ui/components/toolbar/components/toggle-mixin.js
Working off some TODOs from TCR:
* [tree] fixes warning from viewControl about improper mutation in child component
* [tree] show links in tree
* [toolbar] close open menu when clicking on another menu.
> tree and toolbar fixes

- src/plugins/displayLayout/DisplayLayoutToolbar.js
- src/plugins/displayLayout/components/BoxView.vue
- src/plugins/displayLayout/components/DisplayLayout.vue
- src/plugins/displayLayout/components/ImageView.vue
- src/plugins/displayLayout/components/LineView.vue
- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/displayLayout/components/TextView.vue
- Add a toolbar button to toggle snap to grid for all views. 
- Add a listener for useGrid property on selection to update the layout item's coordinates and size depending on the useGrid value.
> [Display Layout] Snap to grid toolbar toggle button

- example/generator/plugin.js
- src/plugins/displayLayout/DisplayLayoutType.js
Also fixes state generator's form.
> [Display Layout] allow setting grid size in create dialog

- index.html
- src/plugins/timeConductor/Conductor.vue
- src/plugins/timeConductor/plugin.js
* Configuration will now be resolved immediately, meaning that time systems and clocks referenced in conductor configuration must be registered before conductor plugin is installed.
* Date picker only shown if time system is UTC based
* Improvements to conductor configuration validation messages
> Resolve conductor configuration immediately

- src/plugins/displayLayout/components/DisplayLayout.vue
Based on [feedback](https://github.com/nasa/openmct/pull/2287#pullrequestreview-203558393) in merged PR.
> Revert object duplication check 

- index.html
- package.json
- src/adapter/runs/LegacyTelemetryProvider.js
- src/plugins/telemetryTable/TelemetryTableRow.js
- src/styles-new/sass-base.scss
- src/ui/router/ApplicationRouter.js
- webpack.config.js
Addresses some problems in our built artifact that prevented it working with VISTA.
> VISTA compatibility issues

- platform/features/hyperlink/bundle.js
- platform/features/pages/bundle.js
- src/plugins/summaryWidget/plugin.js
Removed url validation from create dialogs
> remove url validation from summary widgets, webpage and hyperlink

- platform/commonUI/edit/src/creation/CreateAction.js
Fix issue where root is still in navigation path
> remove root from navigation

- src/ui/layout/Layout.vue
Fixed a regression where edit-views were not showing in the main layout view.
> Edit View - Regression Fix

- src/api/objects/ObjectAPI.js
- src/ui/inspector/Location.vue
> Inspector location

- platform/commonUI/edit/src/actions/SaveAsAction.js
Fixed conflict when saving new item
> save object before triggering mutate

- src/plugins/tabs/components/tabs.vue
- src/ui/inspector/Elements.vue
Fixes the following issues:
1. Tabs does not reorder when elements are reordered.
2. Elements pool does not update on remove
3. Tabs does not update when changes are discarded.
> Tabs view fixes plus elements pool

- platform/commonUI/dialog/src/OverlayService.js
> Revert "Force digest on compilation of overlay template"

- src/plugins/telemetryTable/components/table.vue
> Fix for Chrome 73 overflow bug effecting Telem Tables in Flex Layouts

- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/plugins/flexibleLayout/components/resizeHandle.vue
- src/plugins/flexibleLayout/toolbarProvider.js
- src/plugins/folderView/components/composition-loader.js
- src/plugins/plot/src/inspector/PlotOptionsController.js
- src/plugins/remove/RemoveAction.js
- src/ui/inspector/InspectorViews.vue
- src/ui/layout/BrowseBar.vue
Update flex layout to use remove action, which includes a new function to remove domainObject from parent and update selection to reflect parent
> Remove selection fix

- src/plugins/filters/components/FilterField.vue
- src/plugins/filters/components/FilterObject.vue
- src/ui/inspector/Elements.vue
Fixes 2 issues:
- Filter fields now updates without needing to refresh the page.
- Elements pool does not re-render every time a user clicks on the same object.
> Filters Field Does not update unless refreshed

- src/adapter/views/LegacyViewProvider.js
- src/styles-new/_legacy-plots.scss
* Adds the unsynched status to legacy plots 
* Restores missing legacy styles.
> Plot unsynched alert

- src/ui/layout/AboutDialog.vue
Slight markup change to support VISTA about dialog.
> Markup changes to support VISTA About Dialog

- src/styles-new/_mixins.scss
- src/ui/layout/Layout.vue
- src/ui/layout/mct-tree.vue
- Fix color issue for mobile menu icon, needed to fix VISTA bug;
- Fixed Chrome 73 overflow issue in main folder view;
- Better fixes for Chrome 73 overflow bug;
- Code cleanup;
> Misc Fixes 1

- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/flexibleLayout/components/flexibleLayout.vue
- src/ui/components/ObjectFrame.vue
- src/ui/layout/BrowseBar.vue
- src/ui/layout/Layout.vue
- src/ui/layout/pane.vue
- Fix table resizing issue in Flex Layouts;
- Fix alignment issue in c-so-view__headers;
- Better approach to title in layout frames;
- Removed unneeded !important attribs;
- Remove explicit height from shell status bar;
- Hide nav-to-parent button when editing
> Misc Fixes 2

- platform/import-export/src/actions/ImportAsJSONAction.js
Import works. Tested with nested object
> Fix import export

- package.json
- src/adapter/views/TypeInspectorViewProvider.js
- src/plugins/displayLayout/AlphanumericFormatViewProvider.js
- src/plugins/displayLayout/components/AlphanumericFormatView.vue
- src/plugins/displayLayout/components/DisplayLayout.vue
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/displayLayout/plugin.js
- src/plugins/telemetryTable/TableConfigurationViewProvider.js
- src/ui/inspector/InspectorViews.vue
- webpack.config.js
Display format input in the inspector when alphanumeric is selected in Display Layout. 
In case of multi-select, if alphanumerics have mixed format, display 'Mixed' in the input. If a non-alphanumeric item is in the selection, hide the format view in the inspector.
> Alpha-numeric printf format

- src/styles-new/_constants-espresso.scss
- src/styles-new/_constants-maelstrom.scss
- src/styles-new/_constants-snow.scss
- src/styles-new/_controls.scss
- src/styles-new/_status.scss
- Primarily needed by VISTA Data Products table UI;
- Adds new styling for inline links with icons;
- Adds new status colors in theme files;
> Status styling

- src/plugins/timeConductor/ConductorAxis.vue
- src/plugins/timeConductor/ConductorTimeSystem.vue
Implements JPL user request, whereby users would like the bounds of the time conductor to remain the same when switching between UTC based time systems
> Time conductor Improvement 625

- src/plugins/telemetryTable/components/table-cell.vue
- src/plugins/telemetryTable/components/table-row.vue
- src/plugins/telemetryTable/components/table.vue
> Move table cell selection to table cell component

- src/plugins/telemetryTable/components/table-cell.vue
- src/plugins/telemetryTable/components/table-row.vue
Restores table performance by removing unnecessary extra formatting.
> Removed unnecessary extra formatting

- src/plugins/telemetryTable/TelemetryTableViewProvider.js
> Enabled column reordering on table load

- src/plugins/telemetryTable/components/table.vue
> Fix Row marking

- src/plugins/clearData/components/globalClearIndicator.vue
- src/plugins/plot/src/telemetry/PlotController.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/TelemetryTableViewProvider.js
does not re-request historical data
> only clear data

- src/plugins/summaryWidget/src/Condition.js
> [Summary Widgets] Adding a new condition to a rule deletes the input value from previous ones #2411

- src/plugins/plot/res/templates/mct-plot.html
- src/plugins/plot/src/plot/MCTPlotController.js
> [Plot] Y axis label is not displayed when editing #2487

- src/ui/layout/BrowseBar.vue
> Save and Finish no longer shows blocking modal dialog #2496

- src/ui/layout/mct-tree.vue
Separate search div from main tree, show search div when search value is present, else show main tree
> Fixes issue #2484 - When searching, user looses context of main tree

- app.js
- openmct.js
- platform/commonUI/edit/src/actions/RemoveAction.js
- platform/persistence/queue/test/PersistenceFailureHandlerSpec.js
- src/MCT.js
- src/adapter/views/TypeInspectorViewProvider.js
- src/plugins/displayLayout/DisplayLayoutToolbar.js
- src/plugins/notebook/src/controllers/NotebookController.js
- src/plugins/objectMigration/Migrations.js
- src/plugins/summaryWidget/src/SummaryWidget.js
- src/ui/router/ApplicationRouter.js
The linter found errors violating rules: no-undef, no-unused-vars, no-newcap, and no-shadow. Modified the code as needed to resolve all issues.
Changes address original issue?
- linter now passes with no issues observed
Unit tests included and/or updated with changes?
- n/a
Command line build passes?
- yes
Changes have been smoke-tested?
- console observed for all changes without issue. Some functional testing performed to verify app functionality.
> Fix for remaining eslint errors

- src/plugins/plot/src/configuration/PlotSeries.js
- src/plugins/plot/src/telemetry/PlotController.js
> [Plots] Do not issue min-max queries for "markers only" plots #2468

- src/selection/Selection.js
**Overview**
- isSelectable check should be first to short circuit before variable instantiations
**Required by**
#2530 
#2472 
> Issue 2472 - add isSelectable short circuit

- src/api/overlays/components/OverlayComponent.vue
> Fix OverlayComponent template markup after lint merge mutilation

- API.md
- Unit tests included and/or updated with changes? N/A - documentation only
- Changes have been smoke-tested? N/A
> [refactor-doc] Updates the API doc for new API usage.

- README.md
Fixed the release number in the readme file. Oops.
* Unit tests included and/or updated with changes? N/A - documentation change only
> Correct release number

- API.md
> Fixes API link.

- src/plugins/condition/ConditionSetCompositionPolicy.js
- src/plugins/condition/plugin.js
> Addresses comments from PR: https://github.com/nasa/openmct/pull/2621

- src/plugins/condition/ConditionSetCompositionPolicy.js
- src/plugins/condition/ConditionSetCompositionPolicySpec.js
- src/plugins/condition/ConditionSetViewProvider.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
- src/plugins/condition/plugin.js
- src/plugins/condition/pluginSpec.js
- Change copyright to 2020
- Fix class parameters, tests
Author Checklist
> Addresses code review comments

- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/components/ConditionEdit.vue
- src/plugins/condition/components/ConditionSet.vue
- src/plugins/condition/components/CurrentOutput.vue
- src/plugins/condition/components/TestData.vue
- src/plugins/condition/components/condition.scss
> Revert "Condition reorder"

- src/plugins/telemetryTable/components/table.vue
emit event when rows are marked - useful for other components using telemetry tables.
> An improvement for components using telemetry tables

- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/ConditionSet.vue
- src/ui/inspector/Inspector.vue
Also made some changes to function and variable names for clarity. Fixed lint errors in Inspector.vue.
> Added persistance for changes to output selector

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetMetadataProvider.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
- src/plugins/condition/ConditionSetViewProvider.js
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/components/ConditionSet.vue
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
- src/plugins/condition/plugin.js
- src/ui/inspector/Inspector.vue
Addresses #2642
- provides telemetry based on latest condition->criteria data
- condition set output
- timestamp based on current timesystem
| | |
> [Conditions] Conditions to provide telemetry

- src/plugins/telemetryTable/TelemetryTableViewProvider.js
- src/plugins/telemetryTable/components/table.vue
Fixes needed for Multisession and the alternate control bar in general
> [Telemetry Tables] - Alternate control bar fixes

- src/plugins/telemetryTable/components/table.vue
- src/styles/_controls.scss
Since new telemetry tables were released, the auto-size functionality was gotten rid of. This re-implements it, via a user button for performance reasons. 
> Add a re-calculate column width button

- src/plugins/condition/components/TestData.vue
- src/plugins/condition/components/inspector/ConditionalStylesView.vue
Addresses lint errors/warnings
| | |
> [Conditions] linting fixes

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionManagerSpec.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/components/ConditionSet.vue
- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/components/inspector/ConditionalStyle.vue
- src/plugins/condition/components/inspector/ConditionalStylesView.vue
- src/plugins/condition/plugin.js
- src/plugins/condition/pluginSpec.js
Changes conditions to be plain objects and not domain objects
Removes condition domain object type
Resolves #2746
> Conditions refactor - not domain objects anymore

- src/plugins/condition/ConditionManager.js
Addresses #2750
| | |
| Unit tests included and/or updated with changes? | Y |
> [Conditions] Remove uneccessary update function

- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/utils/operations.js
Added summary description to each condition.
Resolves issue #2728
> Condition dynamic summary description based on criteria

- src/plugins/condition/components/ConditionSet.vue
Addresses orphaned code and linting fix.
| | |
> [Conditions] Condition Set cleanup

- src/plugins/condition/components/Criterion.vue
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
Ensures metadata with sources are also handled correctly
> Handles enum meta data for criteria

- src/plugins/condition/StyleRuleManager.js
> [Conditions] cleanup subscriptions in style rule manager

- src/plugins/condition/components/Criterion.vue
Added persist() on enum selector change.
Resolves #2787
> Criterion enum persist

- src/api/telemetry/TelemetryValueFormatter.js
> Adds formatting for strings

- index.html
> reverted to espresso

- src/plugins/condition/utils/operations.js
- src/plugins/condition/utils/operationsSpec.js
> Cast number inputs to a Number so that operations evaluate correctly

- src/plugins/displayLayout/DisplayLayoutToolbar.js
- src/plugins/displayLayout/components/AlphanumericFormatView.vue
- src/ui/components/ObjectView.vue
Fixes some application breaking errors. 
Fixes issue #2716 and #2798 
> [Toolbar] fix errors when navigated away from a layout that uses toolbar

- src/plugins/notebook/components/notebook-entry.vue
- src/plugins/notebook/components/notebook.vue
> [Notebook] [V2.0]: focus on newly added entry #2819

- src/plugins/notebook/components/notebook-embed.vue
- src/plugins/notebook/utils/notebook-entries.js
- src/ui/preview/Preview.vue
pass correct object path, and remove notebook snapshot button from preview window
Fixes #2842
> [Notebook] Embed preview action fix

- src/plugins/notebook/components/notebook.vue
> [Notebook]: Error in nextTick: "TypeError: Cannot read property 'focus' of null" #2845

- src/plugins/notebook/components/notebook.vue
- src/plugins/notebook/utils/notebook-storage.js
> [Notebook]: When notebook is not default new entry button does not add new entry #2841

- src/ui/inspector/Inspector.vue
> Disables conditional and static styles for hyperlinks and summary widgets

- src/plugins/condition/utils/operations.js
- src/plugins/condition/utils/operationsSpec.js
Adds check for undefined
Resolves #2881
Also checks for undefined for is one of and is not one of operations.
> Fixes enum comparisons

- src/plugins/condition/components/Condition.vue
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/condition/components/conditionals.scss
> Revert "Condition improve reorder"

- src/plugins/condition/ConditionManager.js
Resolves #2927 
Resolves #2897
> Remove telemetry from criteria when not editing a condition set

- index.html
I have updated the year in the copyright text.
* Changes address original issue? N/A - One off change to demonstrate PR process
* Unit tests included and/or updated with changes? N/A - Small change to comment in HTML file does not warrant new unit tests
> Updated year in index.html

- src/ui/layout/BrowseBar.vue
> Fixes #2713 Inline Edit bug

- src/plugins/condition/criterion/AllTelemetryCriterion.js
addendum to #2967
- remove unnecessary if check
- remove unnecessary adding of id prop to datum object
| | |
> [Conditionals] addendum to #2967

- src/ui/inspector/Inspector.vue
> Show the Styles tab for non creatable layout objects including condition sets

- src/plugins/condition/utils/operations.js
> Use only the values required for description

- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
Addresses
- Handling for historical requests that are non-existent
- Handling for historical requests for realtime only telemetry endpoints
| | |
> [Conditionals] Handling for empty requests in vista-r4.4-rc6

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetMetadataProvider.js
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
Addresses
- data is normalized on historical requests
- do not pass unnecessary telemetry object data in options to telemetry requests
- change output metadata to state (enum) and value (string)
| | |
> [Conditionals] evaluation fixes

- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
Addresses
- Handling for historical requests that are non-existent
- Handling for historical requests for realtime only telemetry endpoints
| | |
> [Conditionals] Handling for empty requests

- src/plugins/notebook/components/notebook-entry.vue
> [Notebook] Entries and Embeds need to use the same timesystem #2920

- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/components/inspector/ConditionalStylesView.vue
- src/plugins/condition/components/inspector/conditional-styles.scss
- src/plugins/displayLayout/mixins/objectStyles-mixin.js
- src/ui/components/ObjectView.vue
In edit mode
- Apply selected condition's styles
- Do not evaluate conditional styles 
- If no condition is highlighted, fallback on default style
In view mode
- Highlight evaluated condition in styles inspector
Resolves #2646 
> Preview condition styles on selecting that condition or one of it's styles

- src/plugins/notebook/components/notebook.vue
> [Notebook] : Error in event handler for "updateSection": "TypeError: Cannot read property 'id' of undefined" #2921

- src/plugins/notebook/components/notebook-menu-switcher.vue
- src/plugins/plot/res/templates/stacked-plot.html
- src/plugins/plot/src/services/ExportImageService.js
- src/plugins/telemetryTable/components/table.scss
- src/styles/_controls.scss
- src/styles/_legacy-plots.scss
- src/styles/_legacy.scss
- src/styles/notebook.scss
- src/ui/components/ObjectFrame.vue
- src/ui/components/object-frame.scss
- src/ui/layout/BrowseBar.vue
- src/ui/preview/Preview.vue
- src/ui/preview/preview-header.vue
> [Notebook] Save snapshot dropdown should be available from "view large" overlay #2922

- src/plugins/plot/src/plot/MCTPlotController.js
> Fixes marquee issue when user leaves window while mouse is still down

- src/plugins/plot/src/plot/MCTPlotController.js
> Fixes plot end marquee and lock highlight issue

- src/plugins/tabs/components/tabs.vue
- src/plugins/tabs/plugin.js
Allow users to lazy load tabs and store current tab position on domainObject
> Tabs 4.4.1 Lazy Load

- src/plugins/telemetryTable/collections/FilteredTableRowCollection.js
- src/plugins/telemetryTable/components/table.vue
- src/ui/components/search.scss
- src/ui/components/search.vue
Introduce regex search in R4.4.1
> Regex search 4.4.1

- src/ui/preview/Preview.vue
> Show object styles in preview modal

- src/plugins/plot/src/plot/MCTPlotController.js
> [Plots] Prevent plots from requesting new data when a user clicks on the plot

- example/generator/GeneratorMetadataProvider.js
Addresses #3053 
Testing Instructions in #3053
| | |
> Provide format for State Generator name metadata

- CONTRIBUTING.md
- src/ui/preview/Preview.vue
Provides additional information about pull requests to our contributing guide. Addresses #3021 
2. Unit tests included and/or updated with changes? N/A - No code change
4. Changes have been smoke-tested? N/A - No code change
5. Testing instructions included? N/A - No code change
> Add details about pull requests to contributing guide

- src/plugins/timeConductor/ConductorAxis.vue
> [Time conductor] Ensure axis zoom works after window resize

- API.md
> Revert "Update API.md"

- CONTRIBUTING.md
Fixes https://github.com/nasa/openmct/issues/3081
2. Unit tests included and/or updated with changes? N/A documentation changes only
4. Changes have been smoke-tested? N/A documentation changes only
5. Testing instructions included? N/A documentation changes only
> Tweaked code standards for ternaries and return statements

- src/plugins/imagery/components/ImageryViewLayout.vue
Previously if time bounds were set to a future date the code was looking for an "undefined" image name which threw an error in the console. Also, if you pressed pause in future time bounds (no images) an error would be thrown. Added some checks to make sure there's an image to work with.
Closes #3103 
Unit tests included and/or updated with changes? No, probably should have some
> Imagery Bug Fixes (Future Date Issues)

- src/plugins/plot/src/chart/MCTChartController.js
- src/plugins/plot/src/configuration/Collection.js
- src/plugins/plot/src/draw/Draw2D.js
- src/plugins/plot/src/draw/DrawWebGL.js
- src/plugins/plot/src/inspector/PlotOptionsController.js
- src/plugins/plot/src/inspector/PlotYAxisFormController.js
- src/plugins/plot/src/telemetry/StackedPlotController.js
Addresses #3105
- fix y-axis ticks overlapping y-axis labels
- fix y-axis tick jumpiness
- remove unused lodash imports
| | |
| Unit tests included and/or updated with changes? | N/A bug fix |
> [Plots] y-axis width fix

- LICENSE.md
- src/plugins/displayLayout/DisplayLayoutToolbar.js
- src/plugins/displayLayout/components/DisplayLayout.vue
Fixes issues found during testathon on 06/22/2020. #2973 
> Display layout fixes 062320

- src/plugins/newFolderAction/newFolderAction.js
> Added unnamed folder and made it required

- src/plugins/displayLayout/components/DisplayLayout.vue
This PR fixes #3142 
Tested on VISTA with dictionary items and it works. Need to test on Hulk
> Fix for non working switch from alpha to tables and plots

- src/plugins/displayLayout/components/DisplayLayout.vue
This issue fixes a critical issue #3161 
> Fixes issue created when removing Lodash function

- package.json
Upgrading Painterro to an official 1+ release. There have been various bug fixes and improvement. 2 of which fix currently reported bugs in our repository:
Fixes #3170 and fixes #3171 
> upgrade Painterro to 1.00.35

- src/plugins/tabs/README.md
- src/plugins/tabs/components/tabs.vue
- src/plugins/tabs/tabs.js
- src/ui/components/ObjectView.vue
This PR fixes the following issues:
#3155 and #3014
> [Tabs View] Fixes for VISTA + Open MCT

- src/plugins/folderView/components/GridItem.vue
- src/plugins/folderView/components/ListItem.vue
- src/plugins/plot/res/templates/mct-plot.html
Visual indication for domain objects that are missing due to a change in a data dictionary or other reason. This PR is a followup to #3125 after finding a few issues. Testing notes are in #3179. 
- Fixed Folder grid and list views;
- Fixed plot collapsed and expanded legends;
> Missing items addendum 1

- src/api/telemetry/TelemetryAPI.js
- src/api/telemetry/TelemetryAPISpec.js
- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/components/inspector/ConditionalStylesView.vue
- src/plugins/condition/components/inspector/StylesView.vue
Fixes https://github.com/nasa/openmct/issues/3203
2. Unit tests included and/or updated with changes? Y - Added regression test for Telemetry API
> Data dropout fixes

- webpack.config.js
Reduces size of import and removes erroneous vue warnings.
> Use minified Vue for production

- src/plugins/telemetryTable/TelemetryTableRow.js
- src/plugins/telemetryTable/components/table-row.vue
Addresses #3231 
| | |
| Unit tests included and/or updated with changes? | N |
> [Tables] Allow table row to control object path for context menu actions

- src/plugins/condition/criterion/TelemetryCriterion.js
Fix for VISTA for #3102
2. Unit tests included and/or updated with changes? No
>  Compare the enum value to the input, not the index of the enumeration

- src/plugins/telemetryTable/collections/FilteredTableRowCollection.js
- src/plugins/telemetryTable/components/table.vue
- src/ui/components/search.scss
- src/ui/components/search.vue
Porting the Regex search feature to V1.2
> port regex change to R4.5

- src/plugins/plot/res/templates/mct-plot.html
- src/plugins/plot/src/chart/MCTChartController.js
- src/plugins/plot/src/configuration/PlotSeries.js
- src/plugins/plot/src/configuration/XAxisModel.js
- src/plugins/plot/src/plot/MCTPlotController.js
- src/plugins/plot/src/plot/MCTTicksController.js
- src/plugins/plot/src/telemetry/PlotController.js
- src/styles/_legacy-plots.scss
> [Plots] Allow changing x-axis metadata for release candidate

- src/plugins/plot/src/plot/MCTPlotController.js
Addresses #3279
see #3167 
| | |
> [Plots] fix x axis options check

- package.json
Updating version number for the sprint as per Open MCT versioning process.
5. Testing instructions included? N/A
> Version 1.3.0 snapshot

- src/api/objects/RootObjectProvider.js
- src/ui/layout/mct-tree.vue
Small fixes for new tree refactor.
closes #3317
> Minor fixes for tree refactor (backwards compatibility, multi/single root handling)

- src/plugins/timeConductor/Conductor.vue
Addresses #3346  
see #3346
| | |
> [v1.2-Release-Candidates] Zoom operation should update bounds

- src/plugins/timeConductor/Conductor.vue
Addresses #3344 
see #3344 
| | |
> [Time Conductor] Zoom operation should update bounds

- src/plugins/plot/res/templates/mct-plot.html
- src/plugins/plot/src/plot/MCTPlotController.js
- src/plugins/plot/src/telemetry/PlotController.js
Addresses #3348 in `branch: v1.2-Release-Candidates`
see #3348
| | |
> [Plots] fixes to switch x-axis metadata for release branch

- app.js
- src/MCT.js
- src/adapter/actions/LegacyActionAdapter.js
- src/api/actions/ActionCollection.js
- src/api/actions/ActionsAPI.js
- src/api/menu/MenuAPI.js
- src/api/menu/components/Menu.vue
- src/plugins/clearData/clearDataAction.js
- src/plugins/clearData/plugin.js
- src/plugins/goToOriginalAction/plugin.js
- src/plugins/newFolderAction/plugin.js
- src/plugins/notebook/components/notebook-menu-switcher.vue
- src/plugins/remove/plugin.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/TelemetryTableViewProvider.js
- src/plugins/telemetryTable/ViewActions.js
- src/plugins/telemetryTable/components/table.vue
- src/plugins/telemetryTable/plugin.js
- src/ui/components/ObjectFrame.vue
- src/ui/layout/BrowseBar.vue
- src/ui/layout/Layout.vue
- src/ui/mixins/context-menu-gesture.js
- src/ui/preview/plugin.js
> 3 dot menu refactor

- src/adapter/services/LegacyPersistenceAdapter.js
Fixes NIRVSSOMCT-216
Unit tests included and/or updated with changes? No - this is legacy code?
> [NIRVSSOMCT-216] Legacy read object should correctly return the model and not a promise

- platform/search/bundle.js
- platform/search/src/services/GenericSearchProvider.js
- src/ui/layout/mct-tree.scss
- src/ui/layout/mct-tree.vue
Added the objectService to the GenericSearchProvider to handle cases where the wrong provider was being used to get the object/model. Also small refactor to the navigation tree to handle search more appropriately (searching indicator, clearing children, etc).
closes #3399 
Unit tests included and/or updated with changes? N/A Legacy
> [Search] SearchProvider and Tree Search enhancements/fixes

- src/plugins/displayLayout/AlphanumericFormatViewProvider.js
- src/plugins/displayLayout/actions/CopyToClipboardAction.js
- src/plugins/displayLayout/components/AlphanumericFormatView.vue
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/displayLayout/plugin.js
- src/plugins/notebook/actions/CopyToNotebookAction.js
- src/plugins/notebook/plugin.js
- src/plugins/notebook/snapshot.js
- src/plugins/notebook/utils/notebook-entries.js
- src/utils/clipboard.js
[Notebook] Copy label and value from alphanumeric in Layout directly to a Notebook entry #3299 
- merge branch [three-dot-menu-proto](https://github.com/nasa/openmct/tree/three-dot-menu-proto)
- based of branch [three-dot-menu-proto](https://github.com/nasa/openmct/tree/three-dot-menu-proto)
Check | Passed
-- | --
> Alphanumeric notebook entry

- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
Fixes https://github.com/nasa/openmct/issues/3436
> Cache gets

- src/api/objects/ObjectAPISpec.js
Resolves #3446 
Testing instructions included? N/A
> Move tests to their own describe block

- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
> Duplicate tree ancestors fix

- src/ui/layout/mct-tree.scss
- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
Simplified tree code, removed a lot of timeouts and $nextTicks, consolidated navigation of the tree into one method that can track and cancel if new tree nav requests come in, changed some variable names for clarity, simplified logic.
closes #3439
closes #3455
closes #3438
closes #3384
> [Navigation Tree] Simplify logic

- example/generator/GeneratorProvider.js
- example/generator/generatorWorker.js
- src/plugins/telemetryTable/TelemetryTable.js
- src/plugins/telemetryTable/TelemetryTableNameColumn.js
- src/plugins/telemetryTable/pluginSpec.js
> [Tables] Object names should appear in tables

- src/plugins/notebook/components/NotebookMenuSwitcher.vue
resolves: #3530
Check | Passed
-- | --
> [Notebook] can not add snapshots to default notebook

- src/plugins/notebook/components/NotebookEmbed.vue
- src/plugins/notebook/components/NotebookMenuSwitcher.vue
- src/plugins/notebook/utils/notebook-storage.js
resolves: #3533 Unable to take a snapshot - snapshot dropdown not working
resolves: #3534 Unable to edit Notebooks (Firefox)
resolves: #3538 Navigating to a Notebook snapshot not working
Check | Passed
-- | --
> Notebook localstorage issue

- src/plugins/telemetryTable/ViewActions.js
- src/plugins/telemetryTable/components/table.vue
This PR fixes #3556 
Testing instructions included? Yes, see issue
> Fixes Export marked rows as CSV

- src/plugins/plot/src/services/ExportImageService.js
This PR fixes #3564 
Unit tests included and/or updated with changes? N/A Legacy code
Testing instructions included? Yes in Issue
> Replace dots with underscores in save as filenames

- src/ui/components/object-frame.scss
resolves: #3566 [Notebook] snapshots on plots are empty
Check | Passed
-- | --
> [Notebook] snapshots on plots are empty

- src/selection/Selection.js
Fixes #3572 
Testing instructions included? Yes in issue
> Update Selection only if selectable item has changed

- src/plugins/notebook/components/NotebookEmbed.vue
resolves: #3538 Navigating to a Notebook snapshot not working 
Check | Passed
-- | --
> Navigating to a Notebook snapshot not working #3538

- index.html
> [Conductor] Remove 24 hour default limit in time conductor

- src/plugins/plot/src/telemetry/StackedPlotController.js
- src/styles/_legacy-plots.scss
Closes #3584 
Unit tests included and/or updated with changes? N/A Legacy code
Testing instructions included? Yes, in issue
> [Stacked plots] fixes scroll issue and removed redundant calls to backend

- src/plugins/condition/pluginSpec.js
- src/plugins/notebook/snapshot.js
- src/plugins/timeline/pluginSpec.js
resolves: #3426
Check | Passed
-- | --
> [Testing] Error while running npm test

- src/plugins/notebook/components/NotebookEmbed.vue
resolves: #3445
Check | Passed
-- | --
> [Notebook] Link to snapshot should not be a fully qualified url #3445

- src/plugins/displayLayout/components/TelemetryView.vue
resolves: #3574
Check | Passed
-- | --
> Problem copying unit less telemetry values to notebook

- src/plugins/notebook/pluginSpec.js
resolves: #3463 [Testing] [Notebook] fix failing notebook tests from three-dot-menu-proto 
Check | Passed
-- | --
> [Testing] [Notebook] fix failing notebook tests from three-dot-menu-proto

- src/plugins/telemetryTable/TelemetryTableRow.js
resolves: #3613
Check | Passed
-- | --
> [openmct-YAMCS] TelemetryTableRow refactor createNormalizedDatum to include extra datum

- src/plugins/notebook/components/Notebook.vue
- src/plugins/notebook/components/NotebookMenuSwitcher.vue
- src/plugins/notebook/utils/notebook-entriesSpec.js
- src/plugins/notebook/utils/notebook-storage.js
- src/plugins/notebook/utils/notebook-storageSpec.js
> [Notebook] Do not persist notebook objects in notebook Local Storage

- src/ui/components/ObjectLabel.vue
- src/ui/layout/tree-item.vue
> Revert "[Navigation Tree] Whole tree item clickable"

- src/ui/preview/preview-header.vue
Fixes #3628; testing notes in that issue.
> Fix for changed approach to 'type' object

- package.json
1. Changes address original issue? N/A
4. Changes have been smoke-tested? N/A
5. Testing instructions included? N/A
> Changing master to 1.6.1-SNAPSHOT

- src/ui/components/ObjectLabel.vue
- src/ui/inspector/styles/FontStyleEditor.vue
- src/ui/layout/tree-item.vue
This PR fixes #3644 
Testing instructions included? In Issue
> Fix tree click preview in edit mode

- src/plugins/timeConductor/Conductor.vue
- src/plugins/timeConductor/conductor-mode-icon.scss
Some modest performance improvements to the time conductor. Throttles updates to both the clock animation, and the current time display. This results in a slightly less smooth experience for users.
> Conductor performance improvements

- src/api/notifications/NotificationAPISpec.js
Adding tests for the Notification API
> Notification api tests

- src/ui/components/ObjectLabel.vue
This PR fixes #3667 
5. Testing instructions included? Yes in Issue
> Fix Preview when in edit mode

- src/plugins/tabs/components/tabs.vue
- src/plugins/tabs/plugin.js
This PR fixes the following issues:
Fixes #3672 
Fixes #3673 
Testing instructions included? Yes in issues
> Improve Tab lazy loading logic and fix delete tab issue

- src/plugins/flexibleLayout/components/flexibleLayout.vue
This PR fixes #3679 
Testing instructions included? Yes in issue
> Fixes [Flexible Layout] bug with composition

- src/api/notifications/NotificationAPI.js
- src/plugins/notebook/components/Notebook.vue
- src/plugins/notebook/snapshot.js
- src/plugins/notebook/utils/notebook-storage.js
- src/ui/layout/status-bar/NotificationBanner.vue
~~- [x] merge `notebook-refactor` branch first PR: https://github.com/nasa/openmct/pull/2883~~
~~- [x] @charlesh88 Need to add style for `click to view`~~
Check | Passed
-- | --
Changes address original issue? | Y 
Unit tests included and/or updated with changes? | N/A 
Testing instructions included? | Y (Check original issue  #2860)
> Notebook saved link

- src/ui/layout/mct-tree.vue
Fixes #3648 
Testing instructions included? Yes, in issue
> Remove path from LOCAL_STORAGE

- src/plugins/persistence/couch/CouchObjectProvider.js
Adds the stream: option to TextDecoder.decode and stitch the decoded strings together for the final JSON object.
Resolves: #3700
> Handled chunked response from CouchDB for search results

- src/plugins/imagery/components/Compass/CompassRose.vue
Addresses #3706 
see #3706 
| | |
> [Imagery View] Do not show sun in compass rose if sun heading is undefined

- src/api/actions/ActionCollectionSpec.js
- src/api/objects/ObjectAPI.js
- src/plugins/CouchDBSearchFolder/plugin.js
- src/plugins/CouchDBSearchFolder/pluginSpec.js
- src/plugins/imagery/components/ImageryViewLayout.vue
- src/plugins/notebook/utils/notebook-storageSpec.js
- src/plugins/plan/Plan.vue
Use mutable object for plans so that they can sync when included in other object's composition
Also, Allow the name of couch search folder to be configurable
Resolves #3711 
2. Unit tests included and/or updated with changes?N/A
> Use mutable object for plans

- src/plugins/plan/Plan.vue
- src/ui/components/swim-lane/swimlane.scss
Very simple visual fix to make "no activities" messaging more visible.
> Tweak plan view

- src/plugins/plan/Plan.vue
Change method name from validateJSON to getPlanData.
> Fix method name in Plan.vue

- src/plugins/plan/util.js
> Accept plans from a file OR from JSON object (couchDB)

- src/plugins/imagery/components/ImageryViewLayout.vue
Check | Passed
-- | --
Unit tests included and/or updated with changes? | No
closes #3731
> [Imagery Freshness] Making sure all telemetry for an indicator is fresh

- src/ui/layout/BrowseBar.vue
> Force Vue to look for the reactive property and recompute views

- src/adapter/actions/ActionDialogDecorator.js
> Pass object path when getting views during object creation

- src/plugins/imagery/components/Compass/Compass.vue
- src/plugins/imagery/components/Compass/CompassHUD.vue
- src/plugins/imagery/components/Compass/CompassRose.vue
- src/plugins/imagery/components/Compass/utils.js
- src/plugins/imagery/components/ImageryViewLayout.vue
- src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js
Addresses #3748 
see #3748 
| | |
> [Imagery] Update to be compatible with VIPER

- src/plugins/flexibleLayout/pluginSpec.js
- src/plugins/tabs/components/tabs.vue
- src/plugins/tabs/pluginSpec.js
5. Testing instructions included? N/A
> Tests for flexible layouts and tabs views

- platform/import-export/src/actions/ImportAsJSONAction.js
If value is null, don't process it.
Resolves #3737 
> Fix importing from JSON file where some property values are null

- src/plugins/displayLayout/components/SubobjectView.vue
- src/plugins/displayLayout/components/TelemetryView.vue
> Check if an object is mutable before destroying the mutable

- API.md
- example/imagery/plugin.js
- src/plugins/imagery/components/ImageryViewLayout.vue
NIRVSS issue 
Check | Passed
-- | --
> [NIRVSS] Encode imagery metadata into image file names

- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSetTelemetryProvider.js
- src/plugins/condition/StyleRuleManager.js
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/displayLayout/components/TelemetryView.vue
Resolves #3851
2. Unit tests included and/or updated with changes? N
> Update telemetry views in fixed timespan mode if the datum's timestamp is valid

- src/ui/layout/mct-tree.vue
> [Navigation Tree] Fix composition on close folders and scrolling for items NOT in tree 1.7.3

- package.json
Please ensure this PR is merged first: https://github.com/nasa/openmct/pull/3924
> Prepare master for Sprint 1.7.4

- src/ui/components/ObjectView.vue
- src/ui/inspector/Inspector.vue
Fixes #3949 
* [ x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ x] Changes address original issue?
* [ N/A] Unit tests included and/or updated with changes?
* [ x] Command line build passes?
* [ x] Has this been smoke tested?
* [ x] Testing instructions included in associated issue?
> [Style] check if there is an element to style before applying style

- src/plugins/plot/MctPlot.vue
Fixes #3847 
Pause and play is also not available in time strip view now.
> Disallow pause and play in time strip view for plots.

- src/ui/preview/preview-header.vue
> actionCollection update event looping when open View Large in Display layout

- src/plugins/condition/ConditionManager.js
> Don't save condition set description and testData unless there is a change

- platform/features/clock/bundle.js
- platform/features/clock/test/controllers/TimerControllerSpec.js
- src/plugins/notebook/components/NotebookEmbed.vue
- src/plugins/notebook/components/NotebookSnapshotContainer.vue
- src/plugins/notebook/components/snapshot-template.html
- src/plugins/timeConductor/conductor.scss
- src/styles/_constants-espresso.scss
- src/styles/_constants-maelstrom.scss
- src/styles/_constants-snow.scss
- src/styles/_controls.scss
- src/styles/notebook.scss
- src/ui/inspector/ObjectName.vue
- src/ui/layout/mct-tree.scss
- src/ui/layout/mct-tree.vue
Fixed #3909. If possible, this is a nice to have for the CDA demo.
* N/A: Unit tests included and/or updated with changes?
> UI fixes 3909

- src/plugins/URLTimeSettingsSynchronizer/URLTimeSettingsSynchronizer.js
- src/plugins/plan/pluginSpec.js
- src/plugins/plot/pluginSpec.js
- src/plugins/telemetryTable/pluginSpec.js
- src/ui/router/ApplicationRouterSpec.js
Fixes: https://github.com/nasa/openmct/issues/3921
* [N/A] Unit tests included and/or updated with changes?
* [N/A] Testing instructions included in associated issue?
This is a new PR for #3938. This branch is created from 1.7.4-stable instead of master.
> new PR for fixing local time mode based on 1.7.4-stable

- example/imagery/plugin.js
> added mock values to compass for example imagery.

- src/plugins/plot/pluginSpec.js
This temporarily disables a broken test to be fixed in https://github.com/nasa/openmct/pull/3973
> Temporarily skip a test in chrome

- example/imagery/plugin.js
- src/plugins/plugins.js
> Configurable example imagery 1.7.4 stable

- src/plugins/timeConductor/Conductor.vue
Check | Passed
-- | --
Testing instructions included? | N/A
Testing instructions are included in #4017
> Prevent default on click events for conductor delta buttons

- src/adapter/runs/LegacyTelemetryProvider.js
> [Telemetry API] wrap limits function return in promise if needed

- package.json
> Prepare for sprint 1.7.6

- .github/ISSUE_TEMPLATE/bug_report.md
> Fix typo in template

- .github/ISSUE_TEMPLATE/config.yml
Allows blank issues to be created.
> Not everything fits into the two types of issue templates available

- src/plugins/persistence/couch/CouchObjectProvider.js
> Check for observing changes before asking it to stop

- src/plugins/hyperlink/HyperlinkProvider.js
- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/plot/MctPlot.vue
- src/ui/preview/preview-header.vue
> 1.7.6 master merge

- package.json
> Prepare for sprint 1.7.7

- src/api/overlays/components/OverlayComponent.vue
- src/plugins/notebook/components/NotebookMenuSwitcher.vue
- src/ui/components/ObjectFrame.vue
- src/ui/layout/Layout.vue
- src/ui/preview/Preview.vue
> [Notebook] Create Snapshot directly from any frame in a layout #3300

- src/plugins/notebook/utils/notebook-storage.js
> Notebook doesn't display interface after creation #4144

- .github/workflows/codeql-analysis.yml
resolves https://github.com/nasa/openmct/issues/4162
> Add automated security scanning to our repo

- src/plugins/plot/plugin.js
- src/plugins/plot/pluginSpec.js
Resolves #4100 
Work remaining:
> Adds new types for spectral plots and spectral aggregate plots

- src/plugins/plot/MctPlot.vue
> Fixes resizing handler error - adds null check

- src/plugins/plot/pluginSpec.js
> added some basic tests

- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/timeline/TimelineObjectView.vue
Resolves #4240 
Resolves #4236
> Fix import

- src/plugins/telemetryTable/components/table.vue
All in the title.
closes #4239
> [Telemetry Tables] No progress bar on empty tables

- src/plugins/notebook/components/NotebookEmbed.vue
> snapshot clicked while in edit mode should open in preview mode

- src/plugins/telemetryTable/components/table.vue
- src/plugins/telemetryTable/pluginSpec.js
Closes: #4248
Tests for new progress loading bar in telemetry tables.
> [Telemetry Table] Progress bar tests

- src/styles/_legacy-plots.scss
- src/styles/plotly.scss
Resolves part of #4177
- Cleaned up commenting;
- Removed suppression of 0 line;
> Fix Bar Graph related CSS

- src/plugins/timeConductor/ConductorAxis.vue
- src/plugins/timeConductor/ConductorInputsFixed.vue
> Duplicate Request Fixes

- package.json
- platform/commonUI/edit/src/actions/SaveAsAction.js
- src/plugins/folderView/components/grid-view.scss
> 1.8.0 merge into master

- package.json
> Prep version for sprint 1.8.1

- .github/ISSUE_TEMPLATE/config.yml
- SECURITY.md
Fixes https://github.com/nasa/openmct/issues/4448
> Fix security policy typo, and duplicate security issue template entries

- index.html
- src/api/objects/ObjectAPI.js
- src/api/objects/Transaction.js
- src/plugins/notebook/plugin.js
- src/plugins/notebook/utils/notebook-migration.js
- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/persistence/couch/pluginSpec.js
resolves: #4385, issues mentioned in testathon for #4089
> Transaction fix

- src/plugins/myItems/myItemsInterceptor.js
> [MyItems Plugin] Save My Items object if missing

- src/ui/layout/mct-tree.vue
> Changed descending to ascending in sort order method

- src/plugins/LADTable/components/LADRow.vue
- src/plugins/myItems/myItemsInterceptor.js
Fixes https://github.com/nasa/openmct/issues/3323
> Fixes LAD rows for string telemetry

- karma.conf.js
- platform/import-export/src/actions/ImportAsJSONAction.js
- platform/import-export/test/actions/ImportAsJSONActionSpec.js
> imported objects are not persisting 

- src/api/objects/TransactionSpec.js
- src/plugins/importFromJSONAction/ImportFromJSONActionSpec.js
> transaction changes test fix

- src/api/time/IndependentTimeContext.js
- src/plugins/timeConductor/DatePicker.vue
- src/plugins/timeConductor/independent/Mode.vue
Resolves: #4226  
https://github.com/nasa/openmct/issues/4226#issuecomment-992986844
https://github.com/nasa/openmct/issues/4226#issuecomment-992988384
> Various Independent time conductor bug fixes

- platform/telemetry/src/TelemetryCapability.js
- platform/telemetry/test/TelemetryCapabilitySpec.js
- src/api/telemetry/TelemetryAPI.js
- src/api/telemetry/TelemetryAPISpec.js
> [OpenMCT Tutorial] Using only Realtime (no historical data) telemetry issue #3641

- e2e/playwright-visual.config.js
- e2e/tests/visual/default.spec.js
Addresses: https://github.com/nasa/openmct/issues/4623
> Condition set visual test

- e2e/tests/visual/default.spec.js
> Add Condition Widget visual test

- app.js
- karma.conf.js
- package.json
- src/MCT.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
> separate webpack dev prod configs.

- .circleci/config.yml
> Actually install the correct version of node

- src/plugins/move/MoveAction.js
> Move action issue fix #4663

- .github/ISSUE_TEMPLATE/bug_report.md
Quick issue template change to make the checklist more explicit
> Update Bug Report format to make visual bug distinction clearer

- e2e/playwright-ci.config.js
- e2e/playwright-local.config.js
- src/plugins/summaryWidget/SummaryWidgetsCompositionPolicy.js
Fixes: https://github.com/nasa/openmct/issues/4666 and https://github.com/nasa/openmct/issues/4674
@scottbell @shefalijoshi after this is merged into master, we should cherrypick this back into 1.8.3?
> Unable to create domain objects

- src/plugins/imagery/components/ImageryTimeView.vue
- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/mixins/imageryData.js
> Mct 4555 rebased v3

- src/plugins/notebook/snapshot.js
> Notebook cross domain links

- codecov.yml
- karma.conf.js
- src/tools/url.js
- src/tools/urlSpec.js
> Exclude Spec files from CodeCov - mct4563

- package.json
Set correct version for release
> Remove snapshot from release version

- package.json
> Update version for sprint

- .github/workflows/e2e-pr.yml
- .github/workflows/e2e-visual.yml
- e2e/.percy.yml
- e2e/playwright-ci.config.js
- e2e/playwright-local.config.js
- package.json
Fixes: #4694 
Note: percy has a limitation of 2000 pixels in either dimension
> [e2e] Update Playwright config to include MMOC and Ipad

- README.md
> [Docs] Include note about node version support in the intro install guide

- package.json
More information here https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
Note: this only affects our docsite generator
> Address marked Security Vulnerability

- package.json
> Prepare for sprint 1.8.5

- .github/dependabot.yml
- .github/workflows/prcop-config.json
Closes: 
Missed the dependabot label for npm packages. With this change, PRs opened by dependabot with npm package changes will include this label which will disable PRCop checks
> [CI]Update dependabot rules again

- .github/PULL_REQUEST_TEMPLATE.md
Closes: #4154 
Updating the template while using the old template with the colon to verify whether this is a bug with discovery,linking, or closure of issues with the github api.
> [CI] Update PR Template to remove the colon from Closes

- .github/PULL_REQUEST_TEMPLATE.md
Just adds some additional text to the 'Closes' hidden text with a warning about Release branches
> [Docs] Update PR Template warning

- src/plugins/plot/MctPlot.vue
- src/plugins/timeConductor/ConductorInputsFixed.vue
- src/plugins/timeConductor/ConductorInputsRealtime.vue
Reverts nasa/openmct#4807
Reverts nasa/openmct#4807
> Revert "Request data when switching between real time and fixed."

- package.json
> Prep for release 1.8.6

- src/plugins/imagery/components/ImageryView.vue
> Mct34 refactor

- package.json
> Sprint 2.0.1

- .github/ISSUE_TEMPLATE/bug_report.md
- package.json
Closes https://github.com/nasa/openmct/issues/4857
This leverages the envinfo plugin. This should drastically improve the quality of bug report.
> [Docs] Update Github Bug Report Template with envinfo

- .circleci/config.yml
- package.json
> [CI] Update playwright to 1.19.1

- e2e/tests/plugins/condition/condition.e2e.spec.js
This quickly adds some stubs for open source contributors to pick up.
> [e2e] Add todo-like stubs for CRUD Operation tests

- src/plugins/tabs/components/tabs.vue
Closes #4921  
On route changes, we're now calling `showTab`. With recent eager load changes, this is now necessary.
> [Tabs] Update tab on route change

- e2e/tests/example/generator/SinewaveLimitProvider.e2e.spec.js
> relax text assertion in e2e to be any number

- package.json
Addresses a security vulnerability in applications using lodash < 4.17.21 https://snyk.io/vuln/npm:lodash
> [Build] Update lodash to address vulnerability

- package.json
- webpack.common.js
Addressed (but does not close): https://github.com/nasa/openmct/issues/5007
> remove file loader as dependency

- .circleci/config.yml
> Revert "[Temp] Remove e2e-ci until percy fix"

- package.json
> Prepare for 2.0.3 release

- .circleci/config.yml
- .github/workflows/pr-platform.yml
> [Build] Add support for node18

- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/pluginSpec.js
> Image size thumbs test

- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/components/imagery-view.scss
- src/plugins/imagery/pluginSpec.js
> Show image thumbnails in layout views - 4884

- src/api/telemetry/TelemetryCollection.js
Closes https://github.com/nasa/openmct/issues/5095
> [Telemetry Collection] Telemetry table excluding start and end bound values

- src/plugins/gauge/GaugeViewProvider.js
> Add Gauge plugin #4896, add edit mode

- src/plugins/LADTable/components/LADRow.vue
- src/plugins/LADTable/pluginSpec.js
Closes #5111  
Using Telemetry collections in LAD Tables. This will handle all bounds related filtering (including future dates, which was the issue).
> [LAD Tables] Use Telemetry Collections

- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/components/imagery-view.scss
> Added animation styling for POS and CAM; adjusted cutoff for isNewImage

- src/api/telemetry/TelemetryCollection.js
Closes #5111 
Closes #5095  
Reverting the <= and >= additions to Telemetry Collection processor, that's not the right approach.
> [Telemetry Collections] Include data with start and end bounds

- .circleci/config.yml
Closes #4977
Updating the dependency to pick up the flakey fix
> [Build] Update CircleCI Dependency to fix flakey downloads

- e2e/tests/plugins/condition/condition.e2e.spec.js
- e2e/tests/recycled_storage.json
- package.json
- src/MCT.js
- src/api/objects/Transaction.js
- src/api/objects/TransactionSpec.js
- src/api/telemetry/TelemetryCollection.js
- src/plugins/LADTable/components/LADRow.vue
- src/plugins/LADTable/pluginSpec.js
- src/plugins/conditionWidget/components/ConditionWidget.vue
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/gauge/GaugePluginSpec.js
- src/plugins/gauge/GaugeViewProvider.js
- src/plugins/gauge/components/Gauge.vue
- src/plugins/gauge/components/GaugeFormController.vue
- src/plugins/gauge/gauge-limit-util.js
- src/plugins/gauge/gauge.scss
- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/components/imagery-view.scss
- src/plugins/plot/MctTicks.vue
- src/plugins/plot/configuration/YAxisModel.js
- src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js
- src/plugins/plot/tickUtils.js
- src/ui/components/ObjectView.vue
Merges release/2.0.3 into master
> 2.0.3 merge to master

- package.json
> Update version for 2.0.4

- webpack.common.js
- webpack.prod.js
> Temp source map fix 2.0.4

- src/ui/layout/search/GrandSearch.vue
- src/ui/layout/search/SearchResultsDropDown.vue
Some quick aria changes to existing PR
> some quick additions

- example/generator/WorkerInterface.js
- src/plugins/objectMigration/Migrations.js
Fixes related issue from dependabot version bump in #5170
> Updated the dependency injection syntax to use v4 instead of default

- src/plugins/imagery/components/ImageControls.vue
- src/plugins/imagery/components/ImageryView.vue
- src/plugins/imagery/components/imagery-view.scss
- src/plugins/imagery/mixins/imageryData.js
- src/plugins/imagery/pluginSpec.js
Closes 
#5274 
* Added a height fallback to catch certain cases where the height for the focusedImageElement is not specified
* Removed duplicated requestHistory request in mounted
> Imagery Fixes for release/2.0.4

- src/plugins/faultManagement/FaultManagementListItem.vue
> [Fault Management] Fix class case issue not showing icon

- package.json
Closes 
Notebook tests should not have been running on commit
> Demote notebook tests

- src/plugins/displayLayout/pluginSpec.js
Closes #5310 
Modified the test to actually render the view, before it was in headless mode, so nothing was rendered, but no issues where thrown, because (who knows).
> [Display Layout] Fix broken render test

- e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
> Created Example Imagery in Flexible layout test

- src/plugins/plot/inspector/PlotOptionsEdit.vue
- src/plugins/plot/inspector/forms/YAxisForm.vue
- src/plugins/plot/stackedPlot/StackedPlot.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
> Dont' mutate a stacked plot unless its user initiated

- e2e/tests/moveObjects.e2e.spec.js
- e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/plugins/telemetryTable/telemetryTable.e2e.spec.js
Closes #5184 
The issue seems to have been related to this (now resolved) chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1322473
I removed all of the workarounds for #5184 and was not able to reproduce the console error. Seems to be fixed in Chrome 102.
> Remove workarounds for chrome 'scrollTop' issue

- src/plugins/operatorStatus/operatorStatus/OperatorStatus.vue
Closes https://github.com/nasa/openmct/issues/5424
Sets the default poll question to something more informative than just "--"
> Show a better default poll question

- .circleci/config.yml
Closes:  #5370
- Runs the release branch on 2.0.5 in addition to master
- Runs every 4 hours to get some additional runs
> Update circleCI to run more frequently during Build 6

- e2e/tests/plugins/notebook/tags.e2e.spec.js
- package.json
- src/api/annotation/AnnotationAPI.js
- src/plugins/notebook/components/NotebookEntry.vue
Closes #5361 
Add tag with annotation creation to avoid race condition
> 5361 Tags not persisting when several notebook entries are created at once

- e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js
- src/api/telemetry/TelemetryAPI.js
- src/api/telemetry/TelemetryCollection.js
- src/plugins/displayLayout/components/TelemetryView.vue
- src/plugins/plot/axis/XAxis.vue
- src/plugins/plot/axis/YAxis.vue
- src/plugins/plot/inspector/PlotOptionsBrowse.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
Closes #4258 
Added checks for missing data as a result of missing domain objects to fix console errors located in a display layouts, overlay plots, and stacked plots as shown in the issue #4258.
The result should only display console warnings of missing objects. Stacked plots should have an empty space with no errors shown. See image below.
> Handle missing objects gracefully 

- e2e/tests/visual/addInit.visual.spec.js
This commit was missed on my sync
> fix pathing

- src/api/telemetry/TelemetryAPI.js
Closes #5460
Since TelemetryAPI was upped to an ES6 class no need to reference default import for custom string formatters.
> [TelemetryAPI] Fix CustomStringFormatter instantiation error

- src/api/telemetry/TelemetryCollection.js
- src/plugins/telemetryTable/collections/TableRowCollection.js
- src/plugins/telemetryTable/components/table.vue
- src/plugins/viewLargeAction/viewLargeAction.js
Closes https://github.com/nasa/openmct/issues/5464
Removes performance marks from functional code for now to prevent memory leaks.
> Remove performance marks

- src/plugins/charts/bar/BarGraphView.vue
- src/plugins/charts/bar/BarGraphViewProvider.js
- src/plugins/charts/bar/inspector/BarGraphOptions.vue
Closes #5456 
Ensure that the yKey is set to 'none' if there is no range with array Values
React to clear data action
> Clear data when time bounds are changed

- app.js
Closes #5497 
Use `webpack.dev.js` in the case `NODE_ENV` is not set, or if `NODE_ENV` is expicitly set to `'development'`.
> Fix source maps in dev mode

- package.json
This is failing. Likely an issue in the backmerge
https://github.com/nasa/openmct/issues/5491
> Removing flaky test from CI runs

- e2e/commonActions.js
- e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
- package.json
Closes #5491 
Fixes the flaky `exampleImagery` zoom tests and adds them back into our CI suite. [See this playwright issue](https://github.com/microsoft/playwright/issues/15660).
Uses [getAnimations](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAnimations) to wait until the zoom is finished, since the zoom contains a css transition.
Also refactored the tests a bit, extracting the zoomButton logic to a few different functions.
> [e2e] Fix flaky `exampleImagery` zoom tests

- src/api/forms/components/FormRow.vue
Closes #5545
This will remove some leftover code from a merge that was breaking the form functionality.
> [VISTA Form Error] Merge issue is blocking form functionality

- e2e/tests/search.e2e.spec.js
Relates to [#4667](https://github.com/nasa/openmct/issues/4667)
> [e2e] fix search tests 4667

- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/plugins/formActions/CreateAction.js
- src/plugins/persistence/couch/CouchObjectProvider.js
Closes https://github.com/nasa/openmct/issues/5488
This is a rebased version of https://github.com/nasa/openmct/pull/5487, with some additional changes.
* Re-throws persistence errors in the Couch provider when they occur
* Show a notification on error fetching objects from Couch
* Show a notification on conflict errors when saving objects.
> Fix Persistence Errors

- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- e2e/tests/functional/search.e2e.spec.js
- src/api/annotation/AnnotationAPI.js
- src/api/annotation/AnnotationAPISpec.js
- src/api/objects/ObjectAPI.js
- src/api/objects/object-utils.js
- src/ui/layout/search/GrandSearch.vue
- src/ui/layout/search/GrandSearchSpec.js
- src/ui/layout/search/SearchResultsDropDown.vue
Closes #5572
Also addresses:
https://github.com/nasa/openmct/issues/5469#issuecomment-1203276272
Might also address:
#5603  (can't find orphaned objects anymore in search)
#3823
#3707
#5407 
This PR adds a progress bar when searching, and a message if no search results were found. It also filters results whose `originalPath` is <= 1.
> Search should indicate in progress and no results states, filter orphaned results

- src/api/objects/InMemorySearchProvider.js
- src/plugins/timelist/pluginSpec.js
> Revert "Have in-memory search indexer use composition API"

- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
> Check for circular references in originalPath - 5615

- e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
- src/plugins/condition/criterion/TelemetryCriterion.js
Brings in the condition set fix.
> Moves condition set fix into 2.0.8

- src/plugins/timelist/inspector/TimelistPropertiesView.vue
- src/plugins/timelist/plugin.js
- src/plugins/timelist/timelist.scss
Closes #5534
- Compacted table row spacing.
- Set all timeframes to display by default when creating a new Time List.
- Removed 'Upload plan' file button from Properties.
- Better hint text for editing Timeframe Inspector section.
> Time List 5534 for release/2.0.8

- e2e/tests/functional/example/generator/sineWaveLimitProvider.e2e.spec.js
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- e2e/tests/functional/plugins/notebook/restrictedNotebook.e2e.spec.js
- e2e/tests/functional/plugins/plot/missingPlotObj.e2e.spec.js
- e2e/tests/visual/default.visual.spec.js
- Replaces `test.fixme` with the `@unstable` annotation for tests with contents
- Replaces `test.fixme` with `test.skip` for conditionally skipped tests
> [e2e] Audit `test.fixme`s

- e2e/README.md
> Update getting started readme

- src/api/indicators/IndicatorAPI.js
- src/api/indicators/IndicatorAPISpec.js
- src/api/indicators/SimpleIndicator.js
- src/plugins/URLIndicatorPlugin/URLIndicatorPlugin.js
- src/plugins/operatorStatus/operatorStatus/OperatorStatusIndicator.js
- src/plugins/operatorStatus/pollQuestion/PollQuestionIndicator.js
- src/plugins/performanceIndicator/plugin.js
- src/plugins/persistence/couch/plugin.js
Closes #5728
Does not affect the main branch
> #5621 for O4M 4.10 release

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-pr.yml
- e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
- package.json
- Cleans up / stabilizes some of the existing exampleImagery e2e tests using the new patterns we've established.
- Fixes the "Example Imagery in Display Layout" test to actually embed the imagery within a display layout, as it was not doing this previously.
- Extracts all the "Imagery View" test actions/assertions to a common function.
- Adds tests against Example Imagery embedded within a Tabs View.
> [e2e] Clean up example imagery tests, fix display layout test

- tsconfig.json
No associated issue.
- Fixes erroneous TS language server warnings showing up in the VSCode terminal
- Ensures TypeScript language server features (such as refactor) are able to work properly by excluding build artifacts and dependencies from being watched
> [tsconfig] Add baseUrl, outDir, and exclude config options

- e2e/README.md
- e2e/tests/framework/exampleTemplate.e2e.spec.js
> Update our Browser Support Matrix documentation

- src/api/annotation/AnnotationAPISpec.js
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/plugins/plan/pluginSpec.js
- src/plugins/remove/RemoveAction.js
- src/ui/inspector/InspectorDetailsSpec.js
- src/ui/inspector/details/Properties.vue
> Revert "[User Attribution] "createdBy" and "modifiedBy" fields for domainObjects"

- e2e/test-data/ExampleLayouts.json
No associated issue. 
Publishes an importable JSON containing 2 open source display layouts as representative examples of layouts as they would be used in a real mission.
> Publish example layouts

- e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
- src/api/annotation/AnnotationAPI.js
- src/api/annotation/AnnotationAPISpec.js
- src/plugins/persistence/couch/CouchSearchProvider.js
- src/ui/layout/search/GrandSearchSpec.js
- src/ui/router/ApplicationRouterSpec.js
Closes [#69](https://github.com/akhenry/openmct-yamcs/issues/69)
Added two input sanity checks for search if no tags were matched.
> If no matching tags, do not attempt tag search

- .github/dependabot.yml
Address https://github.com/nasa/openmct/issues/5760
> Add playwright-core to dependabot ignore list

- package.json
No related issue. 
We missed updating the version to `2.1.2-SNAPSHOT` when the `release/2.1.1` branch was cut. I'm in the process of automating the release branch creation / version updates using GitHub Actions, but in order to do that, the current version must be accurate.
This fixes the current version so we can continue on that path today.
> Fix current version so we can automate release branch creation

- src/plugins/formActions/CreateAction.js
> use full identifier instead of key

- package.json
No related issue. 
Increment version on master to `2.1.3-SNAPSHOT`
> Bump version to `2.1.3-SNAPSHOT`

- .github/workflows/npm-prerelease.yml
Automate pre release publishes
Fix typo in the publish script for access parameter.
> Fix typo for publish

- .npmignore
Closes #5928 
Include e2e folder
Ignore e2e/test-data/ files
> Add e2e tests to npm package

- .github/dependabot.yml
Addresses: #5760 
This one doesn't really need z stream changes
> Ignore babel loader z stream

- .github/dependabot.yml
Addresses #5760 
`sinon` added to skip list
> skip one mo

- src/api/objects/ObjectAPI.js
> revert persisted time to last actual persisted time on save error

- package.json
Bumps version to `2.1.3` on `release/2.1.3`
> Bump version to `2.1.3`

- package.json
Increment version to `2.1.4-SNAPSHOT` on `master`
> Bump version to `2.1.4-SNAPSHOT`

- package.json
No related issue
Bump the version to `2.1.5-SNAPSHOT`
> Bump version to `2.1.5-SNAPSHOT`

- package.json
Remove SNAPSHOT for release branch.
> Update version to 2.1.5

- src/ui/inspector/elements.scss
Closes #6169 
Translation: remove the baby scroll bars from empty element item groups
> fix(elementItemGroup): 🚫👶📜📊

- src/ui/layout/recent-objects.scss
Closes #6180
- Reduced size of icon.
- Tightened spacing.
> Visual tweaks to Recently Viewed items

- src/ui/layout/recent-objects.scss
- Reduced size of icon.
- Tightened spacing.
> cherry-pick(#6183) Visual tweaks to Recently Viewed items

- e2e/playwright-ci.config.js
- e2e/playwright-performance.config.js
- e2e/playwright-visual.config.js
Closes #6223 
Simply updates our pathing to match the way test results were calculated <1.27
Before
After
> Playwright pathing change

- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
Closes #6201 
Adds default value of `null` to `targetedPath`. Previously, this was a required prop and it was of type `String`. When the "targeted object" animation ends, we were setting `targetedPath` to `undefined`, causing this vue warning. Now, we set it to `null` (to indicate an initialized variable with no value), and let the default be `null` so that Vue knows what to expect.
> fix(recents): fix vue warnings after target animation

- e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
- src/api/composition/CompositionAPISpec.js
- src/api/composition/CompositionProvider.js
- src/api/composition/DefaultCompositionProvider.js
- src/api/objects/MutableDomainObject.js
- src/api/objects/ObjectAPI.js
- src/api/objects/ObjectAPISpec.js
- src/api/overlays/components/OverlayComponent.vue
- src/plugins/formActions/CreateAction.js
- src/plugins/plot/stackedPlot/StackedPlot.vue
- src/ui/inspector/ElementItem.vue
- src/ui/inspector/PlotElementsPool.vue
- src/ui/layout/CreateButton.vue
* Fixed composition
* Remove unnecessary guard code
* Removing deprecated code
* Use valid key for stacked plot v-for
* Fixed object API specs to expect old values as well as new values in mutation callbacks
* Fixed existing tests
* Added E2E test
* Fixed linting error
---------
Co-authored-by: Shefali Joshi <simplyrender@gmail.com>
> cherry-pick(#6206): Fix plot composition

- src/styles/_constants-espresso.scss
- src/styles/_constants-maelstrom.scss
- src/ui/layout/recent-objects.scss
Closes #6212
- Normalized color styles.
> Color fix for Recently Viewed items

- src/api/objects/MutableDomainObject.js
> cherry-pick(#6237): Replace structuredClone with JSON.parse

- e2e/appActions.js
> cherry-pick(#6226): fix(e2e): temp fix for appAction test flake

- src/plugins/notebook/components/NotebookEntry.vue
- src/styles/_constants.scss
- src/styles/_controls.scss
- src/ui/components/tags/TagEditor.vue
- src/ui/components/tags/TagSelection.vue
- src/ui/components/tags/tags.scss
- src/ui/inspector/annotations/AnnotationsInspectorView.vue
Closes #6215
- Look of tags has been changed for consistency and compatibility with other UI elements.
- Markup cleanups, CSS placement improvements for tags.
- Better approach to tag layout.
- CSS prop migrated to _constants.scss.
- Style and layout improvements for `.c-autocomplete*` input.
> Fixes to tags layout and autocomplete

- src/ui/layout/mct-tree.vue
- src/ui/layout/tree-item.vue
> cherry-pick(#6203): fix(recents): fix vue warnings after target animation

- src/styles/_constants-espresso.scss
- src/styles/_constants-maelstrom.scss
- src/ui/layout/recent-objects.scss
Issue #6212 
- Normalized color styles.
Co-authored-by: David Tsay <3614296+davetsay@users.noreply.github.com>
> cherry-pick(#6227): Color fix for Recently Viewed items

- e2e/helper/addInitNotebookWithUrls.js
- e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
- src/plugins/notebook/plugin.js
* removing dupe nb install, adding whitelist nb init script, testing whitelist urls
* added a secure url test and a subdomain url test and simplified some code
* not messin with protocols atm
* update variable name
Issue: #6155
> cherry-pick(#6190):[Notebook] Entry links tests

- src/plugins/imagery/components/Compass/CompassRose.vue
> cherry-pick(#6260): compass rose rotation fixes

- e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js
- src/plugins/plot/MctPlot.vue
- src/plugins/plot/inspector/PlotOptionsBrowse.vue
- src/plugins/plot/inspector/PlotOptionsEdit.vue
- src/plugins/plot/inspector/forms/YAxisForm.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
- src/ui/inspector/InspectorViews.vue
> cherry-pick(#6275): Fix stacked plot child selection

- src/api/objects/ObjectAPI.js
Closes #6193
Removed the check for mutability as it's done in the `toMutable` method regardless. Will always turn into a mutable, refresh to notify any observers  and destroy.
> [ObjectAPI] Cleanup code and remove possible memory leak

- example/generator/SinewaveStalenessProvider.js
- src/plugins/LADTable/components/LadTableSet.vue
- src/plugins/condition/components/ConditionCollection.vue
- src/plugins/notebook/components/NotebookEntry.vue
- src/plugins/plot/stackedPlot/StackedPlotItem.vue
Closes #6265
And addresses: https://github.com/nasa/openmct/issues/6109#issuecomment-1414231882 (LAD Table Set part, other is this issue)
If an item is added to a Stacked Plot that is NOT a telemetry producing item, then we'll watch it's composition for staleness. Also, when removing a LAD Table from a LAD Table Set, we will stop observing staleness for it's telemetry. And a typo fix. ALSO, also, fixing the `isStale` method of the example SWG Staleness Provider.
> [Staleness] Handle Overlay Plots in Stacked Plots and removing LAD Tables from LAD Table Sets

- src/api/annotation/AnnotationAPISpec.js
- src/plugins/URLTimeSettingsSynchronizer/pluginSpec.js
- src/plugins/plot/stackedPlot/pluginSpec.js
- src/ui/router/ApplicationRouterSpec.js
Fix some router test flakes. Or at least attempt to.
> Fix router test flakes

- e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js
- src/styles/_legacy-plots.scss
> cherry-pick(#6271): fix: remove 1px padding and re-enable autoscale snapshot test

- src/api/time/IndependentTimeContext.js
- src/api/time/independentTimeAPISpec.js
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
> Revert changes that don't allow unregistering independent time context

- src/plugins/plot/chart/MctChart.vue
Original PR: #6320 
* Remove console warn
> cherry-pick(#6320) Remove console warn

- src/plugins/plot/chart/MctChart.vue
> Remove console warn

- src/plugins/notebook/components/NotebookEntry.vue
- src/plugins/notebook/notebook-constants.js
- src/plugins/notebook/plugin.js
Issues https://github.com/nasa/openmct/issues/6202 https://github.com/nasa/openmct/issues/6316
* adding urlWhitelist to data so when/if it is updated it triggers link formatting
* removing dupe notebook and restricted notebook checks and just moving it to base notebook functionality install checks
> cherry-pick(#6317): [Notebook] Fix link formatting on load, remove duplicate snapshot indicator

- e2e/README.md
Closes #6328  
- Fixes an inconsistency in the docs with regards to the docker command for spinning up a Playwright container
- Closes an unclosed markdown code block
> docs: fix docker command and formatting

- src/api/telemetry/TelemetryCollection.js
- src/plugins/imagery/mixins/imageryData.js
> cherry-pick(#6342): Emit indices of out of order telemetry collection items

- src/plugins/notebook/components/NotebookEntry.vue
- src/utils/textHighlight/TextHighlight.vue
Closes #6202 
Significant simplification to highlight component. This will allow us to highlight links in notebook search as well. Also fixed a bug where locked notebooks weren't formatting links correctly.
> [Notebook] Links, Restricted Notebook Links, Search links

- package.json
No related issue 
Bump version to `2.2.0-SNAPSHOT`
> chore: bump version to `2.2.0-SNAPSHOT`

- src/ui/components/tags/TagEditor.vue
Closes: https://github.com/nasa/openmct/issues/6330
> fix(#6330): Clicking Add Tag and then removing an existing tag causes the Add Tag button to disappear

- e2e/tests/functional/plugins/plot/tagging.e2e.spec.js
- src/plugins/plot/MctPlot.vue
Closes #6294 #6276 #6207
Freeze plot when annotation drag detected, and added e2e tests for plot annotations
> Freeze plot automatically when adding tags

- src/plugins/inspectorViews/annotations/AnnotationsViewProvider.js
Closes #6477 
Get available tags at runtime and only allow tab view if tags have been defined.
> Suppress annotations tab if no annotations defined

- src/plugins/inspectorViews/annotations/tags/TagEditor.vue
Closes #6457 
Before:
https://user-images.githubusercontent.com/4138560/227356015-a059ae24-bb9c-488e-adf4-63319ca3e292.mov
After:
https://user-images.githubusercontent.com/4138560/227356144-8c38fc76-2d82-4ea4-947c-ea505b2c22b6.mov
> fix(#6457): Tags disappear after resizing then dismissing the Add Tag select

- src/plugins/plot/chart/MctChart.vue
Closes #6213 
Set the first drawable axis as the rectangleAxisId and set rectangles on any other axis to transparent
> [Plots, Multiple-Y Axis] Fix for rectangle drawn on each axis

- src/plugins/remoteClock/RemoteClock.js
- src/plugins/timelist/Timelist.vue
- src/ui/components/List/ListItem.vue
Closes #5629
Remove the ticker that was causing issues when using Remote clock.
> Remove ticker and rely solely on the clock ticks to update the timelist durations

- e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
- src/plugins/notebook/actions/ExportNotebookAsTextAction.js
- src/plugins/notebook/components/Notebook.vue
- src/plugins/notebook/plugin.js
Closes #6435 
This is a simple text export of a Notebook object into markdown. It iterates through all the sections, pages, and entries and produces a markdown text of the result. Things we may like to add before merging:
- Images
- Snapshots
> Simple text export of Notebook

- .github/workflows/e2e-couchdb.yml
- package.json
> Github doesn't like node '16'

- package.json
> bump to 222

- package.json
> Bump for 2.2.3

- .circleci/config.yml
- e2e/tests/functional/plugins/notebook/tags.e2e.spec.js
No related issue. 
- Fixes a test flake in the notebook tags tests: `Tags persist across reload`
- Fixes the Playwright version for circle ci couchdb test
> Fix test flake and playwright version in couchdb circleci test

- src/plugins/persistence/couch/couchdb-compose.yaml
- src/plugins/persistence/couch/setup-couchdb.sh
Closes #6644  
Updates our couchdb script for readability and removal of duplicate code
Updated to version 3.3.2 (latest)
Removed reference to deprecated script
> [Couchdb] Update couchdb init script and bump version to latest

- package.json
> Remove snapshot

- .git-blame-ignore-revs
Continuation of work for #6381  
- Add the commit SHA that contains the `prettier` formatting changes to a `.git-blame-ignore-revs` file
> chore: add `prettier` (3/3): update `.git-blame-ignore-revs` file

- package.json
Removes snapshot from release version.
> Remove snapshot for release

- src/plugins/timer/components/Timer.vue
> [Timer] Remove "refresh" call, it is not needed

- src/api/time/TimeContext.js
Cherry picks #6875 which closes 6870
> cherry pick (#6875) suppress deprecation warnings to once per unique args

- package.json
Version bump `3.0.0` -> `3.0.1`
> chore: bump version to `3.0.1`

- .github/dependabot.yml
- package.json
- Updates our dependabot config to pick up fewer releases
- Updates to the latest release
> [Dependency] Update to skip regular releases of marked

- package.json
> chore: bump version to `3.1.1`

- API.md
> cherry-pick(#7262): Update API documentation for Visibility-Based Rendering

- package.json
> chore: bump version to `4.0.0-next`

- .github/PULL_REQUEST_TEMPLATE.md
- .github/release.yml
- docs/src/process/release.md
> docs: Update release.yml and docs

- package.json
Version bump for `3.2.1` patch release
> chore: bump version to `3.2.1`

- .github/PULL_REQUEST_TEMPLATE.md
Minor formatting nitpick
Closes N/A
> chore: minor formatting fix for PR template

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- .github/workflows/e2e-pr.yml
- package-lock.json
- package.json
Closes N/A
- Bump @playwright/test to 1.42.1
- Remove circleci individual test rerun implementation for visual tests
> chore: bump `@playwright/test` to `1.42.1`

- e2e/tests/functional/plugins/reloadAction/reloadAction.e2e.spec.js
- src/ui/preview/PreviewHeader.vue
Closes #7638 
As the utility of reloading a Preview seems limited, and it's causing problems, disable it in Previews.
> Disable reload in preview

- src/plugins/notebook/components/NotebookEntry.vue
Reverts nasa/openmct#7628
The modified code makes the situation worse, pasting is completely broken.
> Revert "Handle the case where the pasted data is not an image"

- .circleci/config.yml
- e2e/tests/visual-a11y/planning-gantt.visual.spec.js
- e2e/tests/visual-a11y/planning-timelist.visual.spec.js
- e2e/tests/visual-a11y/planning-view.visual.spec.js
- e2e/tests/visual-a11y/planning.visual.spec.js
- package.json
- src/plugins/timelist/timelist.scss
- src/styles/_constants-espresso.scss
Addresses https://github.com/nasa/openmct/issues/7421 (does not close it)
Closes 
- enable a11y plan suite 
- fix contrast issues that were causing the tests to fail
> [a11y] re-enable and fix all failing plan tests

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- .github/workflows/e2e-pr.yml
- e2e/package.json
- package-lock.json
> chore: bump playwright to `1.45.2`

- package.json
> chore: bump version to `4.0.0`

- e2e/package.json
- package.json
> chore: bump version to `4.1.0-next`

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- .github/workflows/e2e-pr.yml
- .github/workflows/release.yml
- e2e/package.json
- package-lock.json
> chore: bump `@playwright/test` to 1.47.2

- e2e/tests/functional/plugins/performanceIndicator/performanceIndicator.e2e.spec.js
- e2e/tests/functional/plugins/reloadAction/reloadAction.e2e.spec.js
- e2e/tests/functional/staleness.e2e.spec.js
- e2e/tests/functional/userRoles.e2e.spec.js
- karma.conf.cjs
- package.json
- src/plugins/plan/inspector/components/PlanActivityPropertiesView.vue
- src/plugins/plan/inspector/components/PlanActivityStatusView.vue
- src/plugins/reloadAction/ReloadAction.js
- src/plugins/reloadAction/plugin.js
- src/ui/layout/AboutDialog.vue
N/A 
Updates all of our copyright end dates to 2024. Looks like we missed some.
> chore: it is 2024.

- .circleci/config.yml
- e2e/appActions.js
- e2e/tests/framework/appActions.e2e.spec.js
- e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js
- e2e/tests/visual-a11y/displayLayout.visual.spec.js
Partially addresses #7549 
We have some nondeterminism in the percy tests. This PR addresses some of the flake.
Also, I've added 2 appActions which should allow us to refactor out some old patterns.
> [CI] Fix flake with clocks and state generators

- src/plugins/persistence/couch/scripts/lockObjects.mjs
Reverts d8c5095ebb0df923fb289a50695def30a28fc510 by replacing it with the version of the file from the preceding commit.
> Revert d8c5095ebb0df923fb289a50695def30a28fc510

- .circleci/config.yml
- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- e2e/package.json
- package-lock.json
N/A 
Bump `@playwright/test` to v1.48.1
> chore: bump @playwright/test to v1.48.1

- .github/workflows/e2e-couchdb.yml
- .github/workflows/e2e-flakefinder.yml
- .github/workflows/e2e-perf.yml
- .github/workflows/e2e-pr.yml
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
Closes #8001
Use v4 for upload-artifact in github yml files.
> migrate from actions/upload-artifact: v3 to v4.

- package-lock.json
- package.json
- src/plugins/notebook/components/NotebookEntry.vue
Changes:
* Modified the way that marked is called for compatibility with updated library version.
* Combined remaining library version bumps into one PR to save time and compute.
Incorporates 
* https://github.com/nasa/openmct/pull/7973
* https://github.com/nasa/openmct/pull/7976
* https://github.com/nasa/openmct/pull/8008
* https://github.com/nasa/openmct/pull/8009
* https://github.com/nasa/openmct/pull/8010
> Update all remaining dependencies in one go

- e2e/tests/functional/plugins/conditionSet/conditionSetOperations.e2e.spec.js
- src/plugins/condition/components/ConditionItem.vue
PR: https://github.com/nasa/openmct/pull/7914
Issue: https://github.com/nasa/openmct/issues/7994
> cherry-pick Use the disabled attribute on a valid element - the button. (#7914)

- e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
- src/api/time/IndependentTimeContext.js
- src/api/time/TimeAPI.js
- src/plugins/plot/MctPlot.vue
- src/plugins/timeConductor/independent/IndependentTimeConductor.vue
PR: https://github.com/nasa/openmct/pull/7956
Issue: https://github.com/nasa/openmct/issues/7737
> Cherry pick 7737 - Independent Time Conductor interfering with plots behavior even if not enabled

- src/plugins/persistence/couch/CouchObjectProvider.js
- src/plugins/persistence/couch/CouchSearchProvider.js
Cherry pick into 9.1 release branch
Issue: https://github.com/nasa/openmct/issues/8046
PR: https://github.com/nasa/openmct/pull/8047
> cherry-pick Fix partial matches (#8047)

- e2e/tests/functional/plugins/conditionSet/conditionSetOperations.e2e.spec.js
- src/plugins/condition/Condition.js
- src/plugins/condition/ConditionManager.js
- src/plugins/condition/ConditionSpec.js
- src/plugins/condition/components/ConditionItem.vue
- src/plugins/condition/components/TestData.vue
- src/plugins/condition/criterion/AllTelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterion.js
- src/plugins/condition/criterion/TelemetryCriterionSpec.js
Cherry picks PR #8041
Related issue #7992
> cherry-pick #8041 - Condition Sets can incorrectly evaluate telemetry objects that update infre

- src/plugins/telemetryTable/components/TableConfiguration.vue
Closes #6407 
In the Telemetry Table Configuration Inspector component, if no "Name" column is present, we add it in so it has the ability to be hidden.
tests: https://github.com/akhenry/openmct-yamcs/pull/492
> [Telemetry Tables] Ability to hide manually added Name column

- src/plugins/LADTable/LADTableConfigurationViewProvider.js
- src/plugins/LADTable/LADTableSetViewProvider.js
- src/plugins/LADTable/LADTableViewProvider.js
- src/plugins/condition/ConditionSetViewProvider.js
- src/plugins/conditionWidget/ConditionWidgetViewProvider.js
- src/plugins/displayLayout/plugin.js
- src/plugins/faultManagement/FaultManagementInspectorViewProvider.js
- src/plugins/filters/FiltersInspectorViewProvider.js
- src/plugins/flexibleLayout/flexibleLayoutViewProvider.js
- src/plugins/folderView/FolderGridView.js
- src/plugins/folderView/FolderListView.js
- src/plugins/gauge/GaugeViewProvider.js
- src/plugins/inspectorDataVisualization/InspectorDataVisualizationViewProvider.js
- src/plugins/inspectorViews/elements/PlotElementsViewProvider.js
- src/plugins/plot/PlotViewProvider.js
- src/plugins/tabs/tabs.js
- src/plugins/telemetryTable/TelemetryTableViewProvider.js
- src/plugins/webPage/WebPageViewProvider.js
- src/ui/registries/ViewRegistry.js
Closes: #8116
- Make Telemetry tables and plots have priority of LOW
- Change default view priority to return 0 instead of 100 when no priority is specified. 
- Change priority of Filter inspector from DEFAULT (0) to LOW (-1000). 
- Change priority of condition set view to return DEFAULT rather than 100 when viewed as table or plot. 
- Remove priority of 1 for some views. These should now return the default view priority. 
- Remove priority of 100 for Display Layout view.
- Remove priority of 1000 for Fault management Inspector view and MMGIS data visualization inspector view. 
- Remove priority of Default (0) for Plot elements inspector view.
> Update View priorities (especially making telemetry table and plot priorities LOW )

- CONTRIBUTING.md
- SECURITY.md
#8128 
- add security disclaimer
- update contribution instructions
> Update SECURITY.md and CONTRIBUTING.md to address security risk of externally provided code
